### ISSUE TITLE
More meaningful error when port 10000 is occupied by the Storage Emulator

### ISSUE THREAD

**Issue by seguler** [Azure/Azurite#101]
Great job folks on the Azurite!

A colleague of mine encountered an issue where a meaningful error message would be very nice. The error is below. The fix was to stop the Azure STorage Emulator as it was occupying the port. Could we have a error message printed saying "Port 10000 is busy. Try launching Azurite with a different port"

s:618:24)
    at env.init.then (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\lib\AzuriteQueue.js:50:25)
    at tryCatcher (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise._fulfill (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:638:18)
    at C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\nodeback.js:42:21
    at xfs.stat (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:10000
    at Server.setupListenHandle [as _listen2] (net.js:1269:19)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at Function.listen (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\express\lib\application.js:618:24)
    at env.init.then.then (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\lib\AzuriteBlob.js:78:27)
    at tryCatcher (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise._fulfill (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._settlePromise (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:582:21)
    at Promise._settlePromise0 (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise._fulfill (C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:638:18)
    at C:\Users\paulyuk\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\nodeback.js:42:21
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by edwin-huber** [comment]
we can probably wrap the promise evaluation with some error handler to detect the Error: listen EACCES 0.0.0.0:10000

**Comment by edwin-huber** [comment]
Updated documentation.
