### ISSUE TITLE
Unable to verify the first certificate error when using Docker

### ISSUE THREAD

**Issue by El-Gor-do** [Azure/Azurite#1073]
### Which service(blob, file, queue, table) does this issue concern?
Blob, queue and table

### Which version of the Azurite was used?
3.14.2

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
Don't know. It's the version that is in the prebuilt Docker image.

### What problem was encountered?
I am using Windows 10 and Docker Desktop 4.0.1. I am unable to connect to Azurite HTTPS endpoints when Azurite is running in Docker. Is the HTTPS Setup documentation missing any steps?

### Steps to reproduce the issue?
I am following the instructions on https://marketplace.visualstudio.com/items?itemName=Azurite.azurite

**Install certificates**
Open an elevated command prompt and run
```
choco install mkcert
mkcert -install
mkcert 127.0.0.1
```
127.0.0.1.pem and 127.0.0.1-key.pem are generated

**Start Azurite container**
Run "docker-compose up" with the following docker-compose.yml
```
version: '3.9'

services:
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        hostname: azurite
        command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --oauth basic --cert /ssl/127.0.0.1.pem --key /ssl/127.0.0.1-key.pem -d /logs/azuriteLog.txt
        volumes:
            - ./azurite:/logs
            - ./127.0.0.1.pem:/ssl/127.0.0.1.pem
            - ./127.0.0.1-key.pem:/ssl/127.0.0.1-key.pem
        ports:
            - 10000:10000
            - 10001:10001
            - 10002:10002
```

**Use Microsoft Azure Storage Explorer 1.21.2 to browse blob containers**
Import 127.0.0.1.pem by using Edit -> SSL Certificates -> Import Certificates
Restart Storage Explorer
Connect to local storage emulator with all default settings except ticking "Use HTTPS"
Expand Local & Attached -> Storage Accounts -> local-1 (Key) -> Blob Containers
An error dialog is displayed with the following message.
```
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://127.0.0.1:10000/devstoreaccount1?comp=list&include=metadata failed, reason: unable to verify the first certificate",
  "stack": "FetchError: request to https://127.0.0.1:10000/devstoreaccount1?comp=list&include=metadata failed, reason: unable to verify the first certificate\n    at ClientRequest.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "type": "system",
  "errno": "UNABLE_TO_VERIFY_LEAF_SIGNATURE",
  "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
}
```

**Test Azurite HTTPS connection using curl**
```
C:\Users\El-Gor-do>curl https://127.0.0.1:10000

curl: (77) schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
```

**Contents of /logs/azuriteLog.txt**
```
2021-10-01T08:26:39.586Z 	 info: Azurite Blob service is starting on 0.0.0.0:10000
2021-10-01T08:26:39.586Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-10-01T08:26:39.586Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-10-01T08:26:39.592Z 	 info: BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2021-10-01T08:26:39.592Z 	 info: BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2021-10-01T08:26:39.593Z 	 info: BlobGCManager:markSweepLoop() Start next mark and sweep.
2021-10-01T08:26:39.593Z 	 info: BlobGCManager:markSweep() Get all extents.
2021-10-01T08:26:39.593Z 	 info: BlobGCManager:start() BlobGCManager successfully started.
2021-10-01T08:26:39.594Z 	 info: BlobGCManager:markSweep() Got 0 extents.
2021-10-01T08:26:39.594Z 	 info: BlobGCManager:markSweep() Get referred extents.
2021-10-01T08:26:39.594Z 	 info: BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2021-10-01T08:26:39.594Z 	 info: BlobGCManager:markSweepLoop() Mark and sweep finished, taken 1ms.
2021-10-01T08:26:39.594Z 	 info: BlobGCManager:markSweepLoop() Sleep for 600000ms.
2021-10-01T08:26:39.595Z 	 info: Azurite Blob service successfully listens on https://0.0.0.0:10000
2021-10-01T08:26:39.595Z 	 info: Azurite Queue service is starting on 0.0.0.0:10001
2021-10-01T08:26:39.595Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-10-01T08:26:39.595Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-10-01T08:26:39.599Z 	 info: QueueGCManager:start() Starting QueueGCManager, set status to Initializing
2021-10-01T08:26:39.599Z 	 info: QueueGCManager:start() Trigger mark and sweep loop, set status to Running.
2021-10-01T08:26:39.599Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2021-10-01T08:26:39.599Z 	 info: QueueGCManger:markSweep() Get all extents.
2021-10-01T08:26:39.599Z 	 info: QueueGCManager:start() QueueGCManager successfully started.
2021-10-01T08:26:39.599Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2021-10-01T08:26:39.599Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2021-10-01T08:26:39.599Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2021-10-01T08:26:39.599Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 0ms.
2021-10-01T08:26:39.599Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2021-10-01T08:26:39.600Z 	 info: Azurite Queue service successfully listens on https://0.0.0.0:10001
2021-10-01T08:26:39.600Z 	 info: Azurite Table service is starting on 0.0.0.0:10002
2021-10-01T08:26:39.600Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-10-01T08:26:39.600Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-10-01T08:26:39.601Z 	 info: Azurite Table service successfully listens on https://0.0.0.0:10002
2021-10-01T08:27:39.592Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-10-01T08:27:39.592Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-10-01T08:27:39.596Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-10-01T08:27:39.596Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-10-01T08:27:39.599Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2021-10-01T08:27:39.600Z 	 info: QueueGCManger:markSweep() Get all extents.
2021-10-01T08:27:39.600Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2021-10-01T08:27:39.600Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2021-10-01T08:27:39.600Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2021-10-01T08:27:39.600Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 0ms.
2021-10-01T08:27:39.600Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2021-10-01T08:27:39.600Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-10-01T08:27:39.600Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-10-01T08:28:19.720Z 	 info: Azurite Blob service is closing...
2021-10-01T08:28:19.720Z 	 info: Azurite Queue service is closing...
2021-10-01T08:28:19.720Z 	 info: Azurite Table service is closing...
2021-10-01T08:28:19.720Z 	 info: BlobGCManager:close() Start closing BlobGCManager. Set status to Closing.
2021-10-01T08:28:19.721Z 	 info: QueueGCManager:close() Start closing QueueGCManager, set status to Closing.
2021-10-01T08:28:19.721Z 	 info: BlobGCManager:start() Mark and sweep loop is closed.
2021-10-01T08:28:19.721Z 	 info: BlobGCManager:close() BlobGCManager successfully closed. Set status to Closed.
2021-10-01T08:28:19.721Z 	 info: QueueGCManager:start() Mark and sweep loop is closed.
2021-10-01T08:28:19.721Z 	 info: QueueGCManager:close() QueueGCManager successfully closed, set status to Closed.
2021-10-01T08:28:19.721Z 	 info: Azurite Table service successfully closed
2021-10-01T08:28:19.721Z 	 info: Azurite Blob service successfully closed
2021-10-01T08:28:19.721Z 	 info: Azurite Queue service successfully closed
```

### Have you found a mitigation/solution?
No

**Comment by El-Gor-do** [comment]
I don't know if this is relevant but my Windows account _El-Gor-do_ is not an administrator so I run the _mkcert_ commands under a different administrator account while _Storage Explorer_ and _curl_ run as _El-Gor-do_.

**Comment by XiaoningLiu** [comment]
You can try with server.cert and server.key files in azurite repo tests folder. After import server.cert into storage explorer, you can attach to azurite using this connection string for a test:

`DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://localhost:10000/devstoreaccount1;QueueEndpoint=https://localhost:10001/devstoreaccount1;`

**Comment by El-Gor-do** [comment]
I was able to successfully connect to Azurite HTTPS endpoints when I followed the OpenSSL instructions instead of mkcert instructions.

Run these commands
```
openssl req -newkey rsa:2048 -x509 -nodes -keyout key.pem -new -out cert.pem -sha256 -days 365 -addext "subjectAltName=IP:127.0.0.1" -subj "/C=CO/ST=ST/L=LO/O=OR/OU=OU/CN=CN"
certutil –addstore -enterprise –f "Root" cert.pem
```

Changed my docker-compose command to
```
azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --oauth basic --cert /ssl/cert.pem --key /ssl/key.pem
```
