### ISSUE TITLE
Docker - Invalid Storage Account

### ISSUE THREAD

**Issue by Fosol** [Azure/Azurite#1082]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.14.2

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
v14.17.6

### What problem was encountered?
Other docker containers are unable to use it property.  When attempting to upload a file to storage it returns a 400 error with "Invalid storage account".  However if I use the same code with appropriate change to the connection string pointing to Azure cloud, it works.

### Steps to reproduce the issue?

I am using `docker-compose` with a configuration for Azurite.  Within VS Code I can access and use the container.

```conf
  azure-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    entrypoint: azurite
    command:
      - -d
      - /data/debug.log
      - --blobHost
      - 0.0.0.0
      - --queueHost
      - 0.0.0.0
      - --tableHost
      - 0.0.0.0
    ports:
      - ${AZURE_BLOB_PORT:-50020}:10000
      - ${AZURE_QUEUE_PORT:-50021}:10001
      - ${AZURE_TABLE_PORT:-50022}:10002
    volumes:
      - tno-azure-storage-data:/data
    environment:
      - AZURITE_ACCOUNTS=devaccount1:758f3f56abb44ac991922dadf42c08e91863af4c0acf4103ac7a9d3d5159d548
```

The connection string within my Java Spring app is as follows.

```conf
DefaultEndpointsProtocol=http;AccountName=devaccount1;AccountKey=758f3f56abb44ac991922dadf42c08e91863af4c0acf4103ac7a9d3d5159d548;BlobEndpoint=http://host.docker.internal:50020/devaccount1;
```

Debug Log extract

```
2021-10-06T20:01:09.289Z 0331eaa2-0852-4468-a0df-d0731a8985b5 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://host.docker.internal/devaccount1/tno/test.txt RequestHeaders:{"host":"host.docker.internal:50020","date":"Wed, 06 Oct 2021 20:01:09 GMT","authorization":"SharedKey devaccount1:VBDL2PFfKNR3NsfsiZlBOo0QvZVtW8XDVFOoDq4VrXk=","content-length":"19","if-none-match":"*","x-ms-version":"2020-10-02","content-type":"application/octet-stream","x-ms-client-request-id":"07d6006e-6b93-42f1-9321-b8d4403b6d25","x-ms-blob-type":"BlockBlob","accept":"application/xml","user-agent":"azsdk-java-azure-storage-blob/12.14.0 (11.0.12; Linux; 5.10.47-linuxkit)"} ClientIP=172.24.0.1 Protocol=http HTTPVersion=1.1
2021-10-06T20:01:09.289Z 0331eaa2-0852-4468-a0df-d0731a8985b5 info: BlobStorageContextMiddleware: Account=host Container=devaccount1 Blob=tno/test.txt
2021-10-06T20:01:09.289Z 0331eaa2-0852-4468-a0df-d0731a8985b5 verbose: DispatchMiddleware: Dispatching request...
2021-10-06T20:01:09.291Z 0331eaa2-0852-4468-a0df-d0731a8985b5 info: DispatchMiddleware: Operation=BlockBlob_Upload
2021-10-06T20:01:09.291Z 0331eaa2-0852-4468-a0df-d0731a8985b5 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2021-10-06T20:01:09.292Z 0331eaa2-0852-4468-a0df-d0731a8985b5 info: PublicAccessAuthenticator:validate() Start validation against public access.
2021-10-06T20:01:09.292Z 0331eaa2-0852-4468-a0df-d0731a8985b5 debug: PublicAccessAuthenticator:validate() Getting account properties...
2021-10-06T20:01:09.292Z 0331eaa2-0852-4468-a0df-d0731a8985b5 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: host, container: devaccount1, blob: tno/test.txt
2021-10-06T20:01:09.292Z 0331eaa2-0852-4468-a0df-d0731a8985b5 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container devaccount1
2021-10-06T20:01:09.292Z 0331eaa2-0852-4468-a0df-d0731a8985b5 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2021-10-06T20:01:09.292Z 0331eaa2-0852-4468-a0df-d0731a8985b5 error: BlobSharedKeyAuthenticator:validate() Invalid storage account host.
2021-10-06T20:01:09.294Z 0331eaa2-0852-4468-a0df-d0731a8985b5 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-10-06T20:01:09.294Z 0331eaa2-0852-4468-a0df-d0731a8985b5 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Invalid storage account.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=Invalid storage account. ErrorHTTPHeaders={"x-ms-error-code":"InvalidOperation","x-ms-request-id":"0331eaa2-0852-4468-a0df-d0731a8985b5"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:0331eaa2-0852-4468-a0df-d0731a8985b5\nTime:2021-10-06T20:01:09.294Z</Message>\n</Error>" ErrorStack="StorageError: Invalid storage account.\n    at Function.getInvalidOperation (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:58:16)\n    at BlobSharedKeyAuthenticator.validate (/opt/azurite/dist/src/blob/authentication/BlobSharedKeyAuthenticator.js:28:49)\n    at AuthenticationMiddlewareFactory.authenticate (/opt/azurite/dist/src/blob/middlewares/AuthenticationMiddlewareFactory.js:34:40)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2021-10-06T20:01:09.295Z 0331eaa2-0852-4468-a0df-d0731a8985b5 error: ErrorMiddleware: Set HTTP code: 400
2021-10-06T20:01:09.295Z 0331eaa2-0852-4468-a0df-d0731a8985b5 error: ErrorMiddleware: Set HTTP status message: Invalid storage account.
2021-10-06T20:01:09.295Z 0331eaa2-0852-4468-a0df-d0731a8985b5 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidOperation
2021-10-06T20:01:09.295Z 0331eaa2-0852-4468-a0df-d0731a8985b5 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=0331eaa2-0852-4468-a0df-d0731a8985b5
2021-10-06T20:01:09.295Z 0331eaa2-0852-4468-a0df-d0731a8985b5 error: ErrorMiddleware: Set content type: application/xml
2021-10-06T20:01:09.295Z 0331eaa2-0852-4468-a0df-d0731a8985b5 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:0331eaa2-0852-4468-a0df-d0731a8985b5\nTime:2021-10-06T20:01:09.294Z</Message>\n</Error>"
2021-10-06T20:01:09.295Z 0331eaa2-0852-4468-a0df-d0731a8985b5 info: EndMiddleware: End response. TotalTimeInMS=6 StatusCode=400 StatusMessage=Invalid storage account. Headers={"server":"Azurite-Blob/3.14.2","x-ms-error-code":"InvalidOperation","x-ms-request-id":"0331eaa2-0852-4468-a0df-d0731a8985b5","content-type":"application/xml"}
```

### Have you found a mitigation/solution?
No

**Comment by gldraphael** [comment]
Consider pinning the version number for the timebeing 

`mcr.microsoft.com/azure-storage/azurite:3.14.0`
