### ISSUE TITLE
PUT blockblob with comp=block without 'x-ms-blob-type: BlockBlob' returns 400 Bad Request

### ISSUE THREAD

**Issue by synox** [Azure/Azurite#1099]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.14.2

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v16.11.0

### What problem was encountered?
When uploading a block blob without any headers it fails in azurite, but works on azure. 

### Steps to reproduce the issue?

- create container 'todo-todo-todo'

```shell
curl  -v 'http://127.0.0.1:10000/devstoreaccount1/todo-todo-todo/2021-10-12-1c9d36af-fe4b-4508-b499-59262042171a/files/test.txt?sv=2020-08-04&spr=https%2Chttp&se=2021-10-13T06%3A47%3A28Z&sr=b&sp=cw&sig=2T4ET3r9cXXA9COYqON9vy%2F4bRuuJInywEAnHYgKOrs%3D&blockId=MDAwMDAx&comp=block' \
  -X PUT --data-raw 'hello'
```

returns 
```
< HTTP/1.1 400 Bad Request
< Server: Azurite-Blob/3.14.2
< Date: Tue, 12 Oct 2021 19:05:08 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Content-Length: 0

```

and in the logs: 
```
2021-10-12T19:06:03.206Z 6d6378bb-a3bf-4232-a02a-efde529f95b8 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/todo-todo-todo/2021-10-12-1c9d36af-fe4b-4508-b499-59262042171a/files/test.txt?sv=2020-08-04&spr=https%2Chttp&se=2021-10-13T06%3A47%3A28Z&sr=b&sp=cw&sig=2T4ET3r9cXXA9COYqON9vy%2F4bRuuJInywEAnHYgKOrs%3D&blockId=MDAwMDAx&comp=block RequestHeaders:{"host":"127.0.0.1:10000","user-agent":"curl/7.64.1","accept":"*/*","content-length":"5","content-type":"application/x-www-form-urlencoded"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2021-10-12T19:06:03.206Z 6d6378bb-a3bf-4232-a02a-efde529f95b8 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=todo-todo-todo Blob=2021-10-12-1c9d36af-fe4b-4508-b499-59262042171a/files/test.txt
2021-10-12T19:06:03.206Z 6d6378bb-a3bf-4232-a02a-efde529f95b8 verbose: DispatchMiddleware: Dispatching request...
2021-10-12T19:06:03.208Z 6d6378bb-a3bf-4232-a02a-efde529f95b8 error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2021-10-12T19:06:03.209Z 6d6378bb-a3bf-4232-a02a-efde529f95b8 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-10-12T19:06:03.209Z 6d6378bb-a3bf-4232-a02a-efde529f95b8 error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at Object.dispatchMiddleware [as default] (/Users/wingeier/.nvm/versions/node/v16.11.0/lib/node_modules/azurite/dist/src/blob/generated/middleware/dispatch.middleware.js:41:30)\n    at /Users/wingeier/.nvm/versions/node/v16.11.0/lib/node_modules/azurite/dist/src/blob/generated/ExpressMiddlewareFactory.js:49:42\n    at Layer.handle [as handle_request] (/Users/wingeier/.nvm/versions/node/v16.11.0/lib/node_modules/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/wingeier/.nvm/versions/node/v16.11.0/lib/node_modules/azurite/node_modules/express/lib/router/index.js:317:13)\n    at /Users/wingeier/.nvm/versions/node/v16.11.0/lib/node_modules/azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/Users/wingeier/.nvm/versions/node/v16.11.0/lib/node_modules/azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/Users/wingeier/.nvm/versions/node/v16.11.0/lib/node_modules/azurite/node_modules/express/lib/router/index.js:275:10)\n    at blobStorageContextMiddleware (/Users/wingeier/.nvm/versions/node/v16.11.0/lib/node_modules/azurite/dist/src/blob/middlewares/blobStorageContext.middleware.js:72:5)\n    at /Users/wingeier/.nvm/versions/node/v16.11.0/lib/node_modules/azurite/dist/src/blob/middlewares/blobStorageContext.middleware.js:14:16\n    at Layer.handle [as handle_request] (/Users/wingeier/.nvm/versions/node/v16.11.0/lib/node_modules/azurite/node_modules/express/lib/router/layer.js:95:5)"
2021-10-12T19:06:03.209Z 6d6378bb-a3bf-4232-a02a-efde529f95b8 error: ErrorMiddleware: Set HTTP code: 400
2021-10-12T19:06:03.209Z 6d6378bb-a3bf-4232-a02a-efde529f95b8 error: ErrorMiddleware: Set HTTP body: undefined
2021-10-12T19:06:03.209Z 6d6378bb-a3bf-4232-a02a-efde529f95b8 info: EndMiddleware: End response. TotalTimeInMS=3 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.14.2"}

```

Meanwhile the following request on Azure works: 

```shell
curl  -v 'https://REDACTED.blob.core.windows.net/todo-todo-todo/2021-10-12-c4f417e6-e976-4da8-a3ea-906383467bb6/files/test.txt?sv=2020-08-04&spr=https%2Chttp&se=2021-10-13T06%3A46%3A22Z&sr=b&sp=cw&sig=REDACTED&blockId=MDAwMDAz&comp=block' \
  -X PUT --data-raw 'hello'
```

returns 
```
< HTTP/1.1 201 Created
```

### Have you found a mitigation/solution?

add the header 'x-ms-blob-type: BlockBlob'.

**Comment by blueww** [comment]
Per https://datatracker.ietf.org/doc/html/rfc2616#section-3.2.3

> When comparing two URIs to decide if they match or not, a client
>    SHOULD use a case-sensitive octet-by-octet comparison of the entire
>    URIs

In the [rest doc](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block), the `blockid `is lower case, so Azurite will compare it case-sensitive, and need it  be "blockid" instead of "blockId".
