### ISSUE TITLE
Getting 400 bad request when listing containers using Azure CLI

### ISSUE THREAD

**Issue by johananl** [Azure/Azurite#1100]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the Azurite was used?

`v3.14.2`

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Docker Hub

### What's the Node.js version?

`v14.17.6`

### What problem was encountered?

Running `az storage container list` returns an HTTP 400 instead of a successful response (see debug log for more info).

>NOTE: Other commands such as `az storage container create --name foo` work fine.

### Steps to reproduce the issue?

```
docker run --rm -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite -l /data --blobHost 0.0.0.0 -d /dev/stdout

# On a new shell
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;'
az storage container list
```

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
2021-10-13T13:56:32.937Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/?comp=list&maxresults=5000&include= RequestHeaders:{"host":"127.0.0.1:10000","user-agent":"AZURECLI/2.29.0 azsdk-python-storage-blob/12.7.1 Python/3.9.7 (Linux-5.14.8-arch1-1-x86_64-with-glibc2.33)","accept-encoding":"gzip, deflate","accept":"application/xml","connection":"keep-alive","x-ms-version":"2020-04-08","x-ms-client-request-id":"5f84544e-2c2d-11ec-92bf-181dea191b53","commandname":"storage container list","x-ms-date":"Wed, 13 Oct 2021 13:56:32 GMT","authorization":"SharedKey devstoreaccount1:9tQRPNLXTpHbnvOStvAaU9GkeJBRmvql/MyPlMxGxDU="} ClientIP=172.17.0.1 Protocol=http HTTPVersion=1.1
172.17.0.1 - - [13/Oct/2021:13:56:32 +0000] "GET /devstoreaccount1/?comp=list&maxresults=5000&include= HTTP/1.1" 400 -
2021-10-13T13:56:32.937Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container= Blob=
2021-10-13T13:56:32.938Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b verbose: DispatchMiddleware: Dispatching request...
2021-10-13T13:56:32.940Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b info: DispatchMiddleware: Operation=Service_ListContainersSegment
2021-10-13T13:56:32.942Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2021-10-13T13:56:32.942Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b info: PublicAccessAuthenticator:validate() Start validation against public access.
2021-10-13T13:56:32.942Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b debug: PublicAccessAuthenticator:validate() Getting account properties...
2021-10-13T13:56:32.942Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: , blob:
2021-10-13T13:56:32.947Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container
2021-10-13T13:56:32.948Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2021-10-13T13:56:32.965Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:5f84544e-2c2d-11ec-92bf-181dea191b53\nx-ms-date:Wed, 13 Oct 2021 13:56:32 GMT\nx-ms-version:2020-04-08\n/devstoreaccount1/devstoreaccount1/\ncomp:list\ninclude:\nmaxresults:5000"
2021-10-13T13:56:32.966Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:9tQRPNLXTpHbnvOStvAaU9GkeJBRmvql/MyPlMxGxDU=
2021-10-13T13:56:32.966Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2021-10-13T13:56:32.966Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b verbose: DeserializerMiddleware: Start deserializing...
2021-10-13T13:56:32.968Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-10-13T13:56:32.968Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b error: ErrorMiddleware: ErrorName=DeserializationError ErrorMessage= is not a valid value for include. The valid values are: ["metadata"].  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="Error:  is not a valid value for include. The valid values are: [\"metadata\"].\n    at serializeEnumType (/opt/azurite/node_modules/@azure/ms-rest-js/dist/msRest.node.js:749:15)\n    at Serializer.serialize (/opt/azurite/node_modules/@azure/ms-rest-js/dist/msRest.node.js:529:27)\n    at Object.deserialize (/opt/azurite/dist/src/blob/generated/utils/serializer.js:26:25)\n    at Object.deserializerMiddleware [as default] (/opt/azurite/dist/src/blob/generated/middleware/deserializer.middleware.js:29:18)\n    at /opt/azurite/dist/src/blob/generated/ExpressMiddlewareFactory.js:62:46\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:317:13)\n    at /opt/azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:275:10)"
2021-10-13T13:56:32.968Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b error: ErrorMiddleware: Set HTTP code: 400
2021-10-13T13:56:32.968Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b error: ErrorMiddleware: Set HTTP body: undefined
2021-10-13T13:56:32.969Z 4b6642b0-88cb-45d3-b26b-3b40b0c75e2b info: EndMiddleware: End response. TotalTimeInMS=32 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.14.2"}
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?

Yes, using Azure Storage Explorer instead of Azure CLI.

**Comment by blueww** [comment]
@johananl 
This is same issue as https://github.com/Azure/Azurite/issues/813.

Fix PR https://github.com/Azure/Azurite/pull/1063/files is already merged.
The issue will be fixed in the next Azurite release.

Do you mind to close this issue?
Feel free to contact us again if need any further support on Azurite.

**Comment by johananl** [comment]
Thanks @blueww. Closing.
