### ISSUE TITLE
PANIC when posting new message to queue

### ISSUE THREAD

**Issue by inganesa** [Azure/Azurite#114]
When I tried to post a new message to queue using Curl, I see a PANIC in azurite.
This is what I tried
1. Create queue
2. List queue
3. Put message

curl -X PUT http://127.0.0.1:10001/devstoreaccount1/myqueue

curl http://127.0.0.1:10001/devstoreaccount1?comp=list
<?xml version="1.0" encoding="utf-8"?><EnumerationResults ServiceEndpoint="http://localhost:10001/devstoreaccount1"><Queues><Queue><Name>myqueue</Name></Queue></Queues><NextMarker/></EnumerationResults>

curl http://127.0.0.1:10001/devstoreaccount1/myqueue/messages -X POST --data "message-content"
curl: (52) Empty reply from server

from azurite:
PUT /devstoreaccount1/myqueue 201 0.774 ms - -
GET /devstoreaccount1?comp=list 200 1.492 ms - 202
**PANIC** Something unexpected happened! Queue Storage Emulator may be in an inconsistent state!
{ Error: <?xml version="1.0" encoding="utf-8"?><Error><Code>Invalid XML.</Code><Message>One of the XML nodes specified in the request body is not supported.</Message></Error>
    at xml2jsAsync.then.catch (/usr/local/lib/node_modules/azurite/lib/xml/queue/QueueMessageText.js:26:15)
    at tryCatcher (/usr/local/lib/node_modules/azurite/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/azurite/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/azurite/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/azurite/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/azurite/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/usr/local/lib/node_modules/azurite/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/azurite/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/azurite/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/azurite/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
  errorCode: 'Invalid XML.',
  statusCode: 400,
  messageContentType: 'application/xml' }
POST /devstoreaccount1/myqueue/messages - - ms - -

**Comment by XiaoningLiu** [comment]
The put message body is in XML format instead of a plain text. https://docs.microsoft.com/en-us/rest/api/storageservices/put-message
