### ISSUE TITLE
There was an error performing a read operation on the Blob Storage Secret Repository. Please ensure the 'AzureWebJobsStorage' connection string is valid.

### ISSUE THREAD

**Issue by calloncampbell** [Azure/Azurite#1179]
### Which service(blob, file, queue, table) does this issue concern?
My guess is all of them the error message, but I'm only using queue from my app.

### Which version of the Azurite was used?
3.14.3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Came with VS2022. I then uninstall from NPM and reinstall from NPM to v3.14.3

### What's the Node.js version?
v14.18.1.

### What problem was encountered?
Trying to debug my azure function app in VS2022 and on startup I get the above error. I don't get this error on any other function app debug session.

### Steps to reproduce the issue?
Press F5

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "FunctionStorageBindings-StorageConnectionString": "REDACTED",
    "AzureAppConfiguration.ConnectionString_PrimaryStore": "REDACTED",
    "AzureAppConfiguration.ConnectionString_SecondaryStore": "REDACTED",
    "AzureAppConfiguration.CacheExpirationTimeInSeconds": 120,
    "AzureAppConfiguration.EnvironmentLabel": "LabA",
    "DurableTaskHubName": "BulkEditProcessorDEV2",
    "DurableManagementStorage": "UseDevelopmentStorage=true",
    "AzureWebJobs.ProcessBulkEditQueue.Disabled": 0
  }
}
```

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
@calloncampbell 

Would you please share the Azurite debug log, we need it for investigation?

**Comment by calloncampbell** [comment]
Hi @blueww I cleared my debug.log file in `C:\Users\ccampbell\AppData\Local\Temp\Azurite` and restarted VS2022 and tried to debug the function app, I got the same error. Here is the log file.

[debug.log](https://github.com/Azure/Azurite/files/7571305/debug.log)

I was able to get it to work magically last night on this project, but then encountered the same issue with another function app and then again with the reported function app just now. It doesn't seem to be an issue in VS2019.

**Comment by calloncampbell** [comment]
Just an update, if I delete or rename this folder `C:\Users\ccampbell\AppData\Local\Temp\Azurite` I'm able to get past this issue and the function app works locally again.

**Comment by blueww** [comment]
@calloncampbell 
Thanks for the reply!
From the debug log, we see the error is "Error: ENOENT: no such file or directory, open 'C:\\Users\\ccampbell\\AppData\\Local\\Temp\\Azurite\\__blobstorage__\\93e1dd6c-5675-44be-a20f-7168e3618dcc'".

But the debug log only contains get the file fail, not contain how the file is created/removed. 
Would you give the full debug log from remove the folder C:\Users\ccampbell\AppData\Local\Temp\Azurite, to the issue repro? So we can see why Azurite need the file, but the file doesn't exist.

**Comment by calloncampbell** [comment]
@blueww that is what I did. The log file attached is after I deleted the temp Azurite directory and then reproducing the issue. I'm still getting the issue once and while, but deleting the folder helps reset for sure until the issue happens again.

**Comment by blueww** [comment]
@calloncampbell 
Thanks for the confirmation!
It's interesting we didn't see the file created in the log, but azurite try to get it.
We will continue look at it.

**Comment by calloncampbell** [comment]
@blueww let me know if there is anything I can do to help.

**Comment by blueww** [comment]
@calloncampbell 
Would you please confirm do you use SQL server for Azurite？(Have you set the environment variable "AZURITE_DB"?)
And could you share the command you used to start Azurite? (hide any credential.)

**Comment by a99cl208** [comment]
@calloncampbell I ran into the same issue. It killed the azurite process that is started with visual studio, then restarted it using a command line with admin privilege. Then it worked, so it is maybe a security related issue.

**Comment by OzBob** [comment]
i have the same issue. If I create a new v3 AzFn solution and project with VS2022, and copy all the code from my 'broken' project, it works perfectly. I tried deleting the .vs folder from the 'broken' project but still same issue.

**Comment by mkellyelumus** [comment]
> @calloncampbell I ran into the same issue. It killed the azurite process that is started with visual studio, then restarted it using a command line with admin privilege. Then it worked, so it is maybe a security related issue.

FWIW, this fix/work-around resolved the issue for me as well.

**Comment by yhs666** [comment]
I found some process used network port 10000 maybe impacted azurite start.

![image](https://user-images.githubusercontent.com/3980889/149623619-cc114151-dbd3-4d5a-aebe-c9ddca9d2f41.png)

**Comment by calloncampbell** [comment]
@blueww 
The issue I originally reported hasn't happened in a while but every now and then I do get the port in use issue that has also been reported above. For me, the port is usually in use by NodeJs. After terminating the process Azurite starts up correctly. 

For context Visual Studio 2022 is the one starting up Azurite storage emulator when working with Azure Functions app.

**Comment by calloncampbell** [comment]
> @calloncampbell Would you please confirm do you use SQL server for Azurite？(Have you set the environment variable "AZURITE_DB"?) And could you share the command you used to start Azurite? (hide any credential.)

No I'm not using SQL Server for Azurite. 

Azurite is starting with Visual Studio 2022. Here is what shows up in the Output window for "Service Dependencies":

```
Ensuring Azure Functions Core Tools are up to date. This may take a few minutes...
Azure Functions Core Tools are up to date.
DotNetCore31-FunctionApp: azurite.cmd --location "C:\Users\ccampbell\AppData\Local\Temp\Azurite" --debug "C:\Users\ccampbell\AppData\Local\Temp\Azurite\debug.log"
DotNetCore31-FunctionApp: Azurite Blob service is starting at http://127.0.0.1:10000
DotNetCore31-FunctionApp: Azurite Blob service is successfully listening at http://127.0.0.1:10000
DotNetCore31-FunctionApp: Azurite Queue service is starting at http://127.0.0.1:10001
DotNetCore31-FunctionApp: Azurite Queue service is successfully listening at http://127.0.0.1:10001
DotNetCore31-FunctionApp: Azurite Table service is starting at http://127.0.0.1:10002
DotNetCore31-FunctionApp: Azurite Table service is successfully listening at http://127.0.0.1:10002
```

**Comment by blueww** [comment]
@calloncampbell 

Thanks for the information!
Good to know the original issue not repro now.
For the port occupied issue, Azurite need to list on specific port, and the port need be not occupied. So it's expected that Azurite report error if the port is occupied. Please make sure the port Azurite use is not occupied before start Azurite.

**Comment by calloncampbell** [comment]
@blueww 

Could we not change the default ports to something not being used by such a common framework like NodeJS.

**Comment by blueww** [comment]
@calloncampbell 
The default port has been used for a long time from the before version of storage emulator.
We don't plan to change it, or might block many existing customer.

If you can input parameter when start Azurite, you can use the customized port to avoid the port been occupied issue. 
https://github.com/Azure/Azurite#listening-host-configuration

**Comment by zakkra** [comment]
How is durable function going to know about new port used for storage?
Is there a way to specify this new port in the storage connection string i.e. "AzureWebJobsStorage": "UseDevelopmentStorage=true"

**Comment by blueww** [comment]
@zakkra 

For connection string, you can also use a connection string like following, and update the endpoing port to the real port you are using, see more details in https://github.com/Azure/Azurite#connection-strings:
"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;"

**Comment by Power-Maverick** [comment]
I tired to delete the Azurite folder but still facing the same issue.

System.InvalidOperationException
  HResult=0x80131509
  Message=Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.
  Source=Microsoft.Azure.WebJobs.Script.WebHost
  StackTrace:
   at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.CreateSecretsRepository()
   at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.Create()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.get_Current()
   at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptWebHookProvider.<GetOrCreateExtensionKey>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptWebHookProvider.GetExtensionWebHookRoute(String extensionName)
   at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptWebHookProvider.GetUrl(IExtensionConfigProvider extension)
   at Microsoft.Azure.WebJobs.Host.Config.ExtensionConfigContext.GetWebhookHandler() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Config\ExtensionConfigContext.cs:line 55
   at Microsoft.Azure.WebJobs.Extensions.EventGrid.EventGridExtensionConfigProvider.Initialize(ExtensionConfigContext context)
   at Microsoft.Azure.WebJobs.Host.DefaultExtensionRegistryFactory.Create() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\DefaultExtensionRegistryFactory.cs:line 38
   at Microsoft.Azure.WebJobs.WebJobsServiceCollectionExtensions.<>c.<AddWebJobs>b__2_0(IServiceProvider p) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsServiceCollectionExtensions.cs:line 57
   at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r)
   at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r)
   at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2()
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Factory.GetDelegateOrDefault(Request request)
   at DryIoc.DelegateFactory.GetDelegateOrDefault(Request request)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args)
   at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2()
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Factory.GetDelegateOrDefault(Request request)
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved)
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Azure.WebJobs.WebJobsServiceCollectionExtensions.<>c.<AddWebJobs>b__2_6(IServiceProvider p) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsServiceCollectionExtensions.cs:line 97
   at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r)
   at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r)
   at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2()
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Factory.GetDelegateOrDefault(Request request)
   at DryIoc.DelegateFactory.GetDelegateOrDefault(Request request)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args)
   at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2()
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Factory.GetDelegateOrDefault(Request request)
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved)
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.<UnsynchronizedStartHostAsync>d__52.MoveNext()

  This exception was originally thrown at this call stack:
    [External Code]
    Microsoft.Azure.WebJobs.Host.Config.ExtensionConfigContext.GetWebhookHandler() in ExtensionConfigContext.cs
    [External Code]
    Microsoft.Azure.WebJobs.Host.DefaultExtensionRegistryFactory.Create() in DefaultExtensionRegistryFactory.cs
    Microsoft.Azure.WebJobs.WebJobsServiceCollectionExtensions.AddWebJobs.AnonymousMethod__2_0(System.IServiceProvider) in WebJobsServiceCollectionExtensions.cs
    [External Code]
    Microsoft.Azure.WebJobs.WebJobsServiceCollectionExtensions.AddWebJobs.AnonymousMethod__2_6(System.IServiceProvider) in WebJobsServiceCollectionExtensions.cs
    [External Code]

**Comment by angeljoel740604** [comment]
> @blueww
> 
> Could we not change the default ports to something not being used by such a common framework like NodeJS.

**Comment by Asier-Villanueva** [comment]
I have the same issue. As a workaround I have added in my local.settings.json a new setting "AzureWebJobsSecretStorageType" setting the value to "files":

`"AzureWebJobsSecretStorageType": "files"`
