### ISSUE TITLE
Delete Fails with Empty PartitionKey

### ISSUE THREAD

**Issue by jezzsantos** [Azure/Azurite#1201]
### Which service(blob, file, queue, table) does this issue concern?
Table service
### Which version of the Azurite was used?
3.14.3
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm install

### What's the Node.js version?
16.13.1

### What problem was encountered?
Exception when deleting a row in a table that has an empty PartitionKey.

"The values are not specified for all properties in the entity"

### Steps to reproduce the issue?

Create a new row in any table that has an empty PartitionKey and populated RowKey.
(Can also do this in Storage Explorer)

Try deleting using Storage Explorer. Error...
Try and delete the row using `TableOperation.Delete` (SDK: Microsoft.Azure.Cosmos.Table v.1.0.7). Error....

---
Error from Storage Explorer:

Deleting entities from table 'devstoreaccount1/Bananas': Failed: The values are not specified for all properties in the entity.
RequestId:09eaae2a-2819-44a8-aee7-44320ef0d827
Time:2021-12-07T03:59:16.515Z

---
Error from Microsoft.Azure.Cosmos.Table (SDK):

Microsoft.Azure.Cosmos.Table.StorageException: Element 0 in the batch returned an unexpected response code.
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.<>c__DisplayClass0_0`1.<ExecuteSync>b__0()
   at Microsoft.Azure.Cosmos.Table.RestExecutor.Utils.RestUtility.RunWithoutSynchronizationContext[T](Func`1 actionToRun)
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableRestExecutor.ExecuteTableBatchOperation[TResult](TableBatchOperation operation, CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.Azure.Cosmos.Table.TableBatchOperation.Execute(CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.Azure.Cosmos.Table.CloudTable.ExecuteBatch(TableBatchOperation batch, TableRequestOptions requestOptions, OperationContext operationContext)
   at Infrastructure.Storage.Azure.AzureTableStorageRepository.<>c__DisplayClass16_0.<DestroyAll>g__Command|2(TableBatchOperation batch) in C:\Projects\endgame\boost\src\Infrastructure.Storage.Azure\AzureTableStorageRepository.cs:line 168
Request Information
RequestID:083ac65a-0d18-452a-8496-309ce1346481
RequestDate:Mon, 06 Dec 2021 00:54:47 GMT
StatusMessage:The values are not specified for all properties in the entity.
ErrorCode:
ErrorMessage:The values are not specified for all properties in the entity.
RequestId:083ac65a-0d18-452a-8496-309ce1346481
Time:2021-12-06T00:54:47.987Z

### Have you found a mitigation/solution?
No

**Comment by MatthewSteeples** [comment]
This also applies to empty string RowKeys as well

**Comment by edwin-huber** [comment]
Thanks for reporting this.
We have a few related issues to empty partition or row keys and the cosmos SDK.
I'm adding testing for these cases and shall address.
