### ISSUE TITLE
Empty partition key causes errors in table batch operations

### ISSUE THREAD

**Issue by joelverhagen** [Azure/Azurite#1234]
### Which service(blob, file, queue, table) does this issue concern?

table

### Which version of the Azurite was used?

Locally running version of #1157

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Git clone

### What's the Node.js version?

16.13.0

### What problem was encountered?

When a table batch action (e.g. update-replace) contains an empty string partition key, an exception is thrown.

```
Unhandled exception. Azure.Data.Tables.TableTransactionFailedException: The specified table name is empty.
RequestId:40ec2c98-a25d-4a62-8130-e03b2bb3d7dd
Time:2021-12-19T07:30:17.983Z
Status: 400 (Bad Request)
ErrorCode: TableNameEmpty

Content:
{"odata.error":{"code":"TableNameEmpty","message":{"lang":"en-US","value":"The specified table name is empty.\nRequestId:40ec2c98-a25d-4a62-8130-e03b2bb3d7dd\nTime:2021-12-19T07:30:17.983Z"}}}

Headers:
Content-ID: REDACTED
DataServiceVersion: 3.0;
Content-Type: application/json;odata=minimalmetadata;charset=utf-8

   at Azure.Data.Tables.TableRestClient.SendBatchRequest(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Data.Tables.TableClient.SubmitTransaction(IEnumerable`1 transactionActions, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\joelv\Desktop\AzuriteSample\AzuriteSample\Program.cs:line 9
```

### Steps to reproduce the issue?

```csharp
using Azure.Data.Tables;

var tableClient = new TableServiceClient("UseDevelopmentStorage=true");
var table = tableClient.GetTableClient("table0");
table.Delete();
table.Create();
table.AddEntity(new TableEntity("", "RK1"));
table.SubmitTransaction(new[]
{
    new TableTransactionAction(TableTransactionActionType.UpdateReplace, new TableEntity("", "RK1")),
});
```

```
2021-12-19T07:31:18.640Z 	 info: Azurite Blob service is starting on 127.0.0.1:10000
2021-12-19T07:31:18.648Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-12-19T07:31:18.649Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-12-19T07:31:18.695Z 	 info: BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2021-12-19T07:31:18.696Z 	 info: BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2021-12-19T07:31:18.696Z 	 info: BlobGCManager:markSweepLoop() Start next mark and sweep.
2021-12-19T07:31:18.696Z 	 info: BlobGCManager:markSweep() Get all extents.
2021-12-19T07:31:18.698Z 	 info: BlobGCManager:start() BlobGCManager successfully started.
2021-12-19T07:31:18.710Z 	 info: BlobGCManager:markSweep() Got 17 extents.
2021-12-19T07:31:18.711Z 	 info: BlobGCManager:markSweep() Get referred extents.
2021-12-19T07:31:18.714Z 	 info: BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2021-12-19T07:31:18.715Z 	 info: BlobGCManager:markSweepLoop() Mark and sweep finished, taken 19ms.
2021-12-19T07:31:18.715Z 	 info: BlobGCManager:markSweepLoop() Sleep for 600000ms.
2021-12-19T07:31:18.718Z 	 info: Azurite Blob service successfully listens on http://127.0.0.1:10000
2021-12-19T07:31:18.719Z 	 info: Azurite Queue service is starting on 127.0.0.1:10001
2021-12-19T07:31:18.719Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-12-19T07:31:18.720Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-12-19T07:31:18.757Z 	 info: QueueGCManager:start() Starting QueueGCManager, set status to Initializing
2021-12-19T07:31:18.757Z 	 info: QueueGCManager:start() Trigger mark and sweep loop, set status to Running.
2021-12-19T07:31:18.757Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2021-12-19T07:31:18.757Z 	 info: QueueGCManger:markSweep() Get all extents.
2021-12-19T07:31:18.758Z 	 info: QueueGCManager:start() QueueGCManager successfully started.
2021-12-19T07:31:18.758Z 	 info: QueueGCManager:marksweep() Get 4 extents.
2021-12-19T07:31:18.758Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2021-12-19T07:31:18.759Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2021-12-19T07:31:18.759Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 2ms.
2021-12-19T07:31:18.759Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2021-12-19T07:31:18.761Z 	 info: Azurite Queue service successfully listens on http://127.0.0.1:10001
2021-12-19T07:31:18.761Z 	 info: Azurite Table service is starting on 127.0.0.1:10002
2021-12-19T07:31:18.762Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-12-19T07:31:18.762Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-12-19T07:31:18.867Z 	 info: Azurite Table service successfully listens on http://127.0.0.1:10002
2021-12-19T07:31:30.410Z 4ca8af4c-bf29-4543-8f83-f300202cad52 info: TableStorageContextMiddleware: RequestMethod=DELETE RequestURL=http://127.0.0.1/devstoreaccount1/Tables('table0') RequestHeaders:{"host":"127.0.0.1:10002","x-ms-version":"2019-02-02","accept":"application/json","x-ms-client-request-id":"1cf861ff-c1f1-48bf-a678-0f53305e866d","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Data.Tables/12.3.0 (.NET 6.0.0-rtm.21522.10; Microsoft Windows 10.0.22000)","x-ms-date":"Sun, 19 Dec 2021 07:31:30 GMT","authorization":"SharedKeyLite devstoreaccount1:8DZwtpZ8nUokyRgByB0qugVcoKGFCFvIjED6aMc8dEY="} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2021-12-19T07:31:30.411Z 4ca8af4c-bf29-4543-8f83-f300202cad52 debug: tableStorageContextMiddleware: Dispatch pattern string: /Tables('table0')
2021-12-19T07:31:30.411Z 4ca8af4c-bf29-4543-8f83-f300202cad52 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=table0
2021-12-19T07:31:30.411Z 4ca8af4c-bf29-4543-8f83-f300202cad52 verbose: DispatchMiddleware: Dispatching request...
2021-12-19T07:31:30.413Z 4ca8af4c-bf29-4543-8f83-f300202cad52 info: DispatchMiddleware: Operation=Table_Delete
2021-12-19T07:31:30.413Z 4ca8af4c-bf29-4543-8f83-f300202cad52 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2021-12-19T07:31:30.414Z 4ca8af4c-bf29-4543-8f83-f300202cad52 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2021-12-19T07:31:30.415Z 4ca8af4c-bf29-4543-8f83-f300202cad52 info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Sun, 19 Dec 2021 07:31:30 GMT\n/devstoreaccount1/devstoreaccount1/Tables('table0')"
2021-12-19T07:31:30.415Z 4ca8af4c-bf29-4543-8f83-f300202cad52 info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:8DZwtpZ8nUokyRgByB0qugVcoKGFCFvIjED6aMc8dEY=
2021-12-19T07:31:30.416Z 4ca8af4c-bf29-4543-8f83-f300202cad52 info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
2021-12-19T07:31:30.417Z 4ca8af4c-bf29-4543-8f83-f300202cad52 verbose: DeserializerMiddleware: Start deserializing...
2021-12-19T07:31:30.419Z 4ca8af4c-bf29-4543-8f83-f300202cad52 info: HandlerMiddleware: DeserializedParameters={"version":"2019-02-02","options":{"requestId":"1cf861ff-c1f1-48bf-a678-0f53305e866d"}}
2021-12-19T07:31:30.423Z 4ca8af4c-bf29-4543-8f83-f300202cad52 verbose: SerializerMiddleware: Start serializing...
2021-12-19T07:31:30.424Z 4ca8af4c-bf29-4543-8f83-f300202cad52 info: EndMiddleware: End response. TotalTimeInMS=14 StatusCode=204 StatusMessage=undefined Headers={"server":"Azurite-Table/3.15.0","content-type":"application/json;odata=minimalmetadata","x-ms-client-request-id":"1cf861ff-c1f1-48bf-a678-0f53305e866d","x-ms-request-id":"4ca8af4c-bf29-4543-8f83-f300202cad52","x-ms-version":"2021-02-12","date":"Sun, 19 Dec 2021 07:31:30 GMT"}
2021-12-19T07:31:30.447Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 info: TableStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/Tables?$format=application%2Fjson%3Bodata%3Dminimalmetadata RequestHeaders:{"host":"127.0.0.1:10002","x-ms-version":"2019-02-02","dataserviceversion":"3.0","accept":"application/json;odata=minimalmetadata","x-ms-client-request-id":"2adeb208-2245-4461-8e45-0f83d63dd2b2","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Data.Tables/12.3.0 (.NET 6.0.0-rtm.21522.10; Microsoft Windows 10.0.22000)","x-ms-date":"Sun, 19 Dec 2021 07:31:30 GMT","authorization":"SharedKeyLite devstoreaccount1:FY0ClVLO391XMFPHX9g4zlYdI0qCYgQdMV8bZXU3Bqg=","content-type":"application/json;odata=nometadata","content-length":"22"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2021-12-19T07:31:30.447Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 debug: tableStorageContextMiddleware: Dispatch pattern string: /Tables
2021-12-19T07:31:30.447Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=undefined
2021-12-19T07:31:30.447Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 verbose: DispatchMiddleware: Dispatching request...
2021-12-19T07:31:30.448Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 info: DispatchMiddleware: Operation=Table_Create
2021-12-19T07:31:30.448Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2021-12-19T07:31:30.448Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2021-12-19T07:31:30.448Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Sun, 19 Dec 2021 07:31:30 GMT\n/devstoreaccount1/devstoreaccount1/Tables"
2021-12-19T07:31:30.448Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:FY0ClVLO391XMFPHX9g4zlYdI0qCYgQdMV8bZXU3Bqg=
2021-12-19T07:31:30.448Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
2021-12-19T07:31:30.449Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 verbose: DeserializerMiddleware: Start deserializing...
2021-12-19T07:31:30.450Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 debug: deserialize(): Raw request body string is (removed all empty characters) {"TableName":"table0"}
2021-12-19T07:31:30.451Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"format":"application/json;odata=minimalmetadata"},"requestId":"2adeb208-2245-4461-8e45-0f83d63dd2b2","dataServiceVersion":"3.0"},"version":"2019-02-02","tableProperties":{"tableName":"table0"},"body":"ReadableStream"}
2021-12-19T07:31:30.453Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 verbose: SerializerMiddleware: Start serializing...
2021-12-19T07:31:30.454Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 debug: Serializer: Raw response body string is {"odata.metadata":"http://127.0.0.1:10002/devstoreaccount1/$metadata#Tables/@Element","TableName":"table0"}
2021-12-19T07:31:30.454Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 info: Serializer: Start returning stream body.
2021-12-19T07:31:30.455Z dffb3ff8-4d23-4358-b083-d8c41bb8e113 info: EndMiddleware: End response. TotalTimeInMS=7 StatusCode=201 StatusMessage=Created Headers={"server":"Azurite-Table/3.15.0","content-type":"application/json;odata=minimalmetadata","x-ms-client-request-id":"2adeb208-2245-4461-8e45-0f83d63dd2b2","x-ms-request-id":"dffb3ff8-4d23-4358-b083-d8c41bb8e113","x-ms-version":"2021-02-12","date":"Sun, 19 Dec 2021 07:31:30 GMT","preference-applied":"return-content"}
2021-12-19T07:31:30.488Z e4c39a84-18b7-4cdf-8aed-95b936ace398 info: TableStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/table0?$format=application%2Fjson%3Bodata%3Dminimalmetadata RequestHeaders:{"host":"127.0.0.1:10002","x-ms-version":"2019-02-02","dataserviceversion":"3.0","prefer":"return-no-content","accept":"application/json;odata=minimalmetadata","x-ms-client-request-id":"735dc67f-7051-40af-9eb1-4eae701fa1fb","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Data.Tables/12.3.0 (.NET 6.0.0-rtm.21522.10; Microsoft Windows 10.0.22000)","x-ms-date":"Sun, 19 Dec 2021 07:31:30 GMT","authorization":"SharedKeyLite devstoreaccount1:eicyK6yH0vqX9LrbS3M61O5ELRqsztn6csKrKdSqIg4=","content-type":"application/json;odata=nometadata","content-length":"34"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2021-12-19T07:31:30.488Z e4c39a84-18b7-4cdf-8aed-95b936ace398 debug: tableStorageContextMiddleware: Dispatch pattern string: /table0
2021-12-19T07:31:30.488Z e4c39a84-18b7-4cdf-8aed-95b936ace398 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=table0
2021-12-19T07:31:30.488Z e4c39a84-18b7-4cdf-8aed-95b936ace398 verbose: DispatchMiddleware: Dispatching request...
2021-12-19T07:31:30.488Z e4c39a84-18b7-4cdf-8aed-95b936ace398 info: DispatchMiddleware: Operation=Table_InsertEntity
2021-12-19T07:31:30.489Z e4c39a84-18b7-4cdf-8aed-95b936ace398 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2021-12-19T07:31:30.489Z e4c39a84-18b7-4cdf-8aed-95b936ace398 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2021-12-19T07:31:30.489Z e4c39a84-18b7-4cdf-8aed-95b936ace398 info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Sun, 19 Dec 2021 07:31:30 GMT\n/devstoreaccount1/devstoreaccount1/table0"
2021-12-19T07:31:30.489Z e4c39a84-18b7-4cdf-8aed-95b936ace398 info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:eicyK6yH0vqX9LrbS3M61O5ELRqsztn6csKrKdSqIg4=
2021-12-19T07:31:30.489Z e4c39a84-18b7-4cdf-8aed-95b936ace398 info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
2021-12-19T07:31:30.490Z e4c39a84-18b7-4cdf-8aed-95b936ace398 verbose: DeserializerMiddleware: Start deserializing...
2021-12-19T07:31:30.490Z e4c39a84-18b7-4cdf-8aed-95b936ace398 debug: deserialize(): Raw request body string is (removed all empty characters) {"PartitionKey":"","RowKey":"RK1"}
2021-12-19T07:31:30.491Z e4c39a84-18b7-4cdf-8aed-95b936ace398 info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"format":"application/json;odata=minimalmetadata"},"requestId":"735dc67f-7051-40af-9eb1-4eae701fa1fb","dataServiceVersion":"3.0","responsePreference":"return-no-content","tableEntityProperties":{"PartitionKey":"","RowKey":"RK1"}},"version":"2019-02-02","body":"ReadableStream"}
2021-12-19T07:31:30.493Z e4c39a84-18b7-4cdf-8aed-95b936ace398 verbose: SerializerMiddleware: Start serializing...
2021-12-19T07:31:30.493Z e4c39a84-18b7-4cdf-8aed-95b936ace398 info: EndMiddleware: End response. TotalTimeInMS=6 StatusCode=204 StatusMessage=undefined Headers={"server":"Azurite-Table/3.15.0","content-type":"application/json;odata=minimalmetadata","x-ms-client-request-id":"735dc67f-7051-40af-9eb1-4eae701fa1fb","x-ms-request-id":"e4c39a84-18b7-4cdf-8aed-95b936ace398","x-ms-version":"2021-02-12","date":"Sun, 19 Dec 2021 07:31:30 GMT","etag":"W/\"datetime'2021-12-19T07%3A31%3A30.4870000Z'\"","preference-applied":"return-no-content"}
2021-12-19T07:31:30.515Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 info: TableStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/$batch RequestHeaders:{"host":"127.0.0.1:10002","x-ms-version":"2019-02-02","dataserviceversion":"3.0","accept":"application/json","x-ms-client-request-id":"b37bab60-c006-4895-bde0-c13969166bd9","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Data.Tables/12.3.0 (.NET 6.0.0-rtm.21522.10; Microsoft Windows 10.0.22000)","x-ms-date":"Sun, 19 Dec 2021 07:31:30 GMT","authorization":"SharedKeyLite devstoreaccount1:EJMIfIlLyXmQDipoU8bJVMZieUBcsMSH4M/6q7GFLHQ=","content-type":"multipart/mixed; boundary=batch_8a1d6b1c-1591-42a7-b720-d1d8fba562e7","content-length":"665"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2021-12-19T07:31:30.515Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 debug: tableStorageContextMiddleware: Dispatch pattern string: /$batch
2021-12-19T07:31:30.515Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=$batch
2021-12-19T07:31:30.515Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 verbose: DispatchMiddleware: Dispatching request...
2021-12-19T07:31:30.516Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 info: DispatchMiddleware: Operation=Table_Batch
2021-12-19T07:31:30.516Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2021-12-19T07:31:30.516Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2021-12-19T07:31:30.516Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Sun, 19 Dec 2021 07:31:30 GMT\n/devstoreaccount1/devstoreaccount1/$batch"
2021-12-19T07:31:30.516Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:EJMIfIlLyXmQDipoU8bJVMZieUBcsMSH4M/6q7GFLHQ=
2021-12-19T07:31:30.516Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
2021-12-19T07:31:30.516Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 verbose: DeserializerMiddleware: Start deserializing...
2021-12-19T07:31:30.516Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 info: HandlerMiddleware: DeserializedParameters={"version":"2019-02-02","options":{"requestId":"b37bab60-c006-4895-bde0-c13969166bd9","dataServiceVersion":"3.0"},"multipartContentType":"multipart/mixed; boundary=batch_8a1d6b1c-1591-42a7-b720-d1d8fba562e7","contentLength":665,"body":"ReadableStream"}
2021-12-19T07:31:30.518Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 debug: TableHandler:batch() Raw request string is "--batch_8a1d6b1c-1591-42a7-b720-d1d8fba562e7\r\nContent-Type: multipart/mixed; boundary=changeset_96f0d34b-9354-45e4-b595-404b4b5bdf32\r\n\r\n--changeset_96f0d34b-9354-45e4-b595-404b4b5bdf32\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nPUT http://127.0.0.1:10002/devstoreaccount1/table0(PartitionKey='',RowKey='RK1')?$format=application%2Fjson%3Bodata%3Dminimalmetadata HTTP/1.1\r\nHost: 127.0.0.1\r\nx-ms-version: 2019-02-02\r\nDataServiceVersion: 3.0\r\nAccept: application/json\r\nContent-Type: application/json\r\n\r\n{\"PartitionKey\":\"\",\"RowKey\":\"RK1\"}\r\n--changeset_96f0d34b-9354-45e4-b595-404b4b5bdf32--\r\n\r\n--batch_8a1d6b1c-1591-42a7-b720-d1d8fba562e7--\r\n"
2021-12-19T07:31:30.522Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 debug: TableHandler:batch() Raw response string is "--batchresponse_8a1d6b1c-1591-42a7-b720-d1d8fba562e7\r\nContent-Type: multipart/mixed; boundary=changesetresponse_96f0d34b-9354-45e4-b595-404b4b5bdf32\r\n\r\n--changesetresponse_96f0d34b-9354-45e4-b595-404b4b5bdf32\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nHTTP/1.1 400 Bad Request\r\nContent-ID: 1\r\nDataServiceVersion: 3.0;\r\nContent-Type: application/json;odata=minimalmetadata;charset=utf-8\r\n\r\n{\"odata.error\":{\"code\":\"TableNameEmpty\",\"message\":{\"lang\":\"en-US\",\"value\":\"The specified table name is empty.\\nRequestId:2b53c62d-af74-4d71-87cf-618f2ee2eb20\\nTime:2021-12-19T07:31:30.522Z\"}}}\r\n--changesetresponse_96f0d34b-9354-45e4-b595-404b4b5bdf32--\r\n--batchresponse_8a1d6b1c-1591-42a7-b720-d1d8fba562e7--\r\n"
2021-12-19T07:31:30.523Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 verbose: SerializerMiddleware: Start serializing...
2021-12-19T07:31:30.523Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 info: Serializer: Start returning stream body.
2021-12-19T07:31:30.526Z 2b53c62d-af74-4d71-87cf-618f2ee2eb20 info: EndMiddleware: End response. TotalTimeInMS=11 StatusCode=202 StatusMessage=Accepted Headers={"server":"Azurite-Table/3.15.0","content-type":"multipart/mixed; boundary=batchresponse_8a1d6b1c-1591-42a7-b720-d1d8fba562e7","x-ms-request-id":"2b53c62d-af74-4d71-87cf-618f2ee2eb20","x-ms-version":"2021-02-12","date":"Sun, 19 Dec 2021 07:31:30 GMT"}
2021-12-19T07:31:37.269Z 	 info: Azurite Blob service is closing...
2021-12-19T07:31:37.270Z 	 info: Azurite Queue service is closing...
2021-12-19T07:31:37.271Z 	 info: Azurite Table service is closing...
2021-12-19T07:31:37.274Z 	 info: BlobGCManager:close() Start closing BlobGCManager. Set status to Closing.
2021-12-19T07:31:37.274Z 	 info: QueueGCManager:close() Start closing QueueGCManager, set status to Closing.
2021-12-19T07:31:37.275Z 	 info: BlobGCManager:start() Mark and sweep loop is closed.
2021-12-19T07:31:37.275Z 	 info: BlobGCManager:close() BlobGCManager successfully closed. Set status to Closed.
2021-12-19T07:31:37.275Z 	 info: QueueGCManager:start() Mark and sweep loop is closed.
2021-12-19T07:31:37.275Z 	 info: QueueGCManager:close() QueueGCManager successfully closed, set status to Closed.
2021-12-19T07:31:37.275Z 	 info: Azurite Table service successfully closed
2021-12-19T07:31:37.278Z 	 info: Azurite Blob service successfully closed
2021-12-19T07:31:37.278Z 	 info: Azurite Queue service successfully closed
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by joelverhagen** [comment]
This appears to be a fix:

```patch
index 4876a65..84cec05 100644
--- a/src/table/batch/TableBatchOrchestrator.ts
+++ b/src/table/batch/TableBatchOrchestrator.ts
@@ -119,7 +119,7 @@ export default class TableBatchOrchestrator {
         }
       }

-      if (!requestPartitionKey) {
+      if (requestPartitionKey === undefined) {
         this.wasError = true;
         this.errorResponse = this.serialization.serializeGeneralRequestError(
           "Partition key not found in request",
diff --git a/src/table/batch/TableBatchSerialization.ts b/src/table/batch/TableBatchSerialization.ts
index b25a3da..8f32bf6 100644
--- a/src/table/batch/TableBatchSerialization.ts
+++ b/src/table/batch/TableBatchSerialization.ts
@@ -634,13 +634,8 @@ export class TableBatchSerialization extends BatchSerialization {
     odataErrorString: string,
     requestId: string | undefined
   ): string {
-    const changesetBoundary = this.changesetBoundary.replace(
-      "changeset",
-      "changesetresponse"
-    );
     let errorReponse = "";

-    errorReponse += changesetBoundary + "\r\n";
     // Errors in batch processing generate Bad Request error
     errorReponse = this.serializeHttpStatusCode(errorReponse, 400);
     errorReponse = this.SerializeXContentTypeOptions(errorReponse);
@@ -651,11 +646,20 @@ export class TableBatchSerialization extends BatchSerialization {
     errorReponse += "\r\n";
     let requestIdResponseString = "";
     if (requestId !== undefined) {
-      requestIdResponseString = `RequestId:${requestId}\\n`;
+      requestIdResponseString = `RequestId:${requestId}\n`;
     }
     // 2021-04-23T12:40:31.4944778
     const date = truncatedISO8061Date(new Date(), true);
-    errorReponse += `{\"odata.error\":{\"code\":\"InvalidInput\",\"message\":{\"lang\":\"en-US\",\"value\":\"${odataErrorString}\\n${requestIdResponseString}Time:${date}\"}}}\r\n`;
+    errorReponse += JSON.stringify({
+      "odata.error": {
+        code: "InvalidInput",
+        message: {
+          lang: "en-US",
+          value: `${odataErrorString}\n${requestIdResponseString}Time:${date}`
+        }
+      }
+    })
+    errorReponse += "\r\n";
     return errorReponse;
   }
 }
diff --git a/src/table/handlers/TableHandler.ts b/src/table/handlers/TableHandler.ts
index a9a68fa..c1ccbf3 100644
--- a/src/table/handlers/TableHandler.ts
+++ b/src/table/handlers/TableHandler.ts
@@ -288,8 +288,8 @@ export default class TableHandler extends BaseHandler implements ITableHandler {
     const tableContext = new TableStorageContext(context);
     const account = this.getAndCheckAccountName(tableContext);
     const table = this.getAndCheckTableName(tableContext);
-    partitionKey = partitionKey || this.getAndCheckPartitionKey(tableContext);
-    rowKey = rowKey || this.getAndCheckRowKey(tableContext);
+    partitionKey = partitionKey !== undefined ? partitionKey : this.getAndCheckPartitionKey(tableContext);
+    rowKey = rowKey !== undefined ? rowKey : this.getAndCheckRowKey(tableContext);
     const ifMatch = options.ifMatch;

     if (!options.tableEntityProperties) {
@@ -373,8 +373,8 @@ export default class TableHandler extends BaseHandler implements ITableHandler {
     const tableContext = new TableStorageContext(context);
     const account = this.getAndCheckAccountName(tableContext);
     const table = this.getAndCheckTableName(tableContext);
-    partitionKey = partitionKey || this.getAndCheckPartitionKey(tableContext);
-    rowKey = rowKey || this.getAndCheckRowKey(tableContext);
+    partitionKey = partitionKey !== undefined ? partitionKey : this.getAndCheckPartitionKey(tableContext);
+    rowKey = rowKey !== undefined ? rowKey : this.getAndCheckRowKey(tableContext);

     if (!options.tableEntityProperties) {
       throw StorageErrorFactory.getPropertiesNeedValue(context);
@@ -449,8 +449,8 @@ export default class TableHandler extends BaseHandler implements ITableHandler {
     const tableContext = new TableStorageContext(context);
     const accountName = tableContext.account;

-    partitionKey = partitionKey || tableContext.partitionKey!; // Get partitionKey from context
-    rowKey = rowKey || tableContext.rowKey!; // Get rowKey from context
+    partitionKey = partitionKey !== undefined ? partitionKey : tableContext.partitionKey!; // Get partitionKey from context
+    rowKey = rowKey !== undefined ? rowKey : tableContext.rowKey!; // Get rowKey from context

     if (partitionKey === undefined || rowKey === undefined) {
       throw StorageErrorFactory.getPropertiesNeedValue(context);
@@ -595,8 +595,8 @@ export default class TableHandler extends BaseHandler implements ITableHandler {
     const tableContext = new TableStorageContext(context);
     const account = this.getAndCheckAccountName(tableContext);
     const table = _table ? _table : this.getAndCheckTableName(tableContext);
-    partitionKey = partitionKey || this.getAndCheckPartitionKey(tableContext);
-    rowKey = rowKey || this.getAndCheckRowKey(tableContext);
+    partitionKey = partitionKey !== undefined ? partitionKey : this.getAndCheckPartitionKey(tableContext);
+    rowKey = rowKey !== undefined ? rowKey : this.getAndCheckRowKey(tableContext);
     const accept = this.getAndCheckPayloadFormat(tableContext);

     const entity =
```

**Comment by edwin-huber** [comment]
Thanks for the submission and effort to diagnose.
I have just been refactoring the batch transaction rollback PR which aggregates a lot of fixes to table behavior.
I'll add a test case and address this fix after the PR is merged.

**Comment by haozhangms** [comment]
encountered same exception when executing batch merge operation for table. Seems its RCA is similar as this issue?  https://github.com/Azure/Azurite/issues/1211

**Comment by joelverhagen** [comment]
I tested this against 3.16.0 and it's happening still. I also found a different symptom:

```csharp
using Azure.Data.Tables;

var client = new TableServiceClient("UseDevelopmentStorage=true");
var table = client.GetTableClient("test");
table.Delete();
table.Create();

var actions = new List<TableTransactionAction>
{
    new TableTransactionAction(TableTransactionActionType.Add, new TableEntity(string.Empty, "a")),
};

table.SubmitTransaction(actions);
```

The error message looks like this:
```
Unhandled exception. System.InvalidOperationException: Expected an HTTP status line, not changesetresponse_9626b2e4-c1fd-422f-8f0c-8739e327e156
   at Azure.Core.Multipart.ParseAsync(Stream batchContent, String batchContentType, Boolean expectBoundariesWithCRLF, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Data.Tables.TableRestClient.SendBatchRequest(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Data.Tables.TableClient.SubmitTransaction(IEnumerable`1 transactionActions, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\joelv\Desktop\ConsoleApp1\ConsoleApp1\Program.cs:line 13
```
