### ISSUE TITLE
Error thrown when trying to add entity with Boolean or Int32 property

### ISSUE THREAD

**Issue by craxal** [Azure/Azurite#1259]
### Which service (blob, file, queue, table) does this issue concern?
Table
### Which version of the Azurite was used?
3.14.3
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
16.13.1
### What problem was encountered?
Azurite returns an error when attempting to add an entity with a Boolean or Int32 property.
### Steps to reproduce the issue?

1. Form the following entity object in a Node application:
   ```
   {
      partitionKey: "",
      rowKey: "",
      prop: { value: "false", type: "Boolean" }
   }
   ```
2. Use @azure/data-tables to connect to the emulator and insert the entity.

Here are the relevant lines from the debug log:

```
2022-01-04T00:49:30.226Z 2a92d550-f0d2-48aa-b819-f2c8a8d99a47 verbose: DeserializerMiddleware: Start deserializing...
2022-01-04T00:49:30.227Z 2a92d550-f0d2-48aa-b819-f2c8a8d99a47 debug: deserialize(): Raw request body string is (removed all empty characters) {"PartitionKey":"1","RowKey":"2","bin":"false","bin@odata.type":"Edm.Boolean"}
2022-01-04T00:49:30.227Z 2a92d550-f0d2-48aa-b819-f2c8a8d99a47 info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{},"requestId":"73776de8-b219-4a28-870a-151d5a8a1072","dataServiceVersion":"3.0","responsePreference":"return-no-content","tableEntityProperties":{"PartitionKey":"1","RowKey":"2","prop":"false","bin@odata.type":"Edm.Boolean"}},"version":"2019-02-02","body":"ReadableStream"}
2022-01-04T00:49:30.227Z 2a92d550-f0d2-48aa-b819-f2c8a8d99a47 error: TableHandler:insertEntity() TypeError "TypeError: Not a valid EdmBoolean string.\n    at Function.validate (C:\\Users\\cralvord\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\table\\entity\\EdmBoolean.js:11:19)\n    at new EdmBoolean (C:\\Users\\cralvord\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\table\\entity\\EdmBoolean.js:7:38)\n    at Object.parseEntityProperty (C:\\Users\\cralvord\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\table\\entity\\EntityProperty.js:92:56)\n    at new NormalizedEntity (C:\\Users\\cralvord\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\table\\entity\\NormalizedEntity.js:41:55)\n    at TableHandler.insertEntity (C:\\Users\\cralvord\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\table\\handlers\\TableHandler.js:116:32)\n    at C:\\Users\\cralvord\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\table\\generated\\middleware\\HandlerMiddlewareFactory.js:58:18\n    at C:\\Users\\cralvord\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\table\\generated\\ExpressMiddlewareFactory.js:77:63\n    at Layer.handle [as handle_request] (C:\\Users\\cralvord\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\cralvord\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\Users\\cralvord\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:284:7"
```

### Have you found a mitigation/solution?
No. It should be noted that the same step taken against Azure are successful.

**Comment by craxal** [comment]
@edwin-huber @blueww Haven't heard back from anyone about this. Is this getting looked into? Several Storage Explorer users have been reporting on this problem. We use string values with data types to avoid type ambiguity and precision loss for certain types.

**Comment by edwin-huber** [comment]
Hi @craxal thanks for the heads up.
I shall take a look.
We have a few issues pending the large PR #1157, as this has the potential to generate a lot of conflicts.
I'm trying to roll up as many smaller fixes as I can into that, as it is one of the major pieces of work before we consider that we are truly GA on Table.

**Comment by edwin-huber** [comment]
Issue is fixed in pending PR #1259

**Comment by craxal** [comment]
@edwin-huber I think you linked back to this issue, not the PR...

**Comment by edwin-huber** [comment]
Changes merged, pending next release.

**Comment by xaviergxf** [comment]
any news about this issue? Is there a workaround that can be applied?
