### ISSUE TITLE
Copy or put blob with ( in name fails with 403

### ISSUE THREAD

**Issue by houbi56** [Azure/Azurite#1348]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.15

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
16.14

### What problem was encountered?
Using Azure BlobClient SyncCopyFromUri within same azurite instance fails when destination contains ( in name
Same error when doing PUT with blob containing (
Can't handle % either

### Steps to reproduce the issue?

2022-02-17T18:16:21.021Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://10.168.1.25/devstoreaccount1/tenant/project/1015/p/test/Mapp2/92203.Orderbekraftelse2%C3%A4().pdf RequestHeaders:{"connection":"Keep-Alive","accept":"application/xml","authorization":"SharedKey devstoreaccount1:4ddRDyLfyBTblB3nkP+9d8SRT8pPnRnhfAmYVXXm+3Y=","host":"10.168.1.25:10000","user-agent":"azsdk-net-Storage.Blobs/12.10.0 (.NET 5.0.14; Microsoft Windows 10.0.19042)","x-ms-requires-sync":"true","x-ms-copy-source":"http://10.168.1.25:10000/devstoreaccount1/tenant/project/1015/p/test/Mapp2/92203.Orderbekraftelse2%C3%A4%2020.pdf","x-ms-version":"2020-10-02","x-ms-client-request-id":"236f8812-2108-4337-937a-1bdfcf909e01","x-ms-return-client-request-id":"true","x-ms-date":"Thu, 17 Feb 2022 18:16:20 GMT","traceparent":"00-0b3aeeef89f87943b8a26fc66089153d-c69a0c38a7581945-00","x-forwarded-for":"10.168.1.219:62007","x-forwarded-proto":"http","content-length":"0"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2022-02-17T18:16:21.021Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=tenant Blob=project/1015/p/test/Mapp2/92203.Orderbekraftelse2ä().pdf
2022-02-17T18:16:21.021Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 verbose: DispatchMiddleware: Dispatching request...
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: DispatchMiddleware: Operation=Blob_CopyFromURL
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: PublicAccessAuthenticator:validate() Start validation against public access.
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: PublicAccessAuthenticator:validate() Getting account properties...
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: tenant, blob: project/1015/p/test/Mapp2/92203.Orderbekraftelse2ä().pdf
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container tenant
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:236f8812-2108-4337-937a-1bdfcf909e01\nx-ms-copy-source:http://10.168.1.25:10000/devstoreaccount1/tenant/project/1015/p/test/Mapp2/92203.Orderbekraftelse2%C3%A4%2020.pdf\nx-ms-date:Thu, 17 Feb 2022 18:16:20 GMT\nx-ms-requires-sync:true\nx-ms-return-client-request-id:true\nx-ms-version:2020-10-02\n/devstoreaccount1/devstoreaccount1/tenant/project/1015/p/test/Mapp2/92203.Orderbekraftelse2%C3%A4().pdf"
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:ZVfA+iUXL6WPClebMHmmKmoI1vrRAM1lGWlYH6FI9gs=
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: BlobSharedKeyAuthenticator:validate() Validation failed.
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: AccountSASAuthenticator:validate() Start validation against account Shared Access Signature pattern.
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: AccountSASAuthenticator:validate() Getting account properties...
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: AccountSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: tenant, blob: project/1015/p/test/Mapp2/92203.Orderbekraftelse2ä().pdf
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: AccountSASAuthenticator:validate() Got account properties successfully.
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: AccountSASAuthenticator:validate() Retrieved signature from URL parameter sig: undefined
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: AccountSASAuthenticator:validate() Failed to get valid account SAS values from request.
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: BlobSASAuthenticator:validate() Start validation against blob service Shared Access Signature pattern.
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: BlobSASAuthenticator:validate() Getting account properties...
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: BlobSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: tenant, blob: project/1015/p/test/Mapp2/92203.Orderbekraftelse2ä().pdf
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: BlobSASAuthenticator:validate() Got account properties successfully.
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: BlobSASAuthenticator:validate() Retrieved signature from URL parameter sig: undefined
2022-02-17T18:16:21.022Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 debug: BlobSASAuthenticator:validate() No signature found in request. Skip blob service SAS validation.
2022-02-17T18:16:21.023Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2022-02-17T18:16:21.023Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.  ErrorHTTPStatusCode=403 ErrorHTTPStatusMessage=Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature. ErrorHTTPHeaders={"x-ms-error-code":"AuthorizationFailure","x-ms-request-id":"a90a5379-cc1a-49fe-a5e2-d3f0f3f84006"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationFailure</Code>\n  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:a90a5379-cc1a-49fe-a5e2-d3f0f3f84006\nTime:2022-02-17T18:16:21.022Z</Message>\n</Error>" ErrorStack="StorageError: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\n    at Function.getAuthorizationFailure (C:\\ProgramData\\npm\\node_modules\\azurite\\dist\\src\\blob\\errors\\StorageErrorFactory.js:134:16)\n    at C:\\ProgramData\\npm\\node_modules\\azurite\\dist\\src\\blob\\middlewares\\AuthenticationMiddlewareFactory.js:22:56\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
2022-02-17T18:16:21.023Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 error: ErrorMiddleware: Set HTTP code: 403
2022-02-17T18:16:21.023Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 error: ErrorMiddleware: Set HTTP status message: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
2022-02-17T18:16:21.023Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=AuthorizationFailure
2022-02-17T18:16:21.023Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=a90a5379-cc1a-49fe-a5e2-d3f0f3f84006
2022-02-17T18:16:21.023Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 error: ErrorMiddleware: Set content type: application/xml
2022-02-17T18:16:21.023Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationFailure</Code>\n  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:a90a5379-cc1a-49fe-a5e2-d3f0f3f84006\nTime:2022-02-17T18:16:21.022Z</Message>\n</Error>"
2022-02-17T18:16:21.023Z a90a5379-cc1a-49fe-a5e2-d3f0f3f84006 info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=403 StatusMessage=Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature. Headers={"server":"Azurite-Blob/3.15.0","x-ms-error-code":"AuthorizationFailure","x-ms-request-id":"a90a5379-cc1a-49fe-a5e2-d3f0f3f84006","content-type":"application/xml"}
```

**Comment by blueww** [comment]
@houbi56 

I can't repro this copy blob fail, same Azurite version 3.15.0 install from npm, same node version 16.14, and same SDK "azsdk-net-Storage.Blobs/12.10.0".
I also use same blob name.

Would you please send the request? Would you please share the .net SDK code to repro the issue.
As you mentioned, this also repro on upload. If so, would you please also share the upload blob debug log and repro code?

```
2022-02-18T06:55:25.480Z afef7945-6af4-4f9f-89ae-721da4170afd info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/tenant/project/1015/p/test/Mapp2/92203.Orderbekraftelse2%C3%A4().pdf RequestHeaders:{"x-ms-requires-sync":"true","x-ms-copy-source":"http://127.0.0.1:10000/devstoreaccount1/tenant/project/1015/p/test/Mapp2/92203.Orderbekraftelse2%C3%A4%2020.pdf?sv=2020-08-04&se=2022-02-25T06:54:23Z&sr=b&sp=rt&sig=YRMb%2F%2BhCBfAj3tlDO22O5MR9LNv8HyRh%2FpRFLcCiM%2Bc%3D","x-ms-version":"2020-10-02","accept":"application/xml","user-agent":"AzurePowershell/v1.0.0 azsdk-net-Storage.Blobs/12.10.0 (.NET Framework 4.8.4420.0; Microsoft Windows 10.0.19044 )","x-ms-client-request-id":"ba062e08-488e-4007-a2ae-7854997e59d7","x-ms-return-client-request-id":"true","x-ms-date":"Fri, 18 Feb 2022 06:55:25 GMT","authorization":"SharedKey devstoreaccount1:eAfTwqoFEQjH4Gl8CS9DDdI4ek6waN+RVMn4q7uHnCI=","host":"127.0.0.1:10000","content-length":"0"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2022-02-18T06:55:25.480Z afef7945-6af4-4f9f-89ae-721da4170afd info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=tenant Blob=project/1015/p/test/Mapp2/92203.Orderbekraftelse2ä().pdf
2022-02-18T06:55:25.480Z afef7945-6af4-4f9f-89ae-721da4170afd verbose: DispatchMiddleware: Dispatching request...
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd info: DispatchMiddleware: Operation=Blob_CopyFromURL
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd info: PublicAccessAuthenticator:validate() Start validation against public access.
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd debug: PublicAccessAuthenticator:validate() Getting account properties...
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: tenant, blob: project/1015/p/test/Mapp2/92203.Orderbekraftelse2ä().pdf
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container tenant
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:ba062e08-488e-4007-a2ae-7854997e59d7\nx-ms-copy-source:http://127.0.0.1:10000/devstoreaccount1/tenant/project/1015/p/test/Mapp2/92203.Orderbekraftelse2%C3%A4%2020.pdf?sv=2020-08-04&se=2022-02-25T06:54:23Z&sr=b&sp=rt&sig=YRMb%2F%2BhCBfAj3tlDO22O5MR9LNv8HyRh%2FpRFLcCiM%2Bc%3D\nx-ms-date:Fri, 18 Feb 2022 06:55:25 GMT\nx-ms-requires-sync:true\nx-ms-return-client-request-id:true\nx-ms-version:2020-10-02\n/devstoreaccount1/devstoreaccount1/tenant/project/1015/p/test/Mapp2/92203.Orderbekraftelse2%C3%A4().pdf"
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:eAfTwqoFEQjH4Gl8CS9DDdI4ek6waN+RVMn4q7uHnCI=
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd verbose: DeserializerMiddleware: Start deserializing...
2022-02-18T06:55:25.481Z afef7945-6af4-4f9f-89ae-721da4170afd info: HandlerMiddleware: DeserializedParameters={"options":{"metadata":{},"requestId":"ba062e08-488e-4007-a2ae-7854997e59d7","sourceModifiedAccessConditions":{},"modifiedAccessConditions":{},"leaseAccessConditions":{}},"copySource":"http://127.0.0.1:10000/devstoreaccount1/tenant/project/1015/p/test/Mapp2/92203.Orderbekraftelse2%C3%A4%2020.pdf?sv=2020-08-04&se=2022-02-25T06:54:23Z&sr=b&sp=rt&sig=YRMb%2F%2BhCBfAj3tlDO22O5MR9LNv8HyRh%2FpRFLcCiM%2Bc%3D","version":"2020-10-02","xMsRequiresSync":"true"}
2022-02-18T06:55:25.482Z afef7945-6af4-4f9f-89ae-721da4170afd verbose: SerializerMiddleware: Start serializing...
2022-02-18T06:55:25.482Z afef7945-6af4-4f9f-89ae-721da4170afd info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=202 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.15.0","etag":"\"0x24278EE17E9C700\"","last-modified":"Fri, 18 Feb 2022 06:55:25 GMT","x-ms-client-request-id":"ba062e08-488e-4007-a2ae-7854997e59d7","x-ms-request-id":"afef7945-6af4-4f9f-89ae-721da4170afd","x-ms-version":"2021-02-12","date":"Fri, 18 Feb 2022 06:55:25 GMT","x-ms-copy-id":"949eca31-9d80-4b40-a3d4-35ffea079c8f","x-ms-copy-status":"success"}
```

**Comment by houbi56** [comment]
We have IIS as reverse proxy in our local test environment using the module httpPlatformHandler.
When connecting directly to Azurite, not going through IIS, we don't see the auth error. 

Do you have any idea how we could determine the cause of this or how to investigate?

I have a feeling that some header is changed by IIS that causes this.
Which headers are used in the auth check on azurite side (except for the obvious 'Authorization') ?

Would there be anything else that could cause this?

**Comment by blueww** [comment]
@houbi56 
You can find how Azurite generated StringTosign [here](https://github.com/Azure/Azurite/blob/d13cd730a14db7c77a975a591abbfb8472d9c4ef/src/blob/authentication/BlobSharedKeyAuthenticator.ts#L52), then we will sign it with the sharedkey, and compare with the SharedKey signature in authorization header in the request.

**Comment by houbi56** [comment]
Here's the difference: 

AZURITE DIRECTLY: [STRING TO SIGN]:"PUT\n\n\n55808\n\napplication/octet-stream\n\n\n\n\n\n\nx-ms-client-request-id:6ca6d997-f2ca-444f-8e95-47a5c267749c\nx-ms-date:Tue, 22 Feb 2022 17:40:31 GMT\nx-ms-return-client-request-id:true\nx-ms-version:2020-10-02\n/devstoreaccount1/devstoreaccount1/tenant/project/1015/p/Ny%20katalog/01%20Kontraktshandlingar/1%2C4%20%C3%96vrigt/5-8%20Mall%20Arbetsorder.xls\nblockid:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\ncomp:block"
THROUGH IIS: [STRING TO SIGN]:"PUT\n\n\n55808\n\napplication/octet-stream\n\n\n\n\n\n\nx-ms-client-request-id:b9345888-6652-4a49-aa79-6b55ca1751d5\nx-ms-date:Tue, 22 Feb 2022 18:36:16 GMT\nx-ms-return-client-request-id:true\nx-ms-version:2020-10-02\n/devstoreaccount1/devstoreaccount1/tenant/project/1015/p/Ny%20katalog/01%20Kontraktshandlingar/1,4%20%C3%96vrigt/5-8%20Mall%20Arbetsorder.xls\nblockid:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\ncomp:block"

These are from different run so the x-ms-client-request-id differs. 
IIS doesn't encode the comma so the url differs.

I've dropped the IIS httpPlatformhandler solution for a node-windows service solution https://github.com/coreybutler/node-windows

Thanks for the assistance, errand can be closed.

**Comment by blueww** [comment]
@houbi56 
Thanks for the update!
I will close this issue.

Feel free to contact us again if need any further assistance of Azurite.
