### ISSUE TITLE
Table panic

### ISSUE THREAD

**Issue by javier-alvarez** [Azure/Azurite#135]
GET /devstoreaccount1/models?$filter=PartitionKey%20eq%20%27%27 **500** 0.690 ms - 27
**PANIC** Something unexpected happened! Table Storage Emulator may be in an inconsistent state!
SyntaxError: Invalid or unexpected token
    at __dirname.queryEntities.chain.where (C:\snapshot\Azurite\lib\core\table\TableStorageManager.js:0)
    at Resultset.where (C:\snapshot\Azurite\node_modules\lokijs\src\lokijs.js:3349:17)
    at TableStorageManager.queryEntities (C:\snapshot\Azurite\lib\core\table\TableStorageManager.js:0)
    at QueryEntities.process (C:\snapshot\Azurite\lib\actions\table\QueryEntities.js:0)
    at Object.actions.(anonymous function) [as QueryEntity] (C:\snapshot\Azurite\lib\middleware\table\actions.js:0)
    at module.exports.BbPromise.try (C:\snapshot\Azurite\lib\middleware\table\actions.js:0)
    at tryCatcher (C:\snapshot\Azurite\node_modules\bluebird\js\release\util.js:16:23)
    at Function.module.exports.Promise.attempt.Promise.try (C:\snapshot\Azurite\node_modules\bluebird\js\release\method.js:39:29)
    at module.exports (C:\snapshot\Azurite\lib\middleware\table\actions.js:0)
    at Layer.handle [as handle_request] (C:\snapshot\Azurite\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\snapshot\Azurite\node_modules\express\lib\router\index.js:317:13)
    at C:\snapshot\Azurite\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\snapshot\Azurite\node_modules\express\lib\router\index.js:335:12)
    at next (C:\snapshot\Azurite\node_modules\express\lib\router\index.js:275:10)
    at module.exports.BbPromise.try (C:\snapshot\Azurite\lib\middleware\table\validation.js:0)
    at tryCatcher (C:\snapshot\Azurite\node_modules\bluebird\js\release\util.js:16:23)

**Comment by edwin-huber** [comment]
closing old legacy issues which should be addressed in new api
