### ISSUE TITLE
Cannot install Azurite in Visual Studio

### ISSUE THREAD

**Issue by Mike-E-angelo** [Azure/Azurite#1414]
### Which service(blob, file, queue, table) does this issue concern?
Installation
### Which version of the Azurite was used?
Didn't get that far
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VisualStudio
### What's the Node.js version?
Not Sure
### What problem was encountered?

```
Installing NuGet packages to project...
Installing package 'Azure.Storage.Blobs' with version '12.3.0'.
ErrorNuGet.PackageManagement.PackageReferenceRollbackException: Package restore failed. Rolling back package changes for 'starbeam.one'.
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteBuildIntegratedProjectActionsAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalCoreAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at Microsoft.WebTools.Shared.VS.NuGet.NuGetPackageManager.<InstallAsync>d__41.MoveNext()
ErrorFailed to configure NuGet packages.
Adding code to Startup.cs...
ErrorFailed to configure dependency Storage Azurite emulator (Local) storage1.
```

(Note that no code was actually added to Startup.cs as it does not exist)

### Steps to reproduce the issue?

Follow instructions here:
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
Just complaining about it here. :P

**Comment by Brainforce1** [comment]
Am encountering this same issue. 
Am adding it to a (.NET Core) minimal API project in VS 2022, which might be unsupported for now?
Bcs the OP also mentioned the Startup.cs message stating he doesn't have that class either.

**Comment by blueww** [comment]
@Brainforce1 
Your issue looks more like a VS issue.
Would you please report a VS issue by following: [https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fide%2Fhow-to-report-a-problem-with-visual-studio%3Fview%3Dvs-2022&data=05%7C01%7Cweiwei%40microsoft.com%7C018bab47753441a4efbc08da37aa53e8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637883501988809333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O8MtF%2Ft%2B5s7xXFJPiRAQzI7qYU9B3lWj0rXclmmUvXE%3D&reserved=0)

**Comment by ch200c** [comment]
I had the same error for a different package. Turns out, I had a newer version of the package already referenced in my project. 

Solution: downgrade Azure.Storage.Blobs to version 12.3.0 or remove the package reference completely and try again.

**Comment by jainakanksha-msft** [comment]
Not an azurite extension issue
