### ISSUE TITLE
Error when inserting TypeError: Cannot read properties of null (reading 'length')\n    at TableHandler.checkProperties 

### ISSUE THREAD

**Issue by sveinbma** [Azure/Azurite#1456]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.17.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v.16.9.1

### What problem was encountered?
After updating to the newest version (3.17.0), some of our integration tests started failing. The problem happens when we are inserting entities into a table. It looks like it is because some of the properties that we are inserting are 'null'

### Steps to reproduce the issue?

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d info: TableStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/testTable945584?$format=application%2Fjson%3Bodata%3Dminimalmetadata RequestHeaders:{"host":"127.0.0.1:10002","x-ms-version":"2019-02-02","dataserviceversion":"3.0","prefer":"return-no-content","accept":"application/json; odata=minimalmetadata","x-ms-client-request-id":"f4980e87-b413-4c91-a3d2-efa34ee4d72e","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Data.Tables/12.5.0 (.NET 6.0.2; Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64)","x-ms-date":"Thu, 28 Apr 2022 13:16:50 GMT","authorization":"SharedKeyLite devstoreaccount1:pLFpauz4G4TsWFN5R877KI5zn51mqD9vAgnOlXbCEzk=","content-type":"application/json; odata=nometadata","content-length":"197"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d debug: tableStorageContextMiddleware: Dispatch pattern string: /testTable945584
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=testTable945584
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d verbose: DispatchMiddleware: Dispatching request...
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d info: DispatchMiddleware: Operation=Table_InsertEntity
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Thu, 28 Apr 2022 13:16:50 GMT\n/devstoreaccount1/devstoreaccount1/testTable945584"
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:pLFpauz4G4TsWFN5R877KI5zn51mqD9vAgnOlXbCEzk=
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d verbose: DeserializerMiddleware: Start deserializing...
2022-04-28T13:16:50.206Z e1cf5d57-fa43-419f-b58b-59888e23ad2d debug: deserialize(): Raw request body string is (removed all empty characters) {"LeverandorNummer":"1234","LeverandorNummer@odata.type":"Edm.Int64","Orgnummer":"1234","NummerserieType":"Leverandor","IsManuallyHandledInAgresso":null,"PartitionKey":"Leverandor","RowKey":"1234"}
2022-04-28T13:16:50.207Z e1cf5d57-fa43-419f-b58b-59888e23ad2d info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"format":"application/json;odata=minimalmetadata"},"requestId":"f4980e87-b413-4c91-a3d2-efa34ee4d72e","dataServiceVersion":"3.0","responsePreference":"return-no-content","tableEntityProperties":{"LeverandorNummer":"1234","LeverandorNummer@odata.type":"Edm.Int64","Orgnummer":"1234","NummerserieType":"Leverandor","IsManuallyHandledInAgresso":null,"PartitionKey":"Leverandor","RowKey":"1234"}},"version":"2019-02-02","body":"ReadableStream"}
2022-04-28T13:16:50.207Z e1cf5d57-fa43-419f-b58b-59888e23ad2d error: ErrorMiddleware: Received an error, fill error information to HTTP response
2022-04-28T13:16:50.207Z e1cf5d57-fa43-419f-b58b-59888e23ad2d error: ErrorMiddleware: ErrorName=TypeError ErrorMessage=Cannot read properties of null (reading 'length') ErrorStack="TypeError: Cannot read properties of null (reading 'length')\n    at TableHandler.checkProperties (/usr/local/lib/node_modules/azurite/dist/src/table/handlers/TableHandler.js:601:52)\n    at TableHandler.insertEntity (/usr/local/lib/node_modules/azurite/dist/src/table/handlers/TableHandler.js:110:14)\n    at /usr/local/lib/node_modules/azurite/dist/src/table/generated/middleware/HandlerMiddlewareFactory.js:58:18\n    at /usr/local/lib/node_modules/azurite/dist/src/table/generated/ExpressMiddlewareFactory.js:77:63\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:328:13)\n    at /usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:289:7\n    at Function.process_params (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:348:12)\n    at next (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:280:10)\n    at runMicrotasks (<anonymous>)"
2022-04-28T13:16:50.207Z e1cf5d57-fa43-419f-b58b-59888e23ad2d error: ErrorMiddleware: Set HTTP code: 500
2022-04-28T13:16:50.207Z e1cf5d57-fa43-419f-b58b-59888e23ad2d info: EndMiddleware: End response. TotalTimeInMS=1 StatusCode=500 StatusMessage=undefined Headers={"server":"Azurite-Table/3.17.0"}
```

### Have you found a mitigation/solution?
Dont store nulls... But this is a breaking change for us

**Comment by ThumNet** [comment]
Appears to be a duplicate to my issue #1457

**Comment by edwin-huber** [comment]
thanks, I am looking into this

**Comment by edwin-huber** [comment]
Thanks for raising this.
I have added a regression test and updated the logic to handle null properties.
I shall try to fast track releasing this fix.

**Comment by ThumNet** [comment]
Thank you Edwin for the quick response and fix :)
