### ISSUE TITLE
Version 3.17.0 cannot handle nullable properties

### ISSUE THREAD

**Issue by ThumNet** [Azure/Azurite#1457]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.17.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What problem was encountered?
AddEntity() failes when using properties that are nullable

### Steps to reproduce the issue?

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
2022-04-28T13:31:50.513Z a9ac4519-2d0d-4db9-905a-705d13c491be debug: deserialize(): Raw request body string is (removed all empty characters) {"InputJson":"{}","ProcessorTypeName":"eCommerce.API.Processors.FulfilmentProcessor,eCommerce.API,Version=1.0.0.0,Culture=neutral,PublicKeyToken=null","CorrelationId":"8cefa71a-0ce7-478e-93e5-73c8e6e82823","CorrelationId@odata.type":"Edm.Guid","Status":"Unprocessed","LastRun":null,"FailureCount":0,"ResourceIdentifier":null,"PartitionKey":"jobentity","RowKey":"test123"}
2022-04-28T13:31:50.513Z a9ac4519-2d0d-4db9-905a-705d13c491be info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"format":"application/json;odata=minimalmetadata"},"requestId":"93d72cf6-c411-4a34-942d-1185aa67912b","dataServiceVersion":"3.0","responsePreference":"return-no-content","tableEntityProperties":{"InputJson":"{}","ProcessorTypeName":"eCommerce.API.Processors.FulfilmentProcessor, eCommerce.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","CorrelationId":"8cefa71a-0ce7-478e-93e5-73c8e6e82823","CorrelationId@odata.type":"Edm.Guid","Status":"Unprocessed","LastRun":null,"FailureCount":0,"ResourceIdentifier":null,"PartitionKey":"jobentity","RowKey":"test123"}},"version":"2019-02-02","body":"ReadableStream"}
2022-04-28T13:31:50.514Z a9ac4519-2d0d-4db9-905a-705d13c491be error: ErrorMiddleware: Received an error, fill error information to HTTP response
2022-04-28T13:31:50.514Z a9ac4519-2d0d-4db9-905a-705d13c491be error: ErrorMiddleware: ErrorName=TypeError ErrorMessage=Cannot read property 'length' of null ErrorStack="TypeError: Cannot read property 'length' of null\n    at TableHandler.checkProperties (/opt/azurite/dist/src/table/handlers/TableHandler.js:601:52)\n    at TableHandler.insertEntity (/opt/azurite/dist/src/table/handlers/TableHandler.js:110:14)\n    at /opt/azurite/dist/src/table/generated/middleware/HandlerMiddlewareFactory.js:58:18\n    at /opt/azurite/dist/src/table/generated/ExpressMiddlewareFactory.js:77:63\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:328:13)\n    at /opt/azurite/node_modules/express/lib/router/index.js:289:7\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:348:12)\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:280:10)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-04-28T13:31:50.514Z a9ac4519-2d0d-4db9-905a-705d13c491be error: ErrorMiddleware: Set HTTP code: 500
2022-04-28T13:31:50.514Z a9ac4519-2d0d-4db9-905a-705d13c491be info: EndMiddleware: End response. TotalTimeInMS=3 StatusCode=500 StatusMessage=undefined Headers={"server":"Azurite-Table/3.17.0"}
```

Where the Entity class looks like

```
public sealed class JobEntity : BaseTableEntity
{
    public JobEntity()
    {
        InputJson = null!;
        ProcessorTypeName = null!;
    }

    public JobEntity(string id, string inputJson, string processorTypeName, Guid correlationId) : base(nameof(JobEntity), id)
    {
        InputJson = inputJson;
        ProcessorTypeName = processorTypeName;
        CorrelationId = correlationId;
    }

    public string InputJson { get; set; }
    public string ProcessorTypeName { get; set; }
    public Guid CorrelationId { get; set; }
    public JobStatus Status { get; set; }
    public DateTime? LastRun { get; set; }
    public int FailureCount { get; set; }
    public string? ResourceIdentifier { get; set; }
}
```

Note here the properties `LastRun` and `ResourceIdentifier` are nullable!

### Have you found a mitigation/solution?
Yes, revert to version 3.16.0 :(

**Comment by edwin-huber** [comment]
Thanks for raising this.
I have added a regression test and updated the logic to handle null properties.
I shall try to fast track releasing this fix.
