### ISSUE TITLE
Azurite docker custom account returns "Invalid storage account"

### ISSUE THREAD

**Issue by lAnubisl** [Azure/Azurite#1574]
This issue is about connecting to Azurite running in docker and configured to use custom account credentials

I used the latest docker image from DockerHub

Steps to reproduce:

Run azurite in docker on remote host:

docker-compose.yaml
```
version: '3.4'
services:  
  storageemulator:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002 --location /workspace --debug /workspace/debug.log"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./data:/workspace
    environment:
      - AZURITE_ACCOUNTS="devstoreaccount1:YXNmbDtrZm5mc2R0NXJpdGgzNDUzNHRmZHNndiBkZ2ZkZ2RmZ2RmZ2RzZ3I1dDQ1Z3c0Y3RmZyBmZGY0MzU0MzVzZGdmI0AlJEc="
```

Try to connect to it via Azure Storage explorer. Use the following connection string:

`DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=YXNmbDtrZm5mc2R0NXJpdGgzNDUzNHRmZHNndiBkZ2ZkZ2RmZ2RmZ2RzZ3I1dDQ1Z3c0Y3RmZyBmZGY0MzU0MzVzZGdmI0AlJEc=;BlobEndpoint=http://192.168.100.254:10000/devstoreaccount1;QueueEndpoint=http://192.168.100.254:10001/devstoreaccount1;TableEndpoint=http://192.168.100.254:10002/devstoreaccount1;`

where 192.168.100.254 is the remote host IP:

Actual results:

Getting the error in the explorer: Unable to retrieve child resources.

debug.log:

```

2022-06-28T07:48:47.365Z 	 info: Azurite Blob service is starting on 0.0.0.0:10000
2022-06-28T07:48:47.366Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value *****
2022-06-28T07:48:47.376Z 	 info: BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2022-06-28T07:48:47.376Z 	 info: BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2022-06-28T07:48:47.377Z 	 info: BlobGCManager:markSweepLoop() Start next mark and sweep.
2022-06-28T07:48:47.377Z 	 info: BlobGCManager:markSweep() Get all extents.
2022-06-28T07:48:47.377Z 	 info: BlobGCManager:start() BlobGCManager successfully started.
2022-06-28T07:48:47.379Z 	 info: BlobGCManager:markSweep() Got 0 extents.
2022-06-28T07:48:47.379Z 	 info: BlobGCManager:markSweep() Get referred extents.
2022-06-28T07:48:47.379Z 	 info: BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2022-06-28T07:48:47.379Z 	 info: BlobGCManager:markSweepLoop() Mark and sweep finished, taken 2ms.
2022-06-28T07:48:47.379Z 	 info: BlobGCManager:markSweepLoop() Sleep for 600000ms.
2022-06-28T07:48:47.381Z 	 info: Azurite Blob service successfully listens on http://0.0.0.0:10000
2022-06-28T07:48:47.381Z 	 info: Azurite Queue service is starting on 0.0.0.0:10001
2022-06-28T07:48:47.381Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value *****
2022-06-28T07:48:47.386Z 	 info: QueueGCManager:start() Starting QueueGCManager, set status to Initializing
2022-06-28T07:48:47.386Z 	 info: QueueGCManager:start() Trigger mark and sweep loop, set status to Running.
2022-06-28T07:48:47.386Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2022-06-28T07:48:47.386Z 	 info: QueueGCManger:markSweep() Get all extents.
2022-06-28T07:48:47.386Z 	 info: QueueGCManager:start() QueueGCManager successfully started.
2022-06-28T07:48:47.387Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2022-06-28T07:48:47.387Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2022-06-28T07:48:47.387Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2022-06-28T07:48:47.387Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2022-06-28T07:48:47.387Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2022-06-28T07:48:47.387Z 	 info: Azurite Queue service successfully listens on http://0.0.0.0:10001
2022-06-28T07:48:47.387Z 	 info: Azurite Table service is starting on 0.0.0.0:10002
2022-06-28T07:48:47.387Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value *****
2022-06-28T07:48:47.390Z 	 info: Azurite Table service successfully listens on http://0.0.0.0:10002
2022-06-28T07:49:47.369Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value *****
2022-06-28T07:49:47.381Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value *****
2022-06-28T07:49:47.387Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2022-06-28T07:49:47.388Z 	 info: QueueGCManger:markSweep() Get all extents.
2022-06-28T07:49:47.388Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2022-06-28T07:49:47.388Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2022-06-28T07:49:47.389Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2022-06-28T07:49:47.389Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2022-06-28T07:49:47.389Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2022-06-28T07:49:47.389Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value *****
2022-06-28T07:49:50.557Z ba8772b5-61ba-409b-9c41-44dd6c68e5de info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://192.168.100.254/devstoreaccount1?comp=properties&restype=account RequestHeaders:{"x-ms-version":"2020-10-02","accept":"application/xml","user-agent":"Microsoft Azure Storage Explorer/1.24.3 (win32) azsdk-js-storageblob/12.8.0 (NODE-VERSION v16.13.2; Windows_NT 10.0.22000)","x-ms-client-request-id":"38ed343e-84bc-4971-8547-ebe9cdb63093","x-ms-date":"Tue, 28 Jun 2022 07:49:49 GMT","authorization":"SharedKey devstoreaccount1:B4+ewRLLidCTTgXj/JATcnNHkxzBb0Ke15rcAb3AkEs=","cookie":"","host":"192.168.100.254:10000","connection":"keep-alive"} ClientIP=192.168.100.103 Protocol=http HTTPVersion=1.1
2022-06-28T07:49:50.559Z ba8772b5-61ba-409b-9c41-44dd6c68e5de info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=undefined Blob=
2022-06-28T07:49:50.560Z ba8772b5-61ba-409b-9c41-44dd6c68e5de verbose: DispatchMiddleware: Dispatching request...
2022-06-28T07:49:50.566Z ba8772b5-61ba-409b-9c41-44dd6c68e5de info: DispatchMiddleware: Operation=Service_GetAccountInfo
2022-06-28T07:49:50.567Z ba8772b5-61ba-409b-9c41-44dd6c68e5de verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-06-28T07:49:50.567Z ba8772b5-61ba-409b-9c41-44dd6c68e5de info: PublicAccessAuthenticator:validate() Start validation against public access.
2022-06-28T07:49:50.567Z ba8772b5-61ba-409b-9c41-44dd6c68e5de debug: PublicAccessAuthenticator:validate() Getting account properties...
2022-06-28T07:49:50.567Z ba8772b5-61ba-409b-9c41-44dd6c68e5de debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: undefined, blob: 
2022-06-28T07:49:50.567Z ba8772b5-61ba-409b-9c41-44dd6c68e5de info: PublicAccessAuthenticator:validate() Skip public access authentication. Container name is undefined.
2022-06-28T07:49:50.570Z ba8772b5-61ba-409b-9c41-44dd6c68e5de info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2022-06-28T07:49:50.570Z ba8772b5-61ba-409b-9c41-44dd6c68e5de error: BlobSharedKeyAuthenticator:validate() Invalid storage account devstoreaccount1.
2022-06-28T07:49:50.578Z ba8772b5-61ba-409b-9c41-44dd6c68e5de error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2022-06-28T07:49:50.578Z ba8772b5-61ba-409b-9c41-44dd6c68e5de error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Invalid storage account.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=Invalid storage account. ErrorHTTPHeaders={"x-ms-error-code":"InvalidOperation","x-ms-request-id":"ba8772b5-61ba-409b-9c41-44dd6c68e5de"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:ba8772b5-61ba-409b-9c41-44dd6c68e5de\nTime:2022-06-28T07:49:50.571Z</Message>\n</Error>" ErrorStack="StorageError: Invalid storage account.\n    at Function.getInvalidOperation (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:58:16)\n    at BlobSharedKeyAuthenticator.validate (/opt/azurite/dist/src/blob/authentication/BlobSharedKeyAuthenticator.js:29:49)\n    at AuthenticationMiddlewareFactory.authenticate (/opt/azurite/dist/src/blob/middlewares/AuthenticationMiddlewareFactory.js:34:40)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-06-28T07:49:50.578Z ba8772b5-61ba-409b-9c41-44dd6c68e5de error: ErrorMiddleware: Set HTTP code: 400
2022-06-28T07:49:50.578Z ba8772b5-61ba-409b-9c41-44dd6c68e5de error: ErrorMiddleware: Set HTTP status message: Invalid storage account.
2022-06-28T07:49:50.578Z ba8772b5-61ba-409b-9c41-44dd6c68e5de error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidOperation
2022-06-28T07:49:50.579Z ba8772b5-61ba-409b-9c41-44dd6c68e5de error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=ba8772b5-61ba-409b-9c41-44dd6c68e5de
2022-06-28T07:49:50.579Z ba8772b5-61ba-409b-9c41-44dd6c68e5de error: ErrorMiddleware: Set content type: application/xml
2022-06-28T07:49:50.579Z ba8772b5-61ba-409b-9c41-44dd6c68e5de error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:ba8772b5-61ba-409b-9c41-44dd6c68e5de\nTime:2022-06-28T07:49:50.571Z</Message>\n</Error>"
2022-06-28T07:49:50.596Z ba8772b5-61ba-409b-9c41-44dd6c68e5de info: EndMiddleware: End response. TotalTimeInMS=39 StatusCode=400 StatusMessage=Invalid storage account. Headers={"server":"Azurite-Blob/3.18.0","x-ms-error-code":"InvalidOperation","x-ms-request-id":"ba8772b5-61ba-409b-9c41-44dd6c68e5de","content-type":"application/xml"}
2022-06-28T07:50:36.414Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://192.168.100.254/devstoreaccount1?comp=properties&restype=account RequestHeaders:{"x-ms-version":"2020-10-02","accept":"application/xml","user-agent":"Microsoft Azure Storage Explorer/1.24.3 (win32) azsdk-js-storageblob/12.8.0 (NODE-VERSION v16.13.2; Windows_NT 10.0.22000)","x-ms-client-request-id":"c8664cf3-cbbe-41e5-acfe-049131f34eb5","x-ms-date":"Tue, 28 Jun 2022 07:50:35 GMT","authorization":"SharedKey devstoreaccount1:RKFstA3Othw7MouskVcgDy4neR/7w75ilfBEam6RA8c=","cookie":"","host":"192.168.100.254:10000","connection":"keep-alive"} ClientIP=192.168.100.103 Protocol=http HTTPVersion=1.1
2022-06-28T07:50:36.415Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=undefined Blob=
2022-06-28T07:50:36.415Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d verbose: DispatchMiddleware: Dispatching request...
2022-06-28T07:50:36.415Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d info: DispatchMiddleware: Operation=Service_GetAccountInfo
2022-06-28T07:50:36.415Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-06-28T07:50:36.415Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d info: PublicAccessAuthenticator:validate() Start validation against public access.
2022-06-28T07:50:36.415Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d debug: PublicAccessAuthenticator:validate() Getting account properties...
2022-06-28T07:50:36.415Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: undefined, blob: 
2022-06-28T07:50:36.415Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d info: PublicAccessAuthenticator:validate() Skip public access authentication. Container name is undefined.
2022-06-28T07:50:36.415Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2022-06-28T07:50:36.416Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d error: BlobSharedKeyAuthenticator:validate() Invalid storage account devstoreaccount1.
2022-06-28T07:50:36.416Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2022-06-28T07:50:36.416Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Invalid storage account.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=Invalid storage account. ErrorHTTPHeaders={"x-ms-error-code":"InvalidOperation","x-ms-request-id":"dd8c2298-99e6-4f0c-8b80-7a702b9db06d"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:dd8c2298-99e6-4f0c-8b80-7a702b9db06d\nTime:2022-06-28T07:50:36.416Z</Message>\n</Error>" ErrorStack="StorageError: Invalid storage account.\n    at Function.getInvalidOperation (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:58:16)\n    at BlobSharedKeyAuthenticator.validate (/opt/azurite/dist/src/blob/authentication/BlobSharedKeyAuthenticator.js:29:49)\n    at AuthenticationMiddlewareFactory.authenticate (/opt/azurite/dist/src/blob/middlewares/AuthenticationMiddlewareFactory.js:34:40)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-06-28T07:50:36.416Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d error: ErrorMiddleware: Set HTTP code: 400
2022-06-28T07:50:36.416Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d error: ErrorMiddleware: Set HTTP status message: Invalid storage account.
2022-06-28T07:50:36.416Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidOperation
2022-06-28T07:50:36.416Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=dd8c2298-99e6-4f0c-8b80-7a702b9db06d
2022-06-28T07:50:36.416Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d error: ErrorMiddleware: Set content type: application/xml
2022-06-28T07:50:36.417Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:dd8c2298-99e6-4f0c-8b80-7a702b9db06d\nTime:2022-06-28T07:50:36.416Z</Message>\n</Error>"
2022-06-28T07:50:36.417Z dd8c2298-99e6-4f0c-8b80-7a702b9db06d info: EndMiddleware: End response. TotalTimeInMS=3 StatusCode=400 StatusMessage=Invalid storage account. Headers={"server":"Azurite-Blob/3.18.0","x-ms-error-code":"InvalidOperation","x-ms-request-id":"dd8c2298-99e6-4f0c-8b80-7a702b9db06d","content-type":"application/xml"}
2022-06-28T07:50:40.793Z de7e4018-575a-4521-8895-fb961edd559b info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://192.168.100.254/devstoreaccount1?comp=list&include=metadata RequestHeaders:{"x-ms-version":"2020-10-02","accept":"application/xml","user-agent":"Microsoft Azure Storage Explorer/1.24.3 (win32) azsdk-js-storageblob/12.8.0 (NODE-VERSION v16.13.2; Windows_NT 10.0.22000)","x-ms-client-request-id":"502d26ad-4663-4024-821f-66ef154e3184","x-ms-date":"Tue, 28 Jun 2022 07:50:40 GMT","authorization":"SharedKey devstoreaccount1:GFhqUaMgWKVfi8+KJgosIny5W2e3Y1wbCrnXu7qNAUM=","cookie":"","host":"192.168.100.254:10000","connection":"keep-alive"} ClientIP=192.168.100.103 Protocol=http HTTPVersion=1.1
2022-06-28T07:50:40.794Z de7e4018-575a-4521-8895-fb961edd559b info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=undefined Blob=
2022-06-28T07:50:40.794Z de7e4018-575a-4521-8895-fb961edd559b verbose: DispatchMiddleware: Dispatching request...
2022-06-28T07:50:40.795Z de7e4018-575a-4521-8895-fb961edd559b info: DispatchMiddleware: Operation=Service_ListContainersSegment
2022-06-28T07:50:40.796Z de7e4018-575a-4521-8895-fb961edd559b verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-06-28T07:50:40.796Z de7e4018-575a-4521-8895-fb961edd559b info: PublicAccessAuthenticator:validate() Start validation against public access.
2022-06-28T07:50:40.796Z de7e4018-575a-4521-8895-fb961edd559b debug: PublicAccessAuthenticator:validate() Getting account properties...
2022-06-28T07:50:40.796Z de7e4018-575a-4521-8895-fb961edd559b debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: undefined, blob: 
2022-06-28T07:50:40.796Z de7e4018-575a-4521-8895-fb961edd559b info: PublicAccessAuthenticator:validate() Skip public access authentication. Container name is undefined.
2022-06-28T07:50:40.796Z de7e4018-575a-4521-8895-fb961edd559b info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2022-06-28T07:50:40.796Z de7e4018-575a-4521-8895-fb961edd559b error: BlobSharedKeyAuthenticator:validate() Invalid storage account devstoreaccount1.
2022-06-28T07:50:40.797Z de7e4018-575a-4521-8895-fb961edd559b error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2022-06-28T07:50:40.797Z de7e4018-575a-4521-8895-fb961edd559b error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Invalid storage account.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=Invalid storage account. ErrorHTTPHeaders={"x-ms-error-code":"InvalidOperation","x-ms-request-id":"de7e4018-575a-4521-8895-fb961edd559b"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:de7e4018-575a-4521-8895-fb961edd559b\nTime:2022-06-28T07:50:40.796Z</Message>\n</Error>" ErrorStack="StorageError: Invalid storage account.\n    at Function.getInvalidOperation (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:58:16)\n    at BlobSharedKeyAuthenticator.validate (/opt/azurite/dist/src/blob/authentication/BlobSharedKeyAuthenticator.js:29:49)\n    at AuthenticationMiddlewareFactory.authenticate (/opt/azurite/dist/src/blob/middlewares/AuthenticationMiddlewareFactory.js:34:40)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-06-28T07:50:40.797Z de7e4018-575a-4521-8895-fb961edd559b error: ErrorMiddleware: Set HTTP code: 400
2022-06-28T07:50:40.797Z de7e4018-575a-4521-8895-fb961edd559b error: ErrorMiddleware: Set HTTP status message: Invalid storage account.
2022-06-28T07:50:40.797Z de7e4018-575a-4521-8895-fb961edd559b error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidOperation
2022-06-28T07:50:40.797Z de7e4018-575a-4521-8895-fb961edd559b error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=de7e4018-575a-4521-8895-fb961edd559b
2022-06-28T07:50:40.797Z de7e4018-575a-4521-8895-fb961edd559b error: ErrorMiddleware: Set content type: application/xml
2022-06-28T07:50:40.797Z de7e4018-575a-4521-8895-fb961edd559b error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:de7e4018-575a-4521-8895-fb961edd559b\nTime:2022-06-28T07:50:40.796Z</Message>\n</Error>"
2022-06-28T07:50:40.797Z de7e4018-575a-4521-8895-fb961edd559b info: EndMiddleware: End response. TotalTimeInMS=4 StatusCode=400 StatusMessage=Invalid storage account. Headers={"server":"Azurite-Blob/3.18.0","x-ms-error-code":"InvalidOperation","x-ms-request-id":"de7e4018-575a-4521-8895-fb961edd559b","content-type":"application/xml"}
2022-06-28T07:50:40.970Z 67410c6f-b69d-4843-8c2f-c59a257698d6 info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://192.168.100.254/devstoreaccount1?restype=service&comp=properties RequestHeaders:{"x-ms-version":"2020-10-02","accept":"application/xml","user-agent":"Microsoft Azure Storage Explorer/1.24.3 (win32) azsdk-js-storageblob/12.8.0 (NODE-VERSION v16.13.2; Windows_NT 10.0.22000)","x-ms-client-request-id":"55a29e02-1657-4c6b-ab0c-fd92a4e01e57","x-ms-date":"Tue, 28 Jun 2022 07:50:40 GMT","authorization":"SharedKey devstoreaccount1:knFT26tus2yAlrJz6RLsbhPMH7nwxTqUfuELeiQxOlM=","cookie":"","host":"192.168.100.254:10000","connection":"keep-alive"} ClientIP=192.168.100.103 Protocol=http HTTPVersion=1.1
2022-06-28T07:50:40.971Z 67410c6f-b69d-4843-8c2f-c59a257698d6 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=undefined Blob=
2022-06-28T07:50:40.971Z 67410c6f-b69d-4843-8c2f-c59a257698d6 verbose: DispatchMiddleware: Dispatching request...
2022-06-28T07:50:40.972Z 67410c6f-b69d-4843-8c2f-c59a257698d6 info: DispatchMiddleware: Operation=Service_GetProperties
2022-06-28T07:50:40.972Z 67410c6f-b69d-4843-8c2f-c59a257698d6 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-06-28T07:50:40.973Z 67410c6f-b69d-4843-8c2f-c59a257698d6 info: PublicAccessAuthenticator:validate() Start validation against public access.
2022-06-28T07:50:40.973Z 67410c6f-b69d-4843-8c2f-c59a257698d6 debug: PublicAccessAuthenticator:validate() Getting account properties...
2022-06-28T07:50:40.973Z 67410c6f-b69d-4843-8c2f-c59a257698d6 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: undefined, blob: 
2022-06-28T07:50:40.973Z 67410c6f-b69d-4843-8c2f-c59a257698d6 info: PublicAccessAuthenticator:validate() Skip public access authentication. Container name is undefined.
2022-06-28T07:50:40.973Z 67410c6f-b69d-4843-8c2f-c59a257698d6 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2022-06-28T07:50:40.974Z 67410c6f-b69d-4843-8c2f-c59a257698d6 error: BlobSharedKeyAuthenticator:validate() Invalid storage account devstoreaccount1.
2022-06-28T07:50:40.975Z 67410c6f-b69d-4843-8c2f-c59a257698d6 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2022-06-28T07:50:40.975Z 67410c6f-b69d-4843-8c2f-c59a257698d6 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Invalid storage account.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=Invalid storage account. ErrorHTTPHeaders={"x-ms-error-code":"InvalidOperation","x-ms-request-id":"67410c6f-b69d-4843-8c2f-c59a257698d6"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:67410c6f-b69d-4843-8c2f-c59a257698d6\nTime:2022-06-28T07:50:40.974Z</Message>\n</Error>" ErrorStack="StorageError: Invalid storage account.\n    at Function.getInvalidOperation (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:58:16)\n    at BlobSharedKeyAuthenticator.validate (/opt/azurite/dist/src/blob/authentication/BlobSharedKeyAuthenticator.js:29:49)\n    at AuthenticationMiddlewareFactory.authenticate (/opt/azurite/dist/src/blob/middlewares/AuthenticationMiddlewareFactory.js:34:40)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2022-06-28T07:50:40.975Z 67410c6f-b69d-4843-8c2f-c59a257698d6 error: ErrorMiddleware: Set HTTP code: 400
2022-06-28T07:50:40.976Z 67410c6f-b69d-4843-8c2f-c59a257698d6 error: ErrorMiddleware: Set HTTP status message: Invalid storage account.
2022-06-28T07:50:40.976Z 67410c6f-b69d-4843-8c2f-c59a257698d6 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidOperation
2022-06-28T07:50:40.976Z 67410c6f-b69d-4843-8c2f-c59a257698d6 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=67410c6f-b69d-4843-8c2f-c59a257698d6
2022-06-28T07:50:40.976Z 67410c6f-b69d-4843-8c2f-c59a257698d6 error: ErrorMiddleware: Set content type: application/xml
2022-06-28T07:50:40.976Z 67410c6f-b69d-4843-8c2f-c59a257698d6 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:67410c6f-b69d-4843-8c2f-c59a257698d6\nTime:2022-06-28T07:50:40.974Z</Message>\n</Error>"
2022-06-28T07:50:40.977Z 67410c6f-b69d-4843-8c2f-c59a257698d6 info: EndMiddleware: End response. TotalTimeInMS=7 StatusCode=400 StatusMessage=Invalid storage account. Headers={"server":"Azurite-Blob/3.18.0","x-ms-error-code":"InvalidOperation","x-ms-request-id":"67410c6f-b69d-4843-8c2f-c59a257698d6","content-type":"application/xml"}
2022-06-28T07:50:47.369Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value *****
2022-06-28T07:50:47.382Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value *****
2022-06-28T07:50:47.389Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2022-06-28T07:50:47.390Z 	 info: QueueGCManger:markSweep() Get all extents.
2022-06-28T07:50:47.390Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2022-06-28T07:50:47.390Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2022-06-28T07:50:47.391Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2022-06-28T07:50:47.391Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2022-06-28T07:50:47.391Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2022-06-28T07:50:47.391Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value *****

```

**Comment by blueww** [comment]
@[lAnubisl](https://github.com/lAnubisl)

It looks in docker-compose.yaml, you should set the environment variable as following.
(note " are removed)
```
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:YXNmbDtrZm5mc2R0NXJpdGgzNDUzNHRmZHNndiBkZ2ZkZ2RmZ2RmZ2RzZ3I1dDQ1Z3c0Y3RmZyBmZGY0MzU0MzVzZGdmI0AlJEc=
```

This works on my machine. Feel free to let us know if you still see any issue.

**Comment by lAnubisl** [comment]
@blueww Thank you very much.
Do you think it is possible to print all storage account names in debug.log during service startup?
It would be much easier to identify issues like this one.

**Comment by blueww** [comment]
@[lAnubisl](https://github.com/lAnubisl)
There might be some security consideration to print all customized storage account in debug.log. However, only print account name might be OK.

We will discuss internally before do any change on that.
