### ISSUE TITLE
Query filters require table column to be on the left side of the equality operator.

### ISSUE THREAD

**Issue by pwinstead** [Azure/Azurite#1599]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.18.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
16.15.2

### What problem was encountered?
Query filters seem to require the table column to be on the left side of an operator. For example, a filter `PartitionKey eq '2022-07-12'` will return successfully. but a filter `'2022-07-12' eq PartitionKey` will fail with error message, "The query condition specified in the request is invalid."

### Steps to reproduce the issue?

1. Install and launch Azurite from the command line.
2. Install and launch Storage Explorer.
3. In Storage Explorer, create an emulator table .
4. Create a new record in the table with a partition key value of 2022-07-12 (value is not important, just used for the example)
5. Open the Query Builder and go into text edit mode to create the filter '2022-07-12' eq PartitionKey
6. Run the query and get error message "The query condition specified in the request is invalid."
_The same query run against an actual table storage account will succeed._

**Debug output**
```
Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2022-07-12T20:12:15.438Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 info: TableStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/test1 RequestHeaders:{"content-type":"application/json;odata=nometadata","accept":"application/json;odata=minimalmetadata","x-ms-version":"2019-02-02","dataserviceversion":"3.0","prefer":"return-no-content","accept-encoding":"gzip,deflate","user-agent":"Microsoft Azure Storage Explorer/1.24.3 (win32) azsdk-js-data-tables/13.1.1 core-rest-pipeline/1.8.0 Node/v16.13.2 OS/(ia32-Windows_NT-10.0.22000)","x-ms-client-request-id":"b408fc18-78b7-49f0-9a9c-35cb3f32f3fd","x-ms-date":"Tue, 12 Jul 2022 20:12:28 GMT","content-length":"46","authorization":"SharedKeyLite devstoreaccount1:u/QUfY5v64afka+JHC0xOKuHLBVdu6Bk9wJP1hTqIBk=","host":"127.0.0.1:10002","connection":"keep-alive"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 debug: tableStorageContextMiddleware: Dispatch pattern string: /test1
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=test1
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 verbose: DispatchMiddleware: Dispatching request...
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 info: DispatchMiddleware: Operation=Table_InsertEntity
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Tue, 12 Jul 2022 20:12:28 GMT\n/devstoreaccount1/devstoreaccount1/test1"
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:u/QUfY5v64afka+JHC0xOKuHLBVdu6Bk9wJP1hTqIBk=
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 verbose: DeserializerMiddleware: Start deserializing...
2022-07-12T20:12:28.620Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 debug: deserialize(): Raw request body string is (removed all empty characters) {"PartitionKey":"2022-07-12","RowKey":"13243"}
2022-07-12T20:12:28.621Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{},"requestId":"b408fc18-78b7-49f0-9a9c-35cb3f32f3fd","dataServiceVersion":"3.0","responsePreference":"return-no-content","tableEntityProperties":{"PartitionKey":"2022-07-12","RowKey":"13243"}},"version":"2019-02-02","body":"ReadableStream"}
2022-07-12T20:12:28.621Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 verbose: SerializerMiddleware: Start serializing...
2022-07-12T20:12:28.622Z 0ad62d0f-ed08-4988-8ff4-cfff3b72bb90 info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=204 StatusMessage=undefined Headers={"server":"Azurite-Table/3.18.0","content-type":"application/json;odata=minimalmetadata","x-ms-client-request-id":"b408fc18-78b7-49f0-9a9c-35cb3f32f3fd","x-ms-request-id":"0ad62d0f-ed08-4988-8ff4-cfff3b72bb90","x-ms-version":"2021-08-06","date":"Tue, 12 Jul 2022 20:12:28 GMT","etag":"W/\"datetime'2022-07-12T20%3A12%3A28.620794Z'\"","preference-applied":"return-no-content"}
2022-07-12T20:12:28.670Z fa2d49db-57d3-4723-9e85-db7513e32aea info: TableStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/test1()?$top=1000 RequestHeaders:{"accept":"application/json;odata=minimalmetadata","x-ms-version":"2019-02-02","dataserviceversion":"3.0","accept-encoding":"gzip,deflate","user-agent":"Microsoft Azure Storage Explorer/1.24.3 (win32) azsdk-js-data-tables/13.1.1 core-rest-pipeline/1.8.0 Node/v16.13.2 OS/(ia32-Windows_NT-10.0.22000)","x-ms-client-request-id":"892996c6-891f-42a0-ae9d-5bcf51e03f5b","x-ms-date":"Tue, 12 Jul 2022 20:12:28 GMT","authorization":"SharedKeyLite devstoreaccount1:1fLF6yj7neCl7WCVMGeQM8hZjF3H3Av4cmuOcrUfoH0=","host":"127.0.0.1:10002","connection":"keep-alive"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2022-07-12T20:12:28.671Z fa2d49db-57d3-4723-9e85-db7513e32aea debug: tableStorageContextMiddleware: Dispatch pattern string: /test1()
2022-07-12T20:12:28.671Z fa2d49db-57d3-4723-9e85-db7513e32aea info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=test1
2022-07-12T20:12:28.671Z fa2d49db-57d3-4723-9e85-db7513e32aea verbose: DispatchMiddleware: Dispatching request...
2022-07-12T20:12:28.671Z fa2d49db-57d3-4723-9e85-db7513e32aea info: DispatchMiddleware: Operation=Table_QueryEntities
2022-07-12T20:12:28.671Z fa2d49db-57d3-4723-9e85-db7513e32aea verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-07-12T20:12:28.671Z fa2d49db-57d3-4723-9e85-db7513e32aea info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2022-07-12T20:12:28.672Z fa2d49db-57d3-4723-9e85-db7513e32aea info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Tue, 12 Jul 2022 20:12:28 GMT\n/devstoreaccount1/devstoreaccount1/test1()"
2022-07-12T20:12:28.672Z fa2d49db-57d3-4723-9e85-db7513e32aea info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:1fLF6yj7neCl7WCVMGeQM8hZjF3H3Av4cmuOcrUfoH0=
2022-07-12T20:12:28.672Z fa2d49db-57d3-4723-9e85-db7513e32aea info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
2022-07-12T20:12:28.672Z fa2d49db-57d3-4723-9e85-db7513e32aea verbose: DeserializerMiddleware: Start deserializing...
2022-07-12T20:12:28.672Z fa2d49db-57d3-4723-9e85-db7513e32aea info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"top":1000},"requestId":"892996c6-891f-42a0-ae9d-5bcf51e03f5b","dataServiceVersion":"3.0"},"version":"2019-02-02"}
2022-07-12T20:12:28.672Z fa2d49db-57d3-4723-9e85-db7513e32aea debug: TableHandler:queryEntities() Raw response string is "{\"odata.metadata\":\"http://127.0.0.1:10002/devstoreaccount1/$metadata#Tables/@Element\",\"value\":[{\"odata.etag\":\"W/\\\"datetime'2022-07-12T20%3A12%3A28.620794Z'\\\"\",\"PartitionKey\":\"2022-07-12\",\"RowKey\":\"13243\",\"Timestamp@odata.type\":\"Edm.DateTime\",\"Timestamp\":\"2022-07-12T20:12:28.6200000Z\"}]}"
2022-07-12T20:12:28.672Z fa2d49db-57d3-4723-9e85-db7513e32aea verbose: SerializerMiddleware: Start serializing...
2022-07-12T20:12:28.672Z fa2d49db-57d3-4723-9e85-db7513e32aea info: Serializer: Start returning stream body.
2022-07-12T20:12:28.674Z fa2d49db-57d3-4723-9e85-db7513e32aea info: EndMiddleware: End response. TotalTimeInMS=4 StatusCode=200 StatusMessage=OK Headers={"server":"Azurite-Table/3.18.0","content-type":"application/json;odata=minimalmetadata","x-ms-client-request-id":"892996c6-891f-42a0-ae9d-5bcf51e03f5b","x-ms-request-id":"fa2d49db-57d3-4723-9e85-db7513e32aea","x-ms-version":"2021-08-06","date":"Tue, 12 Jul 2022 20:12:28 GMT"}
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da info: TableStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/test1()?$top=1000&$select=&$filter=%272022-07-12%27%20eq%20PartitionKey RequestHeaders:{"accept":"application/json;odata=minimalmetadata","x-ms-version":"2019-02-02","dataserviceversion":"3.0","accept-encoding":"gzip,deflate","user-agent":"Microsoft Azure Storage Explorer/1.24.3 (win32) azsdk-js-data-tables/13.1.1 core-rest-pipeline/1.8.0 Node/v16.13.2 OS/(ia32-Windows_NT-10.0.22000)","x-ms-client-request-id":"8972acdb-7dd4-4a51-9b3b-b163f605e580","x-ms-date":"Tue, 12 Jul 2022 20:12:48 GMT","authorization":"SharedKeyLite devstoreaccount1:ZgH0rgnG/vMj+2kY2b1GT+eV/FJ4GFa3w5sIUZ/ICqI=","host":"127.0.0.1:10002","connection":"keep-alive"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da debug: tableStorageContextMiddleware: Dispatch pattern string: /test1()
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=test1
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da verbose: DispatchMiddleware: Dispatching request...
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da info: DispatchMiddleware: Operation=Table_QueryEntities
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Tue, 12 Jul 2022 20:12:48 GMT\n/devstoreaccount1/devstoreaccount1/test1()"
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:ZgH0rgnG/vMj+2kY2b1GT+eV/FJ4GFa3w5sIUZ/ICqI=
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da verbose: DeserializerMiddleware: Start deserializing...
2022-07-12T20:12:48.685Z ef41ffb0-b682-4ca7-8693-898b699834da info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"top":1000,"select":"","filter":"'2022-07-12' eq PartitionKey"},"requestId":"8972acdb-7dd4-4a51-9b3b-b163f605e580","dataServiceVersion":"3.0"},"version":"2019-02-02"}
2022-07-12T20:12:48.686Z ef41ffb0-b682-4ca7-8693-898b699834da error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2022-07-12T20:12:48.686Z ef41ffb0-b682-4ca7-8693-898b699834da error: ErrorMiddleware: ErrorName=StorageError ErrorMessage="The query condition specified in the request is invalid."  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"InvalidInput","x-ms-request-id":"ef41ffb0-b682-4ca7-8693-898b699834da","x-ms-version":"2021-08-06"} ErrorHTTPBody="{\"odata.error\":{\"code\":\"InvalidInput\",\"message\":{\"lang\":\"en-US\",\"value\":\"The query condition specified in the request is invalid.\\nRequestId:ef41ffb0-b682-4ca7-8693-898b699834da\\nTime:2022-07-12T20:12:48.686Z\"}}}" ErrorStack="\"StorageError: The query condition specified in the request is invalid.\\n    at Function.getQueryConditionInvalid (C:\\\\Users\\\\redacted\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\errors\\\\StorageErrorFactory.js:79:16)\\n    at LokiTableMetadataStore.queryTableEntities (C:\\\\Users\\\\redacted\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\persistence\\\\LokiTableMetadataStore.js:336:49)\\n    at TableHandler.queryEntities (C:\\\\Users\\\\redacted\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\handlers\\\\TableHandler.js:322:81)\\n    at C:\\\\Users\\\\redacted\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\generated\\\\middleware\\\\HandlerMiddlewareFactory.js:58:18\\n    at C:\\\\Users\\\\redacted\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\generated\\\\ExpressMiddlewareFactory.js:77:63\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\redacted\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at trim_prefix (C:\\\\Users\\\\redacted\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:328:13)\\n    at C:\\\\Users\\\\redacted\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:286:9\\n    at Function.process_params (C:\\\\Users\\\\redacted\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:346:12)\\n    at next (C:\\\\Users\\\\redacted\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:280:10)\""
2022-07-12T20:12:48.686Z ef41ffb0-b682-4ca7-8693-898b699834da error: ErrorMiddleware: Set HTTP code: 400
2022-07-12T20:12:48.686Z ef41ffb0-b682-4ca7-8693-898b699834da error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidInput
2022-07-12T20:12:48.686Z ef41ffb0-b682-4ca7-8693-898b699834da error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=ef41ffb0-b682-4ca7-8693-898b699834da
2022-07-12T20:12:48.686Z ef41ffb0-b682-4ca7-8693-898b699834da error: ErrorMiddleware: Set HTTP Header: x-ms-version=2021-08-06
2022-07-12T20:12:48.686Z ef41ffb0-b682-4ca7-8693-898b699834da error: ErrorMiddleware: Set content type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
2022-07-12T20:12:48.686Z ef41ffb0-b682-4ca7-8693-898b699834da error: ErrorMiddleware: Set HTTP body: "{\"odata.error\":{\"code\":\"InvalidInput\",\"message\":{\"lang\":\"en-US\",\"value\":\"The query condition specified in the request is invalid.\\nRequestId:ef41ffb0-b682-4ca7-8693-898b699834da\\nTime:2022-07-12T20:12:48.686Z\"}}}"
2022-07-12T20:12:48.686Z ef41ffb0-b682-4ca7-8693-898b699834da info: EndMiddleware: End response. TotalTimeInMS=1 StatusCode=400 StatusMessage=Bad Request Headers={"server":"Azurite-Table/3.18.0","x-ms-error-code":"InvalidInput","x-ms-request-id":"ef41ffb0-b682-4ca7-8693-898b699834da","x-ms-version":"2021-08-06","content-type":"application/json;odata=minimalmetadata;streaming=true;charset=utf-8"}
```

### Have you found a mitigation/solution?
Yes, simply rework the query so table column comes first. Ex `PartitionKey eq '2022-07-12'`

**Comment by edwin-huber** [comment]
Thanks for raising this.  
This is an unusual request, as convention usually puts the value on the right.  
All OData examples have the value on the right.
We're looking into it to see if we can fix with a reasonable amount of effort, and what the expected behavior is in the service and our SDKs.

**Comment by edwin-huber** [comment]
This requires a re-working of the query parser, which is now underway.

**Comment by edwin-huber** [comment]
This is now resolved in the current version of Azurite and has supporting tests.
