### ISSUE TITLE
ResourceNotFound. Azure.Data.Tables: The specified resource does not exist.  

### ISSUE THREAD

**Issue by rahuljainhere** [Azure/Azurite#1736]
### Which service(blob, file, queue, table) does this issue concern?
Azure Blob Storage Service.

### Which version of the Azurite was used?
Version 3.18

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio 2022

### What problem was encountered?
When we use Azure.Data.Table.UpsertEntityAsync() function, it throws Resource Not found exception
![image](https://user-images.githubusercontent.com/117095484/199031685-638c40d1-b4de-4798-8e4f-31e636f70532.png)

### Steps to reproduce the issue?
TableClient table = new TableClient(storageConnectionString, "Log");
            await table.CreateIfNotExistsAsync();
            await table.UpsertEntityAsync(object);

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
@rahuljainhere 
Would you please attach the Azurite debug log?
It looks we can't repro this issue locally, so we need the Azurite debug log for further investigation.

**Comment by rahuljainhere** [comment]
@blueww Attached Azurite debug log below: 
2022-11-01T08:01:23.515Z 0012076e-60a1-44b0-a979-307fcd35b92c info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/azure-webjobs-hosts/locks/azrdevvm242-954725033/BakerHill.AzureFunctions.Imaging.Export.StartImaging.Run.Listener?comp=lease RequestHeaders:{"host":"127.0.0.1:10000","x-ms-lease-action":"renew","x-ms-lease-id":"2794fedc-6840-4483-aa5b-b24a913e0793","x-ms-version":"2020-08-04","accept":"application/xml","x-ms-client-request-id":"a8ed0a6f-4896-4b40-856f-374d548aa17a","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Storage.Blobs/12.9.0 (.NET 6.0.9; Microsoft Windows 10.0.19044)","x-ms-date":"Tue, 01 Nov 2022 08:01:23 GMT","authorization":"SharedKey devstoreaccount1:MyDKovIyaAaH5hnmQOg0pB32yFmZfYAzQZwAL9n5q68=","content-length":"0"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2022-11-01T08:01:23.515Z 0012076e-60a1-44b0-a979-307fcd35b92c info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=azure-webjobs-hosts Blob=locks/azrdevvm242-954725033/BakerHill.AzureFunctions.Imaging.Export.StartImaging.Run.Listener
2022-11-01T08:01:23.515Z 0012076e-60a1-44b0-a979-307fcd35b92c verbose: DispatchMiddleware: Dispatching request...
2022-11-01T08:01:23.515Z 0012076e-60a1-44b0-a979-307fcd35b92c info: DispatchMiddleware: Operation=Blob_RenewLease
2022-11-01T08:01:23.515Z 0012076e-60a1-44b0-a979-307fcd35b92c verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-11-01T08:01:23.515Z 0012076e-60a1-44b0-a979-307fcd35b92c info: PublicAccessAuthenticator:validate() Start validation against public access.
2022-11-01T08:01:23.515Z 0012076e-60a1-44b0-a979-307fcd35b92c debug: PublicAccessAuthenticator:validate() Getting account properties...
2022-11-01T08:01:23.515Z 0012076e-60a1-44b0-a979-307fcd35b92c debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: azure-webjobs-hosts, blob: locks/azrdevvm242-954725033/BakerHill.AzureFunctions.Imaging.Export.StartImaging.Run.Listener
2022-11-01T08:01:23.515Z 0012076e-60a1-44b0-a979-307fcd35b92c debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container azure-webjobs-hosts
2022-11-01T08:01:23.515Z 0012076e-60a1-44b0-a979-307fcd35b92c info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2022-11-01T08:01:23.516Z 0012076e-60a1-44b0-a979-307fcd35b92c info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:a8ed0a6f-4896-4b40-856f-374d548aa17a\nx-ms-date:Tue, 01 Nov 2022 08:01:23 GMT\nx-ms-lease-action:renew\nx-ms-lease-id:2794fedc-6840-4483-aa5b-b24a913e0793\nx-ms-return-client-request-id:true\nx-ms-version:2020-08-04\n/devstoreaccount1/devstoreaccount1/azure-webjobs-hosts/locks/azrdevvm242-954725033/BakerHill.AzureFunctions.Imaging.Export.StartImaging.Run.Listener\ncomp:lease"
2022-11-01T08:01:23.516Z 0012076e-60a1-44b0-a979-307fcd35b92c info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:MyDKovIyaAaH5hnmQOg0pB32yFmZfYAzQZwAL9n5q68=
2022-11-01T08:01:23.516Z 0012076e-60a1-44b0-a979-307fcd35b92c info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2022-11-01T08:01:23.516Z 0012076e-60a1-44b0-a979-307fcd35b92c verbose: DeserializerMiddleware: Start deserializing...
2022-11-01T08:01:23.516Z 0012076e-60a1-44b0-a979-307fcd35b92c info: HandlerMiddleware: DeserializedParameters={"options":{"requestId":"a8ed0a6f-4896-4b40-856f-374d548aa17a","modifiedAccessConditions":{}},"comp":"lease","leaseId":"2794fedc-6840-4483-aa5b-b24a913e0793","version":"2020-08-04","action":"renew"}
2022-11-01T08:01:23.516Z 0012076e-60a1-44b0-a979-307fcd35b92c verbose: SerializerMiddleware: Start serializing...
2022-11-01T08:01:23.516Z 0012076e-60a1-44b0-a979-307fcd35b92c info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=200 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.18.0","etag":"\"0x1A513AA9730A000\"","last-modified":"Tue, 01 Nov 2022 07:53:37 GMT","x-ms-lease-id":"2794fedc-6840-4483-aa5b-b24a913e0793","x-ms-client-request-id":"a8ed0a6f-4896-4b40-856f-374d548aa17a","x-ms-request-id":"0012076e-60a1-44b0-a979-307fcd35b92c","x-ms-version":"2021-08-06","date":"Tue, 01 Nov 2022 08:01:23 GMT"}
2022-11-01T08:01:24.612Z b8b259e8-3303-4ccb-8dc8-19b707690414 info: QueueStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/imagingfinancialinstitution?comp=metadata RequestHeaders:{"host":"127.0.0.1:10001","x-ms-version":"2018-11-09","accept":"application/xml","x-ms-client-request-id":"a6c00e5a-498b-405a-a737-58c631201944","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Storage.Queues/12.10.0 (.NET 6.0.9; Microsoft Windows 10.0.19044)","x-ms-date":"Tue, 01 Nov 2022 08:01:24 GMT","authorization":"SharedKey devstoreaccount1:yK0hCW+1OBff/urrt/OnKOI6Z7fnlKAIpCYePky59rk="} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2022-11-01T08:01:24.612Z b8b259e8-3303-4ccb-8dc8-19b707690414 info: QueueStorageContextMiddleware: Account=devstoreaccount1 Queue=imagingfinancialinstitution Message=undefined MessageId=undefined
2022-11-01T08:01:24.612Z b8b259e8-3303-4ccb-8dc8-19b707690414 verbose: DispatchMiddleware: Dispatching request...
2022-11-01T08:01:24.612Z b8b259e8-3303-4ccb-8dc8-19b707690414 info: DispatchMiddleware: Operation=Queue_GetProperties
2022-11-01T08:01:24.612Z b8b259e8-3303-4ccb-8dc8-19b707690414 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-11-01T08:01:24.612Z b8b259e8-3303-4ccb-8dc8-19b707690414 info: QueueSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2022-11-01T08:01:24.612Z b8b259e8-3303-4ccb-8dc8-19b707690414 info: QueueSharedKeyAuthenticator:validate() [STRING TO SIGN]:"GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:a6c00e5a-498b-405a-a737-58c631201944\nx-ms-date:Tue, 01 Nov 2022 08:01:24 GMT\nx-ms-return-client-request-id:true\nx-ms-version:2018-11-09\n/devstoreaccount1/devstoreaccount1/imagingfinancialinstitution\ncomp:metadata"
2022-11-01T08:01:24.612Z b8b259e8-3303-4ccb-8dc8-19b707690414 info: QueueSharedKeyAuthenticator:validate() Calculated authentication header based on key1: devstoreaccount1:yK0hCW+1OBff/urrt/OnKOI6Z7fnlKAIpCYePky59rk=
2022-11-01T08:01:24.612Z b8b259e8-3303-4ccb-8dc8-19b707690414 info: QueueSharedKeyAuthenticator:validate() Signature 1 matched.
2022-11-01T08:01:24.612Z b8b259e8-3303-4ccb-8dc8-19b707690414 verbose: DeserializerMiddleware: Start deserializing...
2022-11-01T08:01:24.612Z b8b259e8-3303-4ccb-8dc8-19b707690414 info: HandlerMiddleware: DeserializedParameters={"options":{"requestId":"a6c00e5a-498b-405a-a737-58c631201944"},"comp":"metadata","version":"2018-11-09"}
2022-11-01T08:01:24.613Z b8b259e8-3303-4ccb-8dc8-19b707690414 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2022-11-01T08:01:24.613Z b8b259e8-3303-4ccb-8dc8-19b707690414 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified queue does not exist.  ErrorHTTPStatusCode=404 ErrorHTTPStatusMessage=The specified queue does not exist. ErrorHTTPHeaders={"x-ms-error-code":"QueueNotFound","x-ms-request-id":"b8b259e8-3303-4ccb-8dc8-19b707690414","x-ms-version":"2021-08-06"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>QueueNotFound</Code>\n  <Message>The specified queue does not exist.\nRequestId:b8b259e8-3303-4ccb-8dc8-19b707690414\nTime:2022-11-01T08:01:24.612Z</Message>\n</Error>" ErrorStack="StorageError: The specified queue does not exist.\n    at Function.getQueueNotFound (C:\\snapshot\\_azure_azurite\\dist\\src\\queue\\errors\\StorageErrorFactory.js:110:16)\n    at LokiQueueMetadataStore.getQueue (C:\\snapshot\\_azure_azurite\\dist\\src\\queue\\persistence\\LokiQueueMetadataStore.js:230:49)\n    at QueueHandler.getProperties (C:\\snapshot\\_azure_azurite\\dist\\src\\queue\\handlers\\QueueHandler.js:81:48)\n    at C:\\snapshot\\_azure_azurite\\dist\\src\\queue\\generated\\middleware\\HandlerMiddlewareFactory.js:58:18\n    at C:\\snapshot\\_azure_azurite\\dist\\src\\queue\\generated\\ExpressMiddlewareFactory.js:77:63\n    at Layer.handle [as handle_request] (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:280:10)"
2022-11-01T08:01:24.613Z b8b259e8-3303-4ccb-8dc8-19b707690414 error: ErrorMiddleware: Set HTTP code: 404
2022-11-01T08:01:24.613Z b8b259e8-3303-4ccb-8dc8-19b707690414 error: ErrorMiddleware: Set HTTP status message: The specified queue does not exist.
2022-11-01T08:01:24.613Z b8b259e8-3303-4ccb-8dc8-19b707690414 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=QueueNotFound
2022-11-01T08:01:24.613Z b8b259e8-3303-4ccb-8dc8-19b707690414 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=b8b259e8-3303-4ccb-8dc8-19b707690414
2022-11-01T08:01:24.613Z b8b259e8-3303-4ccb-8dc8-19b707690414 error: ErrorMiddleware: Set HTTP Header: x-ms-version=2021-08-06
2022-11-01T08:01:24.613Z b8b259e8-3303-4ccb-8dc8-19b707690414 error: ErrorMiddleware: Set content type: application/xml
2022-11-01T08:01:24.613Z b8b259e8-3303-4ccb-8dc8-19b707690414 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>QueueNotFound</Code>\n  <Message>The specified queue does not exist.\nRequestId:b8b259e8-3303-4ccb-8dc8-19b707690414\nTime:2022-11-01T08:01:24.612Z</Message>\n</Error>"
2022-11-01T08:01:24.613Z b8b259e8-3303-4ccb-8dc8-19b707690414 info: EndMiddleware: End response. TotalTimeInMS=1 StatusCode=404 StatusMessage=The specified queue does not exist. Headers={"server":"Azurite-Queue/3.18.0","x-ms-error-code":"QueueNotFound","x-ms-request-id":"b8b259e8-3303-4ccb-8dc8-19b707690414","x-ms-version":"2021-08-06","content-type":"application/xml"}
2022-11-01T08:01:24.953Z e91b3ecd-6d47-41d3-952d-914aa18f455c info: QueueStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/imagingtrackingitem?comp=metadata RequestHeaders:{"host":"127.0.0.1:10001","x-ms-version":"2018-11-09","accept":"application/xml","x-ms-client-request-id":"a7209520-797a-411f-b145-8bab78e1647c","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Storage.Queues/12.10.0 (.NET 6.0.9; Microsoft Windows 10.0.19044)","x-ms-date":"Tue, 01 Nov 2022 08:01:24 GMT","authorization":"SharedKey devstoreaccount1:YYS8o+dg21kxakJGzXeSVTPx6EXHf5Ms14OqFEmxhD4="} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2022-11-01T08:01:24.953Z e91b3ecd-6d47-41d3-952d-914aa18f455c info: QueueStorageContextMiddleware: Account=devstoreaccount1 Queue=imagingtrackingitem Message=undefined MessageId=undefined
2022-11-01T08:01:24.953Z e91b3ecd-6d47-41d3-952d-914aa18f455c verbose: DispatchMiddleware: Dispatching request...
2022-11-01T08:01:24.954Z e91b3ecd-6d47-41d3-952d-914aa18f455c info: DispatchMiddleware: Operation=Queue_GetProperties
2022-11-01T08:01:24.954Z e91b3ecd-6d47-41d3-952d-914aa18f455c verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-11-01T08:01:24.954Z e91b3ecd-6d47-41d3-952d-914aa18f455c info: QueueSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2022-11-01T08:01:24.954Z e91b3ecd-6d47-41d3-952d-914aa18f455c info: QueueSharedKeyAuthenticator:validate() [STRING TO SIGN]:"GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:a7209520-797a-411f-b145-8bab78e1647c\nx-ms-date:Tue, 01 Nov 2022 08:01:24 GMT\nx-ms-return-client-request-id:true\nx-ms-version:2018-11-09\n/devstoreaccount1/devstoreaccount1/imagingtrackingitem\ncomp:metadata"
2022-11-01T08:01:24.954Z e91b3ecd-6d47-41d3-952d-914aa18f455c info: QueueSharedKeyAuthenticator:validate() Calculated authentication header based on key1: devstoreaccount1:YYS8o+dg21kxakJGzXeSVTPx6EXHf5Ms14OqFEmxhD4=
2022-11-01T08:01:24.954Z e91b3ecd-6d47-41d3-952d-914aa18f455c info: QueueSharedKeyAuthenticator:validate() Signature 1 matched.
2022-11-01T08:01:24.954Z e91b3ecd-6d47-41d3-952d-914aa18f455c verbose: DeserializerMiddleware: Start deserializing...
2022-11-01T08:01:24.954Z e91b3ecd-6d47-41d3-952d-914aa18f455c info: HandlerMiddleware: DeserializedParameters={"options":{"requestId":"a7209520-797a-411f-b145-8bab78e1647c"},"comp":"metadata","version":"2018-11-09"}
2022-11-01T08:01:24.955Z e91b3ecd-6d47-41d3-952d-914aa18f455c error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2022-11-01T08:01:24.955Z e91b3ecd-6d47-41d3-952d-914aa18f455c error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified queue does not exist.  ErrorHTTPStatusCode=404 ErrorHTTPStatusMessage=The specified queue does not exist. ErrorHTTPHeaders={"x-ms-error-code":"QueueNotFound","x-ms-request-id":"e91b3ecd-6d47-41d3-952d-914aa18f455c","x-ms-version":"2021-08-06"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>QueueNotFound</Code>\n  <Message>The specified queue does not exist.\nRequestId:e91b3ecd-6d47-41d3-952d-914aa18f455c\nTime:2022-11-01T08:01:24.954Z</Message>\n</Error>" ErrorStack="StorageError: The specified queue does not exist.\n    at Function.getQueueNotFound (C:\\snapshot\\_azure_azurite\\dist\\src\\queue\\errors\\StorageErrorFactory.js:110:16)\n    at LokiQueueMetadataStore.getQueue (C:\\snapshot\\_azure_azurite\\dist\\src\\queue\\persistence\\LokiQueueMetadataStore.js:230:49)\n    at QueueHandler.getProperties (C:\\snapshot\\_azure_azurite\\dist\\src\\queue\\handlers\\QueueHandler.js:81:48)\n    at C:\\snapshot\\_azure_azurite\\dist\\src\\queue\\generated\\middleware\\HandlerMiddlewareFactory.js:58:18\n    at C:\\snapshot\\_azure_azurite\\dist\\src\\queue\\generated\\ExpressMiddlewareFactory.js:77:63\n    at Layer.handle [as handle_request] (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:280:10)"
2022-11-01T08:01:24.955Z e91b3ecd-6d47-41d3-952d-914aa18f455c error: ErrorMiddleware: Set HTTP code: 404
2022-11-01T08:01:24.955Z e91b3ecd-6d47-41d3-952d-914aa18f455c error: ErrorMiddleware: Set HTTP status message: The specified queue does not exist.
2022-11-01T08:01:24.955Z e91b3ecd-6d47-41d3-952d-914aa18f455c error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=QueueNotFound
2022-11-01T08:01:24.955Z e91b3ecd-6d47-41d3-952d-914aa18f455c error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=e91b3ecd-6d47-41d3-952d-914aa18f455c
2022-11-01T08:01:24.955Z e91b3ecd-6d47-41d3-952d-914aa18f455c error: ErrorMiddleware: Set HTTP Header: x-ms-version=2021-08-06
2022-11-01T08:01:24.955Z e91b3ecd-6d47-41d3-952d-914aa18f455c error: ErrorMiddleware: Set content type: application/xml
2022-11-01T08:01:24.955Z e91b3ecd-6d47-41d3-952d-914aa18f455c error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>QueueNotFound</Code>\n  <Message>The specified queue does not exist.\nRequestId:e91b3ecd-6d47-41d3-952d-914aa18f455c\nTime:2022-11-01T08:01:24.954Z</Message>\n</Error>"
2022-11-01T08:01:24.955Z e91b3ecd-6d47-41d3-952d-914aa18f455c info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=404 StatusMessage=The specified queue does not exist. Headers={"server":"Azurite-Queue/3.18.0","x-ms-error-code":"QueueNotFound","x-ms-request-id":"e91b3ecd-6d47-41d3-952d-914aa18f455c","x-ms-version":"2021-08-06","content-type":"application/xml"}

**Comment by blueww** [comment]
@rahuljainhere 

From the SDK/API you using, it looks you are trying send table service request.
But from the debug log we see 404 error happens on request Queue service request: "Operation=Queue_GetProperties".

It looks you have set wrong Table Endpoint in the storageConnectionString.
Please note, Azurite table service use Port 10002 by default (Queue use 10001 by default), and you can change it with parameter "--tablePort ". See more details in https://github.com/Azure/Azurite#listening-port-configuration

**Comment by rahuljainhere** [comment]
I tried above and got all three services (blob/ queue/table) up and running on three ports 10000, 10001, 10002 but didn't resolve my issue. 
After that, upgraded the Azurite version to greater than 3.19 and it resolved my issue. 

Thanks for your support. Closing the bug.
