### ISSUE TITLE
Failed table transaction with multiple entities with same RowKey returns HTTP 409(EntityAlreadyExists) instead of HTTP 400(InvalidDuplicateRow) 

### ISSUE THREAD

**Issue by gonzales91** [Azure/Azurite#1754]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
3.20.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v12.18.4

### What problem was encountered?
When submitting a batch transaction which adding more than one elements which same rowKey got inappropriate error.

`1:The specified entity already exists.
RequestId:8a67323b-cde6-41d5-89eb-79ba4ad1b7dc
Time:2022-11-16T14:31:52.155Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.
Status: 409 (Conflict)
ErrorCode: EntityAlreadyExists`

The proper error should be 400 (InvalidDuplicateRow) like this:
`1:The batch request contains multiple changes with same row key. An entity can appear only once in a batch request.
RequestId:37cdf7a6-5873-4efb-8b94-be36221a6b7a
Time:2022-11-16T14:33:57.5727871Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.
Status: 400 (Bad Request)
ErrorCode: InvalidDuplicateRow`

### Steps to reproduce the issue?
```csharp
var tableServiceClient = new TableServiceClient("UseDevelopmentStorage=true;");
var tableClient = tableServiceClient.GetTableClient("sampleTable");
await tableClient.CreateIfNotExistsAsync();

try
{
    await tableClient.SubmitTransactionAsync(new List<TableTransactionAction>
    {
         new(TableTransactionActionType.Add, new TableEntity("samePartition", "sameRowKey")),
         new(TableTransactionActionType.Add, new TableEntity("samePartition", "sameRowKey"))
    });
}
catch (RequestFailedException e)
{
      Console.WriteLine(e.ToString());
}
```

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```2022-11-16T15:13:47.538Z 	 info: Azurite Table service is starting on 127.0.0.1:10002
2022-11-16T15:13:47.539Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2022-11-16T15:13:47.539Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2022-11-16T15:13:47.567Z 	 info: Azurite Table service successfully listens on http://127.0.0.1:10002
2022-11-16T15:13:52.552Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 info: TableStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/Tables?$format=application%2Fjson%3Bodata%3Dminimalmetadata RequestHeaders:{"host":"127.0.0.1:10002","x-ms-version":"2020-12-06","dataserviceversion":"3.0","prefer":"return-no-content","accept":"application/json;odata=minimalmetadata","x-ms-client-request-id":"a825bcd7-9063-4234-92eb-00e6546f0130","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Data.Tables/12.7.1 (.NET 6.0.11; Microsoft Windows 10.0.22000)","x-ms-date":"Wed, 16 Nov 2022 15:13:52 GMT","authorization":"SharedKeyLite devstoreaccount1:J3PgAFlOxa7iVl6rarqpYP6C8KraJtpOZ9Ng9i0Ti94=","content-type":"application/json;odata=nometadata","content-length":"27"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2022-11-16T15:13:52.553Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 debug: tableStorageContextMiddleware: Dispatch pattern string: /Tables
2022-11-16T15:13:52.553Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=undefined
2022-11-16T15:13:52.553Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 verbose: DispatchMiddleware: Dispatching request...
2022-11-16T15:13:52.555Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 info: DispatchMiddleware: Operation=Table_Create
2022-11-16T15:13:52.555Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-11-16T15:13:52.555Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2022-11-16T15:13:52.556Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Wed, 16 Nov 2022 15:13:52 GMT\n/devstoreaccount1/devstoreaccount1/Tables"
2022-11-16T15:13:52.557Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:J3PgAFlOxa7iVl6rarqpYP6C8KraJtpOZ9Ng9i0Ti94=
2022-11-16T15:13:52.557Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
2022-11-16T15:13:52.557Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 verbose: DeserializerMiddleware: Start deserializing...
2022-11-16T15:13:52.559Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 debug: deserialize(): Raw request body string is (removed all empty characters) {"TableName":"sampleTable"}
2022-11-16T15:13:52.560Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"format":"application/json;odata=minimalmetadata"},"requestId":"a825bcd7-9063-4234-92eb-00e6546f0130","dataServiceVersion":"3.0","responsePreference":"return-no-content"},"version":"2020-12-06","tableProperties":{"tableName":"sampleTable"},"body":"ReadableStream"}
2022-11-16T15:13:52.563Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2022-11-16T15:13:52.564Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage="The table specified already exists."  ErrorHTTPStatusCode=409 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"TableAlreadyExists","x-ms-request-id":"50422e6b-4c6a-4fd4-adef-d6f6ac3545e1","x-ms-version":"2021-10-04"} ErrorHTTPBody="{\"odata.error\":{\"code\":\"TableAlreadyExists\",\"message\":{\"lang\":\"en-US\",\"value\":\"The table specified already exists.\\nRequestId:50422e6b-4c6a-4fd4-adef-d6f6ac3545e1\\nTime:2022-11-16T15:13:52.562Z\"}}}" ErrorStack="\"StorageError: The table specified already exists.\\n    at Function.getTableAlreadyExists (C:\\\\azurite\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\errors\\\\StorageErrorFactory.js:23:16)\\n    at LokiTableMetadataStore.createTable (C:\\\\azurite\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\persistence\\\\LokiTableMetadataStore.js:114:49)\\n    at TableHandler.create (C:\\\\azurite\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\handlers\\\\TableHandler.js:40:34)\\n    at C:\\\\azurite\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\generated\\\\middleware\\\\HandlerMiddlewareFactory.js:58:18\\n    at C:\\\\azurite\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\generated\\\\ExpressMiddlewareFactory.js:77:63\\n    at Layer.handle [as handle_request] (C:\\\\azurite\\\\node_modules\\\\azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at trim_prefix (C:\\\\azurite\\\\node_modules\\\\azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:328:13)\\n    at C:\\\\azurite\\\\node_modules\\\\azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:286:9\\n    at Function.process_params (C:\\\\azurite\\\\node_modules\\\\azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:346:12)\\n    at next (C:\\\\azurite\\\\node_modules\\\\azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:280:10)\""
2022-11-16T15:13:52.564Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 error: ErrorMiddleware: Set HTTP code: 409
2022-11-16T15:13:52.564Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=TableAlreadyExists
2022-11-16T15:13:52.564Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=50422e6b-4c6a-4fd4-adef-d6f6ac3545e1
2022-11-16T15:13:52.564Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 error: ErrorMiddleware: Set HTTP Header: x-ms-version=2021-10-04
2022-11-16T15:13:52.564Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 error: ErrorMiddleware: Set content type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
2022-11-16T15:13:52.564Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 error: ErrorMiddleware: Set HTTP body: "{\"odata.error\":{\"code\":\"TableAlreadyExists\",\"message\":{\"lang\":\"en-US\",\"value\":\"The table specified already exists.\\nRequestId:50422e6b-4c6a-4fd4-adef-d6f6ac3545e1\\nTime:2022-11-16T15:13:52.562Z\"}}}"
2022-11-16T15:13:52.565Z 50422e6b-4c6a-4fd4-adef-d6f6ac3545e1 info: EndMiddleware: End response. TotalTimeInMS=13 StatusCode=409 StatusMessage=Conflict Headers={"server":"Azurite-Table/3.20.1","x-ms-error-code":"TableAlreadyExists","x-ms-request-id":"50422e6b-4c6a-4fd4-adef-d6f6ac3545e1","x-ms-version":"2021-10-04","content-type":"application/json;odata=minimalmetadata;streaming=true;charset=utf-8"}
2022-11-16T15:13:52.681Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 info: TableStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/$batch RequestHeaders:{"host":"127.0.0.1:10002","x-ms-version":"2020-12-06","dataserviceversion":"3.0","accept":"application/json","x-ms-client-request-id":"5bc9c666-f106-4d3e-91b5-167ed73b61f8","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Data.Tables/12.7.1 (.NET 6.0.11; Microsoft Windows 10.0.22000)","x-ms-date":"Wed, 16 Nov 2022 15:13:52 GMT","authorization":"SharedKeyLite devstoreaccount1:W6l0867Tt0iztUICd3Q9Bcd9mVXCBjGnEgW/K6Jrips=","content-type":"multipart/mixed; boundary=batch_03995ca5-001f-440d-82f8-11b40121dd5e","content-length":"1216"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2022-11-16T15:13:52.681Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 debug: tableStorageContextMiddleware: Dispatch pattern string: /$batch
2022-11-16T15:13:52.681Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=$batch
2022-11-16T15:13:52.681Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 verbose: DispatchMiddleware: Dispatching request...
2022-11-16T15:13:52.682Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 info: DispatchMiddleware: Operation=Table_Batch
2022-11-16T15:13:52.682Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2022-11-16T15:13:52.682Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2022-11-16T15:13:52.682Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Wed, 16 Nov 2022 15:13:52 GMT\n/devstoreaccount1/devstoreaccount1/$batch"
2022-11-16T15:13:52.682Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:W6l0867Tt0iztUICd3Q9Bcd9mVXCBjGnEgW/K6Jrips=
2022-11-16T15:13:52.682Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
2022-11-16T15:13:52.682Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 verbose: DeserializerMiddleware: Start deserializing...
2022-11-16T15:13:52.683Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 info: HandlerMiddleware: DeserializedParameters={"version":"2020-12-06","options":{"requestId":"5bc9c666-f106-4d3e-91b5-167ed73b61f8","dataServiceVersion":"3.0"},"multipartContentType":"multipart/mixed; boundary=batch_03995ca5-001f-440d-82f8-11b40121dd5e","contentLength":1216,"body":"ReadableStream"}
2022-11-16T15:13:52.684Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 debug: TableHandler:batch() Raw request string is "--batch_03995ca5-001f-440d-82f8-11b40121dd5e\r\nContent-Type: multipart/mixed; boundary=changeset_6ec27c11-728f-4b70-b763-a8cbbf761fe6\r\n\r\n--changeset_6ec27c11-728f-4b70-b763-a8cbbf761fe6\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nPOST http://127.0.0.1:10002/devstoreaccount1/sampleTable?$format=application%2Fjson%3Bodata%3Dminimalmetadata HTTP/1.1\r\nHost: 127.0.0.1\r\nx-ms-version: 2020-12-06\r\nDataServiceVersion: 3.0\r\nPrefer: return-no-content\r\nAccept: application/json;odata=minimalmetadata\r\nContent-Type: application/json;odata=nometadata\r\n\r\n{\"PartitionKey\":\"samePartition\",\"RowKey\":\"sameRowKey\"}\r\n--changeset_6ec27c11-728f-4b70-b763-a8cbbf761fe6\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nPOST http://127.0.0.1:10002/devstoreaccount1/sampleTable?$format=application%2Fjson%3Bodata%3Dminimalmetadata HTTP/1.1\r\nHost: 127.0.0.1\r\nx-ms-version: 2020-12-06\r\nDataServiceVersion: 3.0\r\nPrefer: return-no-content\r\nAccept: application/json;odata=minimalmetadata\r\nContent-Type: application/json;odata=nometadata\r\n\r\n{\"PartitionKey\":\"samePartition\",\"RowKey\":\"sameRowKey\"}\r\n--changeset_6ec27c11-728f-4b70-b763-a8cbbf761fe6--\r\n\r\n--batch_03995ca5-001f-440d-82f8-11b40121dd5e--\r\n"
2022-11-16T15:13:52.692Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 debug: TableHandler:batch() Raw response string is "--batchresponse_03995ca5-001f-440d-82f8-11b40121dd5e\r\nContent-Type: multipart/mixed; boundary=changesetresponse_6ec27c11-728f-4b70-b763-a8cbbf761fe6\r\n\r\n--changesetresponse_6ec27c11-728f-4b70-b763-a8cbbf761fe6\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nHTTP/1.1 409 Conflict\r\nContent-ID: 2\r\nDataServiceVersion: 3.0;\r\nContent-Type: application/json;odata=minimalmetadata;charset=utf-8\r\n\r\n{\"odata.error\":{\"code\":\"EntityAlreadyExists\",\"message\":{\"lang\":\"en-US\",\"value\":\"1:The specified entity already exists.\\nRequestId:b9a8bad9-e3cc-40b3-91d5-de5602d32871\\nTime:2022-11-16T15:13:52.690Z\"}}}\r\n--changesetresponse_6ec27c11-728f-4b70-b763-a8cbbf761fe6--\r\n--batchresponse_03995ca5-001f-440d-82f8-11b40121dd5e--\r\n"
2022-11-16T15:13:52.692Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 verbose: SerializerMiddleware: Start serializing...
2022-11-16T15:13:52.692Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 info: Serializer: Start returning stream body.
2022-11-16T15:13:52.695Z b9a8bad9-e3cc-40b3-91d5-de5602d32871 info: EndMiddleware: End response. TotalTimeInMS=14 StatusCode=202 StatusMessage=Accepted Headers={"server":"Azurite-Table/3.20.1","content-type":"multipart/mixed; boundary=batchresponse_03995ca5-001f-440d-82f8-11b40121dd5e","x-ms-request-id":"b9a8bad9-e3cc-40b3-91d5-de5602d32871","x-ms-version":"2021-10-04","date":"Wed, 16 Nov 2022 15:13:52 GMT"}
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by adamblok** [comment]
I've the same problem.

**Comment by grzewal** [comment]
I can confirm that it works the exact same way for me.

**Comment by jacekmackiewicz** [comment]
Same problem

**Comment by edwin-huber** [comment]
Thanks for raising this.
Once the current Table PR is done, we shall get to this.
