### ISSUE TITLE
Async delete_blobs method raises an exception when using Azurite

### ISSUE THREAD

**Issue by wallflower762** [Azure/Azurite#1756]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used? 
3.20.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Installed using VS Code extension

### What's the Node.js version? 
NA

### What problem was encountered?
Calling `await delete_blobs(*blobs)` results in an exception. This only seems to occur against Azurite, using this method against a standard storage account seems to work as expected. Using the singular `await delete_blob(blob)` works as expected against Azurite.

### Steps to reproduce the issue?
```
import asyncio
from azure.storage.blob.aio import ContainerClient
from typing import List

CONN_STR = "DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=https://127.0.0.1:10001/devstoreaccount1;TableEndpoint=https://127.0.0.1:10002/devstoreaccount1;"


async def main():
    client = ContainerClient.from_connection_string(CONN_STR, "test-container")
    blob_path = "test_name"
    blob_path_2 = "test_name2"
    await upload_schedule_blob(client, blob_path, {"key": "value"})
    await upload_schedule_blob(client, blob_path_2, {"key": "value"})
    print("Blob uploaded.")
    await delete_blobs(client, [blob_path, blob_path_2])
    print("Blob deleted")


async def delete_blobs(client, blob_list: List[str]):
    # Max deletes per request=256
    await client.delete_blobs(*blob_list)


async def upload_schedule_blob(
    client: ContainerClient,
    path: str,
    metadata: dict = {},
) -> None:

    await client.upload_blob(path, "".encode(), metadata=metadata)


if __name__ == "__main__":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    asyncio.run(main())
```

**Stack Trace**
```
Exception has occurred: PartialBatchErrorException       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
There is a partial failure in the batch operation.
ErrorCode:None
Content: --
Content-Type: application/http

HTTP/1.1 400 One of the request inputs is not valid.
x-ms-error-code: InvalidInput
x-ms-request-id: f3c21471-569e-4afa-961a-2312bbe4ebbf
content-type: application/xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>InvalidInput</Code>
  <Message>One of the request inputs is not valid.
RequestId:f3c21471-569e-4afa-961a-2312bbe4ebbf
Time:2022-11-17T05:28:01.429Z</Message>
</Error>
----
  File "C:\_DEV\prototyping\Lib\site-packages\azure\storage\blob\_shared\base_client_async.py", line 167, in _batch_send
    process_storage_error(error)
  File "<string>", line 1, in <module>
  File "C:\_DEV\prototyping\Lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 181, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "C:\_DEV\prototyping\Lib\site-packages\azure\storage\blob\_shared\base_client_async.py", line 167, in _batch_send
    process_storage_error(error)
  File "C:\_DEV\prototyping\Lib\site-packages\azure\storage\blob\aio\_container_client_async.py", line 1110, in delete_blobs
    return await self._batch_send(*reqs, **options)
  File "C:\_DEV\prototyping\Lib\site-packages\azure\core\tracing\decorator_async.py", line 79, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "C:\_DEV\prototyping\azurite_delete_blobs_bug.py", line 22, in delete_blobs
    await client.delete_blobs(*blob_list)
  File "C:\_DEV\prototyping\azurite_delete_blobs_bug.py", line 16, in main
    await delete_blobs(client, [blob_path])
  File "C:\Users\JMONKHOUSE\AppData\Local\Programs\Python\Python38\Lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\JMONKHOUSE\AppData\Local\Programs\Python\Python38\Lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\_DEV\prototyping\azurite_delete_blobs_bug.py", line 77, in <module>
    asyncio.run(main())
  File "C:\Users\JMONKHOUSE\AppData\Local\Programs\Python\Python38\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\JMONKHOUSE\AppData\Local\Programs\Python\Python38\Lib\runpy.py", line 194, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
```

### Have you found a mitigation/solution?
Looping over the singular blob delete method works, but requires patching my code while testing which is not ideal.

**Comment by blueww** [comment]
@wallflower762 
Would you please share the debug log of Azurite?
We need it to do further investigation.

**Comment by wallflower762** [comment]
I am not certain how to get the debug logs for the VS Code extension, but I enabled the debug channel in VS Code and these are the 2 outputs windows:
![image](https://user-images.githubusercontent.com/81551380/202956923-488e32f5-a284-46d8-bb0d-86279e2d3eda.png)
![image](https://user-images.githubusercontent.com/81551380/202957026-dd803046-a69b-4043-aec6-e94a1b1af8f2.png)
It doesn't show anything very interesting, just the PUT of the testing object. Please let me know if you need me to locate other debug logs (and how).

**Comment by blueww** [comment]
@wallflower762 
You can enable debug log for Azurite VC extension like following picture, and restart Azurite:
![image](https://user-images.githubusercontent.com/6926193/202958322-17f871f1-e85c-4966-bf7d-3fd51b647e9a.png)

Or you can just install Azurite with npm, and then start Azurite with command line like, and share the debug log file :
`azurite --location c:\azurite --debug c:\azurite\debug.log`

**Comment by wallflower762** [comment]
Ok, the screenshots posted earlier were with the debug setting enabled in VS Code.

**Comment by blueww** [comment]
@wallflower762 
It looks too less log in the "Azurite Blob Debug" output.
We will need at least the debug log for the orignal error InvalidInput(400). 

If you still can't get enough debug log in "Azurite Blob Debug" output (even by restart VS code), would you like try to install Azurite with npm, and run Azurite with above command line?

**Comment by blueww** [comment]
@wallflower762 

I will close this issue as not hear from you for a long time.
Feel free to contact us again if need any further assistance on Azurite.

**Comment by RobertMatlag** [comment]
@blueww I've got the same issue as  was discribed above by @wallflower762. Azurite returning an error when calling `delete_blobs()` except I do not use async here.

 I've got azurite 3.22.0 from docker hub

I attached file with debug logs.
[debug.log](https://github.com/Azure/Azurite/files/10784579/debug.log)

As a workaround I do the same think as @wallflower762 and patch it globally
```
    def delete_azure_blobs(self, *blobs, **kwargs):
        for blob in blobs:
            with suppress(ResourceNotFoundError):
                self.delete_blob(blob)

    @patch(
        "azure.storage.blob._container_client.ContainerClient.delete_blobs",
        side_effect=delete_azure_blobs,
        autospec=True,
    )
    def run_tests(self, test_labels, mock, **kwargs):
         return super().run_tests(test_labels, **kwargs)
```

I used the script below to check it. With Azurite I've got an error (full stack trace below) `azure.storage.blob._shared.response_handlers.PartialBatchErrorException: There is a partial failure in the batch operation.`
but when I pass connection string to my storage account everything works fine.
```
from azure.core.exceptions import ResourceExistsError

from azure.storage.blob import BlobServiceClient

blob_service_client = BlobServiceClient.from_connection_string((
    "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;"
    "AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/"
    "K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
))

container_client = blob_service_client.get_container_client("container")

try:
    container_client.create_container()
except ResourceExistsError:
    pass

blob_list = [b.name for b in list(container_client.list_blobs())]
# empty list
print(blob_list)

upload_data = b"Hello World"
for index in range(10):
    container_client.upload_blob(name=f"my_blob{index}", data=upload_data, overwrite=True)

# uploaded blobs
blob_list = [b.name for b in list(container_client.list_blobs())]
print(blob_list)

container_client.delete_blobs(*blob_list)

# empty again
blob_list = [b.name for b in list(container_client.list_blobs())]
print(blob_list)

```

Stack trace 
```
Traceback (most recent call last):
  File "/home/myLocalPath/.config/JetBrains/PyCharm2022.3/scratches/azurite.py", line 30, in <module>
    container_client.delete_blobs(*blob_list)
  File "/home/myLocalPath/.virtualenvs/py310/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/myLocalPath/.virtualenvs/py310/lib/python3.10/site-packages/azure/storage/blob/_container_client.py", line 1360, in delete_blobs
    return self._batch_send(*reqs, **options)
  File "/home/myLocalPath/.virtualenvs/py310/lib/python3.10/site-packages/azure/storage/blob/_shared/base_client.py", line 319, in _batch_send
    process_storage_error(error)
  File "/home/myLocalPath/.virtualenvs/py310/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 181, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "/home/myLocalPath/.virtualenvs/py310/lib/python3.10/site-packages/azure/storage/blob/_shared/base_client.py", line 315, in _batch_send
    raise error
azure.storage.blob._shared.response_handlers.PartialBatchErrorException: There is a partial failure in the batch operation.
ErrorCode:None
Content: --batch_7240c4fb-b11c-11ed-ac16-d39098213827
Content-Type: application/http

HTTP/1.1 400 One of the request inputs is not valid.
x-ms-error-code: InvalidInput
x-ms-request-id: 89d6790c-18d2-4a2c-88b3-80c73e5614ab
content-type: application/xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>InvalidInput</Code>
  <Message>One of the request inputs is not valid.
RequestId:89d6790c-18d2-4a2c-88b3-80c73e5614ab
Time:2023-02-20T12:45:25.460Z</Message>
</Error>
--batch_7240c4fb-b11c-11ed-ac16-d39098213827--
```

Logs from azurite
```
Azurite Blob service is starting on 0.0.0.0:10000
Azurite Blob service successfully listens on http://0.0.0.0:10000
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "PUT /devstoreaccount1/container?restype=container HTTP/1.1" 201 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "GET /devstoreaccount1/container?restype=container&comp=list HTTP/1.1" 200 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "PUT /devstoreaccount1/container/my_blob0 HTTP/1.1" 201 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "PUT /devstoreaccount1/container/my_blob1 HTTP/1.1" 201 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "PUT /devstoreaccount1/container/my_blob2 HTTP/1.1" 201 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "PUT /devstoreaccount1/container/my_blob3 HTTP/1.1" 201 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "PUT /devstoreaccount1/container/my_blob4 HTTP/1.1" 201 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "PUT /devstoreaccount1/container/my_blob5 HTTP/1.1" 201 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "PUT /devstoreaccount1/container/my_blob6 HTTP/1.1" 201 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "PUT /devstoreaccount1/container/my_blob7 HTTP/1.1" 201 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "PUT /devstoreaccount1/container/my_blob8 HTTP/1.1" 201 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "PUT /devstoreaccount1/container/my_blob9 HTTP/1.1" 201 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "GET /devstoreaccount1/container?restype=container&comp=list HTTP/1.1" 200 -
172.17.0.1 - - [20/Feb/2023:12:45:25 +0000] "POST /devstoreaccount1/container?restype=container&comp=batch HTTP/1.1" 202 -
```

**Comment by blueww** [comment]
@EmmaZhu 

From the above debug log, I see the failed request operation is "Container_SubmitBatch". 
Would you please help to look why it fails?

@RobertM15 
Would you like to open a new issue to track this?
The before issue has not enough information to investigate, and the behavior is also a little different (yous failed in both sync and async, but the original issue only fails in async), so we can't make sure they are same issue.

**Comment by RobertM15** [comment]
https://github.com/Azure/Azurite/issues/1809
