### ISSUE TITLE
Azurite instance can no longer be communicated in docker after upgrading the SDK to .NET 7.0

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/Azurite#1790]
### Which service(blob, file, queue, table) does this issue concern?

All of them.

### Which version of the Azurite was used?

Assuming the recent version downloaded by the following docker command in `docker-compose.yml` file:

```
image: "mcr.microsoft.com/azure-storage/azurite:latest"
```

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub

### What's the Node.js version?
n/a

### What problem was encountered?

Our  dockerized dotnet-isolated http-triggered azure function app used to work properly when employing .NET 6.0. Upgrading the framework to .NET 7.0 causes exceptions to raise when accessing the storage and the app not to function properly.

### Steps to reproduce the issue?

The following snippet is from `docker-compose.yml` file:

```yml
  storageemulator:
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    container_name: storageemulator
    ports: 
      - 20000:10000
      - 20001:10001
      - 20002:10002
 ```
The function app's environment variable is per the following snippet which is consistent with the `storageemulator`'s definition above:

```
AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://storageemulator:10000/devstoreaccount1;QueueEndpoint=http://storageemulator:10001/devstoreaccount1;TableEndpoint=http://storageemulator:10002/devstoreaccount1;
```

Submitting any web requests to the function app produces error `500` after running the dockerized function app and no logs is generated to share. A couple of points to note:

- This issue is not happening when running the function app in VS 2022 or VS Code
- The functions require function key to access. Therefore the proper `host.json` has been in place in `azure-webjobs-secrets` blob container.
- The azurite's instance in docker can be accessed from outside by tools like Azure Storage Explorer.
- The http-triggered functions are indexed and mapped successfully except for a couple of signalR-triggered functions due to the exception below *(I commented them out but the error 500 still persists when submitting web requests)*:

> fail: Host.Startup[402]
> 2023-01-11 09:19:08       The 'OnDisconnected' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.OnDisconnected'. Microsoft.Azure.WebJobs.Extensions.SignalRService: SignalR trigger is disabled due to 'AzureWebJobsStorage' connection string is not set or invalid. Azure.RequestFailedException: The value for one of the HTTP headers is not in the correct format.
> 2023-01-11 09:19:08       RequestId:29d8d6db-fc85-4a37-a909-4cdb14b1a363
> 2023-01-11 09:19:08       Time:2023-01-11T14:19:07.950Z
> 2023-01-11 09:19:08       Status: 400 (The value for one of the HTTP headers is not in the correct format.)
> 2023-01-11 09:19:08       ErrorCode: InvalidHeaderValue
> 2023-01-11 09:19:08       
> 2023-01-11 09:19:08       Additional Information:
> 2023-01-11 09:19:08       HeaderName: x-ms-version
> 2023-01-11 09:19:08       HeaderValue: 2021-08-06
> 2023-01-11 09:19:08       
> 2023-01-11 09:19:08       Content:
> 2023-01-11 09:19:08       <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> 2023-01-11 09:19:08       <Error>
> 2023-01-11 09:19:08         <Code>InvalidHeaderValue</Code>
> 2023-01-11 09:19:08         <Message>The value for one of the HTTP headers is not in the correct format.
> 2023-01-11 09:19:08       RequestId:29d8d6db-fc85-4a37-a909-4cdb14b1a363
> 2023-01-11 09:19:08       Time:2023-01-11T14:19:07.950Z</Message>
> 2023-01-11 09:19:08         <HeaderName>x-ms-version</HeaderName>
> 2023-01-11 09:19:08         <HeaderValue>2021-08-06</HeaderValue>
> 2023-01-11 09:19:08       </Error>
> 2023-01-11 09:19:08       
> 2023-01-11 09:19:08       Headers:
> 2023-01-11 09:19:08       Server: Azurite-Blob/3.16.0
> 2023-01-11 09:19:08       x-ms-error-code: InvalidHeaderValue
> 2023-01-11 09:19:08       x-ms-request-id: 29d8d6db-fc85-4a37-a909-4cdb14b1a363
> 2023-01-11 09:19:08       Date: Wed, 11 Jan 2023 14:19:07 GMT
> 2023-01-11 09:19:08       Connection: keep-alive
> 2023-01-11 09:19:08       Keep-Alive: REDACTED
> 2023-01-11 09:19:08       Transfer-Encoding: chunked
> 2023-01-11 09:19:08       Content-Type: application/xml
> 2023-01-11 09:19:08       
> 2023-01-11 09:19:08          at Azure.Storage.Blobs.ContainerRestClient.Create(Nullable`1 timeout, IDictionary`2 metadata, Nullable`1 access, String defaultEncryptionScope, Nullable`1 preventEncryptionScopeOverride, CancellationToken cancellationToken)
> 2023-01-11 09:19:08          at Azure.Storage.Blobs.BlobContainerClient.CreateInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken, String operationName)
> 2023-01-11 09:19:08          at Azure.Storage.Blobs.BlobContainerClient.CreateIfNotExistsInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken)
> 2023-01-11 09:19:08          at Azure.Storage.Blobs.BlobContainerClient.CreateIfNotExists(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, CancellationToken cancellationToken)
> 2023-01-11 09:19:08          at Microsoft.Azure.WebJobs.Script.WebHost.BlobStorageSecretsRepository.CreateBlobContainerClient(String connection) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/BlobStorageSecretsRepository.cs:line 69
> 2023-01-11 09:19:08          at Microsoft.Azure.WebJobs.Script.WebHost.BlobStorageSecretsRepository.ReadAsync(ScriptSecretsType type, String functionName) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/BlobStorageSecretsRepository.cs:line 83
> 2023-01-11 09:19:08          at Microsoft.Azure.WebJobs.Script.WebHost.SecretManager.LoadSecretsAsync(ScriptSecretsType type, String keyScope) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/SecretManager.cs:line 388
> 2023-01-11 09:19:08          at Microsoft.Azure.WebJobs.Script.WebHost.SecretManager.LoadSecretsAsync[T](String keyScope) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/SecretManager.cs:line 381
> 2023-01-11 09:19:08          at Microsoft.Azure.WebJobs.Script.WebHost.SecretManager.GetHostSecretsAsync() in /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/SecretManager.cs:line 94
> 2023-01-11 09:19:08          at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptWebHookProvider.GetOrCreateExtensionKey(String extensionName) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebHooks/DefaultScriptWebHookProvider.cs:line 75
> 2023-01-11 09:19:08          at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptWebHookProvider.GetExtensionWebHookRoute(String extensionName) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebHooks/DefaultScriptWebHookProvider.cs:line 67
> 2023-01-11 09:19:08          at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptWebHookProvider.GetUrl(IExtensionConfigProvider extension) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebHooks/DefaultScriptWebHookProvider.cs:line 52
> 2023-01-11 09:19:08          at Microsoft.Azure.WebJobs.Host.Config.ExtensionConfigContext.GetWebhookHandler() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Config\ExtensionConfigContext.cs:line 55
> 2023-01-11 09:19:08          at Microsoft.Azure.WebJobs.Extensions.SignalRService.SignalRConfigProvider.Initialize(ExtensionConfigContext context).

### Have you found a mitigation/solution?
No, to make the application continue working, I had to create an azure storage account on Azure and initialize `AzureWebJobsStorage` environment variable with the azure-hosted storage account's connection string.

**Comment by blueww** [comment]
@Arash-Sabet

Thanks for raising this issue!

As "The azurite's instance in docker can be accessed from outside by tools like Azure Storage Explorer" and "This issue is not happening when running the function app in VS 2022 or VS Code", it looks this is a client issue instead of Azurite (server side) issue.
We are not Azure function app expects, so don't know what's the change when you upgrade SDK for .net 7.0, and might not be the best person to look at this. Would you please contact Azure function owner team to look at it?

Besides that, I see you have port map in docker-compose.yml as :
```
      - 20000:10000
      - 20001:10001
      - 20002:10002
```
So per my understanding, you should connect to Azurite in docker with port 20000/20001/20002, But in the connectionstring you  shared, I see you still use 10000 port "BlobEndpoint=http://storageemulator:10000". Could this be the reason you can't connect to Azurite?

**Comment by jochensiegler** [comment]
we had the same problem.
we solved it by setting the docker image to mcr.microsoft.com/azure-storage/azurite:3.21.0

**Comment by Arash-Sabet** [comment]
> @Arash-Sabet
> 
> Thanks for raising this issue!
> 
> Since "The azurite's instance in docker can be accessed from outside by tools like Azure Storage Explorer" and "This issue is not happening when running the function app in VS 2022 or VS Code", it looks this is a client issue instead of Azurite (server side) issue. We are not Azure function app expects, so don't know what's the client change will happen when you upgrade SDK for .net 7.0, and might not be the best person to look at this. Would you please contact Azure function owner team to look at it?
> 
> Besides that, I see you have port map in docker-compose.yml as :
> 
> ```
>       - 20000:10000
>       - 20001:10001
>       - 20002:10002
> ```
> 
> So per my understanding, you should connect to Azurite in docker with port 20000/20001/20002, But in the connectionstring you shared, I see you still use 10000 port "BlobEndpoint=http://storageemulator:10000". Could this be the reason you can't connect to Azurite? Besides that, why you use port 20000/20001/20002, instead of default 10000/10001/10002?

@blueww Thanks for your reply. 
The mapped ports of `20000`, `20001` and `20002` are for external connections. For e.g. Azure Storage Explorer communicates with the azurite instance inside the docker container over the mentioned port numbers of 20000/20001/20002. The function app inside the docker container has been accessing the azurite instance over port numbers of 10000/10001/10002.

The client app in this context is an azure function app in .NET 7.0 whose .NET 6.0 version of it has been working flawlessly. As I mentioned before, the .NET 7.0 function app communicates with an azure-hosted storage account and that's why I started using it instead of the azurite to get the application going. This translates to me that the latest version of azurite's image is the culprit, especially when I downgraded the image to version 3.21.0 per the suggestion made by @jochensiegler.

@blueww I would have this issue investigated to understand why the latest version of azurite exhibits this problem and release a fix for it as soon as possible.

**Comment by Arash-Sabet** [comment]
> we had the same problem. we solved it by setting the docker image to mcr.microsoft.com/azure-storage/azurite:3.21.0

Thanks for your suggestion @jochensiegler. It worked well.

**Comment by blueww** [comment]
@Arash-Sabet, @jochensiegler 

Thanks for the details!

As the latest Azurite release currently is 3.21.0, the latest / 3.21.0 image should point to same docker image on server.
And I have checked by download them, and the 2 images has same signature and size, so should be same image.
![image](https://user-images.githubusercontent.com/6926193/212231834-2e195df7-f398-431d-b90b-bf5a6083882b.png)

However, as I know, if you have download latest image before, it will be cached on local. Even we have updated the latest image on server, the local latest image will still be the old version. 
Not sure if your case is this case. If so, if you remove the cached latest image in local, and start Azurite with latest image again, the latest image on server will be downloaded.

**Comment by Arash-Sabet** [comment]
Thanks @blueww for clarifying the root cause. I removed the older image and had the docker-compose file download azurite identified with `latest` tag. The issue is now resolved. Appreciate your help.
