### ISSUE TITLE
Azure.Storage.Blobs BlobClient Exists does not throw Exception when Exists method fails

### ISSUE THREAD

**Issue by danieloh1** [Azure/Azurite#1794]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.19.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio 2022 Enterprise

### What's the Node.js version?
16.16.0

### What problem was encountered?
We are migrating to Azure.Storage.Blobs package and Azurite. We have a scenario where we are testing getting the blob client when blob does not exist. Since the blob does not exist, calling Exists() method for BlobClient should result in failure and the exception to get thrown. This exception is not getting thrown. 

### Steps to reproduce the issue?
Try to get blobclient when blob does not exist.
No exception is thrown.

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "D:\AzuriteLogs\debug2.log"
```
[debug2.log](https://github.com/Azure/Azurite/files/10470642/debug2.log)

I can see in the logs the error, but there is no exception getting thrown.
2023-01-20T21:46:57.141Z 67e89564-e1bf-4fe2-89d7-35a3e633c122 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2023-01-20T21:46:57.142Z 67e89564-e1bf-4fe2-89d7-35a3e633c122 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified blob does not exist.  ErrorHTTPStatusCode=404 ErrorHTTPStatusMessage=The specified blob does not exist. ErrorHTTPHeaders={"x-ms-error-code":"BlobNotFound","x-ms-request-id":"67e89564-e1bf-4fe2-89d7-35a3e633c122"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>BlobNotFound</Code>\n  <Message>The specified blob does not exist.\nRequestId:67e89564-e1bf-4fe2-89d7-35a3e633c122\nTime:2023-01-20T21:46:57.141Z</Message>\n</Error>" ErrorStack="StorageError: The specified blob does not exist.\n    at Function.getBlobNotFound (C:\\snapshot\\_azure_azurite\\dist\\src\\blob\\errors\\StorageErrorFactory.js:29:16)\n    at LokiBlobMetadataStore.getBlobProperties (C:\\snapshot\\_azure_azurite\\dist\\src\\blob\\persistence\\LokiBlobMetadataStore.js:805:49)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async BlobHandler.getProperties (C:\\snapshot\\_azure_azurite\\dist\\src\\blob\\handlers\\BlobHandler.js:80:21)"
2023-01-20T21:46:57.142Z 67e89564-e1bf-4fe2-89d7-35a3e633c122 error: ErrorMiddleware: Set HTTP code: 404
2023-01-20T21:46:57.142Z 67e89564-e1bf-4fe2-89d7-35a3e633c122 error: ErrorMiddleware: Set HTTP status message: The specified blob does not exist.
2023-01-20T21:46:57.142Z 67e89564-e1bf-4fe2-89d7-35a3e633c122 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=BlobNotFound
2023-01-20T21:46:57.142Z 67e89564-e1bf-4fe2-89d7-35a3e633c122 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=67e89564-e1bf-4fe2-89d7-35a3e633c122
2023-01-20T21:46:57.142Z 67e89564-e1bf-4fe2-89d7-35a3e633c122 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>BlobNotFound</Code>\n  <Message>The specified blob does not exist.\nRequestId:67e89564-e1bf-4fe2-89d7-35a3e633c122\nTime:2023-01-20T21:46:57.141Z</Message>\n</Error>"
2023-01-20T21:46:57.142Z 67e89564-e1bf-4fe2-89d7-35a3e633c122 info: EndMiddleware: End response. TotalTimeInMS=3 StatusCode=404 StatusMessage=The specified blob does not exist. Headers={"server":"Azurite-Blob/3.19.0","x-ms-error-code":"BlobNotFound","x-ms-request-id":"67e89564-e1bf-4fe2-89d7-35a3e633c122"}

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
@danieloh1 

The SDK API `BlobBaseClient.Exists()` return boolean value, see https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.exists?view=azure-dotnet#returns

When the blob not exist, it should return false instead of throw exception. (return true if exist)
This is by design of the SDK. 

From the debug log, you can also see Azurite returns 404 error code when the blob not exist.
The behavior is aligned with product Azure. 
So this is not an Azurite issue.

If you still have comments for Storage SDK behavior, or need assistance on Storage  SDK, please file issues on https://github.com/Azure/azure-sdk-for-net/issues

**Comment by blueww** [comment]
@danieloh1 

As I know, for `BlobBaseClient.Exists()`, if the request failed with 404, it will just return false (instead throw exception).
Not sure if you have tested this API on product Azure? Per my understanding it should behavior the same with Azurite. Feel free to let me know if you see any difference.
