### ISSUE TITLE
EACCES error on startup

### ISSUE THREAD

**Issue by craxal** [Azure/Azurite#18]
**Azurite Version:** 2.6.5
**OS Version:** Windows 10

I get a continuous stream of error outputs when running Azurite from a PowerShell prompt (see below). However, if I run PowerShell as administrator and allow Node.js through the firewall, everything appears to work normally.

Sounds like a potential security risk.

```
PS> azurite

 _______                   _
(_______)                 (_)  _
 _______ _____ _   _  ____ _ _| |_ _____
|  ___  (___  ) | | |/ ___) (_   _) ___ |
| |   | |/ __/| |_| | |   | | | |_| ____|
|_|   |_(_____)____/|_|   |_| \__)_____)

Azurite, Version 2.6.5
A lightweight server clone of Azure Storage

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:10002
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.listen (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\express\lib\application.js:618:24)
    at env.init.then.then (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\lib\AzuriteTable.js:52:35)
    at tryCatcher (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:638:18)
    at C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\nodeback.js:42:21
    at Timeout._onTimeout (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\lokijs\src\lokijs.js:2633:15)
    at ontimeout (timers.js:475:11)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:10001
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.listen (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\express\lib\application.js:618:24)
    at env.init.then (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\lib\AzuriteQueue.js:48:35)
    at tryCatcher (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\promise.js:638:18)
    at C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\bluebird\js\release\nodeback.js:42:21
    at xfs.stat (C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\cralvord\AppData\Roaming\npm\node_modules\azurite\node_modules\graceful-fs\polyfills.js:287:18
events.js:183
      throw er; // Unhandled 'error' event
      ^
...
```

I noticed that if I run PowerShell as administrator and allow Node.js through the firewall, everything appears to work normally.

**Comment by edwin-huber** [comment]
Hi Craig,

Have you performed any hardening or are you using any special security software?
It might just be your Windows Defender / Firewall settings.

We might need to use the sysinternals tools to check why the functions can’t just create a listener on the required ports without admin mode.
Are you familiar with it’s use?
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon 

Do you have problems with any other apps?

“Works for me” isn’t really helpful here, other than I have a standard windows 10 install on 2 different machines and always start from powershell / conemu without issues.

I assume that you are not trying to run the Azure Storage Emulator at the same time as Azurite.

**Comment by edwin-huber** [comment]
I also checked my local execution policy, mine is set to RemoteSigned.

**Comment by craxal** [comment]
No, I haven't done anything special with security settings or hardware. It's just a build of Windows 10. I've heard of Process Monitor before, but I've never used it. None of my other applications have had this problem before, including Node applications. No other emulators are running.

**Comment by craxal** [comment]
Ah ha, I just figured it out. My PowerShell had the `Bypass` execution policy. I just tried setting the execution policy to `RemoteSigned`. Now Azurite works as intended.

At the very least, I think it's worth adding a note to the documentation. PowerShell is now the default Windows command prompt, so informing users of the minimum execution policy Azurite needs to work properly would be beneficial.

**Comment by searus** [comment]
For me, the problem was something in my system already using that port.
I checked the source code and figured out a command for changing the port numbers when starting:
```
azurite -p 11000 -q 11001 -t 11002
```

**Comment by searus** [comment]
With hindsight, it is kind of obvious that I had the official emulator running which was using the ports.
What I was hoping I could do was use Azurite to simulate multiple local accounts to avoid clashing of container names across multiple projects.
Not sure if this is possible though...

**Comment by edwin-huber** [comment]
you can simulate multiple accounts, you just need to start Azurite with different local paths.
