### ISSUE TITLE
function app run with azurite failed

### ISSUE THREAD

**Issue by Bobilala** [Azure/Azurite#1808]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
not sure, use VS 2022 17.4.4 extension

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio Extension

### What problem was encountered?
Checked Azurite start successfully
![image](https://user-images.githubusercontent.com/109055542/219562069-8229fb19-f62c-436b-8463-ad62b1daf7af.png)

However, when run function app, blob service will refuse connection.
[2023-02-16T03:43:45.570Z] Found C:\Projects\SHSOC.CoreV2\Doe.SHSOC.Function.App\Doe.SHSOC.Function.App.csproj. Using for user secrets file configuration.
[2023-02-16T03:43:54.955Z] There was an error performing a read operation on the Blob Storage Secret Repository.
[2023-02-16T03:43:54.958Z] Azure.Storage.Blobs: Service request failed.
[2023-02-16T03:43:54.959Z] Status: 403 (Forbidden)
[2023-02-16T03:43:54.961Z]
[2023-02-16T03:43:54.962Z] Content:
[2023-02-16T03:43:54.963Z] 

local.setting.json as below
![image](https://user-images.githubusercontent.com/109055542/219562407-f4e2b0f2-bb7f-43f6-8f2d-42698755b366.png)

### Steps to reproduce the issue?

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
Use Azure Storage Account can fix issue, but I want to check how to run it locally

**Comment by blueww** [comment]
@Bobilala 
Would you please share the Azurite debug log for the request failed with 403?
We need the debug log to investigate the failure.

**Comment by Bobilala** [comment]
@blueww 
May I know how can I get Azurite debug log? I just downloaded Visual Studio log and Function Core tools log, not sure whether is what you need.

**Comment by blueww** [comment]
@Bobilala 

Debug log location can be specified by "--debug" or "-d" when start Azurite. 
In the screen shot you shared, you can find the debug log location:
![image](https://user-images.githubusercontent.com/6926193/219996646-748c440d-e08a-4e12-98fc-73f5968e91b7.png)

**Comment by Bobilala** [comment]
@blueww 
I tried running the Azure Function with Azurite again today.
I have attached the debug log from today but did not see any 403 error in the log.
2023-02-20T23:24:18.088Z 	 info: Azurite Blob service is starting on 127.0.0.1:10000
2023-02-20T23:24:18.089Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:24:18.089Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:24:18.125Z 	 info: BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2023-02-20T23:24:18.126Z 	 info: BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2023-02-20T23:24:18.126Z 	 info: BlobGCManager:markSweepLoop() Start next mark and sweep.
2023-02-20T23:24:18.126Z 	 info: BlobGCManager:markSweep() Get all extents.
2023-02-20T23:24:18.128Z 	 info: BlobGCManager:start() BlobGCManager successfully started.
2023-02-20T23:24:18.137Z 	 info: BlobGCManager:markSweep() Got 0 extents.
2023-02-20T23:24:18.137Z 	 info: BlobGCManager:markSweep() Get referred extents.
2023-02-20T23:24:18.138Z 	 info: BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-20T23:24:18.138Z 	 info: BlobGCManager:markSweepLoop() Mark and sweep finished, taken 12ms.
2023-02-20T23:24:18.138Z 	 info: BlobGCManager:markSweepLoop() Sleep for 600000ms.
2023-02-20T23:24:18.141Z 	 info: Azurite Blob service successfully listens on http://127.0.0.1:10000
2023-02-20T23:24:18.142Z 	 info: Azurite Queue service is starting on 127.0.0.1:10001
2023-02-20T23:24:18.142Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:24:18.142Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:24:18.173Z 	 info: QueueGCManager:start() Starting QueueGCManager, set status to Initializing
2023-02-20T23:24:18.173Z 	 info: QueueGCManager:start() Trigger mark and sweep loop, set status to Running.
2023-02-20T23:24:18.173Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-20T23:24:18.173Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-20T23:24:18.173Z 	 info: QueueGCManager:start() QueueGCManager successfully started.
2023-02-20T23:24:18.174Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-20T23:24:18.174Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-20T23:24:18.174Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-20T23:24:18.174Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2023-02-20T23:24:18.174Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-20T23:24:18.175Z 	 info: Azurite Queue service successfully listens on http://127.0.0.1:10001
2023-02-20T23:24:18.176Z 	 info: Azurite Table service is starting on 127.0.0.1:10002
2023-02-20T23:24:18.176Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:24:18.176Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:24:18.189Z 	 info: Azurite Table service successfully listens on http://127.0.0.1:10002
2023-02-20T23:25:18.098Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:25:18.099Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:25:18.146Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:25:18.146Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:25:18.177Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-20T23:25:18.178Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-20T23:25:18.178Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-20T23:25:18.178Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-20T23:25:18.178Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-20T23:25:18.178Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 0ms.
2023-02-20T23:25:18.178Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-20T23:25:18.178Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:25:18.178Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:26:18.106Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:26:18.107Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:26:18.154Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:26:18.154Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:26:18.186Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-20T23:26:18.186Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-20T23:26:18.187Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-20T23:26:18.187Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-20T23:26:18.187Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-20T23:26:18.187Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2023-02-20T23:26:18.187Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-20T23:26:18.187Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:26:18.187Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:27:18.110Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:27:18.111Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:27:18.157Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:27:18.158Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:27:18.211Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-20T23:27:18.211Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-20T23:27:18.212Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-20T23:27:18.212Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-20T23:27:18.212Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-20T23:27:18.212Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2023-02-20T23:27:18.212Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-20T23:27:18.212Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:27:18.212Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:28:18.115Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:28:18.116Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:28:18.159Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:28:18.159Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:28:18.222Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-20T23:28:18.222Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-20T23:28:18.222Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-20T23:28:18.222Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-20T23:28:18.222Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-20T23:28:18.222Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 0ms.
2023-02-20T23:28:18.222Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-20T23:28:18.222Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:28:18.222Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:29:18.115Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-20T23:29:18.116Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-20T23:29:18.162Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined

**Comment by blueww** [comment]
@Bobilala 

From the Azurite debug log, not request is received by Azurite.
We are not so familiar with function app. Please make sure you are really sending request to Azurite and get 403 error.

**Comment by Bobilala** [comment]
@blueww 
Hi I tried again to run function app in VS 2022 and I can see Azurite Blob service successfully listens on http://127.0.0.1:10000/, but I still failed with 403

the exception in code:
![image](https://user-images.githubusercontent.com/109055542/220530112-1c797520-6526-459c-a377-45710cd6671e.png)


the error message in console:

Azure.RequestFailedException
  HResult=0x80131500
  Message=Service request failed.
Status: 403 (Forbidden)

Content:
<!-- IE friendly error message walkround.        
     if error message from server is less than   
     512 bytes IE v5+ will use its own error     
     message instead of the one returned by      
     server.                                 --> 
                                                 
                                                 
                                                 
                                                 
                                                 
                                                 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=8; IE=EDGE">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
        <style type="text/css">
            body {
                height: 100%;
                font-family: Roboto, Helvetica, Arial, sans-serif;
                color: #6a6a6a;
                margin: 0;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            input[type=date], input[type=email], input[type=number], input[type=password], input[type=search], input[type=tel], input[type=text], input[type=time], input[type=url], select, textarea {
                color: #262626;
                vertical-align: baseline;
                margin: .2em;
                border-style: solid;
                border-width: 1px;
                border-color: #a9a9a9;
                background-color: #fff;
                box-sizing: border-box;
                padding: 2px .5em;
                appearance: none;
                border-radius: 0;
            }
            input:focus {
                border-color: #646464;
                box-shadow: 0 0 1px 0 #a2a2a2;
                outline: 0;
            }
            button {
                padding: .5em 1em;
                border: 1px solid;
                border-radius: 3px;
                min-width: 6em;
                font-weight: 400;
                font-size: .8em;
                cursor: pointer;
            }
            button.primary {
                color: #fff;
                background-color: rgb(47, 113, 178);
                border-color: rgb(34, 103, 173);
            }
            .message-container {
                height: 500px;
                width: 600px;
                padding: 0;
                margin: 10px;
            }
            .logo {
                background: url(https://globalurl.fortinet.net:8010/XX/YY/ZZ/CI/MGPGHGPGPFGHDDPFGGHGFHBGCHEGPFBGAHAH) no-repeat left center;
                height: 267px;
                object-fit: contain;
            }
            table {
                background-color: #fff;
                border-spacing: 0;
                margin: 1em;
            }
            table > tbody > tr > td:first-of-type:not([colspan]) {
                white-space: nowrap;
                color: rgba(0,0,0,.5);
            }
            table > tbody > tr > td:first-of-type {
                vertical-align: top;
            }
            table > tbody > tr > td {
                padding: .3em .3em;
            }
            .field {
                display: table-row;
            }
            .field > :first-child {
                display: table-cell;
                width: 20%;
            }
            .field.single > :first-child {
                display: inline;
            }
            .field > :not(:first-child) {
                width: auto;
                max-width: 100%;
                display: inline-flex;
                align-items: baseline;
                virtical-align: top;
                box-sizing: border-box;
                margin: .3em;
            }
            .field > :not(:first-child) > input {
                width: 230px;
            }
            .form-footer {
                display: inline-flex;
                justify-content: flex-start;
            }
            .form-footer > * {
                margin: 1em;
            }
            .text-scrollable {
                overflow: auto;
                height: 150px;
                border: 1px solid rgb(200, 200, 200);
                padding: 5px;
                font-size: 1em;
            }
            .text-centered {
                text-align: center;
            }
            .text-container {
                margin: 1em 1.5em;
            }
            .flex-container {
                display: flex;
            }
            .flex-container.column {
                flex-direction: column;
            }
        </style>
        <title>403 Forbidden: incorrect proxy service was requested</title>
    </head>
    <body><div class="message-container">
    <div class="logo"></div>
    <h1>403 Forbidden: incorrect proxy service was requested</h1>
    <p>The webserver reported that an error occurred while trying to access the website. Please return to the previous page.</p>
    <table><tbody>
        <tr>
            <td>URL</td>
            <td>http://127.0.0.1:10000/devstoreaccount1/azure-webjobs-hosts/locks/pvdsw1cwti0356-1154109527/Doe.SHSOC.Function.App.ScheduledJob.PerformScheduledJobs.ScheduleRun.Listener?comp=lease</td>
        </tr>
        <tr>
            <td>Username</td>
            <td></td>
        </tr>
        <tr>
            <td>Group Name</td>
            <td></td>
        </tr>
    </tbody></table>
</div></body>
</html>



Headers:
Connection: close
Cache-Control: no-cache
X-XSS-Protection: REDACTED
X-Content-Type-Options: REDACTED
Content-Type: text/html
Content-Length: 5574

  Source=Azure.Storage.Blobs
  StackTrace:
   at Azure.Storage.Blobs.BlobRestClient.<AcquireLeaseAsync>d__36.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobLeaseClient.<AcquireInternal>d__26.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobLeaseClient.<AcquireAsync>d__25.MoveNext()
   at Microsoft.Azure.WebJobs.Host.BlobLeaseDistributedLockManager.<TryAcquireLeaseAsync>d__15.MoveNext()
   at Microsoft.Azure.WebJobs.Host.BlobLeaseDistributedLockManager.<TryLockAsync>d__9.MoveNext()
   at Microsoft.Azure.WebJobs.Host.SingletonManager.<TryLockAsync>d__19.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Singleton\SingletonManager.cs:line 113

  This exception was originally thrown at this call stack:
    [External Code]
    Microsoft.Azure.WebJobs.Host.SingletonManager.TryLockAsync(string, string, Microsoft.Azure.WebJobs.SingletonAttribute, System.Threading.CancellationToken, bool) in SingletonManager.cs


the debug.log keep the same as yesterday, I didn't find any 403 in Azurite debug.log. Please help.

**Comment by Bobilala** [comment]
@blueww Paste today debug.log
2023-02-22T05:01:51.462Z 	 info: Azurite Blob service is starting on 127.0.0.1:10000
2023-02-22T05:01:51.464Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:01:51.464Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:01:51.508Z 	 info: BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2023-02-22T05:01:51.509Z 	 info: BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2023-02-22T05:01:51.509Z 	 info: BlobGCManager:markSweepLoop() Start next mark and sweep.
2023-02-22T05:01:51.510Z 	 info: BlobGCManager:markSweep() Get all extents.
2023-02-22T05:01:51.511Z 	 info: BlobGCManager:start() BlobGCManager successfully started.
2023-02-22T05:01:51.522Z 	 info: BlobGCManager:markSweep() Got 0 extents.
2023-02-22T05:01:51.523Z 	 info: BlobGCManager:markSweep() Get referred extents.
2023-02-22T05:01:51.524Z 	 info: BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-22T05:01:51.524Z 	 info: BlobGCManager:markSweepLoop() Mark and sweep finished, taken 15ms.
2023-02-22T05:01:51.525Z 	 info: BlobGCManager:markSweepLoop() Sleep for 600000ms.
2023-02-22T05:01:51.528Z 	 info: Azurite Blob service successfully listens on http://127.0.0.1:10000
2023-02-22T05:01:51.529Z 	 info: Azurite Queue service is starting on 127.0.0.1:10001
2023-02-22T05:01:51.529Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:01:51.529Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:01:51.551Z 	 info: QueueGCManager:start() Starting QueueGCManager, set status to Initializing
2023-02-22T05:01:51.551Z 	 info: QueueGCManager:start() Trigger mark and sweep loop, set status to Running.
2023-02-22T05:01:51.551Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-22T05:01:51.552Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-22T05:01:51.552Z 	 info: QueueGCManager:start() QueueGCManager successfully started.
2023-02-22T05:01:51.553Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-22T05:01:51.553Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-22T05:01:51.553Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-22T05:01:51.553Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 2ms.
2023-02-22T05:01:51.553Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-22T05:01:51.555Z 	 info: Azurite Queue service successfully listens on http://127.0.0.1:10001
2023-02-22T05:01:51.556Z 	 info: Azurite Table service is starting on 127.0.0.1:10002
2023-02-22T05:01:51.556Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:01:51.556Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:01:51.573Z 	 info: Azurite Table service successfully listens on http://127.0.0.1:10002
2023-02-22T05:02:51.492Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:02:51.492Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:02:51.554Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:02:51.554Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:02:51.554Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-22T05:02:51.554Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-22T05:02:51.555Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-22T05:02:51.555Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-22T05:02:51.555Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-22T05:02:51.555Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2023-02-22T05:02:51.555Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-22T05:02:51.586Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:02:51.586Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:03:51.508Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:03:51.509Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:03:51.556Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:03:51.557Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:03:51.557Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-22T05:03:51.557Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-22T05:03:51.558Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-22T05:03:51.558Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-22T05:03:51.558Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-22T05:03:51.558Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2023-02-22T05:03:51.558Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-22T05:03:51.588Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:03:51.589Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:04:51.516Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:04:51.516Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:04:51.564Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:04:51.564Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:04:51.565Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-22T05:04:51.565Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-22T05:04:51.565Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-22T05:04:51.565Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-22T05:04:51.565Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-22T05:04:51.565Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 0ms.
2023-02-22T05:04:51.565Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-22T05:04:51.596Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:04:51.596Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:05:51.517Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:05:51.517Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:05:51.579Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:05:51.579Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:05:51.580Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-22T05:05:51.580Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-22T05:05:51.580Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-22T05:05:51.580Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-22T05:05:51.581Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-22T05:05:51.581Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2023-02-22T05:05:51.581Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-22T05:05:51.610Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:05:51.611Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:06:51.519Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:06:51.519Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:06:51.582Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:06:51.582Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:06:51.582Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-22T05:06:51.582Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-22T05:06:51.583Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-22T05:06:51.584Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-22T05:06:51.584Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-22T05:06:51.584Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 2ms.
2023-02-22T05:06:51.584Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-22T05:06:51.629Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:06:51.629Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:07:51.535Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:07:51.535Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:07:51.582Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:07:51.583Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2023-02-22T05:07:51.598Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2023-02-22T05:07:51.599Z 	 info: QueueGCManger:markSweep() Get all extents.
2023-02-22T05:07:51.599Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2023-02-22T05:07:51.599Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2023-02-22T05:07:51.599Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2023-02-22T05:07:51.599Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 0ms.
2023-02-22T05:07:51.599Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2023-02-22T05:07:51.631Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2023-02-22T05:07:51.631Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.

**Comment by blueww** [comment]
@Bobilala 
Thanks for the update!

However, from the Azurite debug log, still not request is received.

And the 403 error is "403 Forbidden: incorrect proxy service was requested". 
This is not the error can be reported from Azurite or storage server. 

Have configure some proxy locally that make the request is actually not send to Azurite?

**Comment by blueww** [comment]
@Bobilala

I will close this issue as not hear from you for a long time, and it looks a client-side issue.
Feel free to contact us again if need any further assistance on Azurite.

**Comment by ElinaStam** [comment]
Hello, I've got the same issue recently with Azurite. When trying to start the **Azurite Blob** service it didn't succeeded and I've got the same error: 
	`info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined`
I was able to resolve my issue by simply deleting the whole Azurite folder under Temp: C:\Users\<User>\AppData\Local\Temp\Azurite.

**Comment by dkapadia-jb** [comment]
> Hello, I've got the same issue recently with Azurite. When trying to start the **Azurite Blob** service it didn't succeeded and I've got the same error: `info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined` I was able to resolve my issue by simply deleting the whole Azurite folder under Temp: C:\Users<User>\AppData\Local\Temp\Azurite.

Had this same issue with running Azure Function App with VS 2022 Version 17.9.3.
Deleted below folder and started working again
`C:\Users\deepesh.kapadia\AppData\Local\.vstools\azurite`
