### ISSUE TITLE
Azurite returns 400 when trying to access blob from non-existent account. It should be 404 probably?

### ISSUE THREAD

**Issue by sreekara123** [Azure/Azurite#1816]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
Whatever comes with VS2022 (not sure how to check). From response headers it looks like Azurite-Blob/3.20.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Command line from VS2022 download.

### What's the Node.js version?
N/A

### What problem was encountered?
Trying to write a UT where a blob and account does not exist. The expected status code so far, we worked with, in production and storage emulator is 404. But Azurite returns 400 with "Invalid storage account" message.

### Steps to reproduce the issue?
Call BlockBlobClient.GetPropertiesAsync using a non-existent account with Azure Blob SDK 12.8.3.

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```
2023-02-22T19:49:07.686Z 07c893a5-6286-4cf4-a537-eddff04c18ad info: BlobStorageContextMiddleware: RequestMethod=HEAD RequestURL=http://127.0.0.1/devstoreaccountfoo/{removed}/azuretestblob RequestHeaders:{"x-ms-version":"2020-04-08","x-ms-client-request-id":"8ca6876a-9766-4837-bfaa-7ea54a9cc835","x-ms-return-client-request-id":"true","user-agent":"XArchiveST","host":"127.0.0.1","x-ms-internal-archive-blob-etag":"InvalidETag","x-ms-internal-archive-blob-generation-id":"GenerationId","x-ms-internal-archive-request-id":"b8a88210-ea48-4f85-ac12-6dc818547152"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2023-02-22T19:49:07.686Z 07c893a5-6286-4cf4-a537-eddff04c18ad info: BlobStorageContextMiddleware: Account=devstoreaccountfoo Container=301725bf-f235-484a-8825-d577b50b3b23 Blob=azuretestblob
2023-02-22T19:49:07.686Z 07c893a5-6286-4cf4-a537-eddff04c18ad verbose: DispatchMiddleware: Dispatching request...
2023-02-22T19:49:07.687Z 07c893a5-6286-4cf4-a537-eddff04c18ad info: DispatchMiddleware: Operation=Blob_GetProperties
2023-02-22T19:49:07.687Z 07c893a5-6286-4cf4-a537-eddff04c18ad verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2023-02-22T19:49:07.687Z 07c893a5-6286-4cf4-a537-eddff04c18ad info: PublicAccessAuthenticator:validate() Start validation against public access.
2023-02-22T19:49:07.687Z 07c893a5-6286-4cf4-a537-eddff04c18ad debug: PublicAccessAuthenticator:validate() Getting account properties...
2023-02-22T19:49:07.687Z 07c893a5-6286-4cf4-a537-eddff04c18ad debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccountfoo, container: {removed} blob: azuretestblob
2023-02-22T19:49:07.688Z 07c893a5-6286-4cf4-a537-eddff04c18ad debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container {removed}
2023-02-22T19:49:07.688Z 07c893a5-6286-4cf4-a537-eddff04c18ad info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2023-02-22T19:49:07.688Z 07c893a5-6286-4cf4-a537-eddff04c18ad info: BlobSharedKeyAuthenticator:validate() Request doesn't include valid authentication header. Skip shared key authentication.
2023-02-22T19:49:07.688Z 07c893a5-6286-4cf4-a537-eddff04c18ad info: AccountSASAuthenticator:validate() Start validation against account Shared Access Signature pattern.
2023-02-22T19:49:07.688Z 07c893a5-6286-4cf4-a537-eddff04c18ad debug: AccountSASAuthenticator:validate() Getting account properties...
2023-02-22T19:49:07.688Z 07c893a5-6286-4cf4-a537-eddff04c18ad debug: AccountSASAuthenticator:validate() Retrieved account name from context: devstoreaccountfoo, container: {removed}, blob: azuretestblob
2023-02-22T19:49:07.688Z 07c893a5-6286-4cf4-a537-eddff04c18ad error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2023-02-22T19:49:07.689Z 07c893a5-6286-4cf4-a537-eddff04c18ad error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Invalid storage account.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=Invalid storage account. ErrorHTTPHeaders={"x-ms-error-code":"InvalidOperation","x-ms-request-id":"07c893a5-6286-4cf4-a537-eddff04c18ad"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:07c893a5-6286-4cf4-a537-eddff04c18ad\nTime:2023-02-22T19:49:07.688Z</Message>\n</Error>" ErrorStack="StorageError: Invalid storage account.\n    at Function.getInvalidOperation (C:\\snapshot\\_azure_azurite\\dist\\src\\blob\\errors\\StorageErrorFactory.js:58:16)\n    at AccountSASAuthenticator.validate (C:\\snapshot\\_azure_azurite\\dist\\src\\blob\\authentication\\AccountSASAuthenticator.js:30:49)\n    at AuthenticationMiddlewareFactory.authenticate (C:\\snapshot\\_azure_azurite\\dist\\src\\blob\\middlewares\\AuthenticationMiddlewareFactory.js:35:40)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
2023-02-22T19:49:07.689Z 07c893a5-6286-4cf4-a537-eddff04c18ad error: ErrorMiddleware: Set HTTP code: 400
2023-02-22T19:49:07.689Z 07c893a5-6286-4cf4-a537-eddff04c18ad error: ErrorMiddleware: Set HTTP status message: Invalid storage account.
2023-02-22T19:49:07.689Z 07c893a5-6286-4cf4-a537-eddff04c18ad error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidOperation
2023-02-22T19:49:07.689Z 07c893a5-6286-4cf4-a537-eddff04c18ad error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=07c893a5-6286-4cf4-a537-eddff04c18ad
2023-02-22T19:49:07.689Z 07c893a5-6286-4cf4-a537-eddff04c18ad error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>Invalid storage account.\nRequestId:07c893a5-6286-4cf4-a537-eddff04c18ad\nTime:2023-02-22T19:49:07.688Z</Message>\n</Error>"

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No. I want to know if this is a bug in Azurite?

**Comment by blueww** [comment]
@sreekara123 

Thanks for raising the issue!

In product Azure, normally customer will use a Uri with storage account name in hostname to access the blob (e.g. https://accountname.blob.core.windows.net/container/blob).  When the storage account not exist, the host name which include account name actually can't be resolved correctly by DNS, so the request can't be send to product Storage server and will get timeout error in send request. 

For 404, in access blob, normally you will get it when the container or blob not exist (but account exist).

In Azurite, since user normally will use hostname as "127.0.0.1", so in this case the request can always be sent to Azurite. This is an undefined behavior in product Azure, so this is taken as invalid scenario in Azurite. In this case, we return 400 which is bad request.

Feel free to let us know if you have any further questions/comments.

**Comment by sreekara123** [comment]
@blueww we are trying to test a scenario where the DNS exists, but the account does not.

In this case since we should be able to the route the request to Azure (since DNS exists), function like BlockBlobClient.GetBlobProperties should return 404 since blob does not exist.

I'm no expert in what should happen or shouldn't. But I'm just throwing something out to brainstorm. I don't want to change our existing tests until we are sure it's wrong or is not a valid scenario or cannot be fixed by Azurite even if a valid scenario.

**Comment by blueww** [comment]
@sreekara123 

For the scenario "the DNS exists, but the account does not", could you give more details why you would like to test this scenario? How can you meet this scenario with real Azure server? 
Per my understanding, the DNS should come from the storage account exist, so how you get "the DNS exists" with account does not exist.

**Comment by sreekara123** [comment]
Hey @blueww , sorry for the late response. I got sidetracked and had to discuss this with the team.

Storage account being deleted, and DNS being wiped out is not an atomic operation. So even if storage account is deleted, there will be some lag after which DNS is wiped out. This is the scenario we are trying to test. Can this be incorporated into Azurite?

**Comment by blueww** [comment]
@sreekara123 
Thanks for the update!
I will look into the code, and see if we can return 404 in this case, and update you later.

**Comment by blueww** [comment]
@sreekara123 

I have raised a PR to fix it: https://github.com/Azure/Azurite/pull/1825
