### ISSUE TITLE
Status returned in Exception has changed from before, when batch insert with large property size is done.

### ISSUE THREAD

**Issue by PrasantJillella** [Azure/Azurite#1832]
### Which service(blob, file, queue, table) does this issue concern?
Table
### Which version of the Azurite was used?
3.22.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
v18.14.2

### What problem was encountered?
We were have tests to check scenario for Insert operation in Azure Table Storage.
**Scenario is:** 
We want to insert a batch of rows which have a large property size. 

The behavior we expect is that, the Insert operation should fail with 
    Errorcode: PropertyValueTooLarge, and 
    Status: 413 (The request body is too large and exceeds the maximum permissible limit.)

But now when we migrated from Azure Table Storage to Azurite we are seeing the following exception details:
    Errorcode: PropertyValueTooLarge and 
    Status: 413 (Payload Too Large)

Our tests failed because there is a change in Status, Just wanted to ask why there is a change in status
and if actual Azure Table Storage gives this new status as well, If not then can this be reverted in Azurite as well so that it
resembles Azure Table Storage in this respect.

### Steps to reproduce the issue?
Created a sample table, then follow the below code to create records with large property size
and try inserting them into Azure Table storage. This will throw the exception with above mentioned details.

```
var partitionKey = "Some dummy Partition key";
var rows = new ITableRecord[50];
  for (var i = 0; i < rows.Length; i++)
  {
      rows[i] = azureTableReaderWriter.NewRecord(
          partitionKey,
          DataHelper.NewRowKey());

      // Add a property to exceed the allowed batch size
      // in a batch insert.
      rows[i].Properties.Add(
          "propertyname",
          new string('*', 1024 * 1024));
  }

await AzureTableStorage.BatchInsert(rows); 
// Sample function that inserts batch rows into azure table storage.

```

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

Message thrown by Azurite:
```
"The request   body is too large and exceeds the maximum permissible   limit.\nRequestId:771f8a73-901a-4ae4-8368-751f93f2df1a\nTime:2023-03-09T13:55:19.326Z\r\nStatus:   413 (Payload Too Large)\r\nErrorCode:   RequestBodyTooLarge\r\n\r\nContent:\r\n{\"odata.error\":{\"code\":\"RequestBodyTooLarge\",\"message\":{\"lang\":\"en-US\",\"value\":\"The   request body is too large and exceeds the maximum permissible   limit.\\nRequestId:771f8a73-901a-4ae4-8368-751f93f2df1a\\nTime:2023-03-09T13:55:19.326Z\"}}}\r\n\r\nHeaders:\r\nServer:   Azurite-Table/3.22.0\r\nx-ms-error-code: REDACTED\r\nx-ms-request-id:   771f8a73-901a-4ae4-8368-751f93f2df1a\r\nx-ms-version: REDACTED\r\nDate: Thu,   09 Mar 2023 13:55:19 GMT\r\nConnection: keep-alive\r\nKeep-Alive:   REDACTED\r\nTransfer-Encoding: chunked\r\nContent-Type: application/json;   odata=minimalmetadata; streaming=true; charset=utf-8\r\n"
```

Message thrown by Azure Storage Emulator:
```
"The request body is too large and exceeds the maximum permissible limit.\nRequestId:eee6a7e9-43df-4766-ad03-df3ca32ff512\nTime:2023-03-09T18:06:06.9707435Z\r\nStatus: 413 (The request body is too large and exceeds the maximum permissible limit.)\r\nErrorCode: RequestBodyTooLarge\r\n\r\nContent:\r\n{​\"odata.error\":{​\"code\":\"RequestBodyTooLarge\",\"message\":{​\"lang\":\"en-US\",\"value\":\"The request body is too large and exceeds the maximum permissible limit.\\nRequestId:eee6a7e9-43df-4766-ad03-df3ca32ff512\\nTime:2023-03-09T18:06:06.9707435Z\"}​}​}​\r\n\r\nHeaders:\r\nServer: Windows-Azure-Table/1.0,Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: eee6a7e9-43df-4766-ad03-df3ca32ff512\r\nx-ms-version: REDACTED\r\nx-ms-error-code: REDACTED\r\nDate: Thu, 09 Mar 2023 18:06:06 GMT\r\nContent-Length: 239\r\nContent-Type: application/json\r\n"
```

### Have you found a mitigation/solution?
No.

**Comment by blueww** [comment]
@PrasantJillella 

As I see from your comments, it looks the error from Azurite and your expectation has same status code (413) and ErrorCode, only different on error message. (Please correct me if not)
If so, your code should not based on the error message, since this is not stable and might change.

Besides that, would you please share the debug log (hide credentail) for the failed batch request if need further investigation from us?

> The behavior we expect is that, the Insert operation should fail with
> Errorcode: PropertyValueTooLarge, and
> Status: 413 (The request body is too large and exceeds the maximum permissible limit.)
> 
> But now when we migrated from Azure Table Storage to Azurite we are seeing the following exception details:
> Errorcode: PropertyValueTooLarge and
> Status: 413 (Payload Too Large)

**Comment by edwin-huber** [comment]
We have changed the status codes, and they might change again, depending on how the service behaves, we try to stay in parity with the service.

**Comment by PrasantJillella** [comment]
> @PrasantJillella
> 
> As I see from your comments, it looks the error from Azurite and your expectation has same status code (413) and ErrorCode, only different on error message. (Please correct me if not) If so, your code should not based on the error message, since this is not stable and might change.
> 
> Besides that, would you please share the debug log (hide credentail) for the failed batch request if need further investigation from us?

Hi 
Yes the concern was regarding the changed message in the status field. We already have raised a changed to use ErrorCode but it would really be appreciated if the 'Message' field reflects the same value as before since that is still used in Azure Table Storage.

Added logs for reference:

Loga emitted by Azurite 
```
ure 1 matched.
2023-03-15T09:57:15.076Z 8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd verbose: DeserializerMiddleware: Start deserializing...
2023-03-15T09:57:15.076Z 8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd info: HandlerMiddleware: DeserializedParameters={"version":"2020-12-06","options":{"requestId":"15d67b70-4226-4f73-8bd9-d9472dac63af","dataServiceVersion":"3.0"},"multipartContentType":"multipart/mixed; boundary=batch_fc214776-3003-49d0-9928-a56f0cb7ccd1","contentLength":52457238,"body":"ReadableStream"}
2023-03-15T09:57:15.079Z 8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2023-03-15T09:57:15.080Z 8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd error: ErrorMiddleware: ErrorName=StorageError ErrorMessage="The request body is too large and exceeds the maximum permissible limit."  ErrorHTTPStatusCode=413 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"RequestBodyTooLarge","x-ms-request-id":"8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd","x-ms-version":"2021-12-02"} ErrorHTTPBody="{\"odata.error\":{\"code\":\"RequestBodyTooLarge\",\"message\":{\"lang\":\"en-US\",\"value\":\"The request body is too large and exceeds the maximum permissible limit.\\nRequestId:8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd\\nTime:2023-03-15T09:57:15.077Z\"}}}" ErrorStack="\"StorageError: The request body is too large and exceeds the maximum permissible limit.\\n    at StorageErrorFactory.getRequestBodyTooLarge (C:\\\\Users\\\\sjillella\\\\source\\\\Azurite\\\\dist\\\\src\\\\table\\\\errors\\\\StorageErrorFactory.js:117:16)\\n    at TableHandler.batch (C:\\\\Users\\\\sjillella\\\\source\\\\Azurite\\\\dist\\\\src\\\\table\\\\handlers\\\\TableHandler.js:489:49)\\n    at C:\\\\Users\\\\sjillella\\\\source\\\\Azurite\\\\dist\\\\src\\\\table\\\\generated\\\\middleware\\\\HandlerMiddlewareFactory.js:58:18\\n    at C:\\\\Users\\\\sjillella\\\\source\\\\Azurite\\\\dist\\\\src\\\\table\\\\generated\\\\ExpressMiddlewareFactory.js:77:63\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\sjillella\\\\source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at trim_prefix (C:\\\\Users\\\\sjillella\\\\source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:328:13)\\n    at C:\\\\Users\\\\sjillella\\\\source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:286:9\\n    at Function.process_params (C:\\\\Users\\\\sjillella\\\\source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:346:12)\\n    at next (C:\\\\Users\\\\sjillella\\\\source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:280:10)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\""
2023-03-15T09:57:15.080Z 8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd error: ErrorMiddleware: Set HTTP code: 413
2023-03-15T09:57:15.080Z 8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=RequestBodyTooLarge
2023-03-15T09:57:15.080Z 8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd
2023-03-15T09:57:15.080Z 8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd error: ErrorMiddleware: Set HTTP Header: x-ms-version=2021-12-02
2023-03-15T09:57:15.080Z 8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd error: ErrorMiddleware: Set content type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
2023-03-15T09:57:15.080Z 8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd error: ErrorMiddleware: Set HTTP body: "{\"odata.error\":{\"code\":\"RequestBodyTooLarge\",\"message\":{\"lang\":\"en-US\",\"value\":\"The request body is too large and exceeds the maximum permissible limit.\\nRequestId:8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd\\nTime:2023-03-15T09:57:15.077Z\"}}}"
2023-03-15T09:57:15.081Z 8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd info: EndMiddleware: End response. TotalTimeInMS=8 StatusCode=413 StatusMessage=Payload Too Large Headers={"server":"Azurite-Table/3.22.0","x-ms-error-code":"RequestBodyTooLarge","x-ms-request-id":"8011b3a2-1198-4dd3-9bea-aa82b7dd8fcd","x-ms-version":"2021-12-02","content-type":"application/json;odata=minimalmetadata;streaming=true;charset=utf-8"}

```

**Comment by PrasantJillella** [comment]
Hi 

Checking back to see if the plan was to update the StatusMessage to reflect what is present in Prod Azure Table Storage.

Thank you.

**Comment by blueww** [comment]
@PrasantJillella 

I am a little confused. 

From the debug log, I see the error from Azurite is:

- StatusCode: 413
- ErrorCode: RequestBodyTooLarge
- Message: "The request body is too large and exceeds the maximum permissible limit"

However, from your original issue, the Azurite returned error is: 

- Errorcode: PropertyValueTooLarge and
- Status: 413 (Payload Too Large)

They are not aligned. So would you please confirm what's the error you see returned from Azurite, and what's the expected error?

Besides that, from the debug log, it looks the error might be reported on this code: https://github.com/Azure/Azurite/blob/38764d524132a7de6177e62806c772598c949517/src/table/handlers/TableHandler.ts#L898

Azurite welcome contribution!
It would be great if you could raise a PR to fix it!
(The fix might include define a new Error type with the required error code/message in [this file](https://github.com/Azure/Azurite/blob/main/src/table/errors/StorageErrorFactory.ts), then throw the error in the above code location. Please also include test case and change log.)

**Comment by blueww** [comment]
@PrasantJillella 
For "change this StatusMessage back ", do you mean the status message for the 413 error is different in the before Azurite version? If so, please share the before Azurite version, and we can see what's the change.

For "Payload Too Large", it looks not from Azurite code, but it's just status message of 413, see https://developer.mozilla.org/es/docs/Web/HTTP/Status/413.

Your code might should not based on the status message, but should based on the status code.

**Comment by PrasantJillella** [comment]
Hi 

Sorry for the confusion, the previous status that I noticed was from "Azure Storage Emulator" and the new statusMessage "Payload Too Large" that I noticed was when we start to use Azurite.

I also didn't notice this type of status message ("Payload Too Large") in our production code which interacts with actual Azure Table Storage.

So that was the reason why I wanted to check if there was any change made in Azurite that caused the StatusMessage to change from "The request body is too large and exceeds the maximum permissible limit." to "Payload Too Large"

**Comment by blueww** [comment]
@PrasantJillella 
Thanks for the detail!
Then would you please make you code check based on status code, but not on status message?

**Comment by PrasantJillella** [comment]
Done thank you.
