### ISSUE TITLE
filter condition with string.Empty fails to getRows from table

### ISSUE THREAD

**Issue by PrasantJillella** [Azure/Azurite#1880]
### Which service(blob, file, queue, table) does this issue concern?
Table
### Which version of the Azurite was used?
3.22.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
v18.14.2
### What problem was encountered?

Noticed a functionality change when calling TableStorage to fetch all rows in it.
When we try calling the Get table client following parameters:
Filter: string.Empty
ContinuationToken: null
maxPerPage: 20

This operation succeeds in our production code against Azure Storage and even succeeds against
Azure Storage Emulator.
However this fails against Azurite.

### Steps to reproduce the issue?
Please use the following code snippet as reference:

`
tableClient = CreateGetTableClient();

tableClient.QueryAsync<TableEntity>(
    filter: string.Empty,
    maxPerPage: 20,
    select: null,
    cancellationToken);
`

**_QueryAsync**()_  is part of _**TableClient**_ class under namespace "_**Azure.Data.Tables;**_"

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

`   
 2023-03-29T13:05:49.662Z 20f76b43-8584-434d-88cb-993bf20324f7 info: TableStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/ArchiveStreamsTable()?$format=application%2Fjson%3Bodata%3Dminimalmetadata&$top=20&$filter=​​​​​​​ RequestHeaders:{​"host":"127.0.0.1:10002","x-ms-version":"2020-12-06","dataserviceversion":"3.0","accept":"application/json;odata=minimalmetadata","x-ms-client-request-id":"3df45738-de61-4b0c-8faa-062a52738c79","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Data.Tables/12.7.1 (.NET 6.0.15; Microsoft Windows 10.0.19045)","x-ms-date":"Wed, 29 Mar 2023 13:05:49 GMT","authorization":"SharedKeyLite devstoreaccount1:qfkZCLgrpopRpOwmPHNKfkG5lacg9vMF4/cxkUj2TU8="}​ ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
    2023-03-29T13:05:49.662Z 20f76b43-8584-434d-88cb-993bf20324f7 debug: tableStorageContextMiddleware: Dispatch pattern string: /ArchiveStreamsTable()
    2023-03-29T13:05:49.662Z 20f76b43-8584-434d-88cb-993bf20324f7 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=ArchiveStreamsTable
    2023-03-29T13:05:49.662Z 20f76b43-8584-434d-88cb-993bf20324f7 verbose: DispatchMiddleware: Dispatching request...
    2023-03-29T13:05:49.662Z 20f76b43-8584-434d-88cb-993bf20324f7 info: DispatchMiddleware: Operation=Table_QueryEntities
    2023-03-29T13:05:49.662Z 20f76b43-8584-434d-88cb-993bf20324f7 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
    2023-03-29T13:05:49.663Z 20f76b43-8584-434d-88cb-993bf20324f7 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
    2023-03-29T13:05:49.663Z 20f76b43-8584-434d-88cb-993bf20324f7 info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Wed, 29 Mar 2023 13:05:49 GMT\n/devstoreaccount1/devstoreaccount1/ArchiveStreamsTable()"
    2023-03-29T13:05:49.663Z 20f76b43-8584-434d-88cb-993bf20324f7 info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:qfkZCLgrpopRpOwmPHNKfkG5lacg9vMF4/cxkUj2TU8=
    2023-03-29T13:05:49.663Z 20f76b43-8584-434d-88cb-993bf20324f7 info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
    **2023-03-29T13:05:49.663Z 20f76b43-8584-434d-88cb-993bf20324f7 verbose: DeserializerMiddleware: Start deserializing...
    2023-03-29T13:05:49.663Z 20f76b43-8584-434d-88cb-993bf20324f7 info: HandlerMiddleware: DeserializedParameters={​"options":{​"queryOptions":{​"format":"application/json;odata=minimalmetadata","top":20,"filter":""}​,"requestId":"3df45738-de61-4b0c-8faa-062a52738c79","dataServiceVersion":"3.0"}​,"version":"2020-12-06"}​
    2023-03-29T13:05:49.665Z 20f76b43-8584-434d-88cb-993bf20324f7 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
    2023-03-29T13:05:49.665Z 20f76b43-8584-434d-88cb-993bf20324f7 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage="The query condition specified in the request is invalid."  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={​"x-ms-error-code":"InvalidInput","x-ms-request-id":"20f76b43-8584-434d-88cb-993bf20324f7","x-ms-version":"2021-12-02"}​ ErrorHTTPBody="{​\"odata.error\":{​\"code\":\"InvalidInput\",\"message\":{​\"lang\":\"en-US\",\"value\":\"The query condition specified in the request is invalid.\\nRequestId:20f76b43-8584-434d-88cb-993bf20324f7\\nTime:2023-03-29T13:05:49.664Z\"}​}​}​" ErrorStack="\"StorageError: The query condition specified in the request is invalid.\\n    at StorageErrorFactory.getQueryConditionInvalid (***\\\\source\\\\Azurite\\\\dist\\\\src\\\\table\\\\errors\\\\StorageErrorFactory.js:79:16)\\n    at LokiTableStoreQueryGenerator.generateQueryForPersistenceLayer** (***\\\\source\\\\Azurite\\\\dist\\\\src\\\\table\\\\persistence\\\\LokiTableStoreQueryGenerator.js:27:49)\\n    at LokiTableMetadataStore.queryTableEntities (***\\\\source\\\\Azurite\\\\dist\\\\src\\\\table\\\\persistence\\\\LokiTableMetadataStore.js:252:67)\\n    at TableHandler.queryEntities (***\\\\source\\\\Azurite\\\\dist\\\\src\\\\table\\\\handlers\\\\TableHandler.js:316:81)\\n    at ***\\\\source\\\\Azurite\\\\dist\\\\src\\\\table\\\\generated\\\\middleware\\\\HandlerMiddlewareFactory.js:58:18\\n    at ***\\\\source\\\\Azurite\\\\dist\\\\src\\\\table\\\\generated\\\\ExpressMiddlewareFactory.js:77:63\\n    at Layer.handle [as handle_request] (***\\\\source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at trim_prefix (***\\\\source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:328:13)\\n    at ***\\\\source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:286:9\\n    at Function.process_params (***\\\\source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:346:12)\""
    2023-03-29T13:05:49.665Z 20f76b43-8584-434d-88cb-993bf20324f7 error: ErrorMiddleware: Set HTTP code: 400
    2023-03-29T13:05:49.665Z 20f76b43-8584-434d-88cb-993bf20324f7 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidInput
    2023-03-29T13:05:49.665Z 20f76b43-8584-434d-88cb-993bf20324f7 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=20f76b43-8584-434d-88cb-993bf20324f7
    2023-03-29T13:05:49.665Z 20f76b43-8584-434d-88cb-993bf20324f7 error: ErrorMiddleware: Set HTTP Header: x-ms-version=2021-12-02
    2023-03-29T13:05:49.665Z 20f76b43-8584-434d-88cb-993bf20324f7 error: ErrorMiddleware: Set content type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
    2023-03-29T13:05:49.665Z 20f76b43-8584-434d-88cb-993bf20324f7 error: ErrorMiddleware: Set HTTP body: "{​\"odata.error\":{​\"code\":\"InvalidInput\",\"message\":{​\"lang\":\"en-US\",\"value\":\"The query condition specified in the request is invalid.\\nRequestId:20f76b43-8584-434d-88cb-993bf20324f7\\nTime:2023-03-29T13:05:49.664Z\"}​}​}​"
2023-03-29T13:05:49.666Z 20f76b43-8584-434d-88cb-993bf20324f7 info: EndMiddleware: End response. TotalTimeInMS=4 StatusCode=400 StatusMessage=Bad Request Headers={​"server":"Azurite-Table/3.22.0","x-ms-error-code":"InvalidInput","x-ms-request-id":"20f76b43-8584-434d-88cb-993bf20324f7","x-ms-version":"2021-12-02","content-type":"application/json;odata=minimalmetadata;streaming=true;charset=utf-8"}​
`

### Have you found a mitigation/solution?
I noticed that the issue does not occur when we set filter = null instead of filter = string.Empty()
However this change needs to be done in our production service code, which is currently working fine when interacting with AzureTableStorage with string.Empty. 

So we want to check if there is change needed in Azurite instead to support the same, so that it can accept string.Empty as parameter.

**Comment by edwin-huber** [comment]
I"ll take a look

**Comment by PrasantJillella** [comment]
Hi 

Checking to see if there was any update.
Thank you.

**Comment by PrasantJillella** [comment]
Hi 

checking back on this.

**Comment by PrasantJillella** [comment]
Hi Checking to see for any update.
thank you.

**Comment by PrasantJillella** [comment]
Hi @edwin-huber 

Checking to see if verifying and fixing the issue would take longer, Just want to review options with my team
for unblocking our azurite migration task.

Thank you.

**Comment by PrasantJillella** [comment]
Thank you, really appreciate it :-D

**Comment by edwin-huber** [comment]
This is resolved.
Test case is included.
