### ISSUE TITLE
The API version 2021-12-02 is not supported by Azurite

### ISSUE THREAD

**Issue by jsquire** [Azure/Azurite#1897]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#35396](https://github.com/Azure/azure-sdk-for-net/issues/35396).

## Details

I have update the my visual studio to the latest version yesterday and suddenly the method var `azResponse = await blobClient.DownloadToAsync(targetStream);` stopped working. 

i found  the below message in the exception

```
Azure.RequestFailedException
  HResult=0x80131500
  Message=The API version 2021-12-02 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. 
RequestId:464b97a7-707a-4af6-8c25-8cce0e6b42f0
Time:2023-04-06T06:58:42.559Z
Status: 400 (The API version 2021-12-02 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. )
ErrorCode: InvalidHeaderValue

Headers:
Server: Azurite-Blob/3.20.1
x-ms-error-code: InvalidHeaderValue
x-ms-request-id: 464b97a7-707a-4af6-8c25-8cce0e6b42f0
Date: Thu, 06 Apr 2023 06:58:42 GMT
Connection: keep-alive
Keep-Alive: REDACTED
Transfer-Encoding: chunked
Content-Type: application/xml

  Source=Azure.Storage.Blobs
  StackTrace:
   at Azure.Storage.Blobs.BlobRestClient.<DownloadAsync>d__8.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<StartDownloadAsync>d__66.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadStreamingInternal>d__65.MoveNext()
   at Azure.Storage.Blobs.PartitionedDownloader.<DownloadToAsync>d__9.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<StagedDownloadAsync>d__94.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__92.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__84.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__80.MoveNext()
   at VPMS.FuncApp.Services.DocumentRespository.<DownloadDocument>d__3.MoveNext() in C:\Projects\vpms\vpms-legacy\VPMS.AzFunctionApps\VPMS.FuncApp\Services\DocumentRespository.cs:line 27

  This exception was originally thrown at this call stack:
    Azure.Storage.Blobs.BlobRestClient.DownloadAsync(string, string, int?, string, string, bool?, bool?, string, string, Azure.Storage.Blobs.Models.EncryptionAlgorithmTypeInternal?, System.DateTimeOffset?, System.DateTimeOffset?, string, string, string, System.Threading.CancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(Azure.HttpRange, Azure.Storage.Blobs.Models.BlobRequestConditions, Azure.Storage.DownloadTransferValidationOptions, long, bool, System.Threading.CancellationToken)
    System.Threading.Tasks.ValueTask<TResult>.Result.get()
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(Azure.HttpRange, Azure.Storage.Blobs.Models.BlobRequestConditions, Azure.Storage.DownloadTransferValidationOptions, System.IProgress<long>, string, bool, System.Threading.CancellationToken)
    Azure.Storage.Blobs.PartitionedDownloader.DownloadToAsync(System.IO.Stream, Azure.Storage.Blobs.Models.BlobRequestConditions, System.Threading.CancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.StagedDownloadAsync(System.IO.Stream, Azure.Storage.Blobs.Models.BlobRequestConditions, System.IProgress<long>, Azure.Storage.StorageTransferOptions, Azure.Storage.DownloadTransferValidationOptions, bool, System.Threading.CancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(System.IO.Stream, Azure.Storage.Blobs.Models.BlobRequestConditions, Azure.Storage.StorageTransferOptions, System.Threading.CancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(System.IO.Stream, System.Threading.CancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(System.IO.Stream)
    VPMS.FuncApp.Services.DocumentRespository.DownloadDocument(string, string, System.IO.Stream) in DocumentRespository.cs
```

### Expected behavior

The stram must be downloaded

### Actual behavior

Throws error 

 HResult=0x80131500
  Message=The API version 2021-12-02 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. 

### Reproduction Steps

```
public async Task<ResponseResult<Stream>> DownloadDocument(string containerName, string blobName, Stream targetStream)
    {
        try
        {
            var blobContainerClient = GetContainerAsync(containerName);

            var blobClient = blobContainerClient.GetBlobClient(blobName);

            var azResponse = await blobClient.DownloadToAsync(targetStream);

            if (azResponse.IsError) return new(new OperationFailedException("blob", JsonConvert.SerializeObject(azResponse)));

            return new(targetStream);
        }


        catch (Exception ex)
        {
            return new(new OperationFailedException("Blob", JsonConvert.SerializeObject(ex)));
        }
    }
```

### Environment

visual studio enterprise: 17.5.3
azurite version: 3.20.1

**Comment by blueww** [comment]
@jsquire 

2021-12-02 is support by Azurite 3.22.0 or later (you are using 3.20.1), see details in :
https://github.com/Azure/Azurite/blob/main/ChangeLog.md#202302-version-3220

Would you please upgrade to latest Azurite and try again?

Besides that, you can also suppress this error by run Azurite with parameter "--skipApiVersionCheck".

**Comment by cjbush** [comment]
@blueww Thanks that fixed the issue for me. One gotcha is I had to purge the Azurite image from Docker Desktop for it to pull the latest. Just mentioning that in case anybody runs in to the same thing.

**Comment by jmoralesv** [comment]
I have just come across this issue when testing locally with the more recent version of Visual Studio 2022, 17.5.5. The Azure version installed is 3.20.1.

Not sure how the Visual Studio team maintains dependencies updated, but I will resort to use the skipApiVersionCheck parameter for now.
