### ISSUE TITLE
*PANIC* when looking for non-existent row

### ISSUE THREAD

**Issue by tomasaschan** [Azure/Azurite#19]
There seems to be an inconsistency in how this emulator handles non-existent rows compared to how "real" Azure Table Storage handles them. I discovered this while using [Streamstone](https://github.com/yevhen/Streamstone), which builds event streaming capabilities on top of Azure Table Storage, and while I haven't been able to discern exactly what operations they're doing on the table storage, I have been able to build a minimal example that reproduces the problem.

To reproduce, make sure you have the `dotnet` CLI installed, and run

```
mkdir repro && cd repro
dotnet new console
dotnet add package Streamstone
```

Then replace the contents of `Program.cs` with this:

```
using System;
using System.Threading.Tasks;
using Microsoft.WindowsAzure.Storage;
using Streamstone;

namespace AzuritePanicOnStreamstoneTryOpenStream
{
    class Program
    {
        public static async Task Main(string[] args)
        {
            // Replace with CloudStorageAccount.Parse("your connection string"); for using a real Azure Storage Account
            var account = CloudStorageAccount.DevelopmentStorageAccount;

            var table = account
                .CreateCloudTableClient()
                .GetTableReference("Events");
            await table.CreateIfNotExistsAsync();

            var partition = new Partition(table, "foo");

            await Stream.TryOpenAsync(partition);
        }
    }
}
```

Finally, run `dotnet run` to see the program fail with

```
Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: Unexpected response code, Expected:OK or NotFound, Received:InternalServerError
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 315
   at Streamstone.Stream.OpenStreamOperation.ExecuteAsync()
   at AzuritePanicOnStreamstoneTryOpenStream.Program.Main(String[] args) in C:\Work\OSS\Throwaway repros\AzuritePanicOnStreamstoneTryOpenStream\Program.cs:line 17
   at AzuritePanicOnStreamstoneTryOpenStream.Program.<Main>(String[] args)
```

If I look at the logs for my docker container running Azurite, I see

```
GET /devstoreaccount1/Events(PartitionKey='foo',RowKey='SS-HEAD') 500 0.388 ms - 27
**PANIC** Something unexpected happened! Table Storage Emulator may be in an inconsistent state!
ReferenceError: partitionKey is not defined
    at TableStorageManager.queryEntities (/opt/azurite/lib/core/table/TableStorageManager.js:104:40)
    at QueryEntities.process (/opt/azurite/lib/actions/table/QueryEntities.js:12:29)
    at Object.actions.(anonymous function) [as QueryEntity] (/opt/azurite/lib/middleware/table/actions.js:52:19)
    at BbPromise.try (/opt/azurite/lib/middleware/table/actions.js:18:38)
    at tryCatcher (/opt/azurite/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/azurite/node_modules/bluebird/js/release/method.js:39:29)
    at module.exports (/opt/azurite/lib/middleware/table/actions.js:17:18)
    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:317:13)
    at /opt/azurite/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/azurite/node_modules/express/lib/router/index.js:275:10)
    at BbPromise.try (/opt/azurite/lib/middleware/table/validation.js:32:9)
    at tryCatcher (/opt/azurite/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/azurite/node_modules/bluebird/js/release/method.js:39:29)
    at module.exports (/opt/azurite/lib/middleware/table/validation.js:18:18)
```

However, if I connect to a real Azure Storage Account instead of the emulator, the program runs without error.

**Comment by tlycken** [comment]
Looking closer at this, it seems like #17 might be the same problem. Is there a timeframe for when that might merge and result in a new docker image?

**Comment by edwin-huber** [comment]
yes, I'm looking at this and will update in the next couple of days... depending on how quickly I get through everything

**Comment by edwin-huber** [comment]
The changes have been merged into our Dev branch to address this.
We'll merge into Master and release a new update soon. :)

**Comment by xt0rted** [comment]
@edwin-huber I just tried switching to Azurite and immediately ran into this issue. Any idea when the next update will be?

**Comment by edwin-huber** [comment]
Thanks for being patient... we're currently looking at some things, and hope to have a new release to all channels soon.
I wanted to have a couple of features in there before the next release, but if I take much longer with them, we shall release with only a couple of fixes.

**Comment by xt0rted** [comment]
Sounds good. For now I switched back to the storage emulator for this project, but in my other one Azurite is working great so far 👍

**Comment by legigor** [comment]
I've just checked out the `dev` branch and tried to run the code above and got another error:

> The metadata URI 'http://127.0.0.1:10002/devstoreaccount1/$metadata#Events' is not valid for the expected payload kind 'Entry'.

Using Fiddler I discovered the following interaction

```
GET /devstoreaccount1/Events(PartitionKey='foo',RowKey='SS-HEAD') HTTP/1.1
Accept-Charset: UTF-8
MaxDataServiceVersion: 3.0;NetFx
Accept: application/json; odata=minimalmetadata
x-ms-client-request-id: 35332c39-98fe-42ff-978c-f40b0ff3bff6
User-Agent: Azure-Storage/8.6.0 (.NET Core)
x-ms-version: 2017-04-17
x-ms-date: Wed, 06 Jun 2018 17:16:06 GMT
Authorization: SharedKey devstoreaccount1:rILMcfhY+wDXUhkexgZcv/3xjQAeNMeWnHo6gCkXT0o=
Host: 127.0.0.1:10002
```

And the response was **200** but **not 404** 

```
HTTP/1.1 200 OK
X-Powered-By: Express
x-ms-version: 2016-05-31
date: Wed, 06 Jun 2018 17:16:06 GMT
x-ms-request-id: 4c21eab0-69ad-11e8-ba06-c91eeba8504a
Content-Type: application/json; charset=utf-8
Content-Length: 88
ETag: W/"58-B8XnS9xdruTEWRhsL6DbgYh7QhY"
Connection: keep-alive

{"odata.metadata":"http://127.0.0.1:10002/devstoreaccount1/$metadata#Events","value":[]}
```

**Comment by edwin-huber** [comment]
Thanks for reporting this... I'm looking into it...

**Comment by edwin-huber** [comment]
I hope to have an update here in the next couple of days.  
We just need to iron out a few things this end.  
Many thanks for your patience!

**Comment by edwin-huber** [comment]
Sorry, this has taken longer than expected, as we were discussing the switch to a different emulator for table storage and this fell off my radar.  
My bad.  
I am again looking at getting table storage features working.

**Comment by edwin-huber** [comment]
our table API needs quite a bit of work to return the correct values.
I'm working on getting it straightened out.
Thanks for your patience!

**Comment by venkatapaidmarri** [comment]
Just wanted to check any info on the next release, I face Table Storage issue and a couple of tests are effected because of this. However i am planning to use the Azure emulator meanwhile.

**Error:**
 **PANIC** Something unexpected happened! Table Storage Emulator may be in an inconsistent state!
ReferenceError: partitionKey is not defined
    at TableStorageManager.queryEntities (C:\snapshot\Azurite\lib\core\table\TableStorageManager.js:0)
    at QueryEntities.process (C:\snapshot\Azurite\lib\actions\table\QueryEntities.js:0)
    at Object.actions.(anonymous function) [as QueryEntity] (C:\snapshot\Azurite\lib\middleware\table\actions.js:0)
    at module.exports.BbPromise.try (C:\snapshot\Azurite\lib\middleware\table\actions.js:0)
    at tryCatcher (C:\snapshot\Azurite\node_modules\bluebird\js\release\util.js:16:23)
    at Function.module.exports.Promise.attempt.Promise.try (C:\snapshot\Azurite\node_modules\bluebird\js\release\method.js:39:29)
    at module.exports (C:\snapshot\Azurite\lib\middleware\table\actions.js:0)
    at Layer.handle [as handle_request] (C:\snapshot\Azurite\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\snapshot\Azurite\node_modules\express\lib\router\index.js:317:13)
    at C:\snapshot\Azurite\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\snapshot\Azurite\node_modules\express\lib\router\index.js:335:12)
    at next (C:\snapshot\Azurite\node_modules\express\lib\router\index.js:275:10)
    at module.exports.BbPromise.try (C:\snapshot\Azurite\lib\middleware\table\validation.js:0)
    at tryCatcher (C:\snapshot\Azurite\node_modules\bluebird\js\release\util.js:16:23)
    at Function.module.exports.Promise.attempt.Promise.try (C:\snapshot\Azurite\node_modules\bluebird\js\release\method.js:39:29)
    at module.exports (C:\snapshot\Azurite\lib\middleware\table\validation.js:0)
GET /devstoreaccount1/PoisonTestTaskQueue(PartitionKey='1',RowKey='test%201a5f17fc-ed55-496e-9019-4430ea7711b2') 500 0.912 ms - 27

**Comment by edwin-huber** [comment]
addressed in pull request #80

**Comment by venkatapaidmarri** [comment]
Thanks for the update Edwin, may I know when would these changes roll out
as part of nuget package, currently I am using 2.6.5 one.
https://github.com/Azure/Azurite

Regards,
Venkata.

**Comment by edwin-huber** [comment]
"Soon" ? ish?  
Sorry that I can't be precise 😕 
I'd like to get a few more issues resolved before we release the next update.  
I'm aiming for this weekend / next week for pushing a new tagged release to the master branch.

**Comment by jchannon** [comment]
Just hit this too in docker

**Comment by perbergland** [comment]
Is there any workaround for this? I'm currently blocked from moving to Azurite.

**Comment by shahsaurabh0605** [comment]
Is this issue fixed? I am facing the same issue working with Azurite 2.6.5
```
GET /devstoreaccount1/test(PartitionKey='38',RowKey='89ddd9ff-be04-4329-855b-b0cd0aba9fc0') 500 3.133 ms - 27
**PANIC** Something unexpected happened! Table Storage Emulator may be in an inconsistent state!
ReferenceError: partitionKey is not defined
    at TableStorageManager.queryEntities (C:\snapshot\Azurite\lib\core\table\TableStorageManager.js:0)
    at QueryEntities.process (C:\snapshot\Azurite\lib\actions\table\QueryEntities.js:0)
    at Object.actions.(anonymous function) [as QueryEntity] (C:\snapshot\Azurite\lib\middleware\table\actions.js:0)
    at module.exports.BbPromise.try (C:\snapshot\Azurite\lib\middleware\table\actions.js:0)
    at tryCatcher (C:\snapshot\Azurite\node_modules\bluebird\js\release\util.js:16:23)
    at Function.module.exports.Promise.attempt.Promise.try (C:\snapshot\Azurite\node_modules\bluebird\js\release\method.js:39:29)

```

**Comment by edwin-huber** [comment]
hi all, thanks for your patience.
As you can see, we were busy with the new architecture for blob storage.
There is a Cosmos Emulator available as a Docker image (Windows only at the moment) which does a much better job of emulating the Table API.  
The fixes should be in the dev branch, and I'm currently trying to catch up on our backlog, which all now goes into the legacy dev branch, after which we shall push a release to the legacy branch and the various tooling channels.  
Can you try the legacy-dev branch and let me know if you still see the same issues?  
If so, it would be useful to have a sample piece of code that we can add to a test case and get the issue addressed.

**Comment by edwin-huber** [comment]
we have now released table support in the v3 api.
This should address this issue.

**Comment by mm-nbergen** [comment]
Can you confirm which version this is expected to have fixed this issue?  I see the following error in the version of Azurite included with VisualStudio 2022 (14.20.0.0 / 3.19.0 by the EXE details)

```
Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: The metadata URI 'http://127.0.0.1:10002/devstoreaccount1/$metadata#Tables/@Element' is not valid for the expected payload kind 'Feed'. ---> Microsoft.Data.OData.ODataException: The metadata URI 'http://127.0.0.1:10002/devstoreaccount1/$metadata#Tables/@Element' is not valid for the expected payload kind 'Feed'.
   at Microsoft.Data.OData.JsonLight.ODataJsonLightMetadataUriParser.ParseMetadataUri(ODataPayloadKind expectedPayloadKind, ODataReaderBehavior readerBehavior, ODataVersion version)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightMetadataUriParser.Parse(IEdmModel model, String metadataUriFromPayload, ODataPayloadKind payloadKind, ODataVersion version, ODataReaderBehavior readerBehavior)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStart(ODataPayloadKind payloadKind, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementation()
   at Microsoft.Data.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.Data.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableQueryPostProcessGeneric[TElement,TQueryType](Stream responseStream, Func`6 resolver, HttpWebResponse resp, TableRequestOptions options, OperationContext ctx, String accountName)
   at Microsoft.WindowsAzure.Storage.Table.TableQuery`1.<>c__DisplayClass10`2.<QueryImpl>b__f(RESTCommand`1 cmd, HttpWebResponse resp, OperationContext ctx)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessEndOfRequest[T](ExecutionState`1 executionState)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.TableQuery`1.<>c__DisplayClass7.<ExecuteInternal>b__6(IContinuationToken continuationToken)
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.<LazyEnumerable>d__0`1.MoveNext()
```

**Comment by daxtron2** [comment]
@mm-nbergen nearly the same issue I'm having, ours is on initializing a table only in azurite. 
`m_KeyStore = await AzureKeyStore.CreateAsync(m_TableClient, JwtAuthenticationConstants.JwkTableName, JwtAuthenticationConstants.KeystoreRefreshInterval, null);`

From what I've been told (haven't gotten to testing myself yet) it doesn't happen in azure storage emulator, only azurite.

**Comment by edwin-huber** [comment]
Hi,
can you confirm which packages / SDKs you are using?
We are not able to support all the deprecated SDKs like WindowsAzxure.Storage.
Please see:
https://www.nuget.org/packages/WindowsAzure.Storage/
If you open a new issue with steps to repro for the new version, we can take a look and track it properly.
Thanks.

**Comment by mm-nbergen** [comment]
We've recently updated to a later SDK version, I'll follow up when I find some spare bandwidth to give Azurite another go.
