### ISSUE TITLE
Query for escaped quotes fails

### ISSUE THREAD

**Issue by jezzsantos** [Azure/Azurite#1901]
### Which service(blob, file, queue, table) does this issue concern?
table
### Which version of the Azurite was used?
3.23.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
16.13.1
### What problem was encountered?
Exception when querying with an escaped single quote value in a string

### Steps to reproduce the issue?

When query against a row that has a single quote in the value (eg. "o'brien")
`table.Query<TableEntity>("Name eq 'o''brien'")`

Exception: 
Azure.RequestFailedException: The query condition specified in the request is invalid.
Status: 400 (Bad Request)
ErrorCode: InvalidInput

Content:
{"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"The query condition specified in the request is invalid.\nRequestId:93fb094a-1fee-4ba5-b0fe-3c899926ee1c\nTime:2023-04-09T22:19:18.069Z"}}}

Headers:
Server: Azurite-Table/3.23.0
x-ms-error-code: REDACTED
x-ms-request-id: 93fb094a-1fee-4ba5-b0fe-3c899926ee1c
x-ms-version: REDACTED
Date: Sun, 09 Apr 2023 22:19:18 GMT
Connection: keep-alive
Keep-Alive: REDACTED
Transfer-Encoding: chunked
Content-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8

   at Azure.Data.Tables.TableRestClient.QueryEntities(String table, Nullable`1 timeout, String nextPartitionKey, String nextRowKey, QueryOptions queryOptions, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.<>c__DisplayClass51_0`1.<Query>b__0(Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.<>c__DisplayClass5_0`1.<CreateEnumerable>b__0(String continuationToken, Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.FuncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Pageable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)

### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
@jezzsantos 
Thanks for raising this issue!
We will look into it and update you later.

**Comment by blueww** [comment]
@jezzsantos 

I have tried to repro this issue. 
The issue not repro on latest Azurite code in main branch.
However, it do repro on 3.23.0 code base.

So it looks some recent code change has fixed it. 
Would you please try the lastest code on Azurite main branch and see if the issue fixed or not? 
You can build/run Azurite from Azurite main branch by follow: https://github.com/Azure/Azurite#github

**Comment by blueww** [comment]
@jezzsantos

I will close this issue as not get your responds for a longe time, and the issue looks has already resolved in the latest Azurite code (not released).

Feel free to contact us again if need any assistance on Azurite.
