### ISSUE TITLE
Azurite should handle Boolean values case-insensitively for Azure parity

### ISSUE THREAD

**Issue by craxal** [Azure/Azurite#1947]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
N/A

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
N/A

### What's the Node.js version?
N/A

### What problem was encountered?
Azurite does not handle Boolean values in a case-insensitive manner the same way Azure does. I can't upload entities with Boolean values like "TRUE" and "FALSE".

This is particularly frustrating for users who often use Excel (which uses ALL CAPS for Boolean values) to create or edit CSV files and use Storage Explorer to import the data to Azurite.

### Steps to reproduce the issue?

1. Create a CSV file using Excel with the following data:
   PartitionKey | RowKey | Value | Value@type
   -------------|--------|-------|-----------
   a            | b      | FALSE | Boolean
2. Install and launch the latest Azurite.
3. Open Storage Explorer and connect to an public Azure table and the Azurite instance.
4. Create new tables in Azure and Azurite and open the tables in Storage Explorer.
5. Click the Import button and select the CSV file created in Step 1.
6. Observe and compare the results between the Azure import and the Azurite import.

### Have you found a mitigation/solution?
Edit Boolean values in a text editor to be lower case.

**Comment by blueww** [comment]
I can repro this issue.
Debug log:
```
2023-05-04T08:30:51.502Z 923be2be-16a7-4b99-850f-b9c04819c0a6 info: TableStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/$batch RequestHeaders:{"accept":"application/json","x-ms-version":"2019-02-02","dataserviceversion":"3.0;","maxdataserviceversion":"3.0;NetFx","content-type":"multipart/mixed; boundary=batch_8fd5280c-da56-410a-bd9e-dad1ed900244","accept-charset":"UTF-8","connection":"Keep-Alive","accept-encoding":"gzip,deflate","user-agent":"Microsoft Azure Storage Explorer/1.28.0 (win32) azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.9.0 Node/v16.17.1 OS/(ia32-Windows_NT-10.0.19045)","x-ms-client-request-id":"3b029bc5-3314-443c-a54b-23f38ca3c850","x-ms-date":"Thu, 04 May 2023 08:30:51 GMT","content-length":"623","authorization":"SharedKeyLite devstoreaccount1:4hjAPi/zInZ1X2fbGsPGvFxtAVR5QF/Ndroc6ryfAyw=","host":"127.0.0.1:10002"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2023-05-04T08:30:51.503Z 923be2be-16a7-4b99-850f-b9c04819c0a6 debug: tableStorageContextMiddleware: Dispatch pattern string: /$batch
2023-05-04T08:30:51.503Z 923be2be-16a7-4b99-850f-b9c04819c0a6 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=$batch
2023-05-04T08:30:51.503Z 923be2be-16a7-4b99-850f-b9c04819c0a6 verbose: DispatchMiddleware: Dispatching request...
2023-05-04T08:30:51.503Z 923be2be-16a7-4b99-850f-b9c04819c0a6 info: DispatchMiddleware: Operation=Table_Batch
2023-05-04T08:30:51.504Z 923be2be-16a7-4b99-850f-b9c04819c0a6 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2023-05-04T08:30:51.505Z 923be2be-16a7-4b99-850f-b9c04819c0a6 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2023-05-04T08:30:51.505Z 923be2be-16a7-4b99-850f-b9c04819c0a6 info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Thu, 04 May 2023 08:30:51 GMT\n/devstoreaccount1/devstoreaccount1/$batch"
2023-05-04T08:30:51.505Z 923be2be-16a7-4b99-850f-b9c04819c0a6 info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:4hjAPi/zInZ1X2fbGsPGvFxtAVR5QF/Ndroc6ryfAyw=
2023-05-04T08:30:51.505Z 923be2be-16a7-4b99-850f-b9c04819c0a6 info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
2023-05-04T08:30:51.506Z 923be2be-16a7-4b99-850f-b9c04819c0a6 verbose: DeserializerMiddleware: Start deserializing...
2023-05-04T08:30:51.507Z 923be2be-16a7-4b99-850f-b9c04819c0a6 info: HandlerMiddleware: DeserializedParameters={"version":"2019-02-02","options":{"requestId":"3b029bc5-3314-443c-a54b-23f38ca3c850","dataServiceVersion":"3.0;"},"multipartContentType":"multipart/mixed; boundary=batch_8fd5280c-da56-410a-bd9e-dad1ed900244","contentLength":623,"body":"ReadableStream"}
2023-05-04T08:30:51.508Z 923be2be-16a7-4b99-850f-b9c04819c0a6 debug: TableHandler:batch() Raw request string is "--batch_8fd5280c-da56-410a-bd9e-dad1ed900244\r\ncontent-type: multipart/mixed; boundary=changeset_0a9fb659-3e04-47ed-aa39-b248f13c0764\r\n\r\n\r\n--changeset_0a9fb659-3e04-47ed-aa39-b248f13c0764\r\ncontent-type: application/http\r\ncontent-transfer-encoding: binary\r\n\r\nPATCH http://127.0.0.1:10002/devstoreaccount1/issue1947(PartitionKey='a',RowKey='b') HTTP/1.1\r\nContent-Type: application/json\r\nDataServiceVersion: 3.0\r\nAccept: application/json\r\n\r\n\r\n{\"PartitionKey\":\"a\",\"RowKey\":\"b\",\"Value\":\"FALSE\",\"Value@odata.type\":\"Edm.Boolean\"}\r\n--changeset_0a9fb659-3e04-47ed-aa39-b248f13c0764--\r\n--batch_8fd5280c-da56-410a-bd9e-dad1ed900244--\r\n"
2023-05-04T08:30:51.514Z 923be2be-16a7-4b99-850f-b9c04819c0a6 error: TableHandler:mergeEntity() TypeError "TypeError: Not a valid EdmBoolean string.\n    at Function.validate (D:\\code\\azurite\\src\\table\\entity\\EdmBoolean.ts:9:15)\n    at new EdmBoolean (D:\\code\\azurite\\src\\table\\entity\\EdmBoolean.ts:21:34)\n    at parseEntityProperty (D:\\code\\azurite\\src\\table\\entity\\EntityProperty.ts:136:11)\n    at NormalizedEntity.validateSystemProperty (D:\\code\\azurite\\src\\table\\entity\\NormalizedEntity.ts:87:41)\n    at new NormalizedEntity (D:\\code\\azurite\\src\\table\\entity\\NormalizedEntity.ts:60:33)\n    at TableHandler.mergeEntity (D:\\code\\azurite\\src\\table\\handlers\\TableHandler.ts:494:26)\n    at TableBatchOrchestrator.handleBatchMerge (D:\\code\\azurite\\src\\table\\batch\\TableBatchOrchestrator.ts:553:41)\n    at TableBatchOrchestrator.routeAndDispatchBatchRequest (D:\\code\\azurite\\src\\table\\batch\\TableBatchOrchestrator.ts:279:48)\n    at TableBatchOrchestrator.submitRequestsToHandlers (D:\\code\\azurite\\src\\table\\batch\\TableBatchOrchestrator.ts:110:43)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
2023-05-04T08:30:51.515Z 923be2be-16a7-4b99-850f-b9c04819c0a6 debug: TableHandler:batch() Raw response string is "--batchresponse_8fd5280c-da56-410a-bd9e-dad1ed900244\r\nContent-Type: multipart/mixed; boundary=changesetresponse_0a9fb659-3e04-47ed-aa39-b248f13c0764\r\n\r\n--changesetresponse_0a9fb659-3e04-47ed-aa39-b248f13c0764\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nHTTP/1.1 400 Bad Request\r\nContent-ID: 1\r\nDataServiceVersion: 3.0;\r\nContent-Type: application/json;odata=minimalmetadata;charset=utf-8\r\n\r\n{\"odata.error\":{\"code\":\"InvalidInput\",\"message\":{\"lang\":\"en-US\",\"value\":\"0:An error occurred while processing this request.\\nRequestId:923be2be-16a7-4b99-850f-b9c04819c0a6\\nTime:2023-05-04T08:30:51.514Z\"}}}\r\n--changesetresponse_0a9fb659-3e04-47ed-aa39-b248f13c0764--\r\n--batchresponse_8fd5280c-da56-410a-bd9e-dad1ed900244--\r\n"
2023-05-04T08:30:51.515Z 923be2be-16a7-4b99-850f-b9c04819c0a6 verbose: SerializerMiddleware: Start serializing...
2023-05-04T08:30:51.515Z 923be2be-16a7-4b99-850f-b9c04819c0a6 info: Serializer: Start returning stream body.
2023-05-04T08:30:51.518Z 923be2be-16a7-4b99-850f-b9c04819c0a6 info: EndMiddleware: End response. TotalTimeInMS=16 StatusCode=202 StatusMessage=Accepted Headers={"server":"Azurite-Table/3.23.0","content-type":"multipart/mixed; boundary=batchresponse_8fd5280c-da56-410a-bd9e-dad1ed900244","x-ms-request-id":"923be2be-16a7-4b99-850f-b9c04819c0a6","x-ms-version":"2022-11-02","date":"Thu, 04 May 2023 08:30:51 GMT"}
```
It looks the issue can be fixed by convert the user input value to lower case by adding code `value = value.toLocaleLowerCase();` under line https://github.com/Azure/Azurite/blob/42d398a888408c6488d6bf998a992c0681512266/src/table/entity/EdmBoolean.ts#L7

However, from thecode comments "assuming that we do not need to use value.toLocaleLowerCase()", it looks Azurite not convert the value to lower case by purpose.

@edwin-huber 
Could you please confirm why you add the comments here? 
Do you have any concern to fix the issue by convert the user input Boolean value to lower case?
If you agree the fix, I will raise a PR to fix it soon.

**Comment by edwin-huber** [comment]
Thanks.
The issue was in the query parser and fixed.
The EDM type has no effect on this.
PR inbound.
