### ISSUE TITLE
Invalid characters or formats are allowed on blob containers

### ISSUE THREAD

**Issue by fdipuma** [Azure/Azurite#2017]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.24.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
14.21.3

### What problem was encountered?
When interacting with the container, Azurite should return an error when an invalid character (e.g. any invalid domain characters) or format (less than 3 chars or more than 63 chars) is encountered, but it allows such formats.

It seems to be a regression, since invalid chars were detected correctly at least with version 3.21.

### Steps to reproduce the issue?

Some logs from the container: 
```
2023-06-23 18:08:26 172.17.0.1 - - [23/Jun/2023:16:08:26 +0000] "PUT /devstoreaccount1/$INVALID_CONTAINER_NAMEabcd123456789012345678901234567890123456789012345678901234567890:/test HTTP/1.1" 201 -
2023-06-23 18:08:26 172.17.0.1 - - [23/Jun/2023:16:08:26 +0000] "HEAD /devstoreaccount1/$INVALID_CONTAINER_NAMEabcd123456789012345678901234567890123456789012345678901234567890:/test HTTP/1.1" 200 3
2023-06-23 18:10:12 172.17.0.1 - - [23/Jun/2023:16:10:12 +0000] "PUT /devstoreaccount1/test?restype=container HTTP/1.1" 409 -
2023-06-23 18:10:12 172.17.0.1 - - [23/Jun/2023:16:10:12 +0000] "PUT /devstoreaccount1/$INVALID_CONTAINER_NAME:___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890?restype=container HTTP/1.1" 201 -
2023-06-23 18:10:16 172.17.0.1 - - [23/Jun/2023:16:10:16 +0000] "PUT /devstoreaccount1/test?restype=container HTTP/1.1" 409 -
2023-06-23 18:10:17 172.17.0.1 - - [23/Jun/2023:16:10:17 +0000] "PUT /devstoreaccount1/$INVALID_CONTAINER_NAME:___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890/test HTTP/1.1" 201 -
2023-06-23 18:10:17 172.17.0.1 - - [23/Jun/2023:16:10:17 +0000] "HEAD /devstoreaccount1/$INVALID_CONTAINER_NAME:___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890___abcd123456789012345678901234567890123456789012345678901234567890/test HTTP/1.1" 200 3
```

### Have you found a mitigation/solution?
Use an older version

**Comment by blueww** [comment]
@fdipuma 

Would you please make sure you are using the right version of Azurite? 
As you are using docker, please make sure you have the updated docker image in local machine.
You can check the Azurite version by run "docker run mcr.microsoft.com/azure-storage/azurite azurite --version" 

I have test tested with Azurite 3.24.0. In my test, create container with invalid container name will fail as 400. 
```
2023-06-26T06:17:28.718Z 0b5a6587-7b30-4b41-b5ba-47e814e1ac53 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/abcd123456789012345678901234567890123456789012345678901234567890?restype=container&sv=2022-11-02&ss=b&srt=sco&se=2023-06-26T07%3A13%3A09Z&sp=rwdl&sig=XArHi5nzyotTnrXXFHw2q1r2XvU8k1BEzZQJvutAcI0%3D RequestHeaders:{"user-agent":"Mozilla/5.0 (Windows NT; Windows NT 10.0; zh-CN) WindowsPowerShell/5.1.19041.3031","host":"127.0.0.1:10000","content-length":"0"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2023-06-26T06:17:28.720Z 0b5a6587-7b30-4b41-b5ba-47e814e1ac53 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2023-06-26T06:17:28.721Z 0b5a6587-7b30-4b41-b5ba-47e814e1ac53 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified resource name length is not within the permissible limits.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=The specified resource name length is not within the permissible limits. ErrorHTTPHeaders={"x-ms-error-code":"OutOfRangeInput","x-ms-request-id":"0b5a6587-7b30-4b41-b5ba-47e814e1ac53"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>OutOfRangeInput</Code>\n  <Message>The specified resource name length is not within the permissible limits.\nRequestId:0b5a6587-7b30-4b41-b5ba-47e814e1ac53\nTime:2023-06-26T06:17:28.719Z</Message>\n</Error>" ErrorStack="StorageError: The specified resource name length is not within the permissible limits.\n    at Function.getOutOfRangeName (D:\\code\\azurite\\src\\blob\\errors\\StorageErrorFactory.ts:745:12)\n    at validateContainerName (D:\\code\\azurite\\src\\blob\\utils\\utils.ts:142:31)\n    at blobStorageContextMiddleware (D:\\code\\azurite\\src\\blob\\middlewares\\blobStorageContext.middleware.ts:224:26)\n    at D:\\code\\azurite\\src\\blob\\middlewares\\blobStorageContext.middleware.ts:26:12\n    at Layer.handle [as handle_request] (D:\\code\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at logger (D:\\code\\azurite\\node_modules\\morgan\\index.js:144:5)"
2023-06-26T06:17:28.721Z 0b5a6587-7b30-4b41-b5ba-47e814e1ac53 error: ErrorMiddleware: Set HTTP code: 400
2023-06-26T06:17:28.722Z 0b5a6587-7b30-4b41-b5ba-47e814e1ac53 error: ErrorMiddleware: Set HTTP status message: The specified resource name length is not within the permissible limits.
2023-06-26T06:17:28.723Z 0b5a6587-7b30-4b41-b5ba-47e814e1ac53 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=OutOfRangeInput
2023-06-26T06:17:28.724Z 0b5a6587-7b30-4b41-b5ba-47e814e1ac53 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=0b5a6587-7b30-4b41-b5ba-47e814e1ac53
2023-06-26T06:17:28.724Z 0b5a6587-7b30-4b41-b5ba-47e814e1ac53 error: ErrorMiddleware: Set content type: application/xml
2023-06-26T06:17:28.725Z 0b5a6587-7b30-4b41-b5ba-47e814e1ac53 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>OutOfRangeInput</Code>\n  <Message>The specified resource name length is not within the permissible limits.\nRequestId:0b5a6587-7b30-4b41-b5ba-47e814e1ac53\nTime:2023-06-26T06:17:28.719Z</Message>\n</Error>"
2023-06-26T06:17:28.726Z 0b5a6587-7b30-4b41-b5ba-47e814e1ac53 info: EndMiddleware: End response. TotalTimeInMS=8 StatusCode=400 StatusMessage=The specified resource name length is not within the permissible limits. Headers={"server":"Azurite-Blob/3.24.0","x-ms-error-code":"OutOfRangeInput","x-ms-request-id":"0b5a6587-7b30-4b41-b5ba-47e814e1ac53","content-type":"application/xml"}
2023-06-26T06:17:41.469Z d21dc950-4090-40db-a949-c34722b6ad50 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/ab?restype=container&sv=2022-11-02&ss=b&srt=sco&se=2023-06-26T07%3A13%3A09Z&sp=rwdl&sig=XArHi5nzyotTnrXXFHw2q1r2XvU8k1BEzZQJvutAcI0%3D RequestHeaders:{"user-agent":"Mozilla/5.0 (Windows NT; Windows NT 10.0; zh-CN) WindowsPowerShell/5.1.19041.3031","host":"127.0.0.1:10000","content-length":"0"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2023-06-26T06:17:41.474Z d21dc950-4090-40db-a949-c34722b6ad50 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2023-06-26T06:17:41.474Z d21dc950-4090-40db-a949-c34722b6ad50 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified resource name length is not within the permissible limits.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=The specified resource name length is not within the permissible limits. ErrorHTTPHeaders={"x-ms-error-code":"OutOfRangeInput","x-ms-request-id":"d21dc950-4090-40db-a949-c34722b6ad50"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>OutOfRangeInput</Code>\n  <Message>The specified resource name length is not within the permissible limits.\nRequestId:d21dc950-4090-40db-a949-c34722b6ad50\nTime:2023-06-26T06:17:41.473Z</Message>\n</Error>" ErrorStack="StorageError: The specified resource name length is not within the permissible limits.\n    at Function.getOutOfRangeName (D:\\code\\azurite\\src\\blob\\errors\\StorageErrorFactory.ts:745:12)\n    at validateContainerName (D:\\code\\azurite\\src\\blob\\utils\\utils.ts:142:31)\n    at blobStorageContextMiddleware (D:\\code\\azurite\\src\\blob\\middlewares\\blobStorageContext.middleware.ts:224:26)\n    at D:\\code\\azurite\\src\\blob\\middlewares\\blobStorageContext.middleware.ts:26:12\n    at Layer.handle [as handle_request] (D:\\code\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at logger (D:\\code\\azurite\\node_modules\\morgan\\index.js:144:5)"
2023-06-26T06:17:41.475Z d21dc950-4090-40db-a949-c34722b6ad50 error: ErrorMiddleware: Set HTTP code: 400
2023-06-26T06:17:41.476Z d21dc950-4090-40db-a949-c34722b6ad50 error: ErrorMiddleware: Set HTTP status message: The specified resource name length is not within the permissible limits.
2023-06-26T06:17:41.477Z d21dc950-4090-40db-a949-c34722b6ad50 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=OutOfRangeInput
2023-06-26T06:17:41.477Z d21dc950-4090-40db-a949-c34722b6ad50 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=d21dc950-4090-40db-a949-c34722b6ad50
2023-06-26T06:17:41.478Z d21dc950-4090-40db-a949-c34722b6ad50 error: ErrorMiddleware: Set content type: application/xml
2023-06-26T06:17:41.479Z d21dc950-4090-40db-a949-c34722b6ad50 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>OutOfRangeInput</Code>\n  <Message>The specified resource name length is not within the permissible limits.\nRequestId:d21dc950-4090-40db-a949-c34722b6ad50\nTime:2023-06-26T06:17:41.473Z</Message>\n</Error>"
2023-06-26T06:17:41.480Z d21dc950-4090-40db-a949-c34722b6ad50 info: EndMiddleware: End response. TotalTimeInMS=11 StatusCode=400 StatusMessage=The specified resource name length is not within the permissible limits. Headers={"server":"Azurite-Blob/3.24.0","x-ms-error-code":"OutOfRangeInput","x-ms-request-id":"d21dc950-4090-40db-a949-c34722b6ad50","content-type":"application/xml"}
2023-06-26T06:17:59.700Z 0b6043d8-96ee-40ae-83ba-aa8b5c6dd379 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/__ab?restype=container&sv=2022-11-02&ss=b&srt=sco&se=2023-06-26T07%3A13%3A09Z&sp=rwdl&sig=XArHi5nzyotTnrXXFHw2q1r2XvU8k1BEzZQJvutAcI0%3D RequestHeaders:{"user-agent":"Mozilla/5.0 (Windows NT; Windows NT 10.0; zh-CN) WindowsPowerShell/5.1.19041.3031","host":"127.0.0.1:10000","content-length":"0"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2023-06-26T06:17:59.701Z 0b6043d8-96ee-40ae-83ba-aa8b5c6dd379 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2023-06-26T06:17:59.702Z 0b6043d8-96ee-40ae-83ba-aa8b5c6dd379 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specifed resource name contains invalid characters.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=The specifed resource name contains invalid characters. ErrorHTTPHeaders={"x-ms-error-code":"InvalidResourceName","x-ms-request-id":"0b6043d8-96ee-40ae-83ba-aa8b5c6dd379"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidResourceName</Code>\n  <Message>The specifed resource name contains invalid characters.\nRequestId:0b6043d8-96ee-40ae-83ba-aa8b5c6dd379\nTime:2023-06-26T06:17:59.701Z</Message>\n</Error>" ErrorStack="StorageError: The specifed resource name contains invalid characters.\n    at Function.getInvalidResourceName (D:\\code\\azurite\\src\\blob\\errors\\StorageErrorFactory.ts:736:12)\n    at validateContainerName (D:\\code\\azurite\\src\\blob\\utils\\utils.ts:146:31)\n    at blobStorageContextMiddleware (D:\\code\\azurite\\src\\blob\\middlewares\\blobStorageContext.middleware.ts:224:26)\n    at D:\\code\\azurite\\src\\blob\\middlewares\\blobStorageContext.middleware.ts:26:12\n    at Layer.handle [as handle_request] (D:\\code\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at logger (D:\\code\\azurite\\node_modules\\morgan\\index.js:144:5)"
2023-06-26T06:17:59.702Z 0b6043d8-96ee-40ae-83ba-aa8b5c6dd379 error: ErrorMiddleware: Set HTTP code: 400
2023-06-26T06:17:59.703Z 0b6043d8-96ee-40ae-83ba-aa8b5c6dd379 error: ErrorMiddleware: Set HTTP status message: The specifed resource name contains invalid characters.
2023-06-26T06:17:59.703Z 0b6043d8-96ee-40ae-83ba-aa8b5c6dd379 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidResourceName
2023-06-26T06:17:59.704Z 0b6043d8-96ee-40ae-83ba-aa8b5c6dd379 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=0b6043d8-96ee-40ae-83ba-aa8b5c6dd379
2023-06-26T06:17:59.705Z 0b6043d8-96ee-40ae-83ba-aa8b5c6dd379 error: ErrorMiddleware: Set content type: application/xml
2023-06-26T06:17:59.705Z 0b6043d8-96ee-40ae-83ba-aa8b5c6dd379 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidResourceName</Code>\n  <Message>The specifed resource name contains invalid characters.\nRequestId:0b6043d8-96ee-40ae-83ba-aa8b5c6dd379\nTime:2023-06-26T06:17:59.701Z</Message>\n</Error>"
2023-06-26T06:17:59.706Z 0b6043d8-96ee-40ae-83ba-aa8b5c6dd379 info: EndMiddleware: End response. TotalTimeInMS=6 StatusCode=400 StatusMessage=The specifed resource name contains invalid characters. Headers={"server":"Azurite-Blob/3.24.0","x-ms-error-code":"InvalidResourceName","x-ms-request-id":"0b6043d8-96ee-40ae-83ba-aa8b5c6dd379","content-type":"application/xml"}
```

**Comment by blueww** [comment]
@fdipuma 

I will close this issue as this looks not Azurite issue, and not get responds from you for a long time.
Feel free to contact us again if need any further assistance on Azurite.
