### ISSUE TITLE
Error reading block blob from Python API

### ISSUE THREAD

**Issue by tomhosking** [Azure/Azurite#215]
Using v3 blob service (running from source in docker), the following code throws an error:

```
from azure.storage.blob import BlockBlobService
blob_conn = BlockBlobService(is_emulated=True, custom_domain='localhost:10000')
blob_conn.create_container('azurite-test')
blob_conn.create_blob_from_text('azurite-test', 'test-file', 'Test content')
print(blob_conn.get_blob_to_text('azurite-test', 'test-file').content)
```

`TypeError: '<' not supported between instances of 'int' and 'NoneType'`

This code works with v2.7.0

**Comment by XiaoningLiu** [comment]
Hi @tomhosking Your sample works well on my environment (not in docker). Here are my steps. You can enable V3 debugging log by `-d debug.log` and send us the log to us for further investigation.

```cmd
xiaonli@xiaonli-pc MINGW64 /e/sanity/azurite/python
$ npm install azurite -g
C:\Program Files\nodejs\azurite-blob -> C:\Program Files\nodejs\node_modules\azurite\dist\src\blob\main.js
C:\Program Files\nodejs\azurite -> C:\Program Files\nodejs\node_modules\azurite\dist\src\blob\main.js
+ azurite@3.0.0-preview
added 125 packages from 178 contributors in 5.329s


xiaonli@xiaonli-pc MINGW64 /e/sanity/azurite/python
$ azurite -v
3.0.0-preview

xiaonli@xiaonli-pc MINGW64 /e/sanity/azurite/python
$ mkdir workspace

xiaonli@xiaonli-pc MINGW64 /e/sanity/azurite/python
$ azurite -l workspace
Azurite Blob service is starting on 127.0.0.1:10000
Azurite Blob service successfully listens on 127.0.0.1:10000
127.0.0.1 - - [10/May/2019:02:00:56 +0000] "PUT /devstoreaccount1/azurite-test?restype=container HTTP/1.1" 201 -
127.0.0.1 - - [10/May/2019:02:00:56 +0000] "PUT /devstoreaccount1/azurite-test/test-file HTTP/1.1" 201 -
127.0.0.1 - - [10/May/2019:02:00:56 +0000] "GET /devstoreaccount1/azurite-test/test-file HTTP/1.1" 200 12
```

```cmd
xiaonli@xiaonli-pc MINGW64 /e/sanity/azurite/python
$ python ./azurite.py
Test content
```

**Comment by tomhosking** [comment]
Hi, thanks for following up.

I ran the server using the same steps as you, but still get the same error. `debug.log` is attached. 

MacOS `10.14.4`
Node `v11.10.0`
Python `3.6.5_1`
Modules:
`azure-storage-blob==1.5.0`
`azure-storage-common==1.4.0`

```
127.0.0.1 - - [10/May/2019:08:19:27 +0000] "PUT /devstoreaccount1/azurite-test?restype=container HTTP/1.1" 409 -
127.0.0.1 - - [10/May/2019:08:19:27 +0000] "PUT /devstoreaccount1/azurite-test/test-file HTTP/1.1" 201 -
127.0.0.1 - - [10/May/2019:08:19:27 +0000] "GET /devstoreaccount1/azurite-test/test-file HTTP/1.1" 200 12
```

I note that the initial container creation results in a 409 not a 201?

[debug.log](https://github.com/Azure/Azurite/files/3165543/debug.log)

**Comment by XiaoningLiu** [comment]
Hi @tomhosking 409 means the container already exists. You can get response details in debug.log.
Azurite returns handles the request successfully according to the log.

```
2019-05-10T08:19:27.484Z c396dbfe-7b63-4dda-9552-696e95c801cf error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified container already exists.  ErrorHTTPStatusCode=409 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"ContainerAlreadyExists","x-ms-request-id":"c396dbfe-7b63-4dda-9552-696e95c801cf"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:c396dbfe-7b63-4dda-9552-696e95c801cf\nTime:2019-05-10T08:19:27.480Z</Message>\n</Error>" ErrorStack="StorageError: The specified container already exists.\n    at Function.getContainerAlreadyExists (/usr/local/lib/node_modules/azurite/dist/src/blob/errors/StorageErrorFactory.js:16:16)\n    at ContainerHandler.create (/usr/local/lib/node_modules/azurite/dist/src/blob/handlers/ContainerHandler.js:46:49)\n    at processTicksAndRejections (internal/process/next_tick.js:81:5)"
2019-05-10T08:19:27.484Z c396dbfe-7b63-4dda-9552-696e95c801cf error: ErrorMiddleware: Set HTTP code: 409
2019-05-10T08:19:27.484Z c396dbfe-7b63-4dda-9552-696e95c801cf error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=ContainerAlreadyExists
2019-05-10T08:19:27.484Z c396dbfe-7b63-4dda-9552-696e95c801cf error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=c396dbfe-7b63-4dda-9552-696e95c801cf
2019-05-10T08:19:27.484Z c396dbfe-7b63-4dda-9552-696e95c801cf error: ErrorMiddleware: Set content type: application/xml
2019-05-10T08:19:27.484Z c396dbfe-7b63-4dda-9552-696e95c801cf error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:c396dbfe-7b63-4dda-9552-696e95c801cf\nTime:2019-05-10T08:19:27.480Z</Message>\n</Error>"
2019-05-10T08:19:27.485Z c396dbfe-7b63-4dda-9552-696e95c801cf info: EndMiddleware: End response. TotalTimeInMS=19 StatusCode=409 StatusMessage=Conflict Headers={"server":"Azurite-Blob/3.0.0-preview","x-ms-error-code":"ContainerAlreadyExists","x-ms-request-id":"c396dbfe-7b63-4dda-9552-696e95c801cf","content-type":"application/xml"}

```

**Comment by XiaoningLiu** [comment]
I'm using Python 2.7.13, azure-storage-blob-1.5.0 azure-storage-common-1.4.2. Seems major Python version is different with you.

**Comment by tomhosking** [comment]
In case it's useful, here are the `DEBUG` level logs from the `azure-storage-blob` module itself.

v3:
```
2019-05-10 10:01:48,840 azure.storage.common.storageclient INFO  Client-Request-ID=3e9227c0-7302-11e9-af6d-784f43a07631 Outgoing request: Method=GET, Path=/devstoreaccount1/azurite-test/test-file, Query={'snapshot': None, 'timeout': None}, Headers={'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-range': 'bytes=0-33554431', 'x-ms-version': '2018-03-28', 'User-Agent': 'Azure-Storage/1.4.0-1.5.0 (Python CPython 3.6.5; Darwin 18.5.0)', 'x-ms-client-request-id': '3e9227c0-7302-11e9-af6d-784f43a07631', 'x-ms-date': 'Fri, 10 May 2019 09:01:48 GMT', 'Authorization': 'REDACTED'}.
2019-05-10 10:01:48,846 azure.storage.common.storageclient INFO  Client-Request-ID=3e9227c0-7302-11e9-af6d-784f43a07631 Receiving Response: Server-Timestamp=Fri, 10 May 2019 09:01:48 GMT, Server-Request-ID=4fda1843-0f8d-438f-b55e-76fac15d2b8a, HTTP Status Code=200, Message=OK, Headers={'server': 'Azurite-Blob/3.0.0-preview', 'last-modified': 'Fri, 10 May 2019 09:01:48 GMT', 'content-length': '12', 'content-type': 'application/octet-stream', 'etag': '"d-dxP9DGQPvSoV2F7aU59hZWs2utQ"', 'content-md5': 'i/qOBoQQj0GZM6WZUmTRUA==', 'x-ms-blob-type': 'BlockBlob', 'x-ms-lease-state': 'available', 'x-ms-lease-status': 'unlocked', 'x-ms-request-id': '4fda1843-0f8d-438f-b55e-76fac15d2b8a', 'x-ms-version': '2018-03-28', 'date': 'Fri, 10 May 2019 09:01:48 GMT', 'x-ms-server-encrypted': 'true', 'x-ms-blob-content-md5': 'i/qOBoQQj0GZM6WZUmTRUA==', 'connection': 'keep-alive'}.
```

v2:
```
2019-05-10 10:04:09,847 azure.storage.common.storageclient INFO  Client-Request-ID=929e09ba-7302-11e9-a0fb-784f43a07631 Outgoing request: Method=GET, Path=/devstoreaccount1/azurite-test/test-file, Query={'snapshot': None, 'timeout': None}, Headers={'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-range': 'bytes=0-33554431', 'x-ms-version': '2018-03-28', 'User-Agent': 'Azure-Storage/1.4.0-1.5.0 (Python CPython 3.6.5; Darwin 18.5.0)', 'x-ms-client-request-id': '929e09ba-7302-11e9-a0fb-784f43a07631', 'x-ms-date': 'Fri, 10 May 2019 09:04:09 GMT', 'Authorization': 'REDACTED'}.
2019-05-10 10:04:09,889 azure.storage.common.storageclient INFO  Client-Request-ID=929e09ba-7302-11e9-a0fb-784f43a07631 Receiving Response: Server-Timestamp=Fri, 10 May 2019 09:04:09 GMT, Server-Request-ID=929f19e0-7302-11e9-807d-4be07f999011, HTTP Status Code=206, Message=Partial Content, Headers={'x-powered-by': 'Express', 'etag': '"fBzubJ9aKoZwfiQ6EhBudBXCn3I"', 'last-modified': 'Fri, 10 May 2019 09:04:09 GMT', 'x-ms-version': '2017-07-29', 'date': 'Fri, 10 May 2019 09:04:09 GMT', 'content-length': '12', 'x-ms-request-id': '929f19e0-7302-11e9-807d-4be07f999011', 'accept-ranges': 'bytes', 'x-ms-blob-type': 'BlockBlob', 'x-ms-request-server-encrypted': 'false', 'content-type': 'application/octet-stream', 'x-ms-blob-content-md5': 'undefined', 'content-range': 'bytes 0-11/12', 'connection': 'keep-alive'}.
```

**Comment by XiaoningLiu** [comment]
I can reproduce this issue on Python 3.7.3. 

Python V2 doesn't have this issue. As I'm not familiar with Python, it's kind of difficulty to debug into Python SDK.

**Comment by tomhosking** [comment]
Comparing the two logs, it looks like v3 doesn't include the `content-range` header - this is used [here in the python module](https://github.com/Azure/azure-storage-python/blob/b8c5c9a1bc73065fd015c0fec75617cef263c6ee/azure-storage-blob/azure/storage/blob/baseblobservice.py#L2128) to extract the blob size. This would fit with the python error:
```
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_download_chunking.py", line 84, in get_chunk_offsets
    while index < self.blob_end:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

I'm not sure why this works OK in python 2.7, though.

**Comment by XiaoningLiu** [comment]
Thanks for debugging! That's very interesting. I get the root cause. 

For V3, when `GET BLOB` request requires to download the **full blob**, it doesn't return `content-range` header, which leads to Python SDK error. While other SDKs like Node.js or .Net doesn't depend on this response header. 

We can fix this by always return `content-range` header when request includes a `ranges` or `x-ms-ranges` headers which fits REST API spec. https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob

**Comment by XiaoningLiu** [comment]
Should add `content-range` response header in here https://github.com/Azure/Azurite/blob/6e64127f22f0208701f0ba7cca82149fa9dbd648/src/blob/handlers/BlobHandler.ts#L1361

**Comment by XiaoningLiu** [comment]
That should be resolved, thanks to @pjknkda

**Comment by tomhosking** [comment]
Confirmed as fixed. Took me a while to check as I'm having some other issues!

**Comment by efiop** [comment]
Could you please release a new version (preview is fine too) with this fix? :pray: :slightly_smiling_face:

**Comment by XiaoningLiu** [comment]
@efiop Azurite V3 planed a release this week, in V3, Azurite got it's new designed logo (we spent some time for the designing) and will be published in to Visual Studio Code Extension market and docker hub as well.

**Comment by efiop** [comment]
@XiaoningLiu Looking forward to it! 🎉 Thank you!
