### ISSUE TITLE
The specifed resource name contains invalid characters.

### ISSUE THREAD

**Issue by yiqing-zhao** [Azure/Azurite#2152]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.26.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
18.17.1

### What problem was encountered?
```
RestError: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code/>
  <Message>The specifed resource name contains invalid characters.
RequestId:7d4633f4-6506-4e13-8eaf-399a0a0d1ddc
Time:2023-09-05T07:47:29.401Z</Message>
</Error>
    at handleErrorResponse (...\node_modules\@azure\core-client\dist\index.js:1312:19)
    at deserializeResponseBody (...\node_modules\@azure\core-client\dist\index.js:1247:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GeneratedClient.sendOperationRequest (...\node_modules\@azure\core-client\dist\index.js:1948:33)
    at async Object.withSpan (...\node_modules\@azure\core-tracing\dist\index.js:140:28) {name: 'RestError', code: undefined, statusCode: 400, request: PipelineRequestImpl, response: {…}, …}
```

### Steps to reproduce the issue?
```ts
this.client = TableClient.fromConnectionString(
"DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;",
  "table-name",
  { allowInsecureConnection: true }
   const task = {
    partitionKey: this.hash(key),
    rowKey: key,
    ...extractKeyDataFromConversationReference(reference),
  };
  try {
    await this.client.createEntity(task);
    return true;
  } catch (e: unknown) {
    return false;
  }
);
```

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
2023-09-05T07:47:29.351Z 434b194f-83b3-4d8d-8532-863f87f93717 info: Serializer: Start returning stream body.
2023-09-05T07:47:29.351Z 434b194f-83b3-4d8d-8532-863f87f93717 info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=200 StatusMessage=OK Headers={"server":"Azurite-Queue/3.26.0","x-ms-client-request-id":"13283618-d9e4-4a3a-a49c-f771e6c0322b","x-ms-request-id":"434b194f-83b3-4d8d-8532-863f87f93717","x-ms-version":"2023-08-03","date":"Tue, 05 Sep 2023 07:47:29 GMT","content-type":"application/xml"}
2023-09-05T07:47:29.400Z 7d4633f4-6506-4e13-8eaf-399a0a0d1ddc info: TableStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/table-name RequestHeaders:{"content-type":"application/json;odata=nometadata","accept":"application/json;odata=minimalmetadata","x-ms-version":"2019-02-02","dataserviceversion":"3.0","prefer":"return-no-content","accept-encoding":"gzip,deflate","user-agent":"azsdk-js-data-tables/13.1.2 core-rest-pipeline/1.12.0 Node/v18.17.1 OS/(x64-Windows_NT-10.0.22621)","x-ms-client-request-id":"034d5591-8ec2-4375-bf18-8ff4d58e6c6d","x-ms-date":"Tue, 05 Sep 2023 07:47:29 GMT","content-length":"590","authorization":"SharedKeyLite devstoreaccount1:W/3YmOB0JIQDXIYVxKdEe+trwRtYXAbc4w2xuMtU5QE=","host":"127.0.0.1:10002","connection":"keep-alive"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2023-09-05T07:47:29.400Z 7d4633f4-6506-4e13-8eaf-399a0a0d1ddc debug: tableStorageContextMiddleware: Dispatch pattern string: /table-name
2023-09-05T07:47:29.401Z 7d4633f4-6506-4e13-8eaf-399a0a0d1ddc error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2023-09-05T07:47:29.401Z 7d4633f4-6506-4e13-8eaf-399a0a0d1ddc error: ErrorMiddleware: ErrorName=StorageError ErrorMessage="The specifed resource name contains invalid characters."  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"","x-ms-request-id":"7d4633f4-6506-4e13-8eaf-399a0a0d1ddc","x-ms-version":"2023-08-03"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code/>\n  <Message>The specifed resource name contains invalid characters.\nRequestId:7d4633f4-6506-4e13-8eaf-399a0a0d1ddc\nTime:2023-09-05T07:47:29.401Z</Message>\n</Error>" ErrorStack="\"StorageError: The specifed resource name contains invalid characters.\\n    at StorageErrorFactory.getInvalidResourceName (...\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\errors\\\\StorageErrorFactory.js:82:16)\\n    at validateTableName (...\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\utils\\\\utils.js:153:45)\\n    at tableStorageContextMiddleware (...\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\middleware\\\\tableStorageContext.middleware.js:121:39)\\n    at ...\\\\node_modules\\\\azurite\\\\dist\\\\src\\\\table\\\\middleware\\\\tableStorageContext.middleware.js:14:16\\n    at Layer.handle [as handle_request] (...\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at trim_prefix (...\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:328:13)\\n    at ...\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:286:9\\n    at Function.process_params (...\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:346:12)\\n    at next (...\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:280:10)\\n    at expressInit (...\\\\node_modules\\\\express\\\\lib\\\\middleware\\\\init.js:40:5)\""
2023-09-05T07:47:29.401Z 7d4633f4-6506-4e13-8eaf-399a0a0d1ddc error: ErrorMiddleware: Set HTTP code: 400
2023-09-05T07:47:29.401Z 7d4633f4-6506-4e13-8eaf-399a0a0d1ddc error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=7d4633f4-6506-4e13-8eaf-399a0a0d1ddc
2023-09-05T07:47:29.402Z 7d4633f4-6506-4e13-8eaf-399a0a0d1ddc error: ErrorMiddleware: Set HTTP Header: x-ms-version=2023-08-03
2023-09-05T07:47:29.402Z 7d4633f4-6506-4e13-8eaf-399a0a0d1ddc error: ErrorMiddleware: Set content type: application/xml
2023-09-05T07:47:29.402Z 7d4633f4-6506-4e13-8eaf-399a0a0d1ddc error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code/>\n  <Message>The specifed resource name contains invalid characters.\nRequestId:7d4633f4-6506-4e13-8eaf-399a0a0d1ddc\nTime:2023-09-05T07:47:29.401Z</Message>\n</Error>"
2023-09-05T07:47:29.402Z 7d4633f4-6506-4e13-8eaf-399a0a0d1ddc info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=400 StatusMessage=Bad Request Headers={"server":"Azurite-Table/3.26.0","x-ms-request-id":"7d4633f4-6506-4e13-8eaf-399a0a0d1ddc","x-ms-version":"2023-08-03","content-type":"application/xml"}
2023-09-05T07:47:30.705Z 13378412-2bd6-4795-94d8-ecf2e01e7bbe info: QueueStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/testhubname-control-03/messages?numofmessages=32&visibilitytimeout=300 RequestHeaders:{"host":"127.0.0.1:10001","x-ms-client-request-id":"e9b5709f-0cff-48f9-b2cc-365c90a09ee5","user-agent":"Azure-Storage/9.3.1 (.NET Core)","x-ms-version":"2018-03-28","x-ms-date":"Tue, 05 Sep 2023 07:47:30 GMT","authorization":"SharedKey devstoreaccount1:CfPJ7bkRol4vXRszYDA1pGyWdOS4Q/8gAqKSFS78+SA="} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2023-09-05T07:47:30.706Z 13378412-2bd6-4795-94d8-ecf2e01e7bbe info: QueueStorageContextMiddleware: Account=devstoreaccount1 Queue=testhubname-control-03 Message=messages MessageId=undefined
2023-09-05T07:47:30.706Z 13378412-2bd6-4795-94d8-ecf2e01e7bbe verbose: DispatchMiddleware: Dispatching request...
2023-09-05T07:47:30.706Z 13378412-2bd6-4795-94d8-ecf2e01e7bbe info: DispatchMiddleware: Operation=Messages_Dequeue
2023-09-05T07:47:30.706Z 13378412-2bd6-4795-94d8-ecf2e01e7bbe verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2023-09-05T07:47:30.706Z 13378412-2bd6-4795-94d8-ecf2e01e7bbe info: QueueSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2023-09-05T07:47:30.706Z 13378412-2bd6-4795-94d8-ecf2e01e7bbe info: QueueSharedKeyAuthenticator:validate() [STRING TO SIGN]:"GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:e9b5709f-0cff-48f9-b2cc-365c90a09ee5\nx-ms-date:Tue, 05 Sep 2023 07:47:30 GMT\nx-ms-version:2018-03-28\n/devstoreaccount1/devstoreaccount1/testhubname-control-03/messages\nnumofmessages:32\nvisibilitytimeout:300"
2023-09-05T07:47:30.706Z 13378412-2bd6-4795-94d8-ecf2e01e7bbe info: QueueSharedKeyAuthenticator:validate() Calculated authentication header based on key1: devstoreaccount1:CfPJ7bkRol4vXRszYDA1pGyWdOS4Q/8gAqKSFS78+SA=
2023-09-05T07:47:30.706Z 13378412-2bd6-4795-94d8-ecf2e01e7bbe info: QueueSharedKeyAuthenticator:validate() Signature 1 matched.
2023-09-05T07:47:30.706Z 13378412-2bd6-4795-94d8-ecf2e01e7bbe verbose: DeserializerMiddleware: Start deserializing...
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
It is a little wierd that the request URL is `RequestURL=http://127.0.0.1/devstoreaccount1/table-name`, but the dispatch pattern string is `/table-name`. Is there a way to avoid this happening? I follow the guide [here](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=npm#azure-table-storage) to create the table client.

**Comment by blueww** [comment]
@yiqing-zhao 

"table-name" is not a valid storage table name. The valid name should start with a letter and is followed by letters or numbers and is 3 through 63 characters long. Like "tablename".

Would you please retry with a valid table name?

**Comment by yiqing-zhao** [comment]
Hi @blueww, I changed the `table-name` to `tablename`, and received 
```
RestError: {"odata.error":{"code":"TableNotFound","message":{"lang":"en-US","value":"The table specified does not exist.\nRequestId:164b7b29-90a6-450c-8dc5-6024fab4fdc6\nTime:2023-09-06T03:59:44.162Z"}}}
    at handleErrorResponse (C:\Users\yiqingzhao\TeamsApps\large-scale-notification_3\node_modules\@azure\core-client\dist\index.js:1312:19)
    at deserializeResponseBody (C:\Users\yiqingzhao\TeamsApps\large-scale-notification_3\node_modules\@azure\core-client\dist\index.js:1247:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {name: 'RestError', code: undefined, statusCode: 404, request: PipelineRequestImpl, response: {…}, …}
```

BTW, I've tried to connect to blob container with `container-name`, and it works fine.
```ts
this.client = new ContainerClient(
  "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpo  int=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;", 
  "container-name"
);
```

**Comment by yiqing-zhao** [comment]
Hi @blueww , after creating the table `tablename` in Azure Storage Explorer, the app works fine. However, I've noticed that the local storage emulator did not show the data and the table.
![image](https://github.com/Azure/Azurite/assets/45935381/19136100-2224-4175-87bc-451bbb95453d)

I started Azurite as follows:
```
azurite --silent --location ./_storage_emulator --debug ./_storage_emulator/debug.log
```

It would help me a lot if you could kindly answer my questions:
1) Is there a way to show the table locally (show the table in the folder `_storage_emulator`)?
2) Is there a way to create the table by command line instead of creating in the Azure Storage Explorer?

Thanks in advance!

**Comment by blueww** [comment]
@yiqing-zhao 
The table and the data files are not 1:1 match. Azurite has it's own format to save the data to local (or to sql). So you don't see every table name in the local data file.
So to answer your questions:
1. No, you need to use storage rest API to list/get table and see table name
2. This question is actually out of Azurite scope, it's about storage rest API usage. If you would like to use command line to create table, you can use [Azure CLI ](https://learn.microsoft.com/en-us/cli/azure/storage/table?view=azure-cli-latest#az-storage-table-create )or [Azure Powershell](https://learn.microsoft.com/en-us/powershell/module/az.storage/new-azstoragetable) to create table.

**Comment by yiqing-zhao** [comment]
Thanks @blueww for your clarification. This resolves my confusion!
