### ISSUE TITLE
Exception read DownloadResponse info.eTag on blob download

### ISSUE THREAD

**Issue by marcoMobilab** [Azure/Azurite#217]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
[6e64127](https://github.com/Azure/Azurite/commit/6e64127f22f0208701f0ba7cca82149fa9dbd648) (Azurite v3.0.0-preview)
Azurite 2.6.5

### Which version of the SDK was used?
azure-storage-blob 11.0.0 (azure-sdk-for-java)

### What problem was encountered?
The following exception is thrown from azure-storage-blob client on blob download:

```
java.lang.IllegalArgumentException: The argument must not be null or an empty string. Argument name: info.eTag.
	at com.microsoft.azure.storage.blob.Utility.assertNotNull(Utility.java:77) ~[azure-storage-blob-11.0.0.jar!/:na]
	at com.microsoft.azure.storage.blob.DownloadResponse.<init>(DownloadResponse.java:56) ~[azure-storage-blob-11.0.0.jar!/:na]
	at com.microsoft.azure.storage.blob.BlobURL.lambda$0(BlobURL.java:369) ~[azure-storage-blob-11.0.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onSuccess(SingleResumeNext.java:65) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onSuccess(MaybeToSingle.java:83) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:89) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.maybe.MaybeJust.subscribeActual(MaybeJust.java:36) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Maybe.subscribe(Maybe.java:4156) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Maybe.subscribe(Maybe.java:4156) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Single.subscribe(Single.java:3394) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Single.subscribe(Single.java:3394) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onSuccess(SingleResumeNext.java:65) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Single.subscribe(Single.java:3394) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.onSuccess(SingleTimeout.java:133) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:59) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.Single.subscribe(Single.java:3394) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:59) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52) ~[rxjava-2.2.0.jar!/:na]
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68) ~[rxjava-2.2.0.jar!/:na]
	at com.microsoft.rest.v2.http.NettyClient$HttpClientInboundHandler.channelRead(NettyClient.java:918) ~[client-runtime-2.1.0.jar!/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.28.Final.jar!/:4.1.28.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

### Steps to reproduce the issue?
1) Create a container
2) Create a blob into the container
3) Run a Java application with the following code:
```
public void read(String containerName, String blobName) {
    ContainerURL containerURL = serviceURL.createContainerURL(containerName);
    BlobURL blobURL = containerURL.createBlobURL(blobName);
    Throwable throwable = blobURL.download().flatMapCompletable(
        stream -> writeToSystemOut(stream.body(null)))
        .blockingGet();
}

public Completable writeToSystemOut(Flowable<ByteBuffer> content) {
    return Completable.create(
        emitter -> {
            content.subscribe(new BasicFlowableSubscriber(emitter));
        });
}

public class BasicFlowableSubscriber implements FlowableSubscriber<ByteBuffer> {
    private final CompletableEmitter emitter;
    private Subscription subscription;

    public BasicFlowableSubscriber(CompletableEmitter emitter) {
        this.emitter = emitter;
    }

    @Override
    public void onSubscribe(Subscription subscription) {
        this.subscription = subscription;
        subscription.request(1);
    }

    @Override
    public void onNext(ByteBuffer byteBuffer) {
        String value = StandardCharsets.UTF_8.decode(byteBuffer).toString();
        System.out.println(value);
    }

    @Override
    public void onError(Throwable t) {
        subscription.cancel();
        emitter.onError(t);
    }

    @Override
    public void onComplete() {
        emitter.onComplete();
    }
}
```

### Have you found a mitigation/solution?
no

**Comment by XiaoningLiu** [comment]
@marcoMobilab can you share `debug.log` generated by Azurite?

**Comment by marcoMobilab** [comment]
@XiaoningLiu  the following is the generated debug.log by Azurite:
[debug.log](https://github.com/Azure/Azurite/files/3189139/debug.log)

**Comment by XiaoningLiu** [comment]
Interesting. Looks Azurite responses blob download successfully, including the `etag` header. Need further investigation. I'm wondering whether Java SDK try to parser `eTag` case sensitively. In the mean tie, can you open an issue to Java SDK repo for further investigation?

2019-05-16T21:44:11.903Z fb47ab44-93ee-44e2-8957-12d362e66590 info: EndMiddleware: End response. TotalTimeInMS=8 StatusCode=200 StatusMessage=OK Headers={"server":"Azurite-Blob/3.0.0-preview","last-modified":"Thu, 16 May 2019 21:43:54 GMT","content-length":"12","content-type":"application/xml; charset=utf-8","etag":"\"d-iqfmJ9C2M4m37gJkMz3L+A5KN4s\"","content-md5":"lHP90NiApDwht3eNNIchVw==","x-ms-blob-type":"BlockBlob","x-ms-request-id":"fb47ab44-93ee-44e2-8957-12d362e66590","x-ms-version":"2018-03-28","date":"Thu, 16 May 2019 21:44:11 GMT","x-ms-server-encrypted":"true"}

**Comment by rickle-msft** [comment]
@XiaoningLiu any update on this? From my understanding, Azurite should mimic the service pretty exactly and should have the correct casing for the ETag header.

**Comment by XiaoningLiu** [comment]
Hi @rickle-msft HTTP header names are case-insensitive, according to RFC 2616. It's not guarantted the header value are case sensitive in different implementations of HTTP clients, servers or even browsers. We'd better not rely on header cases. For example, firefox will not keep the original header case when receiving HTTP responses. So protocol layer of JS track2 SDK will parser headers case-insensitive. As Azurite leverages typescript autorest generator too, the protocol layer code has the similiar behavior.

**Comment by amolyneaux** [comment]
Hi, This is unfortunately a blocker for us - tested that rewriting the case of the headers in a proxy makes it work, but that is not feasible for us.

**Comment by rickle-msft** [comment]
@amolyneaux @marcoMobilab Can I suggest you guys move away from v11, either to v8 or v12? We have not had this issue reported in v8, which is much more mature, so I hope that you won't hit this issue there, and a quick look at the code in the v12 preview suggests that the headers are case insensitive there.

We are generally suggesting people pause development in v11 because of some stability issues, so I am hoping either v8 or v12 preview will be able to unblock you guys.

**Comment by jfgosselin** [comment]
Did anyone successfully use v12 with Azurite ?

I can't use http://127.0.0.1:10000/devstoreaccount1 because it's stripped by the BlobServiceClientBuilder ...

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceClientBuilder.java#L76

**Comment by XiaoningLiu** [comment]
@jfgosselin @rickle-msft  Does V12 provides way to build a customized url?

**Comment by andreaturli** [comment]
> Interesting. Azurite responses blob download successfully, including the `etag` header. Need further investigation. I'm wondering whether Java SDK try to parser `eTag` case sensitively. In the mean time, can you open an issue to Java SDK repo for further investigation?

I'm using `12.0.0-preview.3` and I have a different experience targeting `docker run -p 10000:10000 -p 10001:10001 mcr.microsoft.com/azure-storage/azurite:3.2.0-preview`

I get the following error when downloading the blob
```
GET /devstoreaccount1/test/test-1569948524676 HTTP/1.1
host: 127.0.0.1:10000
accept: */*
Date: Tue, 01 Oct 2019 16:48:45 GMT
x-ms-version: 2019-02-02
Authorization: SharedKey devstoreaccount1:xr11ejuDYsLobb/kI83E1+gIQkYtV+zMRwid1DfN79Y=
x-ms-client-request-id: 039b354b-80cf-4b44-bc0d-e47e1e1f1480
User-Agent: azsdk-java-azure-storage-blob/12.0.0-preview.3 1.8.0_191; Mac OS X 10.14.6
content-length: 0
18:48:45.325 [reactor-http-nio-4] DEBUG reactor.netty.resources.PooledConnectionProvider - [id: 0xe158c349, L:/127.0.0.1:64039 - R:/127.0.0.1:10000] onStateChange(GET{uri=/devstoreaccount1/test/test-1569948524676, connection=PooledConnection{channel=[id: 0xe158c349, L:/127.0.0.1:64039 - R:/127.0.0.1:10000]}}, [request_sent])
18:48:45.331 [reactor-http-nio-4] DEBUG reactor.netty.http.client.HttpClientOperations - [id: 0xe158c349, L:/127.0.0.1:64039 - R:/127.0.0.1:10000] Received response (auto-read:false) : [Server=Azurite-Blob/3.2.0-preview, last-modified=Tue, 01 Oct 2019 16:48:45 GMT, content-length=7, content-type=application/octet-stream, etag="d-cfoA5+AI4IJNKKh5FiUc3RW1s0A", content-md5=bvkWG5AGMmcQIjWCFsff5w==, x-ms-blob-type=BlockBlob, x-ms-lease-state=available, x-ms-lease-status=unlocked, x-ms-request-id=6727af15-2d33-43b7-98d9-74d123927158, x-ms-version=2018-03-28, date=Tue, 01 Oct 2019 16:48:45 GMT, x-ms-server-encrypted=true, x-ms-blob-content-md5=bvkWG5AGMmcQIjWCFsff5w==, Connection=keep-alive]
18:48:45.331 [reactor-http-nio-4] DEBUG reactor.netty.resources.PooledConnectionProvider - [id: 0xe158c349, L:/127.0.0.1:64039 - R:/127.0.0.1:10000] onStateChange(GET{uri=/devstoreaccount1/test/test-1569948524676, connection=PooledConnection{channel=[id: 0xe158c349, L:/127.0.0.1:64039 - R:/127.0.0.1:10000]}}, [response_received])
Exception in thread "main" java.lang.IllegalArgumentException: The argument must not be null or an empty string. Argument name: info.eTag.
	at com.azure.storage.common.Utility.assertNotNull(Utility.java:284)
	at com.azure.storage.blob.DownloadAsyncResponse.<init>(DownloadAsyncResponse.java:47)
	at com.azure.storage.blob.BlobAsyncClient.lambda$18(BlobAsyncClient.java:494)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1515)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2071)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1879)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1753)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:159)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1515)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1515)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionMainSubscriber.onNext(FluxDelaySubscription.java:179)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:89)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:173)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1515)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1515)
	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:296)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1515)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2073)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:140)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:178)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onNext(FluxRetryPredicate.java:81)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
	at reactor.netty.http.client.HttpClientConnect$HttpObserver.onStateChange(HttpClientConnect.java:383)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:501)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:443)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:483)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:141)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1494)
		at com.azure.storage.common.Utility.blockWithOptionalTimeout(Utility.java:241)
		at com.azure.storage.blob.BlobClient.downloadWithResponse(BlobClient.java:388)
		at com.azure.storage.blob.BlobClient.download(BlobClient.java:349)
```

Following the code with the debugger I can tell `BlobDownloadResponse#statusCode` is `200`, it contains the header `etag` but then `BlobDownloadHeaders` tries to parse it using

```
    @JsonProperty(value = "ETag")
    private String eTag;
```

returning `null`

**Comment by Brico87** [comment]
Hi all, I saw that the issue [#5623](https://github.com/Azure/azure-sdk-for-java/issues/5623) has been closed and the bug fixed. It has been merged on master branch 2 days ago. Do we need to wait for the release of the preview.5 version of the SDK in order to get rid of this bug ?
Do you have a workaround to make this work otherwise ? Thanks.

**Comment by XiaoningLiu** [comment]
preview.5 is planned by the end of Oct. Please goto Java repo issue for detailed schedule.

**Comment by XiaoningLiu** [comment]
Will close this issue.
