### ISSUE TITLE
OPERATION_ACCOUNT_SAS_PERMISSIONS doesn't have configuration for operation BlockBlob_PutBlobFromUrl

### ISSUE THREAD

**Issue by Akinzekeel** [Azure/Azurite#2226]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
3.26.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
20.8.0

### What problem was encountered?
Copying from an Azure Blob storage to Azurite does not work as expected. Azurite responds with HTTP 500 errors and does not properly store the blobs.

### Steps to reproduce the issue?
```
npm i -g azurite
mkdir /home/myuser/azurite
azurite-blob -l /home/myuser/azurite --debug /home/myuser/azurite-debug.log
azcopy cp 'https://myaccount.blob.core.windows.net/?sv=(rest of the SAS token here)' 'http://127.0.0.1:10000/devstoreaccount1/?sv=(rest of the Azurite SAS token here - all permissions included)' --recursive=true --from-to BlobBlob
```

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
2023-10-14T16:31:57.569Z d5b4b6e6-51a5-4cbf-83d3-23e35f462b48 error: ErrorMiddleware: ErrorName=Error ErrorMessage=AccountSASAuthenticator:validate() OPERATION_ACCOUNT_SAS_PERMISSIONS doesn't have configuration for operation BlockBlob_PutBlobFromUrl's account SAS permission. ErrorStack="Error: AccountSASAuthenticator:validate() OPERATION_ACCOUNT_SAS_PERMISSIONS doesn't have configuration for operation BlockBlob_PutBlobFromUrl's account SAS permission.\n    at AccountSASAuthenticator.validate (/usr/lib/node_modules/azurite/dist/src/blob/authentication/AccountSASAuthenticator.js:99:19)\n    at AuthenticationMiddlewareFactory.authenticate (/usr/lib/node_modules/azurite/dist/src/blob/middlewares/AuthenticationMiddlewareFactory.js:35:40)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
2023-10-14T16:31:57.569Z d5b4b6e6-51a5-4cbf-83d3-23e35f462b48 error: ErrorMiddleware: Set HTTP code: 500
2023-10-14T16:31:57.569Z d5b4b6e6-51a5-4cbf-83d3-23e35f462b48 info: EndMiddleware: End response. TotalTimeInMS=3 StatusCode=500 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.26.0"}
2023-10-14T16:32:00.752Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/assets/fonts/NaPecZTIAOhVxoMyOr9n_E7fdM3mDbRS.woff2?se=2023-10-20T12%3A37%3A00Z&sig=UE8diC4XK%2FORndQtgnYnJ7xCyd18UsYfTnRGIH8RPW4%3D&sp=rwdxftlacup&spr=https%2Chttp&srt=sco&ss=b&st=2023-10-14T12%3A37%3A21Z&sv=2021-10-04&timeout=901 RequestHeaders:{"host":"127.0.0.1:10000","user-agent":"AzCopy/10.20.1 Azure-Storage/0.15 (go1.21.3; linux)","content-length":"0","x-ms-access-tier":"Hot","x-ms-blob-cache-control":"","x-ms-blob-content-disposition":"","x-ms-blob-content-encoding":"","x-ms-blob-content-language":"","x-ms-blob-content-type":"font/woff2","x-ms-blob-type":"BlockBlob","x-ms-client-request-id":"0a478eec-64bf-4362-6010-459ab1de25c1","x-ms-copy-source":"(redacted for safety reasons)","x-ms-version":"2020-10-02"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2023-10-14T16:32:00.752Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=assets Blob=fonts/NaPecZTIAOhVxoMyOr9n_E7fdM3mDbRS.woff2
2023-10-14T16:32:00.752Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 verbose: DispatchMiddleware: Dispatching request...
2023-10-14T16:32:00.753Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: DispatchMiddleware: Operation=BlockBlob_PutBlobFromUrl
2023-10-14T16:32:00.753Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2023-10-14T16:32:00.753Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: PublicAccessAuthenticator:validate() Start validation against public access.
2023-10-14T16:32:00.753Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 debug: PublicAccessAuthenticator:validate() Getting account properties...
2023-10-14T16:32:00.753Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: assets, blob: fonts/NaPecZTIAOhVxoMyOr9n_E7fdM3mDbRS.woff2
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container assets
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: BlobSharedKeyAuthenticator:validate() Request doesn't include valid authentication header. Skip shared key authentication.
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: AccountSASAuthenticator:validate() Start validation against account Shared Access Signature pattern.
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 debug: AccountSASAuthenticator:validate() Getting account properties...
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 debug: AccountSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: assets, blob: fonts/NaPecZTIAOhVxoMyOr9n_E7fdM3mDbRS.woff2
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 debug: AccountSASAuthenticator:validate() Got account properties successfully.
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 debug: AccountSASAuthenticator:validate() Retrieved signature from URL parameter sig: UE8diC4XK/ORndQtgnYnJ7xCyd18UsYfTnRGIH8RPW4=
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 debug: AccountSASAuthenticator:validate() Successfully got valid account SAS values from request. {"version":"2021-10-04","protocol":"https,http","startTime":"2023-10-14T12:37:21Z","expiryTime":"2023-10-20T12:37:00Z","permissions":"rwdxftlacup","services":"b","resourceTypes":"sco"}
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: AccountSASAuthenticator:validate() Validate signature based account key1.
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 debug: AccountSASAuthenticator:validate() String to sign is: "devstoreaccount1\nrwdxftlacup\nb\nsco\n2023-10-14T12:37:21Z\n2023-10-20T12:37:00Z\n\nhttps,http\n2021-10-04\n\n"
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 debug: AccountSASAuthenticator:validate() Calculated signature is: UE8diC4XK/ORndQtgnYnJ7xCyd18UsYfTnRGIH8RPW4=
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: AccountSASAuthenticator:validate() Signature based on key1 validation passed.
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: AccountSASAuthenticator:validate() Validate start and expiry time.
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: AccountSASAuthenticator:validate() Validate IP range.
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: AccountSASAuthenticator:validate() Validate request protocol.
2023-10-14T16:32:00.754Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 debug: AccountSASAuthenticator:validate() Got permission requirements for operation BlockBlob_PutBlobFromUrl - undefined
2023-10-14T16:32:00.755Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 error: ErrorMiddleware: Received an error, fill error information to HTTP response
2023-10-14T16:32:00.755Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 error: ErrorMiddleware: ErrorName=Error ErrorMessage=AccountSASAuthenticator:validate() OPERATION_ACCOUNT_SAS_PERMISSIONS doesn't have configuration for operation BlockBlob_PutBlobFromUrl's account SAS permission. ErrorStack="Error: AccountSASAuthenticator:validate() OPERATION_ACCOUNT_SAS_PERMISSIONS doesn't have configuration for operation BlockBlob_PutBlobFromUrl's account SAS permission.\n    at AccountSASAuthenticator.validate (/usr/lib/node_modules/azurite/dist/src/blob/authentication/AccountSASAuthenticator.js:99:19)\n    at AuthenticationMiddlewareFactory.authenticate (/usr/lib/node_modules/azurite/dist/src/blob/middlewares/AuthenticationMiddlewareFactory.js:35:40)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
2023-10-14T16:32:00.755Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 error: ErrorMiddleware: Set HTTP code: 500
2023-10-14T16:32:00.755Z 5dabd4df-36f3-42fa-b8f2-378b3f9abd80 info: EndMiddleware: End response. TotalTimeInMS=3 StatusCode=500 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.26.0"}
2023-10-14T16:32:02.944Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/assets/fonts/NaPDcZTIAOhVxoMyOr9n_E7ffGjEGItzYw.woff2?se=2023-10-20T12%3A37%3A00Z&sig=UE8diC4XK%2FORndQtgnYnJ7xCyd18UsYfTnRGIH8RPW4%3D&sp=rwdxftlacup&spr=https%2Chttp&srt=sco&ss=b&st=2023-10-14T12%3A37%3A21Z&sv=2021-10-04&timeout=901 RequestHeaders:{"host":"127.0.0.1:10000","user-agent":"AzCopy/10.20.1 Azure-Storage/0.15 (go1.21.3; linux)","content-length":"0","x-ms-access-tier":"Hot","x-ms-blob-cache-control":"","x-ms-blob-content-disposition":"","x-ms-blob-content-encoding":"","x-ms-blob-content-language":"","x-ms-blob-content-type":"font/woff2","x-ms-blob-type":"BlockBlob","x-ms-client-request-id":"0cf99683-1f18-49e2-76a0-a1355d0495e9","x-ms-copy-source":"(redacted for safety reasons)","x-ms-version":"2020-10-02"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2023-10-14T16:32:02.945Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=assets Blob=fonts/NaPDcZTIAOhVxoMyOr9n_E7ffGjEGItzYw.woff2
2023-10-14T16:32:02.945Z 60b6ba54-805e-4642-bb70-58c56c6ad20e verbose: DispatchMiddleware: Dispatching request...
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: DispatchMiddleware: Operation=BlockBlob_PutBlobFromUrl
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: PublicAccessAuthenticator:validate() Start validation against public access.
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e debug: PublicAccessAuthenticator:validate() Getting account properties...
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: assets, blob: fonts/NaPDcZTIAOhVxoMyOr9n_E7ffGjEGItzYw.woff2
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container assets
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: BlobSharedKeyAuthenticator:validate() Request doesn't include valid authentication header. Skip shared key authentication.
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: AccountSASAuthenticator:validate() Start validation against account Shared Access Signature pattern.
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e debug: AccountSASAuthenticator:validate() Getting account properties...
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e debug: AccountSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: assets, blob: fonts/NaPDcZTIAOhVxoMyOr9n_E7ffGjEGItzYw.woff2
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e debug: AccountSASAuthenticator:validate() Got account properties successfully.
2023-10-14T16:32:02.946Z 60b6ba54-805e-4642-bb70-58c56c6ad20e debug: AccountSASAuthenticator:validate() Retrieved signature from URL parameter sig: UE8diC4XK/ORndQtgnYnJ7xCyd18UsYfTnRGIH8RPW4=
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e debug: AccountSASAuthenticator:validate() Successfully got valid account SAS values from request. {"version":"2021-10-04","protocol":"https,http","startTime":"2023-10-14T12:37:21Z","expiryTime":"2023-10-20T12:37:00Z","permissions":"rwdxftlacup","services":"b","resourceTypes":"sco"}
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: AccountSASAuthenticator:validate() Validate signature based account key1.
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e debug: AccountSASAuthenticator:validate() String to sign is: "devstoreaccount1\nrwdxftlacup\nb\nsco\n2023-10-14T12:37:21Z\n2023-10-20T12:37:00Z\n\nhttps,http\n2021-10-04\n\n"
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e debug: AccountSASAuthenticator:validate() Calculated signature is: UE8diC4XK/ORndQtgnYnJ7xCyd18UsYfTnRGIH8RPW4=
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: AccountSASAuthenticator:validate() Signature based on key1 validation passed.
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: AccountSASAuthenticator:validate() Validate start and expiry time.
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: AccountSASAuthenticator:validate() Validate IP range.
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: AccountSASAuthenticator:validate() Validate request protocol.
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e debug: AccountSASAuthenticator:validate() Got permission requirements for operation BlockBlob_PutBlobFromUrl - undefined
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e error: ErrorMiddleware: Received an error, fill error information to HTTP response
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e error: ErrorMiddleware: ErrorName=Error ErrorMessage=AccountSASAuthenticator:validate() OPERATION_ACCOUNT_SAS_PERMISSIONS doesn't have configuration for operation BlockBlob_PutBlobFromUrl's account SAS permission. ErrorStack="Error: AccountSASAuthenticator:validate() OPERATION_ACCOUNT_SAS_PERMISSIONS doesn't have configuration for operation BlockBlob_PutBlobFromUrl's account SAS permission.\n    at AccountSASAuthenticator.validate (/usr/lib/node_modules/azurite/dist/src/blob/authentication/AccountSASAuthenticator.js:99:19)\n    at AuthenticationMiddlewareFactory.authenticate (/usr/lib/node_modules/azurite/dist/src/blob/middlewares/AuthenticationMiddlewareFactory.js:35:40)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
2023-10-14T16:32:02.947Z 60b6ba54-805e-4642-bb70-58c56c6ad20e error: ErrorMiddleware: Set HTTP code: 500
2023-10-14T16:32:02.948Z 60b6ba54-805e-4642-bb70-58c56c6ad20e info: EndMiddleware: End response. TotalTimeInMS=4 StatusCode=500 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.26.0"}
```

### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
@Akinzekeel 

This is a known limitation of Azurite: Azurite only support blob copy within same Azurite instance, not support copy from product Azure.
You can find it in Azurite readme.md: https://github.com/Azure/Azurite#:~:text=Copy%20Blob%20From%20URL%20(Only%20supports%20copy%20within%20same%20Azurite%20instance%2C%20only%20on%20Loki)

**Comment by blueww** [comment]
One way is: first download the blobs to local, then upload the blobs to Azurite.

**Comment by Akinzekeel** [comment]
> One way is: first download the blobs to local, then upload the blobs to Azurite.

I have downloaded them to local files now, but as I suspected all the metadata of the blobs are lost in this process.

**Comment by blueww** [comment]
The possible solution might be, write a program (script), when upload a blob, read the metadata from public azure, then upload blob with same metadata to Azurite.

**Comment by Akinzekeel** [comment]
I will consider this approach. Thank you for your help.
