### ISSUE TITLE
Azurite alway return 400 when use sasUrl generate by Azurite

### ISSUE THREAD

**Issue by luyue14** [Azure/Azurite#2391]
### Which service(blob, file, queue, table) does this issue concern?
Blob and file 

### Which version of the Azurite was used?
3.29.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What problem was encountered?
Azurite alway return 400 bad request.
I use the Azure SDK(.net core: Azure.Storage.Files.DataLake SDK) call Azurite, if I use sasUrl which is generated by Storage the code works well, but if I use the sasUrl generate by Azurite, Azurite will return 400.

### Steps to reproduce the issue?
1. start Azurite   azurite -L --skipApiVersionCheck  --silent --location c:\azurite --debug c:\azurite\debug.log
2. Generate sasUrl 

DataLakeSasBuilder builder = new DataLakeSasBuilder();
builder.SetPermissions(DataLakeSasPermissions.All);
builder.ExpiresOn = DateTime.UtcNow.AddDays(1);
builder.Resource = "d"; 
builder.Protocol = SasProtocol.Https;
builder.IsDirectory = true;
Uri uri = client.GenerateSasUri(builder);

3. call Azurite
var client = new DataLakeDirectoryClient(sasUrl, dataLakeClientOptions);
DataLakeFileClient file = client.GetFileClient(path);
file. xxxx

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:
2024-04-24T08:51:20.355Z d2ad1ad1-9e95-4ea9-82c2-6bb448875874 info: HandlerMiddleware: DeserializedParameters={"options":{"metadata":{},"access":"container","requestId":"42f7d644-ba63-4549-9b5d-d5e899e35863","containerCpkScopeInfo":{}},"restype":"container","version":"2023-01-03"}
2024-04-24T08:51:20.356Z d2ad1ad1-9e95-4ea9-82c2-6bb448875874 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2024-04-24T08:51:20.356Z d2ad1ad1-9e95-4ea9-82c2-6bb448875874 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified container already exists.  ErrorHTTPStatusCode=409 ErrorHTTPStatusMessage=The specified container already exists. ErrorHTTPHeaders={"x-ms-error-code":"ContainerAlreadyExists","x-ms-request-id":"d2ad1ad1-9e95-4ea9-82c2-6bb448875874"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:d2ad1ad1-9e95-4ea9-82c2-6bb448875874\nTime:2024-04-24T08:51:20.356Z</Message>\n</Error>" ErrorStack="StorageError: The specified container already exists.\n    at Function.getContainerAlreadyExists (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\errors\\StorageErrorFactory.js:23:16)\n    at LokiBlobMetadataStore.createContainer (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\persistence\\LokiBlobMetadataStore.js:297:49)\n    at ContainerHandler.create (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\handlers\\ContainerHandler.js:44:34)\n    at C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\generated\\middleware\\HandlerMiddlewareFactory.js:58:18\n    at C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\generated\\ExpressMiddlewareFactory.js:78:63\n    at Layer.handle [as handle_request] (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:280:10)"
2024-04-24T08:51:20.356Z d2ad1ad1-9e95-4ea9-82c2-6bb448875874 error: ErrorMiddleware: Set HTTP code: 409
2024-04-24T08:51:20.356Z d2ad1ad1-9e95-4ea9-82c2-6bb448875874 error: ErrorMiddleware: Set HTTP status message: The specified container already exists.
2024-04-24T08:51:20.356Z d2ad1ad1-9e95-4ea9-82c2-6bb448875874 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=ContainerAlreadyExists
2024-04-24T08:51:20.356Z d2ad1ad1-9e95-4ea9-82c2-6bb448875874 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=d2ad1ad1-9e95-4ea9-82c2-6bb448875874
2024-04-24T08:51:20.356Z d2ad1ad1-9e95-4ea9-82c2-6bb448875874 error: ErrorMiddleware: Set content type: application/xml
2024-04-24T08:51:20.356Z d2ad1ad1-9e95-4ea9-82c2-6bb448875874 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:d2ad1ad1-9e95-4ea9-82c2-6bb448875874\nTime:2024-04-24T08:51:20.356Z</Message>\n</Error>"
2024-04-24T08:51:20.356Z d2ad1ad1-9e95-4ea9-82c2-6bb448875874 info: EndMiddleware: End response. TotalTimeInMS=3 StatusCode=409 StatusMessage=The specified container already exists. Headers={"server":"Azurite-Blob/3.29.0","x-ms-error-code":"ContainerAlreadyExists","x-ms-request-id":"d2ad1ad1-9e95-4ea9-82c2-6bb448875874","content-type":"application/xml"}
2024-04-24T08:51:37.871Z 4c638e1a-c673-4a66-ab74-f639b9e872ed info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://devstoreaccount1.blob.localhost/trident-nbs-fs?sv=2023-01-03&spr=https&se=2024-04-25T08%3A51%3A35Z&sr=c&sp=racwdlmeop&sig=xFn8jEk9QbYFdJxEhzqjtHz6gzQ3sAamqWQsLM4Obto%3D&resource=filesystem&directory=&recursive=false&upn=false RequestHeaders:{"host":"devstoreaccount1.blob.localhost:10000","x-ms-version":"2023-01-03","accept":"application/json","x-ms-client-request-id":"54dfdf18-7a75-47de-a088-2ad39458a3b7","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Storage.Files.DataLake/12.15.0 (.NET 6.0.29; Microsoft Windows 10.0.22631)","traceparent":"00-9116ef48897d84a20a1bc6cd696287e5-48a4db8c6d9b7da6-00"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2024-04-24T08:51:37.871Z 4c638e1a-c673-4a66-ab74-f639b9e872ed info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=trident-nbs-fs Blob=
2024-04-24T08:51:37.871Z 4c638e1a-c673-4a66-ab74-f639b9e872ed verbose: DispatchMiddleware: Dispatching request...
2024-04-24T08:51:37.871Z 4c638e1a-c673-4a66-ab74-f639b9e872ed error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2024-04-24T08:51:37.871Z 4c638e1a-c673-4a66-ab74-f639b9e872ed error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2024-04-24T08:51:37.871Z 4c638e1a-c673-4a66-ab74-f639b9e872ed error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at dispatchMiddleware (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\generated\\middleware\\dispatch.middleware.js:41:30)\n    at C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\generated\\ExpressMiddlewareFactory.js:50:47\n    at Layer.handle [as handle_request] (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at blobStorageContextMiddleware (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:137:5)\n    at C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:15:16\n    at Layer.handle [as handle_request] (C:\\Users\\luyue\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)"
2024-04-24T08:51:37.871Z 4c638e1a-c673-4a66-ab74-f639b9e872ed error: ErrorMiddleware: Set HTTP code: 400
2024-04-24T08:51:37.871Z 4c638e1a-c673-4a66-ab74-f639b9e872ed error: ErrorMiddleware: Set HTTP body: undefined
2024-04-24T08:51:37.871Z 4c638e1a-c673-4a66-ab74-f639b9e872ed info: EndMiddleware: End response. TotalTimeInMS=0 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.29.0"}
2024-04-24T08:51:38.067Z bcada83b-fe06-4b9b-a541-662d661d3d14 info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://devstoreaccount1.blob.localhost/trident-nbs-fs?sv=2023-01-03&spr=https&se=2024-04-25T08%3A51%3A35Z&sr=c&sp=racwdlmeop&sig=xFn8jEk9QbYFdJxEhzqjtHz6gzQ3sAamqWQsLM4Obto%3D&resource=filesystem&directory=&recursive=false&upn=false RequestHeaders:{"host":"devstoreaccount1.blob.localhost:10000","x-ms-version":"2023-01-03","accept":"application/json","x-ms-client-request-id":"427c3a90-a790-4786-be86-fa3a88cf2037","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Storage.Files.DataLake/12.15.0 (.NET 6.0.29; Microsoft Windows 10.0.22631)","traceparent":"00-9116ef48897d84a20a1bc6cd696287e5-96f0adf65aeff382-00"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2024-04-24T08:51:38.067Z bcada83b-fe06-4b9b-a541-662d661d3d14 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=trident-nbs-fs Blob=
2024-04-24T08:51:38.067Z bcada83b-fe06-4b9b-a541-662d661d3d14 verbose: DispatchMiddleware: Dispatching request...
2024-04-24T08:51:38.067Z bcada83b-fe06-4b9b-a541-662d661d3d14 error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2024-04-24T08:51:38.067Z bcada83b-fe06-4b9b-a541-662d661d3d14 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2024-04-24T08:51:38.068Z bcada83b-fe06-4b9b-a541-662d661d3d14 error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at dispatchMiddleware (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\generated\\middleware\\dispatch.middleware.js:41:30)\n    at C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\generated\\ExpressMiddlewareFactory.js:50:47\n    at Layer.handle [as handle_request] (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at blobStorageContextMiddleware (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:137:5)\n    at C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:15:16\n    at Layer.handle [as handle_request] (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)"
2024-04-24T08:51:38.068Z bcada83b-fe06-4b9b-a541-662d661d3d14 error: ErrorMiddleware: Set HTTP code: 400
2024-04-24T08:51:38.068Z bcada83b-fe06-4b9b-a541-662d661d3d14 error: ErrorMiddleware: Set HTTP body: undefined
2024-04-24T08:51:38.068Z bcada83b-fe06-4b9b-a541-662d661d3d14 info: EndMiddleware: End response. TotalTimeInMS=1 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.29.0"}

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### Have you found a mitigation/solution?
No

Could you help investigate why the Azurite always return 400?

**Comment by blueww** [comment]
@luyue14 

The sas you generated is with "DataLakeSasBuilder", it's datalakegen2 SAS. And you can calling datalakeGen2 API with " DataLakeDirectoryClient". 

Azurite still not support datalakeGen2, so this does not work in Azurite. 
From Azurite [ReadMe file](https://github.com/Azure/Azurite#:~:text=Blob%2C%20Queue%2C%20and%20Table), you can see only blob, queue, table are supported.

We already has items to track datalakeGen2.
https://github.com/Azure/Azurite/issues/553
https://github.com/Azure/Azurite/issues/409
