### ISSUE TITLE
Upload From Url API

### ISSUE THREAD

**Issue by trungmaihova** [Azure/Azurite#2402]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
latest
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What problem was encountered?
I use the blockBlobClient.uploadFromUrl(urlSource) but it throw exception "Current API is not implement"
```
<Error>
  <Code>APINotImplemented</Code>
  <Message>Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues
RequestId:f1a1d668-c1d5-4f07-aa59-681d88a3ef2a
Time:2024-05-22T02:48:04.724Z</Message>
```
So it mean the Azurite does not support this API, right?

**Comment by blueww** [comment]
@trungmaihova 
Would you please share the Azurite debug log of the failed request?

Per [this doc](https://learn.microsoft.com/en-us/javascript/api/@azure/storage-blob/blockblobclient?view=azure-node-latest) , it looks `BlockBlobClient` only has method `syncUploadFromURL()` method, but no `uploadFromUrl()` method.

Besides that, is the "urlSource" point to an object not in Azurite? In this case, Azurite not support copy/create blobs from a source outside Azurite. See https://github.com/Azure/Azurite#:~:text=Copy%20Blob%20From%20URL%20(Only%20supports%20copy%20within%20same%20Azurite%20instance

**Comment by trungmaihova** [comment]
hi @blueww ,

Currently, I use java sdk.
![image](https://github.com/Azure/Azurite/assets/138564881/13ec4387-859c-4617-9b7d-410774124f48)


The below is the log
```
PS C:\Users\xxx> docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite
Azurite Blob service is starting at http://0.0.0.0:10000
Azurite Blob service is successfully listening at http://0.0.0.0:10000
Azurite Queue service is starting at http://0.0.0.0:10001
Azurite Queue service is successfully listening at http://0.0.0.0:10001
Azurite Table service is starting at http://0.0.0.0:10002
Azurite Table service is successfully listening at http://0.0.0.0:10002
172.28.128.1 - - [22/May/2024:06:35:06 +0000] "PUT /devstoreaccount1/demo-container?restype=container HTTP/1.1" 201 -
172.28.128.1 - - [22/May/2024:06:35:06 +0000] "PUT /devstoreaccount1/demo-container?restype=container HTTP/1.1" 409 -
172.28.128.1 - - [22/May/2024:06:35:06 +0000] "PUT /devstoreaccount1/demo-container/filename HTTP/1.1" 500 -
172.28.128.1 - - [22/May/2024:06:35:10 +0000] "PUT /devstoreaccount1/demo-container/filename HTTP/1.1" 500 -
172.28.128.1 - - [22/May/2024:06:35:22 +0000] "PUT /devstoreaccount1/demo-container/filename HTTP/1.1" 500 -
```
Yes, I try to copy a file outside the Azure,
![image](https://github.com/Azure/Azurite/assets/138564881/58a25175-6c5b-4b47-8e5c-d6665197d711)

**Comment by blueww** [comment]
@trungmaihova 

For Azurite debug log, please run Azurite with "-d c:\azuritedebug.log" (the log path can change to other local file path).
And share the debug log of failed request, then we can get more idea for this failure. (hide credential if any)

BTW, Azurite doesn't support copy/put blob from a source Uri outside of Azurite, so you can either:
1. Copy / create blob from a Uri inside Azurite
2. Or, if you want to copy an external blob to Azurite, first download it to local file, then upload the local file to Azurite.

**Comment by pierreinglebert** [comment]
@blueww 

It seems it doesn't work if the url is from Azurite but is a SAS URL.

`2024-07-10T15:26:29.547Z b521185a-7fc4-40f6-91c3-f8579822a54a info: HandlerMiddleware: DeserializedParameters={"options":{"metadata":{},"requestId":"76a9ef33-ab3e-4b39-8c70-fbdd3ec0535c","blobHTTPHeaders":{},"leaseAccessConditions":{},"cpkInfo":{},"cpkScopeInfo":{},"modifiedAccessConditions":{},"sourceModifiedAccessConditions":{}},"contentLength":0,"version":"2024-05-04","copySource":"http://127.0.0.1:10000/devstoreaccount1/interop-client-1-container/test.txt?sv=2024-05-04&st=2024-07-10T15%3A26%3A25Z&se=2024-07-10T15%3A27%3A52Z&sr=b&sp=racwd&sig=R7XYe%2FfCYPVHYRvL2e28XikvUOLmufy6%2FVAdJJGRkkE%3D","blobType":"BlockBlob"}
2024-07-10T15:26:29.548Z b521185a-7fc4-40f6-91c3-f8579822a54a error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response`

Should I open a new issue or can we continue here as this ticket is not closed yet ?

**Comment by blueww** [comment]
@pierreinglebert 

Feel free to open a new issue for this, as the original issue looks is for copy from outside of Azurite.

And please share the full Azurite debug for the failed request.

**Comment by gaul** [comment]
I believe that I have the same problem when testing S3Proxy with Azurite:

```
2024-11-10T19:02:05.201Z 35faca23-01bc-4eab-9210-255912be46a1 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/s3proxy-l2ff4ked90vcvwb3yxor6-185/bar321foo RequestHeaders:{"host":"127.0.0.1:10000","date":"Sun, 10 Nov 2024 19:02:05 GMT","authorization":"SharedKey devstoreaccount1:VejpxM+Aozv8A04JSlMqBailjr3wg6Pc+GAb8HxNnr4=","x-ms-version":"2024-11-04","x-ms-copy-source":"http://127.0.0.1:10000/devstoreaccount1/s3proxy-l2ff4ked90vcvwb3yxor6-185/foo123bar?sv=2024-11-04&st=2024-11-10T19%3A02%3A05Z&se=2024-11-11T19%3A02%3A05Z&sr=b&sp=r&sig=DpbtEhcuS1WoqhkeHhd1TI%2F6rD%2BdnMwFtSplwOjB%2FZM%3D","x-ms-client-request-id":"45306d47-1af7-4112-be9c-fc242aad2be1","x-ms-blob-type":"BlockBlob","accept":"application/xml","user-agent":"azsdk-java-azure-storage-blob/12.28.0 (23.0.1; Linux; 6.11.6-300.ipu6.fc41.x86_64)","content-length":"0"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2024-11-10T19:02:05.201Z 35faca23-01bc-4eab-9210-255912be46a1 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=s3proxy-l2ff4ked90vcvwb3yxor6-185 Blob=bar321foo
2024-11-10T19:02:05.201Z 35faca23-01bc-4eab-9210-255912be46a1 verbose: DispatchMiddleware: Dispatching request...
2024-11-10T19:02:05.202Z 35faca23-01bc-4eab-9210-255912be46a1 info: DispatchMiddleware: Operation=BlockBlob_PutBlobFromUrl
2024-11-10T19:02:05.202Z 35faca23-01bc-4eab-9210-255912be46a1 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2024-11-10T19:02:05.202Z 35faca23-01bc-4eab-9210-255912be46a1 info: PublicAccessAuthenticator:validate() Start validation against public access.
2024-11-10T19:02:05.202Z 35faca23-01bc-4eab-9210-255912be46a1 debug: PublicAccessAuthenticator:validate() Getting account properties...
2024-11-10T19:02:05.202Z 35faca23-01bc-4eab-9210-255912be46a1 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: s3proxy-l2ff4ked90vcvwb3yxor6-185, blob: bar321foo
2024-11-10T19:02:05.202Z 35faca23-01bc-4eab-9210-255912be46a1 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container s3proxy-l2ff4ked90vcvwb3yxor6-185
2024-11-10T19:02:05.202Z 35faca23-01bc-4eab-9210-255912be46a1 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2024-11-10T19:02:05.202Z 35faca23-01bc-4eab-9210-255912be46a1 info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n\n\n\nSun, 10 Nov 2024 19:02:05 GMT\n\n\n\n\n\nx-ms-blob-type:BlockBlob\nx-ms-client-request-id:45306d47-1af7-4112-be9c-fc242aad2be1\nx-ms-copy-source:http://127.0.0.1:10000/devstoreaccount1/s3proxy-l2ff4ked90vcvwb3yxor6-185/foo123bar?sv=2024-11-04&st=2024-11-10T19%3A02%3A05Z&se=2024-11-11T19%3A02%3A05Z&sr=b&sp=r&sig=DpbtEhcuS1WoqhkeHhd1TI%2F6rD%2BdnMwFtSplwOjB%2FZM%3D\nx-ms-version:2024-11-04\n/devstoreaccount1/devstoreaccount1/s3proxy-l2ff4ked90vcvwb3yxor6-185/bar321foo"
2024-11-10T19:02:05.202Z 35faca23-01bc-4eab-9210-255912be46a1 info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:VejpxM+Aozv8A04JSlMqBailjr3wg6Pc+GAb8HxNnr4=
2024-11-10T19:02:05.202Z 35faca23-01bc-4eab-9210-255912be46a1 info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2024-11-10T19:02:05.202Z 35faca23-01bc-4eab-9210-255912be46a1 verbose: DeserializerMiddleware: Start deserializing...
2024-11-10T19:02:05.203Z 35faca23-01bc-4eab-9210-255912be46a1 info: HandlerMiddleware: DeserializedParameters={"options":{"metadata":{},"requestId":"45306d47-1af7-4112-be9c-fc242aad2be1","blobHTTPHeaders":{},"leaseAccessConditions":{},"cpkInfo":{},"cpkScopeInfo":{},"modifiedAccessConditions":{},"sourceModifiedAccessConditions":{}},"contentLength":0,"version":"2024-11-04","copySource":"http://127.0.0.1:10000/devstoreaccount1/s3proxy-l2ff4ked90vcvwb3yxor6-185/foo123bar?sv=2024-11-04&st=2024-11-10T19%3A02%3A05Z&se=2024-11-11T19%3A02%3A05Z&sr=b&sp=r&sig=DpbtEhcuS1WoqhkeHhd1TI%2F6rD%2BdnMwFtSplwOjB%2FZM%3D","blobType":"BlockBlob"}
2024-11-10T19:02:05.203Z 35faca23-01bc-4eab-9210-255912be46a1 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2024-11-10T19:02:05.203Z 35faca23-01bc-4eab-9210-255912be46a1 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues  ErrorHTTPStatusCode=500 ErrorHTTPStatusMessage=Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues ErrorHTTPHeaders={"x-ms-error-code":"APINotImplemented","x-ms-request-id":"35faca23-01bc-4eab-9210-255912be46a1"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>APINotImplemented</Code>\n  <Message>Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues\nRequestId:35faca23-01bc-4eab-9210-255912be46a1\nTime:2024-11-10T19:02:05.203Z</Message>\n</Error>" ErrorStack="StorageError: Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues\n    at BlockBlobHandler.putBlobFromUrl (/home/gaul/work/Azurite/dist/src/blob/handlers/BlockBlobHandler.js:119:15)\n    at /home/gaul/work/Azurite/dist/src/blob/generated/middleware/HandlerMiddlewareFactory.js:58:18\n    at /home/gaul/work/Azurite/dist/src/blob/generated/ExpressMiddlewareFactory.js:78:63\n    at Layer.handle [as handle_request] (/home/gaul/work/Azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/gaul/work/Azurite/node_modules/express/lib/router/index.js:328:13)\n    at /home/gaul/work/Azurite/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/home/gaul/work/Azurite/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/gaul/work/Azurite/node_modules/express/lib/router/index.js:280:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
2024-11-10T19:02:05.203Z 35faca23-01bc-4eab-9210-255912be46a1 error: ErrorMiddleware: Set HTTP code: 500
2024-11-10T19:02:05.203Z 35faca23-01bc-4eab-9210-255912be46a1 error: ErrorMiddleware: Set HTTP status message: Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues
2024-11-10T19:02:05.204Z 35faca23-01bc-4eab-9210-255912be46a1 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=APINotImplemented
2024-11-10T19:02:05.204Z 35faca23-01bc-4eab-9210-255912be46a1 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=35faca23-01bc-4eab-9210-255912be46a1
2024-11-10T19:02:05.204Z 35faca23-01bc-4eab-9210-255912be46a1 error: ErrorMiddleware: Set content type: application/xml
```
