### ISSUE TITLE
Not being able to launch Azurite from DockerHub.

### ISSUE THREAD

**Issue by electronic-heartbreak** [Azure/Azurite#2429]
### Which service(blob, file, queue, table) does this issue concern?

All.

### Which version of the Azurite was used?

Latest. Using the commands: `docker pull mcr.microsoft.com/azure-storage/azurite` & `docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite`

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub.

### What's the Node.js version?

v20.10.0 (by running `node -v` in the `exec` tab of the container).

### What problem was encountered?
Azurite Blob service is successfully listening at http://0.0.0.0:10000

```
<Error>
    <Code>InvalidQueryParameterValue</Code>
    <Message>Value for one of the query parameters specified in the request URI is invalid. RequestId:6cc67582-7a47-4b9b-bf2f-a6bdf4d0431b Time:2024-07-16T11:27:39.184Z</Message>
</Error>
```

Azurite Queue service is successfully listening at http://0.0.0.0:10001
HTTP ERROR 400

Azurite Table service is successfully listening at http://0.0.0.0:10002:
HTTP ERROR 400

### Steps to reproduce the issue?

Follow the steps from: https://hub.docker.com/r/microsoft/azure-storage-azurite.

```
Azurite Blob service is starting at http://0.0.0.0:10000
Azurite Blob service is successfully listening at http://0.0.0.0:10000
Azurite Queue service is starting at http://0.0.0.0:10001
Azurite Queue service is successfully listening at http://0.0.0.0:10001
Azurite Table service is starting at http://0.0.0.0:10002
Azurite Table service is successfully listening at http://0.0.0.0:10002
172.17.0.1 - - [16/Jul/2024:11:42:48 +0000] "GET / HTTP/1.1" 400 -
172.17.0.1 - - [16/Jul/2024:11:42:48 +0000] "GET /favicon.ico HTTP/1.1" 400 -
172.17.0.1 - - [16/Jul/2024:11:42:55 +0000] "GET / HTTP/1.1" 400 -
172.17.0.1 - - [16/Jul/2024:11:42:59 +0000] "GET / HTTP/1.1" 400 -
```

### Have you found a mitigation/solution?

No.

**Comment by blueww** [comment]
@electronic-heartbreak 

Would you please share the Azurite debug log for the failed request (which returns 400), then we can continue the investigation of the failure.

**Comment by electronic-heartbreak** [comment]
@blueww 

Thank you for your reply. This is the `debug.log` I found in my local Azurite folder:

```
2024-07-16T11:12:35.038Z 	 info: Azurite Blob service is starting on 0.0.0.0:7777
2024-07-16T11:12:35.040Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:12:35.040Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:12:35.077Z 	 info: BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2024-07-16T11:12:35.077Z 	 info: BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2024-07-16T11:12:35.077Z 	 info: BlobGCManager:markSweepLoop() Start next mark and sweep.
2024-07-16T11:12:35.077Z 	 info: BlobGCManager:markSweep() Get all extents.
2024-07-16T11:12:35.078Z 	 info: BlobGCManager:start() BlobGCManager successfully started.
2024-07-16T11:12:35.081Z 	 info: BlobGCManager:markSweep() Got 0 extents.
2024-07-16T11:12:35.081Z 	 info: BlobGCManager:markSweep() Get referred extents.
2024-07-16T11:12:35.081Z 	 info: BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2024-07-16T11:12:35.082Z 	 info: BlobGCManager:markSweepLoop() Mark and sweep finished, taken 5ms.
2024-07-16T11:12:35.082Z 	 info: BlobGCManager:markSweepLoop() Sleep for 600000ms.
2024-07-16T11:12:35.083Z 	 info: Azurite Blob service successfully listens on http://0.0.0.0:7777
2024-07-16T11:12:35.083Z 	 info: Azurite Queue service is starting on 0.0.0.0:8888
2024-07-16T11:12:35.084Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:12:35.084Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:12:35.099Z 	 info: QueueGCManager:start() Starting QueueGCManager, set status to Initializing
2024-07-16T11:12:35.099Z 	 info: QueueGCManager:start() Trigger mark and sweep loop, set status to Running.
2024-07-16T11:12:35.099Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2024-07-16T11:12:35.100Z 	 info: QueueGCManger:markSweep() Get all extents.
2024-07-16T11:12:35.100Z 	 info: QueueGCManager:start() QueueGCManager successfully started.
2024-07-16T11:12:35.100Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2024-07-16T11:12:35.100Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2024-07-16T11:12:35.100Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2024-07-16T11:12:35.100Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2024-07-16T11:12:35.100Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2024-07-16T11:12:35.101Z 	 info: Azurite Queue service successfully listens on http://0.0.0.0:8888
2024-07-16T11:12:35.101Z 	 info: Azurite Table service is starting on 0.0.0.0:9999
2024-07-16T11:12:35.101Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:12:35.101Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:12:35.107Z 	 info: Azurite Table service successfully listens on http://0.0.0.0:9999
2024-07-16T11:12:54.768Z 32994a3b-5522-41ad-b994-589529a80de5 info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://localhost/ RequestHeaders:{"host":"localhost:7777","connection":"keep-alive","sec-ch-ua":"\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\", \"Brave\";v=\"126\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8","sec-gpc":"1","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","accept-encoding":"gzip, deflate, br, zstd","accept-language":"nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6,de;q=0.5","cookie":"_xsrf=2|cda7a733|fed746432ff843c4cd4dcbfb8edfaea0|1719941153; username-localhost-8889=\"2|1:0|10:1719941232|23:username-localhost-8889|44:ZDVjZGEzYmU1N2ZjNGNjOTk1NDI1MDUxMzk2MTBjYmQ=|bd4142edfd4a308ce7b96a4e5de61e455e703e694ea8f8391cf67ab0714e0511\"; username-localhost-8888=\"2|1:0|10:1719942834|23:username-localhost-8888|44:NDdlZWJhODc5NDUyNDZkYWI1ZmZlZDA4ZGQwYmE2ZDI=|baa58d56118aec2b6016c3019c5c01687fb0e28047426c980ad8b10bbb44c82a\""} ClientIP=172.17.0.1 Protocol=http HTTPVersion=1.1
2024-07-16T11:12:54.775Z 32994a3b-5522-41ad-b994-589529a80de5 error: BlobStorageContextMiddleware: BlobStorageContextMiddleware: Value for one of the query parameters specified in the request URI is invalid.
2024-07-16T11:12:54.776Z 32994a3b-5522-41ad-b994-589529a80de5 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2024-07-16T11:12:54.776Z 32994a3b-5522-41ad-b994-589529a80de5 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Value for one of the query parameters specified in the request URI is invalid.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=Value for one of the query parameters specified in the request URI is invalid. ErrorHTTPHeaders={"x-ms-error-code":"InvalidQueryParameterValue","x-ms-request-id":"32994a3b-5522-41ad-b994-589529a80de5"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidQueryParameterValue</Code>\n  <Message>Value for one of the query parameters specified in the request URI is invalid.\nRequestId:32994a3b-5522-41ad-b994-589529a80de5\nTime:2024-07-16T11:12:54.769Z</Message>\n</Error>" ErrorStack="StorageError: Value for one of the query parameters specified in the request URI is invalid.\n    at StorageErrorFactory.getInvalidQueryParameterValue (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:45:16)\n    at blobStorageContextMiddleware (/opt/azurite/dist/src/blob/middlewares/blobStorageContext.middleware.js:127:60)\n    at /opt/azurite/dist/src/blob/middlewares/blobStorageContext.middleware.js:15:16\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:328:13)\n    at /opt/azurite/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:346:12)\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:280:10)\n    at logger (/opt/azurite/node_modules/morgan/index.js:144:5)\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)"
2024-07-16T11:12:54.776Z 32994a3b-5522-41ad-b994-589529a80de5 error: ErrorMiddleware: Set HTTP code: 400
2024-07-16T11:12:54.777Z 32994a3b-5522-41ad-b994-589529a80de5 error: ErrorMiddleware: Set HTTP status message: Value for one of the query parameters specified in the request URI is invalid.
2024-07-16T11:12:54.777Z 32994a3b-5522-41ad-b994-589529a80de5 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidQueryParameterValue
2024-07-16T11:12:54.777Z 32994a3b-5522-41ad-b994-589529a80de5 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=32994a3b-5522-41ad-b994-589529a80de5
2024-07-16T11:12:54.777Z 32994a3b-5522-41ad-b994-589529a80de5 error: ErrorMiddleware: Set content type: application/xml
2024-07-16T11:12:54.777Z 32994a3b-5522-41ad-b994-589529a80de5 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidQueryParameterValue</Code>\n  <Message>Value for one of the query parameters specified in the request URI is invalid.\nRequestId:32994a3b-5522-41ad-b994-589529a80de5\nTime:2024-07-16T11:12:54.769Z</Message>\n</Error>"
2024-07-16T11:12:54.780Z 32994a3b-5522-41ad-b994-589529a80de5 info: EndMiddleware: End response. TotalTimeInMS=13 StatusCode=400 StatusMessage=Value for one of the query parameters specified in the request URI is invalid. Headers={"server":"Azurite-Blob/3.31.0","x-ms-error-code":"InvalidQueryParameterValue","x-ms-request-id":"32994a3b-5522-41ad-b994-589529a80de5","content-type":"application/xml"}
2024-07-16T11:12:54.858Z abc297bb-58da-4c86-ba07-66cae9e76dbd info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://localhost/favicon.ico RequestHeaders:{"host":"localhost:7777","connection":"keep-alive","sec-ch-ua":"\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\", \"Brave\";v=\"126\"","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","sec-ch-ua-platform":"\"Windows\"","accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","sec-gpc":"1","sec-fetch-site":"same-origin","sec-fetch-mode":"no-cors","sec-fetch-dest":"image","referer":"http://localhost:7777/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6,de;q=0.5","cookie":"_xsrf=2|cda7a733|fed746432ff843c4cd4dcbfb8edfaea0|1719941153; username-localhost-8889=\"2|1:0|10:1719941232|23:username-localhost-8889|44:ZDVjZGEzYmU1N2ZjNGNjOTk1NDI1MDUxMzk2MTBjYmQ=|bd4142edfd4a308ce7b96a4e5de61e455e703e694ea8f8391cf67ab0714e0511\"; username-localhost-8888=\"2|1:0|10:1719942834|23:username-localhost-8888|44:NDdlZWJhODc5NDUyNDZkYWI1ZmZlZDA4ZGQwYmE2ZDI=|baa58d56118aec2b6016c3019c5c01687fb0e28047426c980ad8b10bbb44c82a\""} ClientIP=172.17.0.1 Protocol=http HTTPVersion=1.1
2024-07-16T11:12:54.858Z abc297bb-58da-4c86-ba07-66cae9e76dbd info: BlobStorageContextMiddleware: Account=favicon.ico Container=undefined Blob=
2024-07-16T11:12:54.858Z abc297bb-58da-4c86-ba07-66cae9e76dbd verbose: DispatchMiddleware: Dispatching request...
2024-07-16T11:12:54.863Z abc297bb-58da-4c86-ba07-66cae9e76dbd error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2024-07-16T11:12:54.863Z abc297bb-58da-4c86-ba07-66cae9e76dbd error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2024-07-16T11:12:54.863Z abc297bb-58da-4c86-ba07-66cae9e76dbd error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at dispatchMiddleware (/opt/azurite/dist/src/blob/generated/middleware/dispatch.middleware.js:41:30)\n    at /opt/azurite/dist/src/blob/generated/ExpressMiddlewareFactory.js:50:47\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:328:13)\n    at /opt/azurite/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:346:12)\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:280:10)\n    at blobStorageContextMiddleware (/opt/azurite/dist/src/blob/middlewares/blobStorageContext.middleware.js:137:5)\n    at /opt/azurite/dist/src/blob/middlewares/blobStorageContext.middleware.js:15:16\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)"
2024-07-16T11:12:54.864Z abc297bb-58da-4c86-ba07-66cae9e76dbd error: ErrorMiddleware: Set HTTP code: 400
2024-07-16T11:12:54.864Z abc297bb-58da-4c86-ba07-66cae9e76dbd error: ErrorMiddleware: Set HTTP body: undefined
2024-07-16T11:12:54.864Z abc297bb-58da-4c86-ba07-66cae9e76dbd info: EndMiddleware: End response. TotalTimeInMS=6 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.31.0"}
2024-07-16T11:12:58.575Z 0d80eaa7-a4e4-44dc-b550-df416b0e07da info: QueueStorageContextMiddleware: RequestMethod=GET RequestURL=http://localhost/ RequestHeaders:{"host":"localhost:8888","connection":"keep-alive","sec-ch-ua":"\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\", \"Brave\";v=\"126\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8","sec-gpc":"1","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","accept-encoding":"gzip, deflate, br, zstd","accept-language":"nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6,de;q=0.5","cookie":"_xsrf=2|cda7a733|fed746432ff843c4cd4dcbfb8edfaea0|1719941153; username-localhost-8889=\"2|1:0|10:1719941232|23:username-localhost-8889|44:ZDVjZGEzYmU1N2ZjNGNjOTk1NDI1MDUxMzk2MTBjYmQ=|bd4142edfd4a308ce7b96a4e5de61e455e703e694ea8f8391cf67ab0714e0511\"; username-localhost-8888=\"2|1:0|10:1719942834|23:username-localhost-8888|44:NDdlZWJhODc5NDUyNDZkYWI1ZmZlZDA4ZGQwYmE2ZDI=|baa58d56118aec2b6016c3019c5c01687fb0e28047426c980ad8b10bbb44c82a\""} ClientIP=172.17.0.1 Protocol=http HTTPVersion=1.1
2024-07-16T11:12:58.576Z 0d80eaa7-a4e4-44dc-b550-df416b0e07da info: QueueStorageContextMiddleware: Account= Queue=undefined Message=undefined MessageId=undefined
2024-07-16T11:12:58.577Z 0d80eaa7-a4e4-44dc-b550-df416b0e07da verbose: DispatchMiddleware: Dispatching request...
2024-07-16T11:12:58.579Z 0d80eaa7-a4e4-44dc-b550-df416b0e07da error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2024-07-16T11:12:58.581Z 0d80eaa7-a4e4-44dc-b550-df416b0e07da error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2024-07-16T11:12:58.582Z 0d80eaa7-a4e4-44dc-b550-df416b0e07da error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at dispatchMiddleware (/opt/azurite/dist/src/queue/generated/middleware/dispatch.middleware.js:41:30)\n    at /opt/azurite/dist/src/queue/generated/ExpressMiddlewareFactory.js:49:47\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:328:13)\n    at /opt/azurite/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:346:12)\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:280:10)\n    at queueStorageContextMiddleware (/opt/azurite/dist/src/queue/middlewares/queueStorageContext.middleware.js:97:5)\n    at /opt/azurite/dist/src/queue/middlewares/queueStorageContext.middleware.js:15:16\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)"
2024-07-16T11:12:58.582Z 0d80eaa7-a4e4-44dc-b550-df416b0e07da error: ErrorMiddleware: Set HTTP code: 400
2024-07-16T11:12:58.582Z 0d80eaa7-a4e4-44dc-b550-df416b0e07da error: ErrorMiddleware: Set HTTP body: undefined
2024-07-16T11:12:58.583Z 0d80eaa7-a4e4-44dc-b550-df416b0e07da info: EndMiddleware: End response. TotalTimeInMS=8 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Queue/3.31.0"}
2024-07-16T11:13:02.309Z d85d64a3-54f2-40e1-96bf-53ac06c0bf1a info: TableStorageContextMiddleware: RequestMethod=GET RequestURL=http://localhost/ RequestHeaders:{"host":"localhost:9999","connection":"keep-alive","sec-ch-ua":"\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\", \"Brave\";v=\"126\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8","sec-gpc":"1","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","accept-encoding":"gzip, deflate, br, zstd","accept-language":"nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6,de;q=0.5","cookie":"_xsrf=2|cda7a733|fed746432ff843c4cd4dcbfb8edfaea0|1719941153; username-localhost-8889=\"2|1:0|10:1719941232|23:username-localhost-8889|44:ZDVjZGEzYmU1N2ZjNGNjOTk1NDI1MDUxMzk2MTBjYmQ=|bd4142edfd4a308ce7b96a4e5de61e455e703e694ea8f8391cf67ab0714e0511\"; username-localhost-8888=\"2|1:0|10:1719942834|23:username-localhost-8888|44:NDdlZWJhODc5NDUyNDZkYWI1ZmZlZDA4ZGQwYmE2ZDI=|baa58d56118aec2b6016c3019c5c01687fb0e28047426c980ad8b10bbb44c82a\""} ClientIP=172.17.0.1 Protocol=http HTTPVersion=1.1
2024-07-16T11:13:02.310Z d85d64a3-54f2-40e1-96bf-53ac06c0bf1a debug: tableStorageContextMiddleware: Dispatch pattern string: /
2024-07-16T11:13:02.310Z d85d64a3-54f2-40e1-96bf-53ac06c0bf1a info: tableStorageContextMiddleware: Account= tableName=undefined
2024-07-16T11:13:02.311Z d85d64a3-54f2-40e1-96bf-53ac06c0bf1a verbose: DispatchMiddleware: Dispatching request...
2024-07-16T11:13:02.314Z d85d64a3-54f2-40e1-96bf-53ac06c0bf1a error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2024-07-16T11:13:02.316Z d85d64a3-54f2-40e1-96bf-53ac06c0bf1a error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2024-07-16T11:13:02.317Z d85d64a3-54f2-40e1-96bf-53ac06c0bf1a error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage="Incoming URL doesn't match any of swagger defined request patterns."  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="\"UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\\n    at dispatchMiddleware (/opt/azurite/dist/src/table/generated/middleware/dispatch.middleware.js:41:30)\\n    at /opt/azurite/dist/src/table/generated/ExpressMiddlewareFactory.js:49:47\\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:328:13)\\n    at /opt/azurite/node_modules/express/lib/router/index.js:286:9\\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:346:12)\\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:280:10)\\n    at tableStorageContextMiddleware (/opt/azurite/dist/src/table/middleware/tableStorageContext.middleware.js:126:5)\\n    at /opt/azurite/dist/src/table/middleware/tableStorageContext.middleware.js:14:16\\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\""
2024-07-16T11:13:02.317Z d85d64a3-54f2-40e1-96bf-53ac06c0bf1a error: ErrorMiddleware: Set HTTP code: 400
2024-07-16T11:13:02.317Z d85d64a3-54f2-40e1-96bf-53ac06c0bf1a error: ErrorMiddleware: Set HTTP body: undefined
2024-07-16T11:13:02.317Z d85d64a3-54f2-40e1-96bf-53ac06c0bf1a info: EndMiddleware: End response. TotalTimeInMS=8 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Table/3.31.0"}
2024-07-16T11:13:35.046Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:13:35.047Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:13:35.084Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:13:35.084Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:13:35.101Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2024-07-16T11:13:35.101Z 	 info: QueueGCManger:markSweep() Get all extents.
2024-07-16T11:13:35.101Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2024-07-16T11:13:35.101Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2024-07-16T11:13:35.101Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2024-07-16T11:13:35.101Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 0ms.
2024-07-16T11:13:35.101Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2024-07-16T11:13:35.101Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:13:35.101Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:14:35.050Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:14:35.051Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:14:35.084Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:14:35.085Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:14:35.101Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2024-07-16T11:14:35.101Z 	 info: QueueGCManger:markSweep() Get all extents.
2024-07-16T11:14:35.101Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2024-07-16T11:14:35.101Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2024-07-16T11:14:35.102Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2024-07-16T11:14:35.102Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2024-07-16T11:14:35.102Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2024-07-16T11:14:35.102Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:14:35.102Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:15:35.056Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:15:35.056Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:15:35.085Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:15:35.086Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:15:35.102Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2024-07-16T11:15:35.102Z 	 info: QueueGCManger:markSweep() Get all extents.
2024-07-16T11:15:35.102Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2024-07-16T11:15:35.102Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2024-07-16T11:15:35.102Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2024-07-16T11:15:35.102Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 0ms.
2024-07-16T11:15:35.102Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2024-07-16T11:15:35.103Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:15:35.103Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:16:35.061Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:16:35.062Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:16:35.087Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:16:35.087Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:16:35.103Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2024-07-16T11:16:35.103Z 	 info: QueueGCManger:markSweep() Get all extents.
2024-07-16T11:16:35.103Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2024-07-16T11:16:35.103Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2024-07-16T11:16:35.103Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2024-07-16T11:16:35.103Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 0ms.
2024-07-16T11:16:35.103Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2024-07-16T11:16:35.103Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2024-07-16T11:16:35.103Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2024-07-16T11:16:48.266Z 	 info: Azurite Blob service is closing...
2024-07-16T11:16:48.267Z 	 info: Azurite Queue service is closing...
2024-07-16T11:16:48.267Z 	 info: Azurite Table service is closing...
2024-07-16T11:16:48.268Z 	 info: BlobGCManager:close() Start closing BlobGCManager. Set status to Closing.
2024-07-16T11:16:48.269Z 	 info: QueueGCManager:close() Start closing QueueGCManager, set status to Closing.
2024-07-16T11:16:48.270Z 	 info: BlobGCManager:start() Mark and sweep loop is closed.
2024-07-16T11:16:48.270Z 	 info: BlobGCManager:close() BlobGCManager successfully closed. Set status to Closed.
2024-07-16T11:16:48.270Z 	 info: QueueGCManager:start() Mark and sweep loop is closed.
2024-07-16T11:16:48.270Z 	 info: QueueGCManager:close() QueueGCManager successfully closed, set status to Closed.
2024-07-16T11:16:48.271Z 	 info: Azurite Table service successfully closed
2024-07-16T11:16:48.272Z 	 info: Azurite Blob service successfully closed
2024-07-16T11:16:48.273Z 	 info: Azurite Queue service successfully closed

```

Hope this helps 👍 .

**Comment by blueww** [comment]
@electronic-heartbreak 

From the debug log, you are send a request `RequestMethod=GET RequestURL=http://localhost/`. 
This method and Uri doesn't meet any blob rest API. So this is not a valid request. 

Please send a valid request to Azurite.
You can find all blob API in https://learn.microsoft.com/en-us/rest/api/storageservices/blob-service-rest-api

**Comment by electronic-heartbreak** [comment]
Hi there,

Thanks for reaching out. I initially expected that when clicking on `http://0.0.0.0:10000` it would open the Microsoft Azure Storage Explorer (MASE). After some more digging, I found out that MASE is an external program that needed to be installed.

In the end I managed to get a connection through Docker and it all works now.
