### ISSUE TITLE
HealthCheck fails with 400 bad request

### ISSUE THREAD

**Issue by onionhammer** [Azure/Azurite#2450]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.31.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
NA

### What problem was encountered?

```
The query condition specified in the request is invalid.\nRequestId:47a6a1bb-5a89-47e9-8dda-954ba86566dd\nTime:2024-08-09T14:03:38.156Z\r\nStatus: 400 (Bad Request)\r\nErrorCode: InvalidInput\r\n\r\nContent:\r\n{\"odata.error\":{\"code\":\"InvalidInput\",\"message\":{\"lang\":\"en-US\",\"value\":\"The query condition specified in the request is invalid.\\nRequestId:47a6a1bb-5a89-47e9-8dda-954ba86566dd\\nTime:2024-08-09T14:03:38.156Z\"}}}\r\n\r\nHeaders:\r\nServer: Azurite-Table/3.31.0\r\nx-ms-error-code: REDACTED\r\nx-ms-request-id: 47a6a1bb-5a89-47e9-8dda-954ba86566dd\r\nx-ms-version: REDACTED\r\nDate: Fri, 09 Aug 2024 14:03:38 GMT\r\nConnection: keep-alive\r\nKeep-Alive: REDACTED\r\nTransfer-Encoding: chunked\r\nContent-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8\r\n
```

Health check source code:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Azure.Data.Tables/AzureTableServiceHealthCheck.cs

### Steps to reproduce the issue?

After switching to Azurite, using the default health checker that comes with the Aspire component for adding azure table storage, the health check is receiving a 400 bad request.

1. Create a new Aspire app
2. Add azurite to apphost
  ```C#
  // Add Azure Storage
  var storage = builder.AddAzureStorage("storage")
      .RunAsEmulator(c => c.WithImageTag("3.31.0").WithDataVolume();
  );
  var yourComponent = storage.AddTables("yourcomponent");
  ```
3. Add a client app which loads the component, then enable health checks
  ```C#
  builder.AddKeyedAzureTableClient("yourcomponent");
  ```

### Have you found a mitigation/solution?

Not yet

**Comment by onionhammer** [comment]
FYI This is still happening with .NET 9, latest aspire

**Comment by blueww** [comment]
@EmmaZhu 
Would you please help to look?

@onionhammer 
Would you please share the Azurite debug log to help investigation?

**Comment by onionhammer** [comment]
This is the only relevant log the container spits out:

2024-11-15T08:24:11 172.17.0.1 - - [15/Nov/2024:14:24:11 +0000] "GET /devstoreaccount1/Tables?$format=application%2Fjson%3Bodata%3Dminimalmetadata&$filter=false HTTP/1.1" 400 -

**Comment by causer** [comment]
I have the same issue. Looks like this call causes the exception:
` await _tableServiceClient
                .QueryAsync(filter: "false", cancellationToken: cancellationToken)`

Health check source code:
[
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Azure.Data.Tables/AzureTableServiceHealthCheck.cs](url)

So, azurite don't like such query filter.

**Comment by causer** [comment]
The workaround is to disable built-in health check:

`builder.AddAzureTableClient("connectionname", settings => settings.DisableHealthChecks = true);`

and add your own health check.

**Comment by bbrysh** [comment]
> This is the only relevant log the container spits out:
> 
> 2024-11-15T08:24:11 172.17.0.1 - - [15/Nov/2024:14:24:11 +0000] "GET /devstoreaccount1/Tables?$format=application%2Fjson%3Bodata%3Dminimalmetadata&$filter=false HTTP/1.1" 400 -

Whatever is emitting that query is forgetting to put () after Tables. I'm not sure but I think this may be a problem with the Azure table client?

**Comment by AdrianoAE** [comment]
Any update on this?

**Comment by blueww** [comment]
Could anyone share the Azurite debug log (run Azurite with "--debug [log path]")?
Please also share the issue request, and what's expected responds from Azurite, and what's the actually responds.

**Comment by AdrianoAE** [comment]
From the Azurite logs `GET /devstoreaccount1/Tables?$format=application%2Fjson%3Bodata%3Dminimalmetadata&$filter=false HTTP/1.1" 400 -`

From Aspire:
```logs
Azure.RequestFailedException: The query condition specified in the request is invalid.
RequestId:64424b9c-103b-4fc3-8724-13d739c6449b
Time:2025-03-29T17:50:03.545Z
      Status: 400 (Bad Request)
      ErrorCode: InvalidInput
      
      Content:
      {"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"The query condition specified in the request is invalid.\nRequestId:64424b9c-103b-4fc3-8724-13d739c6449b\nTime:2025-03-29T17:50:03.545Z"}}}
      
      Headers:
      Server: Azurite-Table/3.33.0
      x-ms-error-code: REDACTED
      x-ms-request-id: 64424b9c-103b-4fc3-8724-13d739c6449b
      x-ms-version: REDACTED
      Date: Sat, 29 Mar 2025 17:50:03 GMT
      Connection: keep-alive
      Keep-Alive: REDACTED
      Transfer-Encoding: chunked
      Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
      
         at Azure.Data.Tables.TableRestClient.QueryAsync(String nextTableName, QueryOptions queryOptions, CancellationToken cancellationToken)
         at Azure.Data.Tables.TableServiceClient.<>c__DisplayClass34_0.<<QueryAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
         at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
         at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
         at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at HealthChecks.Azure.Data.Tables.AzureTableServiceHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in /home/runner/work/AspNetCore.Diagnostics.HealthChecks/AspNetCore.Diagnostics.HealthChecks/src/HealthChecks.Azure.Data.Tables/AzureTableServiceHealthCheck.cs:line 52
```

**Comment by blueww** [comment]
> Also reported here [#1573](https://github.com/Azure/Azurite/issues/1573) with the logs
> 
> As reported by the OP, when using Aspire:
> 
> From the Azurite logs `GET /devstoreaccount1/Tables?$format=application%2Fjson%3Bodata%3Dminimalmetadata&$filter=false HTTP/1.1" 400 -`
> 
> From Aspire:
> 
> ```
> Azure.RequestFailedException: The query condition specified in the request is invalid.
> RequestId:64424b9c-103b-4fc3-8724-13d739c6449b
> Time:2025-03-29T17:50:03.545Z
>       Status: 400 (Bad Request)
>       ErrorCode: InvalidInput
>       
>       Content:
>       {"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"The query condition specified in the request is invalid.\nRequestId:64424b9c-103b-4fc3-8724-13d739c6449b\nTime:2025-03-29T17:50:03.545Z"}}}
>       
>       Headers:
>       Server: Azurite-Table/3.33.0
>       x-ms-error-code: REDACTED
>       x-ms-request-id: 64424b9c-103b-4fc3-8724-13d739c6449b
>       x-ms-version: REDACTED
>       Date: Sat, 29 Mar 2025 17:50:03 GMT
>       Connection: keep-alive
>       Keep-Alive: REDACTED
>       Transfer-Encoding: chunked
>       Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
>       
>          at Azure.Data.Tables.TableRestClient.QueryAsync(String nextTableName, QueryOptions queryOptions, CancellationToken cancellationToken)
>          at Azure.Data.Tables.TableServiceClient.<>c__DisplayClass34_0.<<QueryAsync>b__0>d.MoveNext()
>       --- End of stack trace from previous location ---
>          at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
>          at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>          at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
>          at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
>          at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>          at HealthChecks.Azure.Data.Tables.AzureTableServiceHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in /home/runner/work/AspNetCore.Diagnostics.HealthChecks/AspNetCore.Diagnostics.HealthChecks/src/HealthChecks.Azure.Data.Tables/AzureTableServiceHealthCheck.cs:line 52
> ```

Hi @AdrianoAE ，

Thanks for the sharing!
However, this is not Azurite debug log. 

Azurite debug log is get by running Azurite with "--debug [log path]".
The log you share above is client side error, we are not expect of client side, and from the client error, we can't find why the error happen on server side. We need to look into the Azurite debug log to know what happened.

**Comment by AdrianoAE** [comment]
@blueww well, was a fun time learning how to get the debug working with Aspire 

```
info: TableStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/Tables?$format=application%2Fjson%3Bodata%3Dminimalmetadata&$filter=false RequestHeaders:{"host":"127.0.0.1:27003","x-ms-version":"2020-12-06","dataserviceversion":"3.0","accept":"application/json;odata=minimalmetadata","x-ms-client-request-id":"699ac0af-bbd0-43dd-94d9-7b6b8fc1145d","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Data.Tables/12.10.0 (.NET 9.0.2; Microsoft Windows 10.0.26100)","x-ms-date":"Mon, 31 Mar 2025 18:29:00 GMT","authorization":"SharedKeyLite devstoreaccount1:K5QekqEORhocjdmaXokdltmnqfSyFtjC+NV4alGfXOw=","traceparent":"00-f184afb7bd600ad36856ea5307d158ad-00274eb707a4da62-01"} ClientIP=172.18.0.1 Protocol=http HTTPVersion=1.1
debug: tableStorageContextMiddleware: Dispatch pattern string: /Tables
info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=undefined
verbose: DispatchMiddleware: Dispatching request...
info: DispatchMiddleware: Operation=Table_Query
verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
info: TableSharedKeyLiteAuthenticator:validate() [STRING TO SIGN]:"Mon, 31 Mar 2025 18:29:00 GMT\n/devstoreaccount1/devstoreaccount1/Tables"
info: TableSharedKeyLiteAuthenticator:validate() Calculated authentication header based on key1: SharedKeyLite devstoreaccount1:K5QekqEORhocjdmaXokdltmnqfSyFtjC+NV4alGfXOw=
info: TableSharedKeyLiteAuthenticator:validate() Signature 1 matched.
verbose: DeserializerMiddleware: Start deserializing...
info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"format":"application/json;odata=minimalmetadata","filter":"false"},"requestId":"699ac0af-bbd0-43dd-94d9-7b6b8fc1145d","dataServiceVersion":"3.0"},"version":"2020-12-06"}
error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
error: ErrorMiddleware: ErrorName=StorageError ErrorMessage="The query condition specified in the request is invalid."  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"InvalidInput","x-ms-request-id":"cd1af397-2f6d-487e-86bd-f3e627483391","x-ms-version":"2025-01-05"} ErrorHTTPBody="{\"odata.error\":{\"code\":\"InvalidInput\",\"message\":{\"lang\":\"en-US\",\"value\":\"The query condition specified in the request is invalid.\\nRequestId:cd1af397-2f6d-487e-86bd-f3e627483391\\nTime:2025-03-31T18:29:00.307Z\"}}}" ErrorStack="\"StorageError: The query condition specified in the request is invalid.\\n    at StorageErrorFactory.getQueryConditionInvalid (/opt/azurite/dist/src/table/errors/StorageErrorFactory.js:83:16)\\n    at LokiTableMetadataStore.queryTable (/opt/azurite/dist/src/table/persistence/LokiTableMetadataStore.js:179:49)\\n    at TableHandler.query (/opt/azurite/dist/src/table/handlers/TableHandler.js:74:71)\\n    at /opt/azurite/dist/src/table/generated/middleware/HandlerMiddlewareFactory.js:58:18\\n    at /opt/azurite/dist/src/table/generated/ExpressMiddlewareFactory.js:77:63\\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:328:13)\\n    at /opt/azurite/node_modules/express/lib/router/index.js:286:9\\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:346:12)\\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:280:10)\""
error: ErrorMiddleware: Set HTTP code: 400
error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidInput
error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=cd1af397-2f6d-487e-86bd-f3e627483391
error: ErrorMiddleware: Set HTTP Header: x-ms-version=2025-01-05
error: ErrorMiddleware: Set content type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
error: ErrorMiddleware: Set HTTP body: "{\"odata.error\":{\"code\":\"InvalidInput\",\"message\":{\"lang\":\"en-US\",\"value\":\"The query condition specified in the request is invalid.\\nRequestId:cd1af397-2f6d-487e-86bd-f3e627483391\\nTime:2025-03-31T18:29:00.307Z\"}}}"
info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=400 StatusMessage=Bad Request Headers={"server":"Azurite-Table/3.33.0","x-ms-error-code":"InvalidInput","x-ms-request-id":"cd1af397-2f6d-487e-86bd-f3e627483391","x-ms-version":"2025-01-05","content-type":"application/json;odata=minimalmetadata;streaming=true;charset=utf-8"}
```

**Comment by blueww** [comment]
Hi @AdrianoAE 

Thanks for the debug log!

I have tried to repro it on the latest Azurite release, but can't repro. 
(I use SAS credencial)
```
2025-04-01T06:54:26.808Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: TableStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/Tables?=application%2Fjson%3Bodata%3Dminimalmetadata&=false&sv=2025-05-05&ss=t&srt=sco&se=2025-04-01T07%3A53%3A47Z&sp=rwdlup&sig=*** RequestHeaders:{"x-ms-version":"2020-12-06","accept":"application/json;odata=minimalmetadata","user-agent":"Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.26100.2161","host":"127.0.0.1:10002"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2025-04-01T06:54:26.809Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 debug: tableStorageContextMiddleware: Dispatch pattern string: /Tables
2025-04-01T06:54:26.809Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=undefined
2025-04-01T06:54:26.809Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 verbose: DispatchMiddleware: Dispatching request...
2025-04-01T06:54:26.810Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: DispatchMiddleware: Operation=Table_Query
2025-04-01T06:54:26.810Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2025-04-01T06:54:26.810Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2025-04-01T06:54:26.810Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: TableSharedKeyLiteAuthenticator:validate() Request doesn't include valid authentication header. Skip SharedKeyLite authentication.
2025-04-01T06:54:26.811Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: TableSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2025-04-01T06:54:26.811Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: TableSharedKeyAuthenticator:validate() Request doesn't include valid authentication header. Skip shared key authentication.
2025-04-01T06:54:26.811Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: AccountSASAuthenticator:validate() Start validation against account Shared Access Signature pattern.
2025-04-01T06:54:26.811Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 debug: AccountSASAuthenticator:validate() Getting account properties...
2025-04-01T06:54:26.812Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 debug: AccountSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, table: undefined
2025-04-01T06:54:26.812Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 debug: AccountSASAuthenticator:validate() Got account properties successfully.
2025-04-01T06:54:26.812Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 debug: AccountSASAuthenticator:validate() Retrieved signature from URL parameter sig: FuTUN0KI0ZU/cJHKU+va+aU8uVBB+s71KT3miCs4fag=
2025-04-01T06:54:26.812Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 debug: AccountSASAuthenticator:validate() Successfully got valid account SAS values from request. {"version":"2025-05-05","expiryTime":"2025-04-01T07:53:47Z","permissions":"rwdlup","services":"t","resourceTypes":"sco"}
2025-04-01T06:54:26.812Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: AccountSASAuthenticator:validate() Validate signature based account key1.
2025-04-01T06:54:26.812Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 debug: AccountSASAuthenticator:validate() String to sign is: "devstoreaccount1\nrwdlup\nt\nsco\n\n2025-04-01T07:53:47Z\n\n\n2025-05-05\n\n"
2025-04-01T06:54:26.812Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 debug: AccountSASAuthenticator:validate() Calculated signature is: **
2025-04-01T06:54:26.813Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: AccountSASAuthenticator:validate() Signature based on key1 validation passed.
2025-04-01T06:54:26.813Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: AccountSASAuthenticator:validate() Validate start and expiry time.
2025-04-01T06:54:26.813Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: AccountSASAuthenticator:validate() Validate IP range.
2025-04-01T06:54:26.813Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: AccountSASAuthenticator:validate() Validate request protocol.
2025-04-01T06:54:26.813Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 debug: AccountSASAuthenticator:validate() Got permission requirements for operation Table_Query - {"service":"t","resourceType":"c","permission":"l"}
2025-04-01T06:54:26.813Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: AccountSASAuthenticator:validate() Account SAS validation successfully.
2025-04-01T06:54:26.813Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 verbose: DeserializerMiddleware: Start deserializing...
2025-04-01T06:54:26.814Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{}},"version":"2020-12-06"}
2025-04-01T06:54:26.814Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 verbose: SerializerMiddleware: Start serializing...
2025-04-01T06:54:26.815Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 debug: Serializer: Raw response body string is {"odata.metadata":"http://127.0.0.1:10002/devstoreaccount1/$metadata#Tables","value":[{"TableName":"test1"},{"TableName":"test2"}]}
2025-04-01T06:54:26.815Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: Serializer: Start returning stream body.
2025-04-01T06:54:26.816Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 verbose: Send Table telemetry: T_Table_Query
2025-04-01T06:54:26.816Z 7d2a120c-9c80-4c5e-b053-e1df922d9169 info: EndMiddleware: End response. TotalTimeInMS=8 StatusCode=200 StatusMessage=OK Headers={"server":"Azurite-Table/3.34.0","content-type":"application/json;odata=minimalmetadata","x-ms-request-id":"7d2a120c-9c80-4c5e-b053-e1df922d9169","x-ms-version":"2025-05-05","date":"Tue, 01 Apr 2025 06:54:26 GMT"}

```

**Comment by blueww** [comment]
@AdrianoAE 

Thanks for the sharing!

It looks the issue is caused by the `LokiTableStoreQueryGenerator.generateQueryTableWhereFunction()` can't parse filter query string "false" or "". 
https://github.com/Azure/Azurite/blob/7032904936ec34e793e57886748ab0c7531c410f/src/table/persistence/LokiTableStoreQueryGenerator.ts#L47

As possible fix might be just handle filter query string in same way as undefined when it's "false" or "" .

@edwin-huber , @XiaoningLiu , @EmmaZhu  Do you have any comments/concern for the way to fix it by handle filter query string "false" or "" in the same way as undefined?

**Comment by XiaoningLiu** [comment]
> [@AdrianoAE](https://github.com/AdrianoAE)
> 
> Thanks for the sharing!
> 
> It looks the issue is caused by the [generateQueryTableWhereFunction()](https://github.com/Azure/Azurite/blob/7032904936ec34e793e57886748ab0c7531c410f/src/table/persistence/LokiTableStoreQueryGenerator.ts#L47) can't parse filter query string "false" or "true" or "".
> 
> A possible fix might be just handle filter query string "true" or "" to return all tables (in same way as undefined), and handle "false" to return no tables .
> 
> [@edwin-huber](https://github.com/edwin-huber) , [@XiaoningLiu](https://github.com/XiaoningLiu) , [@EmmaZhu](https://github.com/EmmaZhu) Do you have any comments/concern for the way to fix it?
> 
> A sample code change for the fix: Change line 50-52 in
> 
> [Azurite/src/table/persistence/LokiTableStoreQueryGenerator.ts](https://github.com/Azure/Azurite/blob/7032904936ec34e793e57886748ab0c7531c410f/src/table/persistence/LokiTableStoreQueryGenerator.ts#L51)
> 
> Line 51 in [7032904](/Azure/Azurite/commit/7032904936ec34e793e57886748ab0c7531c410f)
> 
>  return () => true; 
> 
> From
> ```
>     if (query === undefined) {
>       return () => true;
>     }
> ```
> 
> To
> 
> ```
>     if (query === undefined || query === "" || query === "true") {
>       return () => true;
>     }
>     if (query === "false") {
>       return () => false;
>     }
> ```

Looks good. Better to cross check when will query be `undefined`

**Comment by blueww** [comment]
Hi @XiaoningLiu 

Thanks for the confirmation!
query be undefined means there are no query, so all tables will be returned.

I see a customer PR has raised to fix this issue with the same way in my comment. [#2545](https://github.com/Azure/Azurite/pull/2545) Emma is looking at the PR. 
The PR not only fixed the the table query, but also table entity query. @EmmaZhu , we might should also check if table entity query behavior with "false" or "true" or "" is aligned between product Azure  and fixed Azurite.

**Comment by illay1994** [comment]
Hi @blueww 
I was looking at C# health check library.
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Azure.Data.Tables/AzureTableServiceHealthCheck.cs

![Image](https://github.com/user-attachments/assets/1afa0ccd-d0ab-4a33-8f11-c7db420a8100)

We have the same filter query for tables and table entities.
