### ISSUE TITLE
[Table Storage] Azurite query behavior different from Azure for null values

### ISSUE THREAD

**Issue by yohny** [Azure/Azurite#2471]
The behavior when querying Azurite table storage and real Azure table storage is different.
The query `myCol eq null` works without issue against Azurite table storage, but when executed against real Azure table storage the error occures:
```
Exception: {"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"One of the request inputs is not valid.\nRequestId:10d6a929-e002-007e-4cd3-110d71000000\nTime:2024-09-28T18:25:57.3856306Z"}}}
Stack: RestError: {"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"One of the request inputs is not valid.\nRequestId:10d6a929-e002-007e-4cd3-110d71000000\nTime:2024-09-28T18:25:57.3856306Z"}}}
    at handleErrorResponse (C:\Users\nej\source\repos\azf-samples-ts\node_modules\@azure\core-client\dist\commonjs\deserializationPolicy.js:148:19)
    at deserializeResponseBody (C:\Users\nej\source\repos\azf-samples-ts\node_modules\@azure\core-client\dist\commonjs\deserializationPolicy.js:83:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5).
```

Azurite 3.32.0

**Comment by blueww** [comment]
@EmmaZhu  Would you please help to look?

**Comment by WolfspiritM** [comment]
We also experienced a similar issue when it comes to default aspire Healthchecks:
https://github.com/Azure/Azurite/issues/2450

The reason is that the healthcheck uses a filter of just "false" so no elements get returned but azurite seems to not like that:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/116a4eac95eac47d1811d33a1f93b053ff87fa19/src/HealthChecks.Azure.Data.Tables/AzureTableServiceHealthCheck.cs#L38

I think "false" and also maybe "true" even so they don't make much sense in general use cases should be supported here.
