### ISSUE TITLE
Hadoop File access the Azurite failed.

### ISSUE THREAD

**Issue by horizonzy** [Azure/Azurite#2520]
In my integration test, I tried to write the parquet file into Azurite, but it showed `400` request error.

This is my Hadoop configuration.
```
        hadoopConf.set("fs.abfs.impl", AzureBlobFileSystem.class.getName());
        hadoopConf.set(ConfigurationKeys.FS_AZURE_ACCOUNT_AUTH_TYPE_PROPERTY_NAME + "." + azureHost, "SharedKey");
        hadoopConf.set(ConfigurationKeys.FS_AZURE_ACCOUNT_KEY_PROPERTY_NAME + "." + azureHost,
                "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==");
        hadoopConf.set(ConfigurationKeys.AZURE_ABFS_ENDPOINT + "." + azureHost,
                "127.0.0.1:10000");
        hadoopConf.set(ConfigurationKeys.FS_AZURE_ALWAYS_USE_HTTPS, "false");
```

And this is the exception during the test.
```
org.apache.hadoop.fs.azurebfs.contracts.exceptions.AbfsRestOperationException: Operation failed: "Bad Request", 400, PUT, http://127.0.0.1:10000/devstoreaccount1/ursa-test/compaction/public/default/test-topic-2/part-0000-535f51db-e74b-4f99-97ce-ba137caa14e1-c000.zstd.parquet?resource=file&timeout=90, rId: , , ""
	at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.completeExecute(AbfsRestOperation.java:289) ~[hadoop-azure-3.4.1.jar:?]
	at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.lambda$execute$0(AbfsRestOperation.java:235) ~[hadoop-azure-3.4.1.jar:?]
	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.measureDurationOfInvocation(IOStatisticsBinding.java:494) ~[hadoop-common-3.4.1.jar:?]
	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDurationOfInvocation(IOStatisticsBinding.java:465) ~[hadoop-common-3.4.1.jar:?]
	at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.execute(AbfsRestOperation.java:233) ~[hadoop-azure-3.4.1.jar:?]
	at org.apache.hadoop.fs.azurebfs.services.AbfsClient.createPath(AbfsClient.java:533) ~[hadoop-azure-3.4.1.jar:?]
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.createFile(AzureBlobFileSystemStore.java:680) ~[hadoop-azure-3.4.1.jar:?]
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.create(AzureBlobFileSystem.java:372) ~[hadoop-azure-3.4.1.jar:?]
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1233) ~[hadoop-common-3.4.1.jar:?]
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1210) ~[hadoop-common-3.4.1.jar:?]
	at org.apache.parquet.hadoop.util.HadoopOutputFile.create(HadoopOutputFile.java:74) ~[parquet-hadoop-1.13.1.jar:1.13.1]
	at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:347) ~[parquet-hadoop-1.13.1.jar:1.13.1]
	at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:314) ~[parquet-hadoop-1.13.1.jar:1.13.1]
	at org.apache.parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:292) ~[parquet-hadoop-1.13.1.jar:1.13.1]
	at org.apache.parquet.hadoop.ParquetWriter$Builder.build(ParquetWriter.java:707) ~[parquet-hadoop-1.13.1.jar:1.13.1]
```

And I find the same error logs in the Azurite contains
```
2024-12-19 20:48:50 192.168.65.1 - - [19/Dec/2024:12:48:50 +0000] "PUT /devstoreaccount1/ursa-test/compaction/public/default/test-topic-2/part-0000-f7cf76e5-5a2c-4743-a690-8743c8fed7d1-c000.zstd.parquet?resource=file&timeout=90 HTTP/1.1" 400 -
```

It shows that the request was already sent to azurite, but the azurite returned the `400` status, how did I trace the issue. Is there any way to know why the azurite return `400` code?

Hadoop version: 3.4.1
Azurite version: 3.33.0

**Comment by blueww** [comment]
@horizonzy 

Azurite still not support datalakegen2. 
From https://github.com/Azure/Azurite#:~:text=Blob%2C%20Queue%2C%20and%20Table, you can see Azurite currently only support Blob, Queue and Table services.

**Comment by horizonzy** [comment]
Thanks, got it.
