### ISSUE TITLE
Incoming URL doesn't match any of swagger defined request patterns

### ISSUE THREAD

**Issue by jpsaraiva** [Azure/Azurite#258]
Hi,

I'm using Azurite-Blob/3.1.2-preview and getting the message in the title when calling a fairly standard URL to put a new blob:
http://localhost/devstoreaccount1/teste/green.png

```
2019-09-17T16:33:30.653Z 1e0514da-455f-46b0-8152-06619d1bb326 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://localhost/devstoreaccount1/teste/green.png RequestHeaders:{"host":"localhost:10000","x-ms-version":"2018-03-28","content-enconding":"","content-language":"","content-length":"2784","content-md5":"","content-type":"","if-modified-since":"","if-match":"","if-none-match":"","if-unmodified-since":"","range":"","x-ms-date":"17-SEP-19 17.33.30.645000","authorization":"SharedKey devstoreaccount1:0f460687a872072434eefb756220bea85dfba0c194e80df06fc1c8375a897af4","connection":"close"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2019-09-17T16:33:30.653Z 1e0514da-455f-46b0-8152-06619d1bb326 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=teste Blob=green.png
2019-09-17T16:33:30.653Z 1e0514da-455f-46b0-8152-06619d1bb326 verbose: DispatchMiddleware: Dispatching request...
2019-09-17T16:33:30.654Z 1e0514da-455f-46b0-8152-06619d1bb326 error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2019-09-17T16:33:30.654Z 1e0514da-455f-46b0-8152-06619d1bb326 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2019-09-17T16:33:30.654Z 1e0514da-455f-46b0-8152-06619d1bb326 error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at Object.dispatchMiddleware [as default] (C:\\var\\Azurite-master\\dist\\src\\blob\\generated\\middleware\\dispatch.middleware.js:41:30)\n    at C:\\var\\Azurite-master\\dist\\src\\blob\\generated\\ExpressMiddlewareFactory.js:49:42\n    at Layer.handle [as handle_request] (C:\\var\\Azurite-master\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\var\\Azurite-master\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\var\\Azurite-master\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\var\\Azurite-master\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\var\\Azurite-master\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at blobStorageContextMiddleware (C:\\var\\Azurite-master\\dist\\src\\blob\\context\\blobStorageContext.middleware.js:51:5)\n    at Layer.handle [as handle_request] (C:\\var\\Azurite-master\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\var\\Azurite-master\\node_modules\\express\\lib\\router\\index.js:317:13)"
2019-09-17T16:33:30.654Z 1e0514da-455f-46b0-8152-06619d1bb326 error: ErrorMiddleware: Set HTTP code: 400
2019-09-17T16:33:30.654Z 1e0514da-455f-46b0-8152-06619d1bb326 error: ErrorMiddleware: Set HTTP body: undefined
2019-09-17T16:33:30.654Z 1e0514da-455f-46b0-8152-06619d1bb326 info: EndMiddleware: End response. TotalTimeInMS=1 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.1.2-preview"}
```

Similar request, to create a container does its job, but says that there are undefined headers:

```
2019-09-17T16:40:17.080Z 22a52ddd-40a5-4db5-9d29-818798df8cae info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://localhost/devstoreaccount1/alpha?restype=container RequestHeaders:{"host":"localhost:10000","x-ms-version":"2018-03-28","content-enconding":"","content-language":"","content-length":"","content-md5":"","content-type":"application/xml","if-modified-since":"","if-match":"","if-none-match":"","if-unmodified-since":"","range":"","x-ms-date":"17-SEP-19 17.40.17.049000","authorization":"SharedKey devstoreaccount1:HQKC0pBSwzW16eITZi4D7MeiUH1guag8egHagPxfPC0=","connection":"close"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2019-09-17T16:40:17.080Z 22a52ddd-40a5-4db5-9d29-818798df8cae info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=alpha Blob=
2019-09-17T16:40:17.080Z 22a52ddd-40a5-4db5-9d29-818798df8cae verbose: DispatchMiddleware: Dispatching request...
2019-09-17T16:40:17.080Z 22a52ddd-40a5-4db5-9d29-818798df8cae info: DispatchMiddleware: Operation=Container_Create
2019-09-17T16:40:17.080Z 22a52ddd-40a5-4db5-9d29-818798df8cae verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-09-17T16:40:17.081Z 22a52ddd-40a5-4db5-9d29-818798df8cae info: PublicAccessAuthenticator:validate() Start validation against public access.
2019-09-17T16:40:17.081Z 22a52ddd-40a5-4db5-9d29-818798df8cae debug: PublicAccessAuthenticator:validate() Getting account properties...
2019-09-17T16:40:17.081Z 22a52ddd-40a5-4db5-9d29-818798df8cae debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: alpha, blob:
2019-09-17T16:40:17.082Z 22a52ddd-40a5-4db5-9d29-818798df8cae debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container alpha
2019-09-17T16:40:17.082Z 22a52ddd-40a5-4db5-9d29-818798df8cae info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-09-17T16:40:17.082Z 22a52ddd-40a5-4db5-9d29-818798df8cae info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n\n\napplication/xml\n\n\n\n\n\n\nx-ms-date:17-SEP-19 17.40.17.049000\nx-ms-version:2018-03-28\n/devstoreaccount1/devstoreaccount1/alpha\nrestype:container"
2019-09-17T16:40:17.083Z 22a52ddd-40a5-4db5-9d29-818798df8cae info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:HQKC0pBSwzW16eITZi4D7MeiUH1guag8egHagPxfPC0=
2019-09-17T16:40:17.083Z 22a52ddd-40a5-4db5-9d29-818798df8cae info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2019-09-17T16:40:17.083Z 22a52ddd-40a5-4db5-9d29-818798df8cae verbose: DeserializerMiddleware: Start deserializing...
2019-09-17T16:40:17.083Z 22a52ddd-40a5-4db5-9d29-818798df8cae info: HandlerMiddleware: DeserializedParameters={"options":{"metadata":{}},"restype":"container","version":"2018-03-28"}
2019-09-17T16:40:17.084Z 22a52ddd-40a5-4db5-9d29-818798df8cae verbose: SerializerMiddleware: Start serializing...
2019-09-17T16:40:17.084Z 22a52ddd-40a5-4db5-9d29-818798df8cae info: EndMiddleware: End response. TotalTimeInMS=4 StatusCode=201 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.1.2-preview","etag":"\"d-dQPnU6fHRBHttxzO3qxhhevYTIQ\"","last-modified":"Tue, 17 Sep 2019 16:40:17 GMT","x-ms-request-id":"22a52ddd-40a5-4db5-9d29-818798df8cae","x-ms-version":"2018-03-28"}
```
Am I missing something?

**Comment by XiaoningLiu** [comment]
@jpsaraiva I think you missed required header "x-ms-blob-type" when creating blob. See https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob

Create container is successful according to the log. Which undefind header are your referring to?

**Comment by jpsaraiva** [comment]
Hi Xiaoning,

You are correct, missing header despite having it on the stringtosign, it's now working. Thanks!

Regarding the undefined headers when creating a container, this is the response from azurite:
End response. TotalTimeInMS=1 StatusCode=201 StatusMessage=**undefined Headers**={"server":"Azurite-Blob/3.1.2-preview","etag":"\"d-A/Mzqn5yaBJW8TBXCCoDHUUw3og\"","last-modified":"Wed, 18 Sep 2019 09:55:44 GMT","x-ms-request-id":"b1d5ed6a-93bf-422f-acfb-879c36e9a546","x-ms-version":"2018-03-28"}

I thought it might have been because I was setting all the headers in my code even if I had no values form them, but removing does not change the behavior.

**Comment by XiaoningLiu** [comment]
Aha. `undefined` is for `StatusMessage` not for `Headers`.

**Comment by jpsaraiva** [comment]
Oh, I see. I thought there would be something wrong with the headers.
All solved and working, thanks!
