### ISSUE TITLE
Get/download blob snapshot fail with 404

### ISSUE THREAD

**Issue by blueww** [Azure/Azurite#293]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code
### What's the Node.js version?
v10.15.3
### What problem was encountered?
Get/download blob snapshot always fail with 404, while Create snapshot works well, list also include snapshot. 
Test with Powershell, which based on .NET Storage client library v11.0
### Steps to reproduce the issue?
create snapshot of a blob, them try to download it.

> 2019-12-12T04:02:39.107Z 399cb32e-d412-4f2d-b402-674adf0cf429 info: HandlerMiddleware: DeserializedParameters={"options":{"snapshot":"2019-12-12T04:02:19.0110000Z","leaseAccessConditions":{},"cpkInfo":{},"modifiedAccessConditions":{}}}
> 2019-12-12T04:02:39.108Z 399cb32e-d412-4f2d-b402-674adf0cf429 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
> 2019-12-12T04:02:39.108Z 399cb32e-d412-4f2d-b402-674adf0cf429 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified blob does not exist.  ErrorHTTPStatusCode=404 ErrorHTTPStatusMessage=The specified blob does not exist. ErrorHTTPHeaders={"x-ms-error-code":"BlobNotFound","x-ms-request-id":"399cb32e-d412-4f2d-b402-674adf0cf429"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>BlobNotFound</Code>\n  <Message>The specified blob does not exist.\nRequestId:399cb32e-d412-4f2d-b402-674adf0cf429\nTime:2019-12-12T04:02:39.107Z</Message>\n</Error>" ErrorStack="StorageError: The specified blob does not exist.\n    at Function.getBlobNotFound (C:\\code\\azurite\\src\\blob\\errors\\StorageErrorFactory.ts:35:12)\n    at LokiBlobMetadataStore.getBlobWithLeaseUpdated (C:\\code\\azurite\\src\\blob\\persistence\\LokiBlobMetadataStore.ts:2487:35)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
> 2019-12-12T04:02:39.109Z 399cb32e-d412-4f2d-b402-674adf0cf429 error: ErrorMiddleware: Set HTTP code: 404
> 

### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
This is because the Snapshot time has different format in Js and .NET.
Js has 3 digital of ms.
2019-12-13T06:23:17.475Z

But actually snapshot time has 7 digital of ms. 
2019-12-13T06:23:17.4750000Z

I will fix it.

**Comment by blueww** [comment]
Fixed
