### ISSUE TITLE
[blob] BlockBlobClient..setAccessTier() encounters SAS error

### ISSUE THREAD

**Issue by ljian3377** [Azure/Azurite#306]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
v12.13.0
### What problem was encountered?
Sample failure: azure-sdk-for-js/sdk/storage/storage-blob/samples/typescript/advanced.ts
```
await blockBlobClient.setAccessTier("Archive");
```
Failed with "ErrorMessage=AccountSASAuthenticator:validate() OPERATION_ACCOUNT_SAS_PERMISSIONS doesn't have configuration for operation Blob_SetTier's account SAS permission."
Using a SAS with `sp=rwdlacup`.

### debug.log
```
2019-12-16T08:35:33.092Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/newcontainer1576485332080/newblob1576485332203?sv=2019-02-02&ss=btqf&srt=sco&spr=https%2Chttp&st=2019-12-16T05%3A37%3A03Z&se=2020-03-25T05%3A42%3A03Z&sp=rwdlacup&sig=6DTmbrZlY0EWr8pkag1UZg1nFDt2hNSg%2Fu1X6WZRqGQ%3D&comp=tier RequestHeaders:{"x-ms-access-tier":"Archive","x-ms-version":"2019-02-02","user-agent":"AdvancedSampleV1.0.0 azsdk-js-storageblob/12.0.1 (NODE-VERSION v12.13.0; Windows_NT 10.0.18362)","x-ms-client-request-id":"32f177db-6ecf-4fe4-a6c3-7a4cc35dbe45","cookie":"","accept":"*/*","content-length":"0","accept-encoding":"gzip,deflate","host":"127.0.0.1:10000","connection":"close"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2019-12-16T08:35:33.092Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=newcontainer1576485332080 Blob=newblob1576485332203
2019-12-16T08:35:33.092Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 verbose: DispatchMiddleware: Dispatching request...
2019-12-16T08:35:33.093Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: DispatchMiddleware: Operation=Blob_SetTier
2019-12-16T08:35:33.093Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-12-16T08:35:33.093Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: PublicAccessAuthenticator:validate() Start validation against public access.
2019-12-16T08:35:33.093Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 debug: PublicAccessAuthenticator:validate() Getting account properties...
2019-12-16T08:35:33.093Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: newcontainer1576485332080, blob: newblob1576485332203
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container newcontainer1576485332080
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: BlobSharedKeyAuthenticator:validate() Request doesn't include valid authentication header. Skip shared key authentication.
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: AccountSASAuthenticator:validate() Start validation against account Shared Access Signature pattern.
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 debug: AccountSASAuthenticator:validate() Getting account properties...
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 debug: AccountSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: newcontainer1576485332080, blob: newblob1576485332203
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 debug: AccountSASAuthenticator:validate() Got account properties successfully.
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 debug: AccountSASAuthenticator:validate() Retrieved signature from URL parameter sig: 6DTmbrZlY0EWr8pkag1UZg1nFDt2hNSg/u1X6WZRqGQ=
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 debug: AccountSASAuthenticator:validate() Successfully got valid account SAS values from request. {"version":"2019-02-02","protocol":"https,http","startTime":"2019-12-16T05:37:03Z","expiryTime":"2020-03-25T05:42:03Z","permissions":"rwdlacup","services":"btqf","resourceTypes":"sco"}
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: AccountSASAuthenticator:validate() Validate signature based account key1.
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 debug: AccountSASAuthenticator:validate() String to sign is: "devstoreaccount1\nrwdlacup\nbtqf\nsco\n2019-12-16T05:37:03Z\n2020-03-25T05:42:03Z\n\nhttps,http\n2019-02-02\n"
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 debug: AccountSASAuthenticator:validate() Calculated signature is: 6DTmbrZlY0EWr8pkag1UZg1nFDt2hNSg/u1X6WZRqGQ=
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: AccountSASAuthenticator:validate() Signature based on key1 validation passed.
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: AccountSASAuthenticator:validate() Validate start and expiry time.
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: AccountSASAuthenticator:validate() Validate IP range.
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: AccountSASAuthenticator:validate() Validate request protocol.
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 debug: AccountSASAuthenticator:validate() Got permission requirements for operation Blob_SetTier - undefined
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 error: ErrorMiddleware: Received an error, fill error information to HTTP response
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 error: ErrorMiddleware: ErrorName=Error ErrorMessage=AccountSASAuthenticator:validate() OPERATION_ACCOUNT_SAS_PERMISSIONS doesn't have configuration for operation Blob_SetTier's account SAS permission. ErrorStack="Error: AccountSASAuthenticator:validate() OPERATION_ACCOUNT_SAS_PERMISSIONS doesn't have configuration for operation Blob_SetTier's account SAS permission.\n    at AccountSASAuthenticator.validate (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\authentication\\AccountSASAuthenticator.js:89:19)\n    at AuthenticationMiddlewareFactory.authenticate (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\authentication\\AuthenticationMiddlewareFactory.js:34:40)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 error: ErrorMiddleware: Set HTTP code: 500
2019-12-16T08:35:33.094Z 08eba736-8a52-4f45-8b51-cfcfbbc513f3 info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=500 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.3.0-preview"}
```

**Comment by XiaoningLiu** [comment]
@blueww Added fix, please review PR #342 .
