### ISSUE TITLE
Blob_Download: download page blob failed with "range start value 3145600 doesn't align with 512 boundary."

### ISSUE THREAD

**Issue by blueww** [Azure/Azurite#307]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code
### What's the Node.js version?
v10.15.3
### What problem was encountered?
download page blob failed with "range start value 3145600 doesn't align with 512 boundary."
### Steps to reproduce the issue?
Download Page blob with Seeked blobStream
### Have you found a mitigation/solution?
No

Test Case:
Test Name:	PageBlobReadStreamSeekTest
Test FullName:	Microsoft.Azure.Storage.Blob.BlobReadStreamTest.PageBlobReadStreamSeekTest
Test Source:	C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\BlobReadStreamTest.cs : line 1101
Test Outcome:	Failed
Test Duration:	0:00:26.1399485

Result StackTrace:	
```
at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 274
   at Microsoft.Azure.Storage.Blob.BlobReadStream.DispatchReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Blob\BlobReadStream.cs:line 141
   at Microsoft.Azure.Storage.Blob.BlobReadStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Blob\BlobReadStream.cs:line 57
   at Microsoft.Azure.Storage.Blob.BlobReadStreamTest.BlobReadStreamSeekAndCompare(Stream blobStream, Byte[] bufferToCompare, Int64 offset, Int32 readSize, Int32 expectedReadCount, Boolean isAsync) in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\BlobReadStreamTest.cs:line 989
   at Microsoft.Azure.Storage.Blob.BlobReadStreamTest.BlobReadStreamSeekTest(Stream blobStream, Int64 streamReadSize, Byte[] bufferToCompare, Boolean isAsync) in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\BlobReadStreamTest.cs:line 1014
   at Microsoft.Azure.Storage.Blob.BlobReadStreamTest.PageBlobReadStreamSeekTest() in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\BlobReadStreamTest.cs:line 1119
Result Message:	
Test method Microsoft.Azure.Storage.Blob.BlobReadStreamTest.PageBlobReadStreamSeekTest threw exception: 
Microsoft.Azure.Storage.StorageException: Internal Server Error
```

[debug.log](https://github.com/Azure/Azurite/files/3967164/debug.log)
RequestId: 401f4144-4539-49d5-a2e3-88835b50b008

Another Log:
```
2019-12-17T08:01:04.321Z 966bf73b-56df-4fb9-868c-10c518e80c68 info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/testcfcfcd1277d7b466080b4d2408e14511b/pageblob RequestHeaders:{"x-ms-range":"bytes=496-1007","x-ms-client-request-id":"4a885e8c-d3b0-4d56-a8e1-15830a475d8f","user-agent":"Azure-Storage/11.1.1 (.NET Core; Win32NT 6.2.9200.0)","x-ms-version":"2019-02-02","x-ms-date":"Tue, 17 Dec 2019 08:01:04 GMT","authorization":"SharedKey devstoreaccount1:vsQj0tov9eVbSCgYOfO9tP8kQQ3ForR8Yu2g9qI30eg=","host":"127.0.0.1:10000"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2019-12-17T08:01:04.321Z 966bf73b-56df-4fb9-868c-10c518e80c68 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=testcfcfcd1277d7b466080b4d2408e14511b Blob=pageblob
2019-12-17T08:01:04.322Z 966bf73b-56df-4fb9-868c-10c518e80c68 verbose: DispatchMiddleware: Dispatching request...
2019-12-17T08:01:04.322Z 966bf73b-56df-4fb9-868c-10c518e80c68 info: DispatchMiddleware: Operation=Blob_Download
2019-12-17T08:01:04.322Z 966bf73b-56df-4fb9-868c-10c518e80c68 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-12-17T08:01:04.323Z 966bf73b-56df-4fb9-868c-10c518e80c68 info: PublicAccessAuthenticator:validate() Start validation against public access.
2019-12-17T08:01:04.323Z 966bf73b-56df-4fb9-868c-10c518e80c68 debug: PublicAccessAuthenticator:validate() Getting account properties...
2019-12-17T08:01:04.323Z 966bf73b-56df-4fb9-868c-10c518e80c68 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: testcfcfcd1277d7b466080b4d2408e14511b, blob: pageblob
2019-12-17T08:01:04.327Z 966bf73b-56df-4fb9-868c-10c518e80c68 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container testcfcfcd1277d7b466080b4d2408e14511b
2019-12-17T08:01:04.327Z 966bf73b-56df-4fb9-868c-10c518e80c68 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-12-17T08:01:04.327Z 966bf73b-56df-4fb9-868c-10c518e80c68 info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:4a885e8c-d3b0-4d56-a8e1-15830a475d8f\nx-ms-date:Tue, 17 Dec 2019 08:01:04 GMT\nx-ms-range:bytes=496-1007\nx-ms-version:2019-02-02\n/devstoreaccount1/devstoreaccount1/testcfcfcd1277d7b466080b4d2408e14511b/pageblob"
2019-12-17T08:01:04.327Z 966bf73b-56df-4fb9-868c-10c518e80c68 info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:vsQj0tov9eVbSCgYOfO9tP8kQQ3ForR8Yu2g9qI30eg=
2019-12-17T08:01:04.328Z 966bf73b-56df-4fb9-868c-10c518e80c68 info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2019-12-17T08:01:04.328Z 966bf73b-56df-4fb9-868c-10c518e80c68 verbose: DeserializerMiddleware: Start deserializing...
2019-12-17T08:01:04.328Z 966bf73b-56df-4fb9-868c-10c518e80c68 info: HandlerMiddleware: DeserializedParameters={"options":{"range":"bytes=496-1007","requestId":"4a885e8c-d3b0-4d56-a8e1-15830a475d8f","leaseAccessConditions":{},"cpkInfo":{},"modifiedAccessConditions":{}},"version":"2019-02-02"}
2019-12-17T08:01:04.331Z 966bf73b-56df-4fb9-868c-10c518e80c68 error: ErrorMiddleware: Received an error, fill error information to HTTP response
2019-12-17T08:01:04.331Z 966bf73b-56df-4fb9-868c-10c518e80c68 error: ErrorMiddleware: ErrorName=RangeError ErrorMessage=deserializePageBlobRangeHeader: range start value 496 doesn't align with 512 boundary. ErrorStack="RangeError: deserializePageBlobRangeHeader: range start value 496 doesn't align with 512 boundary.\n    at Object.deserializePageBlobRangeHeader (C:\\code\\azurite\\src\\blob\\utils\\utils.ts:185:11)\n    at BlobHandler.downloadPageBlob (C:\\code\\azurite\\src\\blob\\handlers\\BlobHandler.ts:863:25)\n    at BlobHandler.download (C:\\code\\azurite\\src\\blob\\handlers\\BlobHandler.ts:105:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-12-17T08:01:04.331Z 966bf73b-56df-4fb9-868c-10c518e80c68 error: ErrorMiddleware: Set HTTP code: 500
2019-12-17T08:01:04.332Z 966bf73b-56df-4fb9-868c-10c518e80c68 info: EndMiddleware: End response. TotalTimeInMS=11 StatusCode=500 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.3.0-preview"}

```

**Comment by XiaoningLiu** [comment]
fixed in dev branch.
