### ISSUE TITLE
Messages_Enqueue: failed with "String 'Thu, 29 Aug 31247 12:21:50 GMT' was not recognized as a valid DateTime."

### ISSUE THREAD

**Issue by blueww** [Azure/Azurite#308]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code
### What's the Node.js version?
v10.15.3
### What problem was encountered?
Messages_Enqueue: failed with "String 'Thu, 29 Aug 31247 12:21:50 GMT' was not recognized as a valid DateTime.
### Steps to reproduce the issue?
See following test case and debug log.
### Have you found a mitigation/solution?
No

Test case:

> Test Name:	CloudQueueAddMessageFullParameter
> Test FullName:	Microsoft.Azure.Storage.Queue.CloudQueueMessageTest.CloudQueueAddMessageFullParameter
> Test Source:	C:\code\azure-storage-net\Test\ClassLibraryCommon\Queue\CloudQueueMessageTest.cs : line 1881
> Test Outcome:	Failed
> Test Duration:	0:00:23.355565
> 
> Result StackTrace:	
> at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
>    at System.DateTime.Parse(String s, IFormatProvider provider, DateTimeStyles styles)
>    at Microsoft.Azure.Storage.Shared.Protocol.HttpResponseParsers.ToUTCTime(String str) in C:\code\azure-storage-net\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 43
>    at Microsoft.Azure.Storage.Core.Util.XMLReaderExtensions.ReadElementContentAsDateTimeOffsetAsync(XmlReader reader) in C:\code\azure-storage-net\Lib\Common\Core\Util\AsyncExtensions.Common.cs:line 134
>    at Microsoft.Azure.Storage.Queue.Protocol.GetMessagesResponse.ParseMessageEntryAsync(XmlReader reader, CancellationToken token) in C:\code\azure-storage-net\Lib\Common\Queue\Protocol\GetMessagesResponse.cs:line 82
>    at Microsoft.Azure.Storage.Queue.Protocol.GetMessagesResponse.ParseAsync(Stream stream, CancellationToken token) in C:\code\azure-storage-net\Lib\Common\Queue\Protocol\GetMessagesResponse.cs:line 168
>    at Microsoft.Azure.Storage.Queue.CloudQueue.<>c__DisplayClass154_0.<<AddMessageImpl>b__3>d.MoveNext() in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 2518
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.Storage.Core.Executor.Executor.ProcessEndOfRequestAsync[T](ExecutionState`1 executionState, CancellationToken cancellationToken) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 342
>    at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 197
> --- End of inner exception stack trace ---
>     at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 274
>    at Microsoft.Azure.Storage.Core.Executor.Executor.<>c__DisplayClass0_0`1.<ExecuteSync>b__0() in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 41
>    at Microsoft.Azure.Storage.Core.Util.CommonUtility.RunWithoutSynchronizationContext[T](Func`1 actionToRun) in C:\code\azure-storage-net\Lib\Common\Core\Util\CommonUtility.cs:line 378
>    at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 40
>    at Microsoft.Azure.Storage.Queue.CloudQueue.AddMessage(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 1217
>    at Microsoft.Azure.Storage.Queue.CloudQueueMessageTest.CloudQueueAddMessageFullParameter() in C:\code\azure-storage-net\Test\ClassLibraryCommon\Queue\CloudQueueMessageTest.cs:line 1915
> Result Message:	
> Test method Microsoft.Azure.Storage.Queue.CloudQueueMessageTest.CloudQueueAddMessageFullParameter threw exception: 
> Microsoft.Azure.Storage.StorageException: String 'Thu, 29 Aug 31247 12:21:50 GMT' was not recognized as a valid DateTime. ---> System.FormatException: String 'Thu, 29 Aug 31247 12:21:50 GMT' was not recognized as a valid DateTime.

Debug Log:

> 2019-12-16T09:33:45.606Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 info: QueueStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/libqueuetestbd6f0c1b95db4e58a4c2e677683542c8/messages?messagettl=922337203685 RequestHeaders:{"x-ms-client-request-id":"bcbac19a-bd42-400d-ac15-5c196ed54074","user-agent":"Azure-Storage/11.1.1 (.NET Core; Win32NT 6.2.9200.0)","x-ms-version":"2019-02-02","x-ms-date":"Mon, 16 Dec 2019 09:33:45 GMT","authorization":"SharedKey devstoreaccount1:TckMFQBg9KdgL/w4iATGKT23x0L783fji6aQtIVDnig=","content-length":"141","host":"127.0.0.1:10001"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
> 2019-12-16T09:33:45.607Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 info: QueueStorageContextMiddleware: Account=devstoreaccount1 Queue=libqueuetestbd6f0c1b95db4e58a4c2e677683542c8 Message=messages MessageId=undefined
> 2019-12-16T09:33:45.608Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 verbose: DispatchMiddleware: Dispatching request...
> 2019-12-16T09:33:45.608Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 info: DispatchMiddleware: Operation=Messages_Enqueue
> 2019-12-16T09:33:45.609Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
> 2019-12-16T09:33:45.610Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 info: QueueSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
> 2019-12-16T09:33:45.610Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 info: QueueSharedKeyAuthenticator:validate() [STRING TO SIGN]:"POST\n\n\n141\n\n\n\n\n\n\n\n\nx-ms-client-request-id:bcbac19a-bd42-400d-ac15-5c196ed54074\nx-ms-date:Mon, 16 Dec 2019 09:33:45 GMT\nx-ms-version:2019-02-02\n/devstoreaccount1/devstoreaccount1/libqueuetestbd6f0c1b95db4e58a4c2e677683542c8/messages\nmessagettl:922337203685"
> 2019-12-16T09:33:45.611Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 info: QueueSharedKeyAuthenticator:validate() Calculated authentication header based on key1: devstoreaccount1:TckMFQBg9KdgL/w4iATGKT23x0L783fji6aQtIVDnig=
> 2019-12-16T09:33:45.611Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 info: QueueSharedKeyAuthenticator:validate() Signature 1 matched.
> 2019-12-16T09:33:45.612Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 verbose: DeserializerMiddleware: Start deserializing...
> 2019-12-16T09:33:45.613Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 debug: deserialize(): Raw request body string is ﻿<?xml version="1.0" encoding="utf-8"?><QueueMessage><MessageText>VGhpcyBtZXNzYWdlIGlzIGZvciB0aGUgcHJlc2VudC4=</MessageText></QueueMessage>
> 2019-12-16T09:33:45.614Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 info: HandlerMiddleware: DeserializedParameters={"options":{"messageTimeToLive":922337203685,"requestId":"bcbac19a-bd42-400d-ac15-5c196ed54074"},"version":"2019-02-02","queueMessage":{"messageText":"VGhpcyBtZXNzYWdlIGlzIGZvciB0aGUgcHJlc2VudC4="},"body":"ReadableStream"}
> 2019-12-16T09:33:45.614Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 debug: OperationQueue.operate() Schedule incoming job fb494e48-258c-48b1-8270-4a7d9c3b2a85
> 2019-12-16T09:33:45.614Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 debug: OperationQueue:execute() Current runningConcurrency:0 maxConcurrency:1 operations.length:1
> 2019-12-16T09:33:45.615Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 info: FSExtentStore:appendExtent() Select extent from idle location for extent append operation. LocationId:0 extentId:bf87f92d-9e61-484b-a046-348fe600971b offset:66080 MAX_EXTENT_SIZE:4194304 
> 2019-12-16T09:33:45.615Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 debug: FSExtentStore:appendExtent() Get fd:10 for extent:bf87f92d-9e61-484b-a046-348fe600971b from cache.
> 2019-12-16T09:33:45.615Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 debug: FSExtentStore:appendExtent() Start writing to extent bf87f92d-9e61-484b-a046-348fe600971b
> 2019-12-16T09:33:45.617Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 debug: FSExtentStore:appendExtent() Write finish, start updating extent metadata. extent:{"id":"bf87f92d-9e61-484b-a046-348fe600971b","persistencyId":"Default","path":"bf87f92d-9e61-484b-a046-348fe600971b","size":66124,"lastModifiedInMS":1576488825617}
> 2019-12-16T09:33:45.617Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 debug: FSExtentStore:appendExtent() Update extent metadata done. Resolve()
> 2019-12-16T09:33:45.617Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 debug: OperationQueue.operate() Job fb494e48-258c-48b1-8270-4a7d9c3b2a85 completes callback, resolve.
> 2019-12-16T09:33:45.618Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 verbose: SerializerMiddleware: Start serializing...
> 2019-12-16T09:33:45.619Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 debug: Serializer: Raw response body string is <?xml version="1.0" encoding="UTF-8" standalone="yes"?><QueueMessagesList><QueueMessage><MessageId>dd82f1f8-6014-4d34-b071-f433a1f52dbd</MessageId><InsertionTime>Mon, 16 Dec 2019 09:33:45 GMT</InsertionTime><ExpirationTime>Thu, 29 Aug 31247 12:21:50 GMT</ExpirationTime><PopReceipt>MTZEZWMyMDE5MDk6MzM6NDU0M2Ez</PopReceipt><TimeNextVisible>Mon, 16 Dec 2019 09:33:45 GMT</TimeNextVisible></QueueMessage></QueueMessagesList>
> 2019-12-16T09:33:45.619Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 info: Serializer: Start returning stream body.
> 2019-12-16T09:33:45.619Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 info: EndMiddleware: End response. TotalTimeInMS=13 StatusCode=201 StatusMessage=Created Headers={"server":"Azurite-Queue/3.3.0-preview","x-ms-client-request-id":"bcbac19a-bd42-400d-ac15-5c196ed54074","x-ms-request-id":"8abd1e77-3592-4faa-9156-a1ef0ebe3f26","x-ms-version":"2019-02-02","date":"Mon, 16 Dec 2019 09:33:45 GMT","content-type":"application/xml"}
> 2019-12-16T09:33:45.620Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 debug: OperationQueue:execute() Current runningConcurrency:0 maxConcurrency:1 operations.length:0
> 2019-12-16T09:33:45.620Z 8abd1e77-3592-4faa-9156-a1ef0ebe3f26 debug: OperationQueue:execute() return. Operation.length === 0

**Comment by blueww** [comment]
Fixed.
