### ISSUE TITLE
Queue/Blob:Service_SetProperties: Set Cors with 64 Origins, fail with 400

### ISSUE THREAD

**Issue by blueww** [Azure/Azurite#311]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code
### What's the Node.js version?
v10.15.3
### What problem was encountered?
Queue:Service_SetProperties: Set Cors with 64 Origins, fail with 400
### Steps to reproduce the issue?
See following debug log
### Have you found a mitigation/solution?
No.

Test Case:
```
Test Name:	CloudQueueTestCorsMaxOrigins
Test FullName:	Microsoft.Azure.Storage.Queue.QueueAnalyticsUnitTests.CloudQueueTestCorsMaxOrigins
Test Source:	C:\code\azure-storage-net\Test\ClassLibraryCommon\Queue\QueueAnalyticsUnitTests.cs : line 652
Test Outcome:	Failed
Test Duration:	0:00:00.0118019

Result StackTrace:	
at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 274
   at Microsoft.Azure.Storage.Core.Executor.Executor.<>c__DisplayClass0_0`1.<ExecuteSync>b__0() in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 41
   at Microsoft.Azure.Storage.Core.Util.CommonUtility.RunWithoutSynchronizationContext[T](Func`1 actionToRun) in C:\code\azure-storage-net\Lib\Common\Core\Util\CommonUtility.cs:line 378
   at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 40
   at Microsoft.Azure.Storage.Queue.CloudQueueClient.SetServiceProperties(ServiceProperties properties, QueueRequestOptions requestOptions, OperationContext operationContext) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Queue\CloudQueueClient.cs:line 553
   at Microsoft.Azure.Storage.Queue.QueueAnalyticsUnitTests.TestCorsRules(CloudQueueClient client, IList`1 corsProps) in C:\code\azure-storage-net\Test\ClassLibraryCommon\Queue\QueueAnalyticsUnitTests.cs:line 836
   at Microsoft.Azure.Storage.Queue.QueueAnalyticsUnitTests.CloudQueueTestCorsMaxOrigins() in C:\code\azure-storage-net\Test\ClassLibraryCommon\Queue\QueueAnalyticsUnitTests.cs:line 664
Result Message:	
Test method Microsoft.Azure.Storage.Queue.QueueAnalyticsUnitTests.CloudQueueTestCorsMaxOrigins threw exception: 
Microsoft.Azure.Storage.StorageException: Bad Request
```

Debug log:
```
2019-12-16T09:33:51.483Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 info: QueueStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1?restype=service&comp=properties RequestHeaders:{"x-ms-client-request-id":"e0818b56-ffd0-4bfb-8abe-ec8e79cffc05","user-agent":"Azure-Storage/11.1.1 (.NET Core; Win32NT 6.2.9200.0)","x-ms-version":"2019-02-02","x-ms-date":"Mon, 16 Dec 2019 09:33:51 GMT","authorization":"SharedKey devstoreaccount1:3xhztEFWpTIRgnDBlQF2rJw8VV5FFvp+VPIwS0Ezq9M=","content-length":"1612","host":"127.0.0.1:10001"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2019-12-16T09:33:51.484Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 info: QueueStorageContextMiddleware: Account=devstoreaccount1 Queue=undefined Message=undefined MessageId=undefined
2019-12-16T09:33:51.484Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 verbose: DispatchMiddleware: Dispatching request...
2019-12-16T09:33:51.485Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 info: DispatchMiddleware: Operation=Service_SetProperties
2019-12-16T09:33:51.485Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-12-16T09:33:51.486Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 info: QueueSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-12-16T09:33:51.486Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 info: QueueSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n1612\n\n\n\n\n\n\n\n\nx-ms-client-request-id:e0818b56-ffd0-4bfb-8abe-ec8e79cffc05\nx-ms-date:Mon, 16 Dec 2019 09:33:51 GMT\nx-ms-version:2019-02-02\n/devstoreaccount1/devstoreaccount1\ncomp:properties\nrestype:service"
2019-12-16T09:33:51.487Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 info: QueueSharedKeyAuthenticator:validate() Calculated authentication header based on key1: devstoreaccount1:3xhztEFWpTIRgnDBlQF2rJw8VV5FFvp+VPIwS0Ezq9M=
2019-12-16T09:33:51.487Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 info: QueueSharedKeyAuthenticator:validate() Signature 1 matched.
2019-12-16T09:33:51.488Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 verbose: DeserializerMiddleware: Start deserializing...
2019-12-16T09:33:51.489Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 debug: deserialize(): Raw request body string is ﻿<?xml version="1.0" encoding="utf-8"?><StorageServiceProperties><Logging><Version>1.0</Version><Delete>false</Delete><Read>false</Read><Write>false</Write><RetentionPolicy><Enabled>false</Enabled></RetentionPolicy></Logging><HourMetrics><Version>1.0</Version><Enabled>false</Enabled><RetentionPolicy><Enabled>false</Enabled></RetentionPolicy></HourMetrics><MinuteMetrics><Version>1.0</Version><Enabled>false</Enabled><RetentionPolicy><Enabled>false</Enabled></RetentionPolicy></MinuteMetrics><Cors><CorsRule><AllowedOrigins>www.xyz0.com,www.xyz1.com,www.xyz2.com,www.xyz3.com,www.xyz4.com,www.xyz5.com,www.xyz6.com,www.xyz7.com,www.xyz8.com,www.xyz9.com,www.xyz10.com,www.xyz11.com,www.xyz12.com,www.xyz13.com,www.xyz14.com,www.xyz15.com,www.xyz16.com,www.xyz17.com,www.xyz18.com,www.xyz19.com,www.xyz20.com,www.xyz21.com,www.xyz22.com,www.xyz23.com,www.xyz24.com,www.xyz25.com,www.xyz26.com,www.xyz27.com,www.xyz28.com,www.xyz29.com,www.xyz30.com,www.xyz31.com,www.xyz32.com,www.xyz33.com,www.xyz34.com,www.xyz35.com,www.xyz36.com,www.xyz37.com,www.xyz38.com,www.xyz39.com,www.xyz40.com,www.xyz41.com,www.xyz42.com,www.xyz43.com,www.xyz44.com,www.xyz45.com,www.xyz46.com,www.xyz47.com,www.xyz48.com,www.xyz49.com,www.xyz50.com,www.xyz51.com,www.xyz52.com,www.xyz53.com,www.xyz54.com,www.xyz55.com,www.xyz56.com,www.xyz57.com,www.xyz58.com,www.xyz59.com,www.xyz60.com,www.xyz61.com,www.xyz62.com,www.xyz63.com</AllowedOrigins><AllowedMethods>GET</AllowedMethods><ExposedHeaders></ExposedHeaders><AllowedHeaders></AllowedHeaders><MaxAgeInSeconds>0</MaxAgeInSeconds></CorsRule></Cors></StorageServiceProperties>
2019-12-16T09:33:51.490Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2019-12-16T09:33:51.490Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 error: ErrorMiddleware: ErrorName=DeserializationError ErrorMessage=StorageServiceProperties.Cors.AllowedHeaders cannot be null or undefined.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="Error: StorageServiceProperties.Cors.AllowedHeaders cannot be null or undefined.\n    at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:105:13)\n    at serializeCompositeType (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:502:44)\n    at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:134:19)\n    at serializeSequenceType (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:408:31)\n    at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:130:19)\n    at serializeCompositeType (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:502:44)\n    at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:134:19)\n    at Object.deserialize (C:\\code\\azurite\\src\\queue\\generated\\utils\\serializer.ts:171:21)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-12-16T09:33:51.491Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 error: ErrorMiddleware: Set HTTP code: 400
2019-12-16T09:33:51.491Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 error: ErrorMiddleware: Set HTTP body: undefined
2019-12-16T09:33:51.492Z 54d9ff4e-90fe-4229-9c22-6b397276c1e3 info: EndMiddleware: End response. TotalTimeInMS=8 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Queue/3.3.0-preview"}
```

**Comment by blueww** [comment]
Fail with missing Allowed header.
Should be fixed, will test again.

**Comment by blueww** [comment]
64 Origins works. But 65 Origins won't fail, so the case still fail.
65 not fail is tracked in https://github.com/Azure/Azurite/issues/310, so close this issue, as the original issue fixed.
