### ISSUE TITLE
Queue/Blob:Service_SetProperties: Set Cors with only 1 AllowedOrigins, and 1 AllowedMethods, get 400 error

### ISSUE THREAD

**Issue by blueww** [Azure/Azurite#312]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code
### What's the Node.js version?
v10.15.3
### What problem was encountered?
Queue:Service_SetProperties: Set Cors with only 1 AllowedOrigins, and 1 AllowedMethods, get 400 error
### Steps to reproduce the issue?
Set cors rule with            
```
CorsRule ruleMinRequired = new CorsRule()
            {
                AllowedOrigins = new List<string>() { "www.xyz.com" },
                AllowedMethods = CorsHttpMethods.Get
            };
```
### Have you found a mitigation/solution?
No

Test Case:
```
Test Name:	CloudQueueTestValidCorsRules
Test FullName:	Microsoft.Azure.Storage.Queue.QueueAnalyticsUnitTests.CloudQueueTestValidCorsRules
Test Source:	C:\code\azure-storage-net\Test\ClassLibraryCommon\Queue\QueueAnalyticsUnitTests.cs : line 479
Test Outcome:	Failed
Test Duration:	0:00:00.032475

Result StackTrace:	
at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 274
   at Microsoft.Azure.Storage.Core.Executor.Executor.<>c__DisplayClass0_0`1.<ExecuteSync>b__0() in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 41
   at Microsoft.Azure.Storage.Core.Util.CommonUtility.RunWithoutSynchronizationContext[T](Func`1 actionToRun) in C:\code\azure-storage-net\Lib\Common\Core\Util\CommonUtility.cs:line 378
   at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 40
   at Microsoft.Azure.Storage.Queue.CloudQueueClient.SetServiceProperties(ServiceProperties properties, QueueRequestOptions requestOptions, OperationContext operationContext) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Queue\CloudQueueClient.cs:line 553
   at Microsoft.Azure.Storage.Queue.QueueAnalyticsUnitTests.TestCorsRules(CloudQueueClient client, IList`1 corsProps) in C:\code\azure-storage-net\Test\ClassLibraryCommon\Queue\QueueAnalyticsUnitTests.cs:line 836
   at Microsoft.Azure.Storage.Queue.QueueAnalyticsUnitTests.CloudQueueTestValidCorsRules() in C:\code\azure-storage-net\Test\ClassLibraryCommon\Queue\QueueAnalyticsUnitTests.cs:line 565
Result Message:	
Test method Microsoft.Azure.Storage.Queue.QueueAnalyticsUnitTests.CloudQueueTestValidCorsRules threw exception: 
Microsoft.Azure.Storage.StorageException: Bad Request


```
Debug Log:
```
2019-12-16T09:33:51.469Z 187335f8-d5f6-4834-bd17-6c421767a191 info: QueueStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1?restype=service&comp=properties RequestHeaders:{"x-ms-client-request-id":"f3725885-a690-4b21-982a-598b5f413ddd","user-agent":"Azure-Storage/11.1.1 (.NET Core; Win32NT 6.2.9200.0)","x-ms-version":"2019-02-02","x-ms-date":"Mon, 16 Dec 2019 09:33:51 GMT","authorization":"SharedKey devstoreaccount1:feoty/I40jsoRTNNRtD00qKqroxmSr7iM3VAzLcTsEk=","content-length":"738","host":"127.0.0.1:10001"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2019-12-16T09:33:51.470Z 187335f8-d5f6-4834-bd17-6c421767a191 info: QueueStorageContextMiddleware: Account=devstoreaccount1 Queue=undefined Message=undefined MessageId=undefined
2019-12-16T09:33:51.471Z 187335f8-d5f6-4834-bd17-6c421767a191 verbose: DispatchMiddleware: Dispatching request...
2019-12-16T09:33:51.471Z 187335f8-d5f6-4834-bd17-6c421767a191 info: DispatchMiddleware: Operation=Service_SetProperties
2019-12-16T09:33:51.472Z 187335f8-d5f6-4834-bd17-6c421767a191 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-12-16T09:33:51.472Z 187335f8-d5f6-4834-bd17-6c421767a191 info: QueueSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-12-16T09:33:51.473Z 187335f8-d5f6-4834-bd17-6c421767a191 info: QueueSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n738\n\n\n\n\n\n\n\n\nx-ms-client-request-id:f3725885-a690-4b21-982a-598b5f413ddd\nx-ms-date:Mon, 16 Dec 2019 09:33:51 GMT\nx-ms-version:2019-02-02\n/devstoreaccount1/devstoreaccount1\ncomp:properties\nrestype:service"
2019-12-16T09:33:51.473Z 187335f8-d5f6-4834-bd17-6c421767a191 info: QueueSharedKeyAuthenticator:validate() Calculated authentication header based on key1: devstoreaccount1:feoty/I40jsoRTNNRtD00qKqroxmSr7iM3VAzLcTsEk=
2019-12-16T09:33:51.474Z 187335f8-d5f6-4834-bd17-6c421767a191 info: QueueSharedKeyAuthenticator:validate() Signature 1 matched.
2019-12-16T09:33:51.475Z 187335f8-d5f6-4834-bd17-6c421767a191 verbose: DeserializerMiddleware: Start deserializing...
2019-12-16T09:33:51.475Z 187335f8-d5f6-4834-bd17-6c421767a191 debug: deserialize(): Raw request body string is ﻿<?xml version="1.0" encoding="utf-8"?><StorageServiceProperties><Logging><Version>1.0</Version><Delete>false</Delete><Read>false</Read><Write>false</Write><RetentionPolicy><Enabled>false</Enabled></RetentionPolicy></Logging><HourMetrics><Version>1.0</Version><Enabled>false</Enabled><RetentionPolicy><Enabled>false</Enabled></RetentionPolicy></HourMetrics><MinuteMetrics><Version>1.0</Version><Enabled>false</Enabled><RetentionPolicy><Enabled>false</Enabled></RetentionPolicy></MinuteMetrics><Cors><CorsRule><AllowedOrigins>www.xyz.com</AllowedOrigins><AllowedMethods>GET</AllowedMethods><ExposedHeaders></ExposedHeaders><AllowedHeaders></AllowedHeaders><MaxAgeInSeconds>0</MaxAgeInSeconds></CorsRule></Cors></StorageServiceProperties>
2019-12-16T09:33:51.476Z 187335f8-d5f6-4834-bd17-6c421767a191 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2019-12-16T09:33:51.477Z 187335f8-d5f6-4834-bd17-6c421767a191 error: ErrorMiddleware: ErrorName=DeserializationError ErrorMessage=StorageServiceProperties.Cors.AllowedHeaders cannot be null or undefined.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="Error: StorageServiceProperties.Cors.AllowedHeaders cannot be null or undefined.\n    at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:105:13)\n    at serializeCompositeType (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:502:44)\n    at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:134:19)\n    at serializeSequenceType (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:408:31)\n    at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:130:19)\n    at serializeCompositeType (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:502:44)\n    at Serializer.serialize (C:\\code\\azurite\\node_modules\\@azure\\ms-rest-js\\lib\\serializer.ts:134:19)\n    at Object.deserialize (C:\\code\\azurite\\src\\queue\\generated\\utils\\serializer.ts:171:21)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-12-16T09:33:51.477Z 187335f8-d5f6-4834-bd17-6c421767a191 error: ErrorMiddleware: Set HTTP code: 400
2019-12-16T09:33:51.478Z 187335f8-d5f6-4834-bd17-6c421767a191 error: ErrorMiddleware: Set HTTP body: undefined
2019-12-16T09:33:51.478Z 187335f8-d5f6-4834-bd17-6c421767a191 info: EndMiddleware: End response. TotalTimeInMS=9 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Queue/3.3.0-preview"}

```

On Product Server, it pass:

```
PUT https://***.queue.core.windows.net/?restype=service&comp=properties HTTP/1.1
x-ms-client-request-id: Azure-Storage-PowerShell-055ced57-0d2d-4841-896a-c62e996c0bad
User-Agent: Azure-Storage/11.1.0 (.NET Core; Win32NT 10.0.18363.0)
x-ms-version: 2019-02-02
x-ms-date: Mon, 16 Dec 2019 10:09:22 GMT
Authorization: ***
Host: ***.queue.core.windows.net
Content-Length: 310
Connection: Keep-Alive

﻿<?xml version="1.0" encoding="utf-8"?><StorageServiceProperties><Cors><CorsRule><AllowedOrigins>www.xyz.com</AllowedOrigins><AllowedMethods>GET</AllowedMethods><ExposedHeaders></ExposedHeaders><AllowedHeaders></AllowedHeaders><MaxAgeInSeconds>0</MaxAgeInSeconds></CorsRule></Cors></StorageServiceProperties>
HTTP/1.1 202 Accepted
Content-Length: 0
Server: Windows-Azure-Queue/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 3b88c93b-7003-0041-38f8-b3cadf000000
x-ms-client-request-id: Azure-Storage-PowerShell-055ced57-0d2d-4841-896a-c62e996c0bad
x-ms-version: 2019-02-02
Date: Mon, 16 Dec 2019 10:09:38 GMT
```

**Comment by blueww** [comment]
This might be the same issue of https://github.com/Azure/Azurite/issues/294

**Comment by XiaoningLiu** [comment]
This is caused by Azurite requires AllowedOrigins and AllowedMethods. dev branch has updated them to be optional.
