### ISSUE TITLE
[queue]QueueClient.sendMessage() complains RequestBodyTooLarge with message with 64KB characters including special char

### ISSUE THREAD

**Issue by ljian3377** [Azure/Azurite#314]
### Which service(blob, file, queue, table) does this issue concern?
queue
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
v12.13.0
### What problem was encountered?
Unit test failure:
```
  1) QueueClient messageId methods, Node.js only
       update message with 64KB characters including special char which is computed after encoding:
     Error: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>RequestBodyTooLarge</Code>
  <Message>The request body is too large and exceeds the maximum permissible limit.
RequestId:bba9e101-406d-47ab-8402-920ebd3aa36c
Time:2019-12-17T06:16:59.393Z</Message>
  <MaxLimit>65536</MaxLimit>
</Error>
      at new RestError (S:\dev\azure-sdk-for-js\sdk\core\core-http\lib\restError.ts:23:5)
      at S:\dev\azure-sdk-for-js\sdk\core\core-http\lib\policies\deserializationPolicy.ts:169:19
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) QueueClient message methods, Node.js only
       enqueue, peek, dequeue with 64KB characters including special char which is computed after encoding:
     Error: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>RequestBodyTooLarge</Code>
  <Message>The request body is too large and exceeds the maximum permissible limit.
RequestId:5920045f-9d41-43e0-b167-704f29c17e68
Time:2019-12-17T06:16:59.539Z</Message>
  <MaxLimit>65536</MaxLimit>
</Error>
      at new RestError (S:\dev\azure-sdk-for-js\sdk\core\core-http\lib\restError.ts:23:5)
      at S:\dev\azure-sdk-for-js\sdk\core\core-http\lib\policies\deserializationPolicy.ts:169:19
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### debug.log
[debug.log](https://github.com/Azure/Azurite/files/3971693/debug.log)

**Comment by XiaoningLiu** [comment]
Fixed in https://github.com/Azure/Azurite/pull/363
