### ISSUE TITLE
BlockBlob_CommitBlockList： Commit 10 blocks first, then remove the first block and commit the left 9 blocks again, will fail with 400

### ISSUE THREAD

**Issue by blueww** [Azure/Azurite#323]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code
### What's the Node.js version?
v10.15.3
### What problem was encountered?
BlockBlob_CommitBlockList： Commit 10 blocks first, then remove the first block and commit the left 9 blocks again, will fail with 400
### Steps to reproduce the issue?
See debug log
### Have you found a mitigation/solution?
No

Test Case:
```
Test Name:	CloudBlockBlobBlockReordering
Test FullName:	Microsoft.Azure.Storage.Blob.CloudBlockBlobTest.CloudBlockBlobBlockReordering
Test Source:	C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\CloudBlockBlobTest.cs : line 4577
Test Outcome:	Failed
Test Duration:	0:06:00.751329

Result StackTrace:	
at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 274
   at Microsoft.Azure.Storage.Core.Executor.Executor.<>c__DisplayClass0_0`1.<ExecuteSync>b__0() in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 41
   at Microsoft.Azure.Storage.Core.Util.CommonUtility.RunWithoutSynchronizationContext[T](Func`1 actionToRun) in C:\code\azure-storage-net\Lib\Common\Core\Util\CommonUtility.cs:line 378
   at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 40
   at Microsoft.Azure.Storage.Blob.CloudBlockBlob.PutBlockList(IEnumerable`1 blockList, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 2875
   at Microsoft.Azure.Storage.Blob.CloudBlockBlobTest.CloudBlockBlobBlockReordering() in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\CloudBlockBlobTest.cs:line 4601
Result Message:	
Test method Microsoft.Azure.Storage.Blob.CloudBlockBlobTest.CloudBlockBlobBlockReordering threw exception: 
Microsoft.Azure.Storage.StorageException: Bad Request


```

Debug Log:
```
2019-12-17T09:46:03.558Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/testc8f8adf75367f4f1eb8be4c5f01b5222f/blob1?comp=blocklist RequestHeaders:{"x-ms-client-request-id":"2d322530-36c1-41eb-b5c9-31b4d5954191","user-agent":"Azure-Storage/11.1.1 (.NET Core; Win32NT 6.2.9200.0)","x-ms-version":"2019-02-02","x-ms-date":"Tue, 17 Dec 2019 09:46:03 GMT","authorization":"SharedKey devstoreaccount1:YM6+IfNRNiVNtBPq5KISoZv+KnIAybD325rE9OVNtcQ=","content-length":"474","host":"127.0.0.1:10000"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2019-12-17T09:46:03.559Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=testc8f8adf75367f4f1eb8be4c5f01b5222f Blob=blob1
2019-12-17T09:46:03.559Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 verbose: DispatchMiddleware: Dispatching request...
2019-12-17T09:46:03.560Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 info: DispatchMiddleware: Operation=BlockBlob_CommitBlockList
2019-12-17T09:46:03.560Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-12-17T09:46:03.560Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 info: PublicAccessAuthenticator:validate() Start validation against public access.
2019-12-17T09:46:03.561Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 debug: PublicAccessAuthenticator:validate() Getting account properties...
2019-12-17T09:46:03.561Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: testc8f8adf75367f4f1eb8be4c5f01b5222f, blob: blob1
2019-12-17T09:46:03.565Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container testc8f8adf75367f4f1eb8be4c5f01b5222f
2019-12-17T09:46:03.566Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-12-17T09:46:03.566Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n474\n\n\n\n\n\n\n\n\nx-ms-client-request-id:2d322530-36c1-41eb-b5c9-31b4d5954191\nx-ms-date:Tue, 17 Dec 2019 09:46:03 GMT\nx-ms-version:2019-02-02\n/devstoreaccount1/devstoreaccount1/testc8f8adf75367f4f1eb8be4c5f01b5222f/blob1\ncomp:blocklist"
2019-12-17T09:46:03.566Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:YM6+IfNRNiVNtBPq5KISoZv+KnIAybD325rE9OVNtcQ=
2019-12-17T09:46:03.567Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2019-12-17T09:46:03.567Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 verbose: DeserializerMiddleware: Start deserializing...
2019-12-17T09:46:03.567Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 debug: deserialize(): Raw request body string is ﻿<?xml version="1.0" encoding="utf-8"?><BlockList><Latest>e99RbXM1D0iXf9zmKiR4FQ==</Latest><Latest>yJQ2BNhi7kKejkZhl9Jr8A==</Latest><Latest>z+JOHiCRyk2y2h58cy4w1g==</Latest><Latest>lUbaaZgZGESFCZDf2dj2zQ==</Latest><Latest>B/J0ZLzQZ0SsxoRMSdoxRw==</Latest><Latest>NDDaSl+h30+XINZdnEnyYA==</Latest><Latest>6/p/A2zY7EaseQmMEeaXbQ==</Latest><Latest>jRtMqZ63YEGsX2yldweLJw==</Latest><Latest>tdszCEe6Sk6shBMmWHTNtw==</Latest><Latest>744s8sNuwkOi26/dJLm21w==</Latest></BlockList>
2019-12-17T09:46:03.569Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 info: HandlerMiddleware: DeserializedParameters={"options":{"metadata":{},"requestId":"2d322530-36c1-41eb-b5c9-31b4d5954191","blobHTTPHeaders":{},"leaseAccessConditions":{},"cpkInfo":{},"modifiedAccessConditions":{}},"comp":"blocklist","version":"2019-02-02","blocks":{"committed":[],"uncommitted":[],"latest":["e99RbXM1D0iXf9zmKiR4FQ==","yJQ2BNhi7kKejkZhl9Jr8A==","z+JOHiCRyk2y2h58cy4w1g==","lUbaaZgZGESFCZDf2dj2zQ==","B/J0ZLzQZ0SsxoRMSdoxRw==","NDDaSl+h30+XINZdnEnyYA==","6/p/A2zY7EaseQmMEeaXbQ==","jRtMqZ63YEGsX2yldweLJw==","tdszCEe6Sk6shBMmWHTNtw==","744s8sNuwkOi26/dJLm21w=="]},"body":"ReadableStream"}
2019-12-17T09:46:12.621Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 verbose: SerializerMiddleware: Start serializing...
2019-12-17T09:46:12.622Z 788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4 info: EndMiddleware: End response. TotalTimeInMS=9064 StatusCode=201 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.3.0-preview","etag":"\"d-oLGZB5rjCk4ruX78tWyXVVngc5Y\"","last-modified":"Tue, 17 Dec 2019 09:46:03 GMT","content-md5":"cpRelZ9HRlR91CyL8w2JFg==","x-ms-client-request-id":"2d322530-36c1-41eb-b5c9-31b4d5954191","x-ms-request-id":"788b6f2e-fa78-4bc1-b1b3-6a6d6ca86fb4","x-ms-version":"2019-02-02","date":"Tue, 17 Dec 2019 09:46:03 GMT","x-ms-request-server-encrypted":"true"}


2019-12-17T09:46:55.895Z 4ee0e14a-7725-47ef-898d-7980361d2bdc info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/testc8f8adf75367f4f1eb8be4c5f01b5222f/blob1?comp=blocklist RequestHeaders:{"x-ms-blob-content-type":"application/octet-stream","x-ms-blob-content-md5":"eB5eJF1ptWaXm4bijSPyxw==","x-ms-client-request-id":"d91c0274-9642-4014-8870-29147f53c00d","user-agent":"Azure-Storage/11.1.1 (.NET Core; Win32NT 6.2.9200.0)","x-ms-version":"2019-02-02","x-ms-date":"Tue, 17 Dec 2019 09:46:55 GMT","authorization":"SharedKey devstoreaccount1:X4/F3+p9PWdoD4fnQ4rmUaaPF3n1pIoQTLPRPrUKtjo=","content-length":"433","host":"127.0.0.1:10000"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2019-12-17T09:46:55.895Z 4ee0e14a-7725-47ef-898d-7980361d2bdc info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=testc8f8adf75367f4f1eb8be4c5f01b5222f Blob=blob1
2019-12-17T09:46:55.896Z 4ee0e14a-7725-47ef-898d-7980361d2bdc verbose: DispatchMiddleware: Dispatching request...
2019-12-17T09:46:55.897Z 4ee0e14a-7725-47ef-898d-7980361d2bdc info: DispatchMiddleware: Operation=BlockBlob_CommitBlockList
2019-12-17T09:46:55.897Z 4ee0e14a-7725-47ef-898d-7980361d2bdc verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-12-17T09:46:55.897Z 4ee0e14a-7725-47ef-898d-7980361d2bdc info: PublicAccessAuthenticator:validate() Start validation against public access.
2019-12-17T09:46:55.898Z 4ee0e14a-7725-47ef-898d-7980361d2bdc debug: PublicAccessAuthenticator:validate() Getting account properties...
2019-12-17T09:46:55.898Z 4ee0e14a-7725-47ef-898d-7980361d2bdc debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: testc8f8adf75367f4f1eb8be4c5f01b5222f, blob: blob1
2019-12-17T09:46:55.908Z 4ee0e14a-7725-47ef-898d-7980361d2bdc debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container testc8f8adf75367f4f1eb8be4c5f01b5222f
2019-12-17T09:46:55.909Z 4ee0e14a-7725-47ef-898d-7980361d2bdc info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-12-17T09:46:55.909Z 4ee0e14a-7725-47ef-898d-7980361d2bdc info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n433\n\n\n\n\n\n\n\n\nx-ms-blob-content-md5:eB5eJF1ptWaXm4bijSPyxw==\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:d91c0274-9642-4014-8870-29147f53c00d\nx-ms-date:Tue, 17 Dec 2019 09:46:55 GMT\nx-ms-version:2019-02-02\n/devstoreaccount1/devstoreaccount1/testc8f8adf75367f4f1eb8be4c5f01b5222f/blob1\ncomp:blocklist"
2019-12-17T09:46:55.910Z 4ee0e14a-7725-47ef-898d-7980361d2bdc info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:X4/F3+p9PWdoD4fnQ4rmUaaPF3n1pIoQTLPRPrUKtjo=
2019-12-17T09:46:55.910Z 4ee0e14a-7725-47ef-898d-7980361d2bdc info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2019-12-17T09:46:55.911Z 4ee0e14a-7725-47ef-898d-7980361d2bdc verbose: DeserializerMiddleware: Start deserializing...
2019-12-17T09:46:55.912Z 4ee0e14a-7725-47ef-898d-7980361d2bdc debug: deserialize(): Raw request body string is ﻿<?xml version="1.0" encoding="utf-8"?><BlockList><Latest>yJQ2BNhi7kKejkZhl9Jr8A==</Latest><Latest>z+JOHiCRyk2y2h58cy4w1g==</Latest><Latest>lUbaaZgZGESFCZDf2dj2zQ==</Latest><Latest>B/J0ZLzQZ0SsxoRMSdoxRw==</Latest><Latest>NDDaSl+h30+XINZdnEnyYA==</Latest><Latest>6/p/A2zY7EaseQmMEeaXbQ==</Latest><Latest>jRtMqZ63YEGsX2yldweLJw==</Latest><Latest>tdszCEe6Sk6shBMmWHTNtw==</Latest><Latest>744s8sNuwkOi26/dJLm21w==</Latest></BlockList>
2019-12-17T09:46:55.915Z 4ee0e14a-7725-47ef-898d-7980361d2bdc info: HandlerMiddleware: DeserializedParameters={"options":{"metadata":{},"requestId":"d91c0274-9642-4014-8870-29147f53c00d","blobHTTPHeaders":{"blobContentType":"application/octet-stream","blobContentMD5":{"type":"Buffer","data":[120,30,94,36,93,105,181,102,151,155,134,226,141,35,242,199]}},"leaseAccessConditions":{},"cpkInfo":{},"modifiedAccessConditions":{}},"comp":"blocklist","version":"2019-02-02","blocks":{"committed":[],"uncommitted":[],"latest":["yJQ2BNhi7kKejkZhl9Jr8A==","z+JOHiCRyk2y2h58cy4w1g==","lUbaaZgZGESFCZDf2dj2zQ==","B/J0ZLzQZ0SsxoRMSdoxRw==","NDDaSl+h30+XINZdnEnyYA==","6/p/A2zY7EaseQmMEeaXbQ==","jRtMqZ63YEGsX2yldweLJw==","tdszCEe6Sk6shBMmWHTNtw==","744s8sNuwkOi26/dJLm21w=="]},"body":"ReadableStream"}
2019-12-17T09:47:00.148Z 4ee0e14a-7725-47ef-898d-7980361d2bdc error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2019-12-17T09:47:00.149Z 4ee0e14a-7725-47ef-898d-7980361d2bdc error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage= ErrorHTTPHeaders={"x-ms-error-code":"InvalidOperation","x-ms-request-id":"4ee0e14a-7725-47ef-898d-7980361d2bdc"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>\nRequestId:4ee0e14a-7725-47ef-898d-7980361d2bdc\nTime:2019-12-17T09:47:00.148Z</Message>\n</Error>" ErrorStack="StorageError: \n    at Function.getInvalidOperation (C:\\code\\azurite\\src\\blob\\errors\\StorageErrorFactory.ts:56:12)\n    at LokiBlobMetadataStore.commitBlockList (C:\\code\\azurite\\src\\blob\\persistence\\LokiBlobMetadataStore.ts:1917:39)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-12-17T09:47:00.149Z 4ee0e14a-7725-47ef-898d-7980361d2bdc error: ErrorMiddleware: Set HTTP code: 400
2019-12-17T09:47:00.149Z 4ee0e14a-7725-47ef-898d-7980361d2bdc error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=InvalidOperation
2019-12-17T09:47:00.149Z 4ee0e14a-7725-47ef-898d-7980361d2bdc error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=4ee0e14a-7725-47ef-898d-7980361d2bdc
2019-12-17T09:47:00.150Z 4ee0e14a-7725-47ef-898d-7980361d2bdc error: ErrorMiddleware: Set content type: application/xml
2019-12-17T09:47:00.150Z 4ee0e14a-7725-47ef-898d-7980361d2bdc error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidOperation</Code>\n  <Message>\nRequestId:4ee0e14a-7725-47ef-898d-7980361d2bdc\nTime:2019-12-17T09:47:00.148Z</Message>\n</Error>"
2019-12-17T09:47:00.150Z 4ee0e14a-7725-47ef-898d-7980361d2bdc info: EndMiddleware: End response. TotalTimeInMS=4256 StatusCode=400 StatusMessage=Bad Request Headers={"server":"Azurite-Blob/3.3.0-preview","x-ms-error-code":"InvalidOperation","x-ms-request-id":"4ee0e14a-7725-47ef-898d-7980361d2bdc","content-type":"application/xml"}
```

**Comment by XiaoningLiu** [comment]
Cannot reproduce, added a test case covering this in #349
