### ISSUE TITLE
BlobBatchDelete: Azurite report Internal Server Error

### ISSUE THREAD

**Issue by blueww** [Azure/Azurite#364]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code
### What's the Node.js version?
v10.15.3
### What problem was encountered?
BlobBatchDelete: Azurite report Internal Server Error
It should return: "Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues"
### Steps to reproduce the issue?
Run blob batch delete
### Have you found a mitigation/solution?
No

Debug log
```
2019-12-25T09:16:03.915Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c info: BlobStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1?comp=batch RequestHeaders:{"x-ms-client-request-id":"00b1e14a-fb36-4671-97e6-d6ea08e2c40f","user-agent":"Azure-Storage/11.1.1 (.NET Core; Win32NT 6.2.9200.0)","x-ms-version":"2019-02-02","x-ms-date":"Wed, 25 Dec 2019 09:16:03 GMT","authorization":"SharedKey devstoreaccount1:mRZT5Gz5Lb4gdEWsYKg/Jn4bCM22PIFJXiux7m8dN7Q=","content-type":"multipart/mixed; boundary=batch_e429b27b-c21f-4181-a847-bcf6d7fccefc","content-length":"888","host":"127.0.0.1:10000"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2019-12-25T09:16:03.915Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=undefined Blob=
2019-12-25T09:16:03.916Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c verbose: DispatchMiddleware: Dispatching request...
2019-12-25T09:16:03.916Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c info: DispatchMiddleware: Operation=Service_SubmitBatch
2019-12-25T09:16:03.917Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-12-25T09:16:03.917Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c info: PublicAccessAuthenticator:validate() Start validation against public access.
2019-12-25T09:16:03.917Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c debug: PublicAccessAuthenticator:validate() Getting account properties...
2019-12-25T09:16:03.918Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: undefined, blob: 
2019-12-25T09:16:03.918Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c info: PublicAccessAuthenticator:validate() Skip public access authentication. Container name is undefined.
2019-12-25T09:16:03.918Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-12-25T09:16:03.919Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"POST\n\n\n888\n\nmultipart/mixed; boundary=batch_e429b27b-c21f-4181-a847-bcf6d7fccefc\n\n\n\n\n\n\nx-ms-client-request-id:00b1e14a-fb36-4671-97e6-d6ea08e2c40f\nx-ms-date:Wed, 25 Dec 2019 09:16:03 GMT\nx-ms-version:2019-02-02\n/devstoreaccount1/devstoreaccount1\ncomp:batch"
2019-12-25T09:16:03.919Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:mRZT5Gz5Lb4gdEWsYKg/Jn4bCM22PIFJXiux7m8dN7Q=
2019-12-25T09:16:03.919Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2019-12-25T09:16:03.920Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c verbose: DeserializerMiddleware: Start deserializing...
2019-12-25T09:16:03.920Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c info: HandlerMiddleware: DeserializedParameters={"options":{"requestId":"00b1e14a-fb36-4671-97e6-d6ea08e2c40f"},"comp":"batch","contentLength":888,"multipartContentType":"multipart/mixed; boundary=batch_e429b27b-c21f-4181-a847-bcf6d7fccefc","version":"2019-02-02","body":"ReadableStream"}
2019-12-25T09:16:03.920Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c error: ErrorMiddleware: Received an error, fill error information to HTTP response
2019-12-25T09:16:03.922Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c error: ErrorMiddleware: ErrorName=Error ErrorMessage=Method not implemented. ErrorStack="Error: Method not implemented.\n    at ServiceHandler.submitBatch (C:\\code\\azurite\\src\\blob\\handlers\\ServiceHandler.ts:75:11)\n    at C:\\code\\azurite\\src\\blob\\generated\\middleware\\HandlerMiddlewareFactory.ts:82:10\n    at C:\\code\\azurite\\src\\blob\\generated\\ExpressMiddlewareFactory.ts:97:57\n    at Layer.handle [as handle_request] (C:\\code\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-12-25T09:16:03.923Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c error: ErrorMiddleware: Set HTTP code: 500
2019-12-25T09:16:03.923Z 5f96d410-79b5-4ec5-9d3f-97da2a85b78c info: EndMiddleware: End response. TotalTimeInMS=8 StatusCode=500 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.3.0-preview"}

Microsoft.Azure.Storage.StorageException: Internal Server Error
   at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 274
   at Microsoft.Azure.Storage.Blob.CloudBlockBlobTest.CloudBlockBlobDeleteBatchTestAsync() in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\CloudBlockBlobTest.cs:line 370
Request Information
RequestID:
RequestDate:Wed, 25 Dec 2019 17:16:03 GMT
StatusMessage:Internal Server Error
ErrorCode:
```

Test Case:
```
Test Name:	CloudBlockBlobDeleteBatchTestAsync
Test FullName:	Microsoft.Azure.Storage.Blob.CloudBlockBlobTest.CloudBlockBlobDeleteBatchTestAsync
Test Source:	C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\CloudBlockBlobTest.cs : line 347
Test Outcome:	Failed
Test Duration:	0:00:00.5155217

Result StackTrace:	
at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 274
   at Microsoft.Azure.Storage.Blob.CloudBlockBlobTest.CloudBlockBlobDeleteBatchTestAsync() in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\CloudBlockBlobTest.cs:line 370
   at Microsoft.Azure.Storage.Blob.CloudBlockBlobTest.CloudBlockBlobDeleteBatchTestAsync() in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\CloudBlockBlobTest.cs:line 475
Result Message:	
Test method Microsoft.Azure.Storage.Blob.CloudBlockBlobTest.CloudBlockBlobDeleteBatchTestAsync threw exception: 
Microsoft.Azure.Storage.StorageException: Internal Server Error

```

**Comment by XiaoningLiu** [comment]
Fixed and aligned all error type for un supported APIs.

**Comment by fnumrich** [comment]
@blueww : Is there any overview of the APIs supported by Azurite?

**Comment by blueww** [comment]
@fnumrich 

You can find the supported API/features of Azurite from https://github.com/Azure/Azurite#support-matrix.
BTW, we recently supported blob batch, and will update this doc soon.
