### ISSUE TITLE
Blob_Download: download a specified range should returns 206 (Partial Content), instead of 200

### ISSUE THREAD

**Issue by blueww** [Azure/Azurite#367]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.3.0-preview
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
VS code
### What's the Node.js version?
v10.15.3
### What problem was encountered?
Per https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob,
A successful operation to read the full blob returns status code 200 (OK).
A successful operation to read a specified range returns status code 206 (Partial Content).

But when download a rage of page blob in Azurite, Azurite returns 200.

### Steps to reproduce the issue?
See following case.
### Have you found a mitigation/solution?

Debug Log:
```
2019-12-26T03:16:44.973Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/testcbfdca7340d1d478ba5c029a7aa42d392/pageblob RequestHeaders:{"x-ms-range":"bytes=496-","x-ms-client-request-id":"2e2db1fc-f8bf-4b37-9aef-518ef5a2c9fd","user-agent":"Azure-Storage/11.1.1 (.NET Core; Win32NT 6.2.9200.0)","x-ms-version":"2019-02-02","x-ms-date":"Thu, 26 Dec 2019 03:16:44 GMT","authorization":"SharedKey devstoreaccount1:hDVFiLdbBdx/QhjUIjwYWmnKREfEB5+0qB395SDvvUc=","host":"127.0.0.1:10000"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2019-12-26T03:16:44.974Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=testcbfdca7340d1d478ba5c029a7aa42d392 Blob=pageblob
2019-12-26T03:16:44.974Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 verbose: DispatchMiddleware: Dispatching request...
2019-12-26T03:16:44.975Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 info: DispatchMiddleware: Operation=Blob_Download
2019-12-26T03:16:44.976Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-12-26T03:16:44.977Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 info: PublicAccessAuthenticator:validate() Start validation against public access.
2019-12-26T03:16:44.977Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: PublicAccessAuthenticator:validate() Getting account properties...
2019-12-26T03:16:44.977Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: testcbfdca7340d1d478ba5c029a7aa42d392, blob: pageblob
2019-12-26T03:16:44.978Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container testcbfdca7340d1d478ba5c029a7aa42d392
2019-12-26T03:16:44.979Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-12-26T03:16:44.979Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:2e2db1fc-f8bf-4b37-9aef-518ef5a2c9fd\nx-ms-date:Thu, 26 Dec 2019 03:16:44 GMT\nx-ms-range:bytes=496-\nx-ms-version:2019-02-02\n/devstoreaccount1/devstoreaccount1/testcbfdca7340d1d478ba5c029a7aa42d392/pageblob"
2019-12-26T03:16:44.980Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:hDVFiLdbBdx/QhjUIjwYWmnKREfEB5+0qB395SDvvUc=
2019-12-26T03:16:44.980Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2019-12-26T03:16:44.980Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 verbose: DeserializerMiddleware: Start deserializing...
2019-12-26T03:16:44.981Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 info: HandlerMiddleware: DeserializedParameters={"options":{"range":"bytes=496-","requestId":"2e2db1fc-f8bf-4b37-9aef-518ef5a2c9fd","leaseAccessConditions":{},"cpkInfo":{},"modifiedAccessConditions":{}},"version":"2019-02-02"}
2019-12-26T03:16:44.982Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 info: BlobHandler:downloadPageBlob() NormalizedDownloadRange=bytes=496-1023 RequiredContentLength=528
2019-12-26T03:16:44.983Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 verbose: FSExtentStore:readExtents() Start read from multi extents...
2019-12-26T03:16:44.983Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: OperationQueue.operate() Schedule incoming job 4923cf72-5c05-4646-89f6-0ae2cedd4adb
2019-12-26T03:16:44.984Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: OperationQueue:execute() Current runningConcurrency:0 maxConcurrency:100 operations.length:1
2019-12-26T03:16:44.984Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 verbose: FSExtentStore:readExtent() Creating read stream. LocationId:Default extentId:500c26d3-d384-4817-825e-853df085940e path:C:\code\azurite\__blobstorage__\500c26d3-d384-4817-825e-853df085940e offset:31548 count:528 end:32075
2019-12-26T03:16:44.985Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: OperationQueue.operate() Job 4923cf72-5c05-4646-89f6-0ae2cedd4adb completes callback, resolve.
2019-12-26T03:16:44.986Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: OperationQueue:execute() Current runningConcurrency:0 maxConcurrency:100 operations.length:0
2019-12-26T03:16:44.986Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: OperationQueue:execute() return. Operation.length === 0
2019-12-26T03:16:44.988Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 verbose: FSExtentStore:readExtents() Start read from multi extents...
2019-12-26T03:16:44.990Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: OperationQueue.operate() Schedule incoming job 88813488-4790-4a7c-9fab-011584e9bb53
2019-12-26T03:16:44.990Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: OperationQueue:execute() Current runningConcurrency:0 maxConcurrency:100 operations.length:1
2019-12-26T03:16:44.990Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 verbose: FSExtentStore:readExtent() Creating read stream. LocationId:Default extentId:500c26d3-d384-4817-825e-853df085940e path:C:\code\azurite\__blobstorage__\500c26d3-d384-4817-825e-853df085940e offset:31548 count:528 end:32075
2019-12-26T03:16:44.991Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: OperationQueue.operate() Job 88813488-4790-4a7c-9fab-011584e9bb53 completes callback, resolve.
2019-12-26T03:16:44.992Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 verbose: SerializerMiddleware: Start serializing...
2019-12-26T03:16:44.993Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 info: Serializer: Start returning stream body.
2019-12-26T03:16:44.994Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: OperationQueue:execute() Current runningConcurrency:0 maxConcurrency:100 operations.length:0
2019-12-26T03:16:44.995Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 debug: OperationQueue:execute() return. Operation.length === 0
2019-12-26T03:16:44.996Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 verbose: FSExtentStore:readExtent() Read stream closed. LocationId:Default extentId:500c26d3-d384-4817-825e-853df085940e path:C:\code\azurite\__blobstorage__\500c26d3-d384-4817-825e-853df085940e offset:31548 count:528 end:32075
2019-12-26T03:16:44.998Z b896dc64-b2d3-43b5-a7c8-5f1e21f0c8f5 verbose: FSExtentStore:readExtent() Read stream closed. LocationId:Default extentId:500c26d3-d384-4817-825e-853df085940e path:C:\code\azurite\__blobstorage__\500c26d3-d384-4817-825e-853df085940e offset:31548 count:528 end:32075
```
Test Case:
```
Test Name:	CloudPageBlobEncryptionValidateRangeDecryption
Test FullName:	Microsoft.Azure.Storage.Blob.BlobClientEncryptionTests.CloudPageBlobEncryptionValidateRangeDecryption
Test Source:	C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\BlobClientEncryptionTests.cs : line 683
Test Outcome:	Failed
Test Duration:	0:00:26.82542

Result StackTrace:	
at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 274
   at Microsoft.Azure.Storage.Core.Executor.Executor.<>c__DisplayClass0_0`1.<ExecuteSync>b__0() in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 41
   at Microsoft.Azure.Storage.Core.Util.CommonUtility.RunWithoutSynchronizationContext[T](Func`1 actionToRun) in C:\code\azure-storage-net\Lib\Common\Core\Util\CommonUtility.cs:line 378
   at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 40
   at Microsoft.Azure.Storage.Blob.CloudBlob.DownloadRangeToStream(Stream target, Nullable`1 offset, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext) in C:\code\azure-storage-net\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 1038
   at Microsoft.Azure.Storage.Blob.BlobClientEncryptionTests.ValidateRangeDecryption(BlobType type, Int32 blobSize, Nullable`1 blobOffset, Nullable`1 length, Nullable`1 verifyLength) in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\BlobClientEncryptionTests.cs:line 753
   at Microsoft.Azure.Storage.Blob.BlobClientEncryptionTests.CloudPageBlobEncryptionValidateRangeDecryption() in C:\code\azure-storage-net\Test\ClassLibraryCommon\Blob\BlobClientEncryptionTests.cs:line 687
Result Message:	
Test method Microsoft.Azure.Storage.Blob.BlobClientEncryptionTests.CloudPageBlobEncryptionValidateRangeDecryption threw exception: 
Microsoft.Azure.Storage.StorageException: Unexpected response code, Expected:PartialContent, Received:OK
```

**Comment by XiaoningLiu** [comment]
Fixed in https://github.com/Azure/Azurite/pull/369
