### ISSUE TITLE
BlobClient GetUserDelegationKeyAsync returns invalid response

### ISSUE THREAD

**Issue by onionhammer** [Azure/Azurite#453]
### Which service(blob, file, queue, table) does this issue concern?
Blobs

### Which version of the Azurite was used?
Latest nuget as of 6/5/2020

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
nuget

### What problem was encountered?
When creating a delegationkey, the client throws an exception

```
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at Azure.Storage.Blobs.BlobRestClient.Service.GetUserDelegationKeyAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Service.GetUserDelegationKeyAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, KeyInfo keyInfo, String version, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetUserDelegationKeyInternal(Nullable`1 startsOn, DateTimeOffset expiresOn, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetUserDelegationKeyAsync(Nullable`1 startsOn, DateTimeOffset expiresOn, CancellationToken cancellationToken)
   at  ...
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce the issue?
Use the latest Azure SDK (https://www.nuget.org/packages/Azure.Storage.Blobs) and the latest Azurite, and try to create a SasQueryParameter.

**Comment by blueww** [comment]
@onionhammer 
Thanks for reporting this error!

Azurite still not support delegationkey now.
Will add this to the feature request list.

Besides that, we will see if can make the exception message more informational.

**Comment by bas-deweerd** [comment]
> @onionhammer
> Azurite still not support delegationkey now.
> Will add this to the feature request list.

Any idea when this feature will be implemented? 

How can we vote for this feature request?

**Comment by Exitare** [comment]
Are there any plans to support this feature?

**Comment by blueww** [comment]
@Exitare 
The GetUserDelegationKey is still not supported by azurite, and the delegation SAS authentication is also not supported by Azurite now.

Azurite welcome contribution!
If would be great it you can raise PR to implement it or part of it!

**Comment by blueww** [comment]
The feature is already released in https://github.com/Azure/Azurite/releases/tag/v3.21.0
