### ISSUE TITLE
[syncCopyFromURL] BlobNotFound - The specified blob does not exist.

### ISSUE THREAD

**Issue by AlexanderYW** [Azure/Azurite#461]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.7.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
v12.13.1

### What problem was encountered?
[syncCopyFromURL](https://azuresdkdocs.blob.core.windows.net/$web/javascript/azure-storage-blob/12.1.2/classes/blobclient.html#synccopyfromurl) api is not working?, i'm trying to copy a blob but my test are failing when using Azurite, my test's works as expected when using AzureStorageEmulator

### Steps to reproduce the issue?

1. git clone https://github.com/AlexanderYW/Adonis-Drive-Azure-Storage.git
2. git checkout actions/blob-storage-emulator 
3. npm install
4. node test/blob.spec.js

### Error details
Details about this failing https://github.com/AlexanderYW/Adonis-Drive-Azure-Storage/pull/7/checks?check_run_id=816053411

### Have you found a mitigation/solution?
Not yet

**Comment by XiaoningLiu** [comment]
Hi @AlexanderYW Can you enable Azurite debug log and share it here? SyncCopyBlob is not supported by Azurite yet. Like to check Azurite log for double confirm.

**Comment by AlexanderYW** [comment]
Hi @XiaoningLiu, Sure I will provide you with the log in about 2 hours.

I'm not 100% sure that it's the SyncCopyBlob, just what I assumed it was since that's the main difference between the rest of the test and the ones that fails :)

**Comment by AlexanderYW** [comment]
Hi @XiaoningLiu,

Here is the debug log
https://gist.github.com/AlexanderYW/7d20871b786f604a54eaa0f8d3ae9ffc

**Comment by XiaoningLiu** [comment]
@AlexanderYW It's true it's an not implemented API. You can find "Current API is not implemented yet." in debug.log and response.

2020-06-29T14:57:53.995Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=adonis-driver-test Blob=hello-moved.txt
2020-06-29T14:57:53.995Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee verbose: DispatchMiddleware: Dispatching request...
2020-06-29T14:57:53.996Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee info: DispatchMiddleware: Operation=Blob_CopyFromURL
2020-06-29T14:57:53.996Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2020-06-29T14:57:53.996Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee info: PublicAccessAuthenticator:validate() Start validation against public access.
2020-06-29T14:57:53.996Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee debug: PublicAccessAuthenticator:validate() Getting account properties...
2020-06-29T14:57:53.996Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: adonis-driver-test, blob: hello-moved.txt
2020-06-29T14:57:53.996Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container adonis-driver-test
2020-06-29T14:57:53.996Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2020-06-29T14:57:53.996Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:6a94b67b-e0e2-40a4-b457-3c051894f8b9\nx-ms-copy-source:http://127.0.0.1:10000/devstoreaccount1/adonis-driver-test/hello.txt?sv=2019-07-07&st=2020-06-29T14%3A57%3A53Z&se=2020-06-29T15%3A57%3A53Z&sr=c&sp=r&sig=OaklvId8MtsSPCz3D6N3WNuTXhJAw06SuOK9VCko3vE%3D\nx-ms-date:Mon, 29 Jun 2020 14:57:53 GMT\nx-ms-requires-sync:true\nx-ms-version:2019-07-07\n/devstoreaccount1/devstoreaccount1/adonis-driver-test/hello-moved.txt"
2020-06-29T14:57:53.996Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:fpTEmrDx0kBmsmW4tZ9R6WaFOmLUVdGKN3lOZDiXjOg=
2020-06-29T14:57:53.996Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2020-06-29T14:57:53.996Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee verbose: DeserializerMiddleware: Start deserializing...
2020-06-29T14:57:53.997Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee info: HandlerMiddleware: DeserializedParameters={"options":{"metadata":{},"requestId":"6a94b67b-e0e2-40a4-b457-3c051894f8b9","sourceModifiedAccessConditions":{},"modifiedAccessConditions":{},"leaseAccessConditions":{}},"copySource":"http://127.0.0.1:10000/devstoreaccount1/adonis-driver-test/hello.txt?sv=2019-07-07&st=2020-06-29T14%3A57%3A53Z&se=2020-06-29T15%3A57%3A53Z&sr=c&sp=r&sig=OaklvId8MtsSPCz3D6N3WNuTXhJAw06SuOK9VCko3vE%3D","version":"2019-07-07","xMsRequiresSync":"true"}
2020-06-29T14:57:53.997Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2020-06-29T14:57:53.997Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues  ErrorHTTPStatusCode=500 ErrorHTTPStatusMessage=Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues ErrorHTTPHeaders={"x-ms-error-code":"APINotImplemented","x-ms-request-id":"4d778175-3e41-48d0-9b27-ee2e8d2dbeee"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>APINotImplemented</Code>\n  <Message>Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues\nRequestId:4d778175-3e41-48d0-9b27-ee2e8d2dbeee\nTime:2020-06-29T14:57:53.997Z</Message>\n</Error>" ErrorStack="StorageError: Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues\n    at BlobHandler.copyFromURL (C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\handlers\\BlobHandler.js:37:15)\n    at C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\generated\\middleware\\HandlerMiddlewareFactory.js:58:18\n    at C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\generated\\ExpressMiddlewareFactory.js:77:63\n    at Layer.handle [as handle_request] (C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
2020-06-29T14:57:53.997Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee error: ErrorMiddleware: Set HTTP code: 500
2020-06-29T14:57:53.997Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee error: ErrorMiddleware: Set HTTP status message: Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues
2020-06-29T14:57:53.997Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=APINotImplemented
2020-06-29T14:57:53.998Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=4d778175-3e41-48d0-9b27-ee2e8d2dbeee
2020-06-29T14:57:53.998Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee error: ErrorMiddleware: Set content type: application/xml
2020-06-29T14:57:53.998Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>APINotImplemented</Code>\n  <Message>Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues\nRequestId:4d778175-3e41-48d0-9b27-ee2e8d2dbeee\nTime:2020-06-29T14:57:53.997Z</Message>\n</Error>"
2020-06-29T14:57:53.998Z 4d778175-3e41-48d0-9b27-ee2e8d2dbeee info: EndMiddleware: End response. TotalTimeInMS=3 StatusCode=500 StatusMessage=Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues Headers={"server":"Azurite-Blob/3.7.0","x-ms-error-code":"APINotImplemented","x-ms-request-id":"4d778175-3e41-48d0-9b27-ee2e8d2dbeee","content-type":"application/xml"}

**Comment by AlexanderYW** [comment]
Perfect :), how often is work being done on this project from "Azure/Microsoft" side, or is this purely hobby and community contributed?

**Comment by XiaoningLiu** [comment]
We will triage pending features and issues before monthly release planning, Due to the limiited resource, we need to prioritise critical issues and important features according to the triage meeting. In the same time, we are pretty welcome for community contribution : ) Azurite already has CopyBlob implemented, it should be simliar for SyncCopyBlob.

**Comment by AlexanderYW** [comment]
Just what i wanted to hear :D, if I get the time I will try to give it a look, no promise :)

**Comment by AlexanderYW** [comment]
PR: #469
