### ISSUE TITLE
Upgrade to sequelize 6.3.0

### ISSUE THREAD

**Issue by patrickcarnahan** [Azure/Azurite#467]
While moving to azurite in an attempt to increase agility and reliability for developers on my team, I tried to make use of the mssql dialect since there is already an mssql instance available. Unfortunately when attempting to `PUT` blob content with this backend I immediately ran into https://github.com/sequelize/sequelize/issues/11902. 

I have already had a change accepted in the master branch of sequelize and am currently porting to the `v6` branch for release to npm. 

Is there any reason an upgrade to a 6.x version with this fix would not be accepted? I'm happy to drive this in addition to adding an mssql run to the test matrix.

**Comment by patrickcarnahan** [comment]
This is now available in https://github.com/sequelize/sequelize/releases/tag/v6.3.0

**Comment by patrickcarnahan** [comment]
@blueww if it helps expedite this in any way I have gotten confirmation from a maintainer of sequelize that this can be ported to 5.x.

**Comment by blueww** [comment]
@patrickcarnahan 
Thanks for raising this!

Would you please share the debug log for Azurite, so we can know the detail error.
This can help us to evaluate the request, and add test case for this issue.

**Comment by patrickcarnahan** [comment]
@blueww sure thing, I will post this evening. Having said that, it's not difficult to cause the failure as long as the `Deleted` and `Snapshot` fields of the blob are `false` and `""` respectively. It should be as simple as doing a block blob creation with mssql as the dialect.

**Comment by patrickcarnahan** [comment]
below you can find the debug log. this includes output both with and without the fix (i changed the file in my local `node_modules` folder. 

## failure sample

```
2020-07-01T18:44:56.210Z 53930802-52d0-4fb2-9a79-facd2639d083 verbose: FSExtentStore:readExtent() Read stream closed. LocationId:Default extentId:08052e63-949e-4ccc-8f0a-1af36767c933 path:/Users/patcarna/code/azurite/__blobstorage__/08052e63-949e-4ccc-8f0a-1af36767c933 offset:0 count:1024 end:1023
2020-07-01T18:44:56.233Z 53930802-52d0-4fb2-9a79-facd2639d083 error: ErrorMiddleware: Received an error, fill error information to HTTP response
2020-07-01T18:44:56.233Z 53930802-52d0-4fb2-9a79-facd2639d083 error: ErrorMiddleware: ErrorName=Error ErrorMessage=Primary Key or Unique key should be passed to upsert query ErrorStack="Error: Primary Key or Unique key should be passed to upsert query\n    at MSSQLQueryGenerator.upsertQuery (/Users/patcarna/code/azurite/node_modules/sequelize/lib/dialects/mssql/query-generator.js:462:13)\n    at QueryInterface.upsert (/Users/patcarna/code/azurite/node_modules/sequelize/lib/query-interface.js:948:37)\n    at /Users/patcarna/code/azurite/node_modules/sequelize/lib/model.js:2490:38\n    at tryCatcher (/Users/patcarna/code/azurite/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/patcarna/code/azurite/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/Users/patcarna/code/azurite/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/Users/patcarna/code/azurite/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/Users/patcarna/code/azurite/node_modules/bluebird/js/release/promise.js:699:18)\n    at _drainQueueStep (/Users/patcarna/code/azurite/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/Users/patcarna/code/azurite/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/Users/patcarna/code/azurite/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/Users/patcarna/code/azurite/node_modules/bluebird/js/release/async.js:17:14)\n    at processImmediate (internal/timers.js:445:21)"
2020-07-01T18:44:56.233Z 53930802-52d0-4fb2-9a79-facd2639d083 error: ErrorMiddleware: Set HTTP code: 500
2020-07-01T18:44:56.233Z 53930802-52d0-4fb2-9a79-facd2639d083 info: EndMiddleware: End response. TotalTimeInMS=121 StatusCode=500 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.7.0"}
```

[debug.log.zip](https://github.com/Azure/Azurite/files/4887840/debug.log.zip)

**Comment by blueww** [comment]
@patrickcarnahan 
Thanks for the log!
We will investigate it and prioritize the upgrade.

**Comment by patrickcarnahan** [comment]
@blueww as mentioned before I have also gotten buy off to port this back to `v5`, which is your current major version. This may be a less risky option so let me know if that helps get this bumped and I can work on getting it ported.

**Comment by blueww** [comment]
@patrickcarnahan 
Thanks for the support!
It would be great if the fix can be back port to v5, then Azurite should can take it without any code change.

We need time to evaluate if v6 works well in Azurite. We have put it in our tasks, but might need to work on some other higher priority work first.

**Comment by patrickcarnahan** [comment]
@blueww the fix is being cherry-picked to v5 here: https://github.com/sequelize/sequelize/pull/12504. i will update this issue once it has been accepted and released to npm.

**Comment by blueww** [comment]
@patrickcarnahan 
Thanks for the update!
