### ISSUE TITLE
Unable to create storage container via ruby gem

### ISSUE THREAD

**Issue by kirillrdy** [Azure/Azurite#515]
### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
git ad9395761a06bb3de10da17d5aace2eb40c4bdae

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
github

### What's the Node.js version?
v12.16.3
### What problem was encountered?
When trying to create storage container, i get this response from blob
```
2020-07-22T22:19:23.157Z 	 info: Azurite Blob service is starting on 127.0.0.1:10000
2020-07-22T22:19:23.157Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2020-07-22T22:19:23.158Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2020-07-22T22:19:23.163Z 	 info: BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2020-07-22T22:19:23.163Z 	 info: BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2020-07-22T22:19:23.163Z 	 info: BlobGCManager:markSweepLoop() Start next mark and sweep.
2020-07-22T22:19:23.164Z 	 info: BlobGCManager:markSweep() Get all extents.
2020-07-22T22:19:23.164Z 	 info: BlobGCManager:start() BlobGCManager successfully started.
2020-07-22T22:19:23.165Z 	 info: BlobGCManager:markSweep() Got 0 extents.
2020-07-22T22:19:23.165Z 	 info: BlobGCManager:markSweep() Get referred extents.
2020-07-22T22:19:23.165Z 	 info: BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2020-07-22T22:19:23.165Z 	 info: BlobGCManager:markSweepLoop() Mark and sweep finished, taken 1ms.
2020-07-22T22:19:23.166Z 	 info: BlobGCManager:markSweepLoop() Sleep for 600000ms.
2020-07-22T22:19:23.166Z 	 info: Azurite Blob service successfully listens on http://127.0.0.1:10000
2020-07-22T22:19:25.106Z 29215a59-d2fa-4606-8bc6-eaba7f58777d info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://localhost/test-container?restype=container RequestHeaders:{"user-agent":"Azure-Storage/1.1.0-1.1.0 (Ruby 2.5.8-p224; Linux linux-gnu)","x-ms-date":"Wed, 22 Jul 2020 22:19:25 GMT","x-ms-version":"2017-11-09","dataserviceversion":"1.0;NetFx","maxdataserviceversion":"3.0;NetFx","content-type":"application/atom+xml; charset=utf-8","content-length":"0","authorization":"SharedKey devstoreaccount1:Qz7tPoDe/yrtAl0WOZGg19TDCMn2pqgSQQfzmLnWCDQ=","accept-encoding":"gzip;q=1.0,deflate;q=0.6,identity;q=0.3","accept":"*/*","connection":"close","host":"localhost:10000"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2020-07-22T22:19:25.106Z 29215a59-d2fa-4606-8bc6-eaba7f58777d info: BlobStorageContextMiddleware: Account=test-container Container=undefined Blob=
2020-07-22T22:19:25.107Z 29215a59-d2fa-4606-8bc6-eaba7f58777d verbose: DispatchMiddleware: Dispatching request...
2020-07-22T22:19:25.108Z 29215a59-d2fa-4606-8bc6-eaba7f58777d error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2020-07-22T22:19:25.108Z 29215a59-d2fa-4606-8bc6-eaba7f58777d error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2020-07-22T22:19:25.118Z 29215a59-d2fa-4606-8bc6-eaba7f58777d error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at Object.dispatchMiddleware [as default] (/home/kirillvr/Azurite/src/blob/generated/middleware/dispatch.middleware.ts:60:26)\n    at /home/kirillvr/Azurite/src/blob/generated/ExpressMiddlewareFactory.ts:54:25\n    at Layer.handle [as handle_request] (/home/kirillvr/Azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/kirillvr/Azurite/node_modules/express/lib/router/index.js:317:13)\n    at /home/kirillvr/Azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/home/kirillvr/Azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/home/kirillvr/Azurite/node_modules/express/lib/router/index.js:275:10)\n    at blobStorageContextMiddleware (/home/kirillvr/Azurite/src/blob/middlewares/blobStorageContext.middleware.ts:111:3)\n    at /home/kirillvr/Azurite/src/blob/middlewares/blobStorageContext.middleware.ts:21:12\n    at Layer.handle [as handle_request] (/home/kirillvr/Azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/kirillvr/Azurite/node_modules/express/lib/router/index.js:317:13)\n    at /home/kirillvr/Azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/home/kirillvr/Azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/home/kirillvr/Azurite/node_modules/express/lib/router/index.js:275:10)\n    at logger (/home/kirillvr/Azurite/node_modules/morgan/index.js:144:5)\n    at Layer.handle [as handle_request] (/home/kirillvr/Azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/kirillvr/Azurite/node_modules/express/lib/router/index.js:317:13)\n    at /home/kirillvr/Azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/home/kirillvr/Azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/home/kirillvr/Azurite/node_modules/express/lib/router/index.js:275:10)\n    at expressInit (/home/kirillvr/Azurite/node_modules/express/lib/middleware/init.js:40:5)\n    at Layer.handle [as handle_request] (/home/kirillvr/Azurite/node_modules/express/lib/router/layer.js:95:5)"
2020-07-22T22:19:25.118Z 29215a59-d2fa-4606-8bc6-eaba7f58777d error: ErrorMiddleware: Set HTTP code: 400
2020-07-22T22:19:25.118Z 29215a59-d2fa-4606-8bc6-eaba7f58777d error: ErrorMiddleware: Set HTTP body: undefined
2020-07-22T22:19:25.118Z 29215a59-d2fa-4606-8bc6-eaba7f58777d info: EndMiddleware: End response. TotalTimeInMS=12 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.8.0"}

```
### Steps to reproduce the issue?

npm build
npm run-script blob -- -d foo

ruby code using this library https://github.com/Azure/azure-storage-ruby
```ruby
client = Azure::Storage::Blob::BlobService.create(
  storage_blob_host: 'http://localhost:10000',
  storage_account_name: 'devstoreaccount1',
  storage_access_key: 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==')

client.create_container("test-container")
```

### Have you found a mitigation/solution?
No, I am not sure if its ruby gem or azurite but we can start conversation from here

Thanks in advance

**Comment by XiaoningLiu** [comment]
Try 'http://localhost:10000/devstoreaccount1' as host.

**Comment by kirillrdy** [comment]
Sorry, I haven't had a chance to get back to you. Closing for now, if I have any more questions I'll reopen or open a new issue.

Thanks
