### ISSUE TITLE
Azurite allows blob storage metadata which is not allowed by Azure proper

### ISSUE THREAD

**Issue by alexwlchan** [Azure/Azurite#532]
### Which service(blob, file, queue, table) does this issue concern?

Blob

### Which version of the Azurite was used?

3.8.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

Docker Hub

### What's the Node.js version?

Whatever comes in the container

### What problem was encountered?

Azurite allows the user to write blob storage metadata with names which are not allowed by Azure proper.

In particular, we've found that Azurite allows hyphens in metadata names, which are not allowed in the real blob storage – [names have to be valid C# identifiers](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-properties-metadata?tabs=dotnet).

e.g. `Content-SHA256` is allowed as a metadata name in Azurite, but not in Azure.

### Steps to reproduce the issue?

Here's a small Scala program that tries to set a tag with a hyphen:

```scala
import com.azure.storage.blob.{BlobServiceClient, BlobServiceClientBuilder}
import java.io.ByteArrayInputStream
import scala.collection.JavaConverters._

val blobServiceClient: BlobServiceClient

val containerName = "tagtesting"
val blobName = "my_blob"

blobServiceClient.createBlobContainer(containerName)

val blobClient = blobServiceClient
  .getBlobContainerClient(containerName)
  .getBlobClient(blobName)

blobClient.upload(new ByteArrayInputStream(Array[Byte]()), 0)

blobClient.setMetadata(Map("Content-SHA256" -> "123").asJava)

println(blobClient.getProperties.getMetadata.asScala)
```

If I create a client that talks to Azurite, this sets the metadata, and prints the correct metadata when I call `getMetadata`:

```scala
val azureClient: BlobServiceClient =
  new BlobServiceClientBuilder()
    .connectionString("UseDevelopmentStorage=true;")
    .buildClient()
```

If I run this against our live storage account, I get an error:

```
Status code 400, "<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidMetadata</Code><Message>The metadata specified is invalid. It has characters that are not permitted.
```

Removing the hyphen (i.e. `ContentSHA256`) allows me to write the metadata.

<details><summary>Full Java stack trace, in case it's useful</summary>

```
Status code 400, "<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidMetadata</Code><Message>The metadata specified is invalid. It has characters that are not permitted.
RequestId:2610d6e3-601e-00e8-4505-72d5ed000000
Time:2020-08-14T06:40:25.0727996Z</Message></Error>"
com.azure.storage.blob.models.BlobStorageException: Status code 400, "<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidMetadata</Code><Message>The metadata specified is invalid. It has characters that are not permitted.
RequestId:2610d6e3-601e-00e8-4505-72d5ed000000
Time:2020-08-14T06:40:25.0727996Z</Message></Error>"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:320)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$3(RestProxy.java:361)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2317)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:366)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:367)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:423)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:607)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1279)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1316)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1678)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
		at com.azure.storage.blob.specialized.BlobClientBase.setMetadataWithResponse(BlobClientBase.java:717)
		at com.azure.storage.blob.specialized.BlobClientBase.setMetadata(BlobClientBase.java:693)
		at uk.ac.wellcome.storage.azure.AzureBlobLocationTest.$anonfun$new$1(AzureBlobLocationTest.scala:29)
		at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
		at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
		at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
		at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
		at org.scalatest.Transformer.apply(Transformer.scala:22)
		at org.scalatest.Transformer.apply(Transformer.scala:20)
		at org.scalatest.funspec.AnyFunSpecLike$$anon$1.apply(AnyFunSpecLike.scala:456)
		at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
		at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
		at org.scalatest.funspec.AnyFunSpec.withFixture(AnyFunSpec.scala:1631)
		at org.scalatest.funspec.AnyFunSpecLike.invokeWithFixture$1(AnyFunSpecLike.scala:454)
		at org.scalatest.funspec.AnyFunSpecLike.$anonfun$runTest$1(AnyFunSpecLike.scala:466)
		at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
		at org.scalatest.funspec.AnyFunSpecLike.runTest(AnyFunSpecLike.scala:466)
		at org.scalatest.funspec.AnyFunSpecLike.runTest$(AnyFunSpecLike.scala:448)
		at org.scalatest.funspec.AnyFunSpec.runTest(AnyFunSpec.scala:1631)
		at org.scalatest.funspec.AnyFunSpecLike.$anonfun$runTests$1(AnyFunSpecLike.scala:499)
		at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
		at scala.collection.immutable.List.foreach(List.scala:389)
		at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
		at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
		at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
		at org.scalatest.funspec.AnyFunSpecLike.runTests(AnyFunSpecLike.scala:499)
		at org.scalatest.funspec.AnyFunSpecLike.runTests$(AnyFunSpecLike.scala:498)
		at org.scalatest.funspec.AnyFunSpec.runTests(AnyFunSpec.scala:1631)
		at org.scalatest.Suite.run(Suite.scala:1112)
		at org.scalatest.Suite.run$(Suite.scala:1094)
		at org.scalatest.funspec.AnyFunSpec.org$scalatest$funspec$AnyFunSpecLike$$super$run(AnyFunSpec.scala:1631)
		at org.scalatest.funspec.AnyFunSpecLike.$anonfun$run$1(AnyFunSpecLike.scala:503)
		at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
		at org.scalatest.funspec.AnyFunSpecLike.run(AnyFunSpecLike.scala:503)
		at org.scalatest.funspec.AnyFunSpecLike.run$(AnyFunSpecLike.scala:502)
		at org.scalatest.funspec.AnyFunSpec.run(AnyFunSpec.scala:1631)
		at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
		at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1320)
		at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1314)
		at scala.collection.immutable.List.foreach(List.scala:389)
		at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1314)
		at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
		at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
		at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
		at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
		at org.scalatest.tools.Runner$.run(Runner.scala:798)
		at org.scalatest.tools.Runner.run(Runner.scala)
		at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
		at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

</details>

### Have you found a mitigation/solution?

n/a.

This isn’t a blocker, just an annoyance – all our code is tested against Azurite, and it was writing these tags merrily until we pointed it at real Azure. If Azurite had caught this in tests, we'd have fixed this earlier.

**Comment by blueww** [comment]
@alexwlchan

Thanks for reporting this issue!
We will investigate/triage it and see how to fix it.

**Comment by mma5997-nuance** [comment]
I faced the same issue that Azurite allows setting the metadata but when I open the Azure Storage Explorer and check the metadata, the Explorer highlights the metadata key which contains hyphen, with red border, saying it contains invalid C# identifier... seems hyphen creates an issue if its present in the keys of metadata map... I also faced that when my AzureJavaClient uses the same metadata to be set for a blob, it fails with an exception as aforementioned in thread above.

**Comment by blueww** [comment]
I have raise a PR to fix it: https://github.com/Azure/Azurite/pull/1920

**Comment by blueww** [comment]
The fix Pr is already merged, should be release in the next Azurite release which might will out in 1-2 months.
Before the fix is released, you can also build/run Azurite from latest code on your own machine by follow: https://github.com/Azure/Azurite#github
