### ISSUE TITLE
Azurite returns a HTTP header error when called with the new Azure.Storage.Blobs (12.5.0 Stable) package

### ISSUE THREAD

**Issue by rishu73** [Azure/Azurite#534]
### Which service(blob, file, queue, table) does this issue concern?
Blob Service
### Which version of the Azurite was used?
3.6
Works better in 3.8 though. Closing

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
mcr.microsoft.com/azure-storage/azurite
### What's the Node.js version?
12.18.2
### What problem was encountered?
Attempted to iterate through the results of Azure.Storage.Blobs.BlobServiceClient.GetBlobContainersAsync() using the new v12.5.0 (stable) NuGet package and got the following exception:

RequestFailedException exception thrown: The value for one of the HTTP headers is not in the correct format.
RequestId:2ef3909a-5575-4975-be65-1f4f98510a5e
Time:2020-08-14T18:02:54.015Z
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue

Headers:
Server: Azurite-Blob/3.7.0
x-ms-error-code: InvalidHeaderValue
x-ms-request-id: 2ef3909a-5575-4975-be65-1f4f98510a5e
Date: Fri, 14 Aug 2020 18:02:54 GMT
Connection: keep-alive
Transfer-Encoding: chunked
Content-Type: application/xml

Stack Trace:
   at Azure.Storage.Blobs.BlobRestClient.Service.ListBlobContainersSegmentAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Service.ListBlobContainersSegmentAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, String prefix, String marker, Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetBlobContainersInternal(String continuationToken, BlobContainerTraits traits, BlobContainerStates states, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Models.GetBlobContainersAsyncCollection.GetNextPageAsync(String continuationToken, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at MyCompany.MyProduct.Common.Storage.Services.StorageService.GetContainersAsync() in C:\Services\StorageService.cs:line 245

Using Azure.Storage.Blobs v12.4.4 the operation works fine.
### Steps to reproduce the issue?
Use Azure.Storage.Blobs v12.5.0 NuGet package
BlobServiceClient serviceClient = await GetServiceClient();
await foreach (var container in serviceClient.GetBlobContainersAsync())
{
      Debug.Write("Don't even get here");
}
### Have you found a mitigation/solution?
Don't use v12.5.0 which is a shame because I wanted to play with the new Azure Blob Versioning functionality....

**Comment by rishu73** [comment]
Updated Azurite to 3.8 and error went away.
