### ISSUE TITLE
The simplest way to setup new containers via http api?

### ISSUE THREAD

**Issue by longtimeago** [Azure/Azurite#602]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
3.9.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
-

### What problem was encountered?
```
curl -XPUT http://localhost:10000/devstoreaccount1/proemion?restype=container -H "Authorization: AccountName=devstoreaccount1;AccountKey=foobar"
```
doesn't work anymore
```xml
<Error>
  <Code>AuthorizationFailure</Code>
  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
RequestId:17dc1230-47a1-4c6a-b607-28ee5ac6c536
Time:2020-10-23T15:26:56.486Z</Message>
</Error>
```

### Have you found a mitigation/solution?
No

We are using no longer maintained https://github.com/arafato/azurite v 2.6.5.
Currently, decided to migrate to latest 3.9.0 but the request above not longer work.
We use azurite in integration tests in a following way
1) Start a Docker container with azurite
2) Create several blob containers
3) Run a test on service-under-development
4) Check expected content of blob containers

What would be the best way to perform step 2 now with 3.9.0 (in an automated way of course)?
Thanks in advance!

P.S. Didn't found any google group or another way to ask questions like this :(

**Comment by blueww** [comment]
@longtimeago 

Please  check you have input the storage account name and key in https://github.com/Azure/Azurite#default-storage-account.
Azurite will check the account credential.

If you have already input the correct account credential, would you please share the debug log for the failure request?

**Comment by longtimeago** [comment]
@blueww yup, I've tried to change my url with mentioned account key
```
curl -XPUT http://localhost:10000/devstoreaccount1/proemion?restype=container -H "Authorization: AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
```

Got the same 403 error.
Here is the debug output
```
2020-10-26T06:22:43.323Z 	 info: Azurite Blob service is starting on 127.0.0.1:10000
2020-10-26T06:22:43.324Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2020-10-26T06:22:43.324Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2020-10-26T06:22:43.330Z 	 info: BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2020-10-26T06:22:43.330Z 	 info: BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2020-10-26T06:22:43.330Z 	 info: BlobGCManager:markSweepLoop() Start next mark and sweep.
2020-10-26T06:22:43.331Z 	 info: BlobGCManager:markSweep() Get all extents.
2020-10-26T06:22:43.331Z 	 info: BlobGCManager:start() BlobGCManager successfully started.
2020-10-26T06:22:43.332Z 	 info: BlobGCManager:markSweep() Got 0 extents.
2020-10-26T06:22:43.332Z 	 info: BlobGCManager:markSweep() Get referred extents.
2020-10-26T06:22:43.332Z 	 info: BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2020-10-26T06:22:43.333Z 	 info: BlobGCManager:markSweepLoop() Mark and sweep finished, taken 3ms.
2020-10-26T06:22:43.333Z 	 info: BlobGCManager:markSweepLoop() Sleep for 600000ms.
2020-10-26T06:22:43.333Z 	 info: Azurite Blob service successfully listens on http://127.0.0.1:10000
2020-10-26T06:22:43.334Z 	 info: Azurite Queue service is starting on 127.0.0.1:10001
2020-10-26T06:22:43.334Z 	 info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2020-10-26T06:22:43.334Z 	 info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2020-10-26T06:22:43.337Z 	 info: QueueGCManager:start() Starting QueueGCManager, set status to Initializing
2020-10-26T06:22:43.337Z 	 info: QueueGCManager:start() Trigger mark and sweep loop, set status to Running.
2020-10-26T06:22:43.337Z 	 info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2020-10-26T06:22:43.337Z 	 info: QueueGCManger:markSweep() Get all extents.
2020-10-26T06:22:43.337Z 	 info: QueueGCManager:start() QueueGCManager successfully started.
2020-10-26T06:22:43.338Z 	 info: QueueGCManager:marksweep() Get 0 extents.
2020-10-26T06:22:43.338Z 	 info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2020-10-26T06:22:43.338Z 	 info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2020-10-26T06:22:43.338Z 	 info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2020-10-26T06:22:43.338Z 	 info: QueueGCManager:markSweepLoop() Sleep for 60000
2020-10-26T06:22:43.338Z 	 info: Azurite Queue service successfully listens on http://127.0.0.1:10001
2020-10-26T06:23:11.838Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://localhost/devstoreaccount1/proemion?restype=container RequestHeaders:{"host":"localhost:10000","user-agent":"curl/7.68.0","accept":"*/*","authorization":"AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2020-10-26T06:23:11.838Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=proemion Blob=
2020-10-26T06:23:11.838Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 verbose: DispatchMiddleware: Dispatching request...
2020-10-26T06:23:11.839Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: DispatchMiddleware: Operation=Container_Create
2020-10-26T06:23:11.840Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2020-10-26T06:23:11.840Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: PublicAccessAuthenticator:validate() Start validation against public access.
2020-10-26T06:23:11.840Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: PublicAccessAuthenticator:validate() Getting account properties...
2020-10-26T06:23:11.840Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: proemion, blob: 
2020-10-26T06:23:11.853Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container proemion
2020-10-26T06:23:11.853Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2020-10-26T06:23:11.854Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n\n\n\n\n\n\n\n\n\n/devstoreaccount1/devstoreaccount1/proemion\nrestype:container"
2020-10-26T06:23:11.854Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:3yomgI6L/f9kANRR3kfNqmSOI/PngEmvqML0WRCHQdE=
2020-10-26T06:23:11.854Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: BlobSharedKeyAuthenticator:validate() Validation failed.
2020-10-26T06:23:11.854Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: AccountSASAuthenticator:validate() Start validation against account Shared Access Signature pattern.
2020-10-26T06:23:11.854Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: AccountSASAuthenticator:validate() Getting account properties...
2020-10-26T06:23:11.854Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: AccountSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: proemion, blob: 
2020-10-26T06:23:11.854Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: AccountSASAuthenticator:validate() Got account properties successfully.
2020-10-26T06:23:11.854Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: AccountSASAuthenticator:validate() Retrieved signature from URL parameter sig: undefined
2020-10-26T06:23:11.855Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: AccountSASAuthenticator:validate() Failed to get valid account SAS values from request.
2020-10-26T06:23:11.855Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: BlobSASAuthenticator:validate() Start validation against blob service Shared Access Signature pattern.
2020-10-26T06:23:11.855Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: BlobSASAuthenticator:validate() Getting account properties...
2020-10-26T06:23:11.855Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: BlobSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: proemion, blob: 
2020-10-26T06:23:11.855Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: BlobSASAuthenticator:validate() Got account properties successfully.
2020-10-26T06:23:11.855Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: BlobSASAuthenticator:validate() Retrieved signature from URL parameter sig: undefined
2020-10-26T06:23:11.855Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 debug: BlobSASAuthenticator:validate() No signature found in request. Skip blob service SAS validation.
2020-10-26T06:23:11.856Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2020-10-26T06:23:11.856Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.  ErrorHTTPStatusCode=403 ErrorHTTPStatusMessage=Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature. ErrorHTTPHeaders={"x-ms-error-code":"AuthorizationFailure","x-ms-request-id":"0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationFailure</Code>\n  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5\nTime:2020-10-26T06:23:11.855Z</Message>\n</Error>" ErrorStack="StorageError: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\n    at Function.getAuthorizationFailure (/home/papolishchuk/.nvm/versions/node/v12.18.3/lib/node_modules/azurite/dist/src/blob/errors/StorageErrorFactory.js:134:16)\n    at /home/papolishchuk/.nvm/versions/node/v12.18.3/lib/node_modules/azurite/dist/src/blob/middlewares/AuthenticationMiddlewareFactory.js:22:56\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
2020-10-26T06:23:11.856Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 error: ErrorMiddleware: Set HTTP code: 403
2020-10-26T06:23:11.856Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 error: ErrorMiddleware: Set HTTP status message: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
2020-10-26T06:23:11.856Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=AuthorizationFailure
2020-10-26T06:23:11.856Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5
2020-10-26T06:23:11.856Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 error: ErrorMiddleware: Set content type: application/xml
2020-10-26T06:23:11.856Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationFailure</Code>\n  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5\nTime:2020-10-26T06:23:11.855Z</Message>\n</Error>"
2020-10-26T06:23:11.856Z 0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5 info: EndMiddleware: End response. TotalTimeInMS=19 StatusCode=403 StatusMessage=Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature. Headers={"server":"Azurite-Blob/3.9.0","x-ms-error-code":"AuthorizationFailure","x-ms-request-id":"0cfb0702-f5c1-415a-9ac1-4ddec1ec80f5","content-type":"application/xml"}
```

**Comment by blueww** [comment]
@longtimeago

The credentail you input with Curl is not in the correct format.

If you want to use key credential, you can reference following link to see how to set key credential necessary with Curl : https://stackoverflow.com/questions/20103258/accessing-azure-blob-storage-using-bash-curl

For a simpler way, you can just create an account SAS token with at least blob service, and container resource type, and w permission, then try to call curl with the SASUri ,like following: 
```
curl -XPUT "http://localhost.:10000/devstoreaccount1/proemion?sv=2019-07-07&sig=[hidden]&se=2050-12-11T16%3A00%3A00Z&srt=sco&ss=b&sp=rwdl&api-version=2019-07-07&restype=container"
```
For more information of account sas, see: https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas?redirectedfrom=MSDN

**Comment by longtimeago** [comment]
@blueww uff ... took me a while but eventually SAS way worked.
The lack of proper tooling makes this way quite challenging.
TBH, for the integration-testing use-case I'd expect azurite to have simplified technical API to setup and assert internal state (just as it was in 2.6.5).

Anyway, thanks for your help! :+1:

**Comment by blueww** [comment]
@longtimeago 
Good to know you get it work for you!

Azurite V3 will validate the credential from the input request, this is an enhancement from Azurite V2, make Azurite be more aligned with server.

To generate SAS, you can generate it with SDK or other tools. I use Powershell as following steps:
1. Install Powershell Storage module with adminitrator priviliage (one time work) : `Install-Module Az.Storage -Repository PSGallery -Force` 
2. Open a new Powershell console, and run following script:
```powershell
$ctx = New-AzStorageContext -ConnectionString "AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://localhost.:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;"

New-AzStorageAccountSASToken -Service Blob -ResourceType Service,Container,Object -Permission wrdl -Context $ctx -ExpiryTime 2050-12-12
```

**Comment by longtimeago** [comment]
@blueww thank you! :+1:

**Comment by dimaqq** [comment]
I helped to ban Azure Storage in my company because it's such a pain to automate.

Take it how you will.
