### ISSUE TITLE
Azurite v3 Tables (alpha.1) - Durable Functions fails to start (Unsupported Media Type)

### ISSUE THREAD

**Issue by cgillum** [Azure/Azurite#613]
### Which service(blob, file, queue, table) does this issue concern?
Tables

### Which version of the Azurite was used?
azurite@3.9.0-table-alpha.1

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm install -g azurite@alpha

### What's the Node.js version?
v10.14.1

### Azure Storage SDK Version
Durable Functions on the latest version of the Azure Functions runtime uses [WindowsAzure.Storage v9.3.1](https://www.nuget.org/packages/WindowsAzure.Storage/9.3.1).

### What problem was encountered?
When attempting to start a Durable Functions application that uses Azurite in the backend, the following error is encountered.

```
[2020-11-11T18:53:28.682] General error: Failed to create the task hub: Microsoft.WindowsAzure.Storage.StorageException: Unsupported Media Type
[2020-11-11T18:53:28.684]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
[2020-11-11T18:53:28.684]    at Microsoft.WindowsAzure.Storage.Table.CloudTable.CreateIfNotExistsAsync(TableRequestOptions requestOptions, OperationContext operationContext, CancellationToken cancellationToken)
[2020-11-11T18:53:28.685]    at DurableTask.AzureStorage.AzureStorageOrchestrationService.GetTaskHubCreatorTask() in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 363
[2020-11-11T18:53:28.686]    at DurableTask.AzureStorage.AzureStorageOrchestrationService.EnsureTaskHubAsync() in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 325
[2020-11-11T18:53:28.687] Request Information
[2020-11-11T18:53:28.687] RequestID:d2461c28-be61-480d-b374-927410c122ec
[2020-11-11T18:53:28.688] RequestDate:Wed, 11 Nov 2020 10:53:28 GMT
[2020-11-11T18:53:28.688] StatusMessage:Unsupported Media Type
[2020-11-11T18:53:28.689] ErrorCode:AtomFormatNotSupported
[2020-11-11T18:53:28.690] ErrorMessage:Atom format is not supported.
RequestId:d2461c28-be61-480d-b374-927410c122ec
Time:2020-11-11T18:53:28.601Z
```

### Steps to reproduce the issue?
1. Install the [Azure Functions Core Tools](https://github.com/Azure/azure-functions-core-tools#installing) (v3)
1. Clone and build the following sample app: https://github.com/Azure/azure-functions-durable-extension/tree/dev/samples/precompiled
1. `cd` into the `samples\precompiled\bin\Debug\netcoreapp3.1` directory
1. Run `func host start`

### Have you found a mitigation/solution?
Not yet, but I'm guessing that our internal use of the older storage SDK is part of the problem. We plan to upgrade eventually, but this needs to be carefully coordinated with the Azure Functions storage SDK dependencies.

**Comment by XiaoningLiu** [comment]
Hi @cgillum Can you share the Azurite debug.log here?

According to https://docs.microsoft.com/en-us/rest/api/storageservices/payload-format-for-table-service-operations.

> JSON is the recommended payload format. JSON is supported for version 2013-08-15 and newer. You must use JSON with version 2015-12-11 and later. ATOM is supported for versions earlier than 2015-12-11.

Azurite V3 Table targets API version from 2019-12-12, thus Atom payload is not supported.

**Comment by XiaoningLiu** [comment]
Hi @cgillum Does this looks good?

![image](https://user-images.githubusercontent.com/6889160/98891721-bbab4900-24d9-11eb-9cc0-316241206449.png)

**Comment by XiaoningLiu** [comment]
Failure reason is, the SDK you are using addes an additional space character in the accept parameter. Ideally azurite expects "application/json;odata=minimalmetadata" while SDK sends out "application/json; odata=minimalmetadata".

After updated Azurite to compatible with the addtional space. `func host start` starts successfully.

**Comment by cgillum** [comment]
@XiaoningLiu yes, that looks better! I would need to investigate the blob lease operation failure warnings that you're seeing, but it looks like you progressed past the table creation operation.

**Comment by XiaoningLiu** [comment]
Created a PR  #615 for fix. Please build and start Azurite from table branch and try again after PR merged.

**Comment by XiaoningLiu** [comment]
PR merged.

**Comment by XiaoningLiu** [comment]
Fixed a lease management issue on table branch. Now the warnings all gone.

![image](https://user-images.githubusercontent.com/6889160/98911666-ee683800-24ff-11eb-90a5-4fc6e286947e.png)

**Comment by cgillum** [comment]
I can confirm that the latest build from the table branch resolves the startup issue. Thanks! This issue can be closed. I'll open new issues for subsequent blockers.

**Comment by nelsonmorais** [comment]
@XiaoningLiu Will the docker images be updated as well? Which tag will contain this changes?
![image](https://user-images.githubusercontent.com/4737667/99109310-e801bb00-25e8-11eb-8236-3950f1257aa0.png)

**Comment by cnieren** [comment]
@XiaoningLiu Any movement on Azureite Table support?

**Comment by XiaoningLiu** [comment]
@edwin is helping with Table Batch support, after that we will have another release for table. Close this.
