### ISSUE TITLE
Azurite | Durable functions not starting - no connection could be made

### ISSUE THREAD

**Issue by command0r** [Azure/Azurite#614]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the Azurite was used?
Latest

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Trying to use both Visual Studio Code Extension and npm

### What's the Node.js version?
14.5.0 (latest)

### What problem was encountered?
The listener for function 'Functions.<...>' was unable to start. Microsoft.WindowsAzure.Storage: No connection could be made because the target machine actively refused it. System.Net.Http: No connection could be made because the target machine actively refused it. System.Private.CoreLib: No connection could be made because the target machine actively refused it.

### Steps to reproduce the issue?

- Install Azurite
- Setup Azure durable functions (HTTP trigger) for Python
- Run Azure function and try to trigger it via Postman
- Enjoy the errors popping up

### Have you found a mitigation/solution?
Works fine with remote storage, which made me think that either I'm doing something wrong or it doesn't want to work with the local storage indeed. Azure Storage Explorer recognizes Azurite and I can see it. Neither npm package nor VS Code extension works here.

**Comment by command0r** [comment]
I'm running Azurite in a debug mode and seeing quite interesting details... It seems it's erroring on the container creation?
`
2020-11-12T03:47:03.090Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://127.0.0.1/devstoreaccount1/azure-webjobs-secrets?restype=container RequestHeaders:{"x-ms-client-request-id":"c1d433d5-ee1d-4cdf-b58e-ef7b2191371d","user-agent":"Azure-Storage/11.1.7 (.NET Core; Win32NT 6.2.9200.0)","x-ms-version":"2019-02-02","x-ms-date":"Thu, 12 Nov 2020 03:47:03 GMT","authorization":"SharedKey devstoreaccount1:oZ1hHaOudmsZBFjCv0vJRLBDsdfarjkacM3W4g3U/+M=","content-length":"0","host":"127.0.0.1:10000"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2020-11-12T03:47:03.090Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=**azure-webjobs-secrets** Blob=
2020-11-12T03:47:03.090Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 verbose: DispatchMiddleware: Dispatching request...
2020-11-12T03:47:03.091Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 info: DispatchMiddleware: Operation=Container_Create
2020-11-12T03:47:03.091Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2020-11-12T03:47:03.091Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 info: PublicAccessAuthenticator:validate() Start validation against public access.
2020-11-12T03:47:03.091Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 debug: PublicAccessAuthenticator:validate() Getting account properties...
2020-11-12T03:47:03.091Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: azure-webjobs-secrets, blob: 
2020-11-12T03:47:03.091Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container azure-webjobs-secrets
2020-11-12T03:47:03.091Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2020-11-12T03:47:03.092Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:c1d433d5-ee1d-4cdf-b58e-ef7b2191371d\nx-ms-date:Thu, 12 Nov 2020 03:47:03 GMT\nx-ms-version:2019-02-02\n/devstoreaccount1/devstoreaccount1/azure-webjobs-secrets\nrestype:container"
2020-11-12T03:47:03.092Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:oZ1hHaOudmsZBFjCv0vJRLBDsdfarjkacM3W4g3U/+M=
2020-11-12T03:47:03.092Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2020-11-12T03:47:03.092Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 verbose: DeserializerMiddleware: Start deserializing...
2020-11-12T03:47:03.092Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 info: HandlerMiddleware: DeserializedParameters={"options":{"metadata":{},"requestId":"c1d433d5-ee1d-4cdf-b58e-ef7b2191371d"},"restype":"container","version":"2019-02-02"}
2020-11-12T03:47:03.092Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2020-11-12T03:47:03.092Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 error: **ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified container already exists**.  ErrorHTTPStatusCode=409 ErrorHTTPStatusMessage=The specified container already exists. ErrorHTTPHeaders={"x-ms-error-code":"ContainerAlreadyExists","x-ms-request-id":"80d001a1-6c8c-4730-b71b-7d46ad8321e3"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:80d001a1-6c8c-4730-b71b-7d46ad8321e3\nTime:2020-11-12T03:47:03.092Z</Message>\n</Error>" ErrorStack="StorageError: The specified container already exists.\n    at Function.getContainerAlreadyExists (C:\\Users\\alexk\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\errors\\StorageErrorFactory.js:23:16)\n    at LokiBlobMetadataStore.createContainer (C:\\Users\\alexk\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\persistence\\LokiBlobMetadataStore.js:292:49)\n    at ContainerHandler.create (C:\\Users\\alexk\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\handlers\\ContainerHandler.js:35:34)\n    at C:\\Users\\alexk\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\generated\\middleware\\HandlerMiddlewareFactory.js:58:18\n    at C:\\Users\\alexk\\AppData\\Roaming\\npm\\node_modules\\azurite\\dist\\src\\blob\\generated\\ExpressMiddlewareFactory.js:77:63\n    at Layer.handle [as handle_request] (C:\\Users\\alexk\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\alexk\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\Users\\alexk\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\Users\\alexk\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\alexk\\AppData\\Roaming\\npm\\node_modules\\azurite\\node_modules\\express\\lib\\router\\index.js:275:10)"
2020-11-12T03:47:03.092Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 error: ErrorMiddleware: Set HTTP code: 409
2020-11-12T03:47:03.092Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 error: ErrorMiddleware: Set HTTP status message: The specified container already exists.
2020-11-12T03:47:03.093Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=ContainerAlreadyExists
2020-11-12T03:47:03.093Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=80d001a1-6c8c-4730-b71b-7d46ad8321e3
2020-11-12T03:47:03.093Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 error: ErrorMiddleware: Set content type: application/xml
2020-11-12T03:47:03.093Z 80d001a1-6c8c-4730-b71b-7d46ad8321e3 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:80d001a1-6c8c-4730-b71b-7d46ad8321e3\nTime:2020-11-12T03:47:03.092Z</Message>\n</Error>"
`

**Comment by XiaoningLiu** [comment]
Durable functions requires Table, Table is under alpha ealry access versions.

Please get azurite from table branch (latest updates and fixes). Or from alpha tagged packages. For example, `npm install -g azurite@alpha`.

See #613, there is an known issue with durable function dpedending .net sdk. I have a PR for that, after PR merged, please try with codes from table branch.

**Comment by XiaoningLiu** [comment]
BTW, posted blob error is expected if trying to create an container on existing container.

**Comment by command0r** [comment]
Thanks for your reply, @XiaoningLiu 
Following your advice, I installed table alpha and the error message changed. Right now, the function doesn't even start displaying the following error: `"The listener for function 'Functions.<...>' was unable to start. Microsoft.WindowsAzure.Storage: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature."` 
Looked at the 'debug.log'. The message I see there is different. It's still complaining about the existing container: `error: ErrorMiddleware: Set HTTP status message: The specified container already exists.`

I'll use the remote storage for a while, no issues there... Any info on the ETA for GA (that includes Azurite Tables)?

**Comment by XiaoningLiu** [comment]
@command0r Can you share your reproduce steps as mentioned in #613? I'd like to give it a try. Crerate container over existing container is expected to fail. Believe there are other things blocking you.

**Comment by command0r** [comment]
@XiaoningLiu, I have committed a 'template project' to a public GitHub repo [here](https://github.com/command0r/DurableFunction.git), just to make things easier in terms of repro steps. As mentioned, it's a Python-based Azure Durable Function and the logic in there is all that the Azure CLI creates by default (i.e. nothing extra, just for the clarity of the experiment). The connection strings are already set to a local storage emulator. If you start it with 'azurite -s -l L:\_Azurite -d L:\_Azurite\debug.log' (or wherever you want to store your debug logs), you're all set to run a function: 'func start'. The errors will be displayed immediately in the VS Code terminal. Also, Azurite debug logs is where I get that info extracted from.

**Comment by XiaoningLiu** [comment]
Thanks @command0r! I'll give https://github.com/command0r/DurableFunction.git a try.

**Comment by command0r** [comment]
@XiaoningLiu, any news on the issue resolution?

**Comment by edwin-huber** [comment]
Hi @command0r we now support Azure Durable Functions, is this issue now resolved for you?
thanks.

**Comment by command0r** [comment]
Hi @edwin-huber, awesome news. Yes, it does resolve the issue, thanks.
