### ISSUE TITLE
Batch [Durable Functions] Single entity Table query returns HTTP 400

### ISSUE THREAD

**Issue by cgillum** [Azure/Azurite#620]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
Latest from `table` branch (https://github.com/Azure/Azurite/commit/e99fa46807a8bc8449be77d3dc1e55a64c32a07c)

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Local npm build, see above.

### What's the Node.js version?
v10.14.1

### What problem was encountered?
I'm getting a 400 Bad Request when trying to fetch an entity from table storage. Here is the C# code that uses the Azure Storage SDK:

```cs
await this.InstancesTable.ExecuteAsync(TableOperation.Retrieve<OrchestrationInstanceStatus>(
    instanceId,
    "",
    columnsToRetrieve));
```

Here is the HTTP request to table storage and the response from Azurite:

> 127.0.0.1 - - [12/Nov/2020:19:18:13 +0000] "GET /devstoreaccount1/SampleHubVSInstances(PartitionKey='c29160b0c0674fc4b08e2b52b2124620',RowKey='')?$select=ExecutionId%2CName%2CVersion%2COutput%2CCustomStatus%2CCreatedTime%2CLastUpdatedTime%2CRuntimeStatus%2CScheduledStartTime%2CPartitionKey%2CRowKey%2CTimestamp%2CETag HTTP/1.1" 400 -

And here is the detailed log information from azurite:

```
2020-11-12T19:24:38.837Z 65c9b35d-7c49-42ea-97e7-6780bdfef34a info: TableStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1/SampleHubVSInstances(PartitionKey='8597d25da4a6419f9ae9646870cd914c',RowKey='')?$select=ExecutionId%2CName%2CVersion%2COutput%2CCustomStatus%2CCreatedTime%2CLastUpdatedTime%2CRuntimeStatus%2CScheduledStartTime%2CPartitionKey%2CRowKey%2CTimestamp%2CETag RequestHeaders:{"host":"127.0.0.1:10002","accept-charset":"UTF-8","maxdataserviceversion":"3.0;NetFx","accept":"application/json; odata=minimalmetadata","dataserviceversion":"3.0;","x-ms-client-request-id":"de37098c-64dd-4585-90f0-fc41ee16d9d1","user-agent":"Azure-Storage/9.3.1 (.NET Core)","x-ms-version":"2018-03-28","x-ms-date":"Thu, 12 Nov 2020 19:24:38 GMT","authorization":"SharedKey devstoreaccount1:ejVYKm1jVKl4XU1nzIbfHB/OQlskVTdprYbSdwhmBrk="} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2020-11-12T19:24:38.837Z 65c9b35d-7c49-42ea-97e7-6780bdfef34a info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=SampleHubVSInstances
2020-11-12T19:24:38.837Z 65c9b35d-7c49-42ea-97e7-6780bdfef34a verbose: DispatchMiddleware: Dispatching request...
2020-11-12T19:24:38.837Z 65c9b35d-7c49-42ea-97e7-6780bdfef34a error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2020-11-12T19:24:38.837Z 65c9b35d-7c49-42ea-97e7-6780bdfef34a error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2020-11-12T19:24:38.837Z 65c9b35d-7c49-42ea-97e7-6780bdfef34a error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at Object.dispatchMiddleware [as default] (C:\\GitHub\\azurite\\dist\\src\\table\\generated\\middleware\\dispatch.middleware.js:41:30)\n    at C:\\GitHub\\azurite\\dist\\src\\table\\generated\\ExpressMiddlewareFactory.js:49:42\n    at Layer.handle [as handle_request] (C:\\GitHub\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\GitHub\\azurite\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\GitHub\\azurite\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\GitHub\\azurite\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\GitHub\\azurite\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at tableStorageContextMiddleware (C:\\GitHub\\azurite\\dist\\src\\table\\middleware\\tableStorageContext.middleware.js:111:5)\n    at C:\\GitHub\\azurite\\dist\\src\\table\\middleware\\tableStorageContext.middleware.js:13:16\n    at Layer.handle [as handle_request] (C:\\GitHub\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)"
2020-11-12T19:24:38.838Z 65c9b35d-7c49-42ea-97e7-6780bdfef34a error: ErrorMiddleware: Set HTTP code: 400
2020-11-12T19:24:38.838Z 65c9b35d-7c49-42ea-97e7-6780bdfef34a error: ErrorMiddleware: Set HTTP body: undefined
```

### Steps to reproduce the issue?
(same as #613 for starting up the Functions host, but one new step to start the orchestration)
1. Install the [Azure Functions Core Tools](https://github.com/Azure/azure-functions-core-tools#installing) (v3)
1. Clone and build the following sample app: https://github.com/Azure/azure-functions-durable-extension/tree/dev/samples/precompiled
1. `cd` into the `samples\precompiled\bin\Debug\netcoreapp3.1` directory
1. Run `func host start`
1. Send an HTTP POST request to http://localhost:7071/orchestrators/E1_HelloSequence

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
Hi @cgillum, thanks for bringing this. Fix included in #622

After the fix, I think the function E1_HelloSequence should executed succesfully. But features requring Batch doesn't work because Batch support is still under development.

![image](https://user-images.githubusercontent.com/6889160/99058475-39ee1500-25d8-11eb-875f-41eebd883a50.png)

**Comment by cgillum** [comment]
@XiaoningLiu great! Yes, support for batch updates is an important but expected blocker for us. I look forward to the next release that has support for this.

**Comment by XiaoningLiu** [comment]
Close this, refer to #493 for Batch progress
