### ISSUE TITLE
Azure Function with Event Hub Trigger doesn't work using Azurite 

### ISSUE THREAD

**Issue by NTTLuke** [Azure/Azurite#645]
### Which service(blob, file, queue, table) does this issue concern?
Blob storage

### Which version of the Azurite was used?
3.9.0

### SDK Versions (EventHub-Storage-Functions)
 
    <PackageReference Include="Microsoft.Azure.EventHubs.Processor" Version="4.3.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.1.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What problem was encountered?
Running an Azure Function with Event Hub Trigger as docker container using Azurite as docker container I receive this error and the function is not able to receive events sent to the Event Hub

-----
fail: Host.Startup[0]
The listener for function 'process-data-events' was unable to start.
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'process-data-events' was unable to start.
---> Microsoft.Azure.EventHubs.Processor.EventProcessorConfigurationException: Encountered error while fetching the list of EventHub PartitionIds
---> Microsoft.Azure.EventHubs.EventHubsException: ExpiredToken: The token is expired. Expiration time: '2020-11-26 01:26:01Z'
at Microsoft.Azure.EventHubs.Amqp.Management.AmqpServiceClient.GetRuntimeInformationAsync()
at Microsoft.Azure.EventHubs.EventHubClient.GetRuntimeInformationAsync()
at Microsoft.Azure.EventHubs.Processor.PartitionManager.GetPartitionIdsAsync()
--- End of inner exception stack trace ---
at Microsoft.Azure.EventHubs.Processor.PartitionManager.GetPartitionIdsAsync()
at Microsoft.Azure.EventHubs.Processor.PartitionManager.GetPartitionIdsAsync()
at Microsoft.Azure.EventHubs.Processor.PartitionManager.InitializeStoresAsync()
at Microsoft.Azure.EventHubs.Processor.PartitionManager.StartAsync()
at Microsoft.Azure.EventHubs.Processor.EventProcessorHost.RegisterEventProcessorFactoryAsync(IEventProcessorFactory factory, EventProcessorOptions processorOptions)
at Microsoft.Azure.WebJobs.EventHubs.EventHubListener.StartAsync(CancellationToken cancellationToken)
at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(CancellationToken cancellationToken, Boolean allowRetry) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 69
--- End of inner exception stack trace ---

info: Host.General[316]

Host lock lease acquired by instance ID '0000000000000000000000005CE8C91F'.
[00:26:03 INF] Host lock lease acquired by instance ID '0000000000000000000000005CE8C91F'.
info: Host.Startup[0]

### Docker Compose 
Removed unnecessary info for dm-af

<img width="669" alt="docker-compose" src="https://user-images.githubusercontent.com/1864745/100475407-53688400-30e3-11eb-96c2-bf08abefecfc.PNG">

### Azurite Container Logs 

<img width="528" alt="Azurite Log" src="https://user-images.githubusercontent.com/1864745/100476738-ad1e7d80-30e6-11eb-9e70-8f8d5116f95f.PNG">

### Steps to reproduce the issue?

- Run Azurite on docker container 
- Create an Azure Function with Event Hub Trigger 
- Run the Azure Function on docker and setting Azurite endpoint for AzureWebJobsStorage (see docker compose)

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
Hi, Azurite Table is required for Azure Function. Table is under alpha early access. Try following ways to get Azurite Table support.

### Get from Azurite GitHub table branch (Recommended, always with latest fixes and updates)
Download & install Node.js https://nodejs.org/dist/v14.15.0/node-v14.15.0-x64.msi
git clone https://github.com/azure/azurite
cd azurite
git checkout table
npm ci
npm run build
npm install -g
azurite

### Npm 

https://www.npmjs.com/package/azurite/v/3.9.0-table-alpha.1

·       npm install -g azurite@alpha

### Docker

·       docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite:alpha

**Comment by NTTLuke** [comment]
Thank you @XiaoningLiu .
I will test in this way . 

In the meantime I changed my AzureWebJobsStorage connection pointing to an  Azure Storage Account on my Azure subscription created for testing.

A strange stuff happens 

### Scenario 
 - Azure Function with Event Hub trigger on docker container 
 - Azure Storage Account on my Azure subscription

### Behaviour 

- Tue : it worked fine
- Wed : it worked fine 
- Today : no way to work with it . Below the error message

`
Microsoft.Azure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
`

I want to point out that :

- The connection string to Azure Storage is the same used yesterday. 
- On VS2019 same connection works fine.

So my questions are :
- Why this issue today  ? 
- Is there something I'm missing ? 


thanks

**Comment by XiaoningLiu** [comment]
Hi @NTTLuke Can you share Azurite debug.log and we will have a look.

**Comment by NTTLuke** [comment]
Hi @XiaoningLiu 

thanks a lot since I'm becoming crazy with this random behavior

This is the Connection I have always used (it worked and It works on VS2019) 

`
AzureWebJobsStorage: DefaultEndpointsProtocol=https;AccountName={TheAccountName};AccountKey={TheAccountKey};BlobEndpoint=https://{Name}.blob.core.windows.net/;TableEndpoint=https://{Name}.table.core.windows.net/;QueueEndpoint=https://{Name}.queue.core.windows.net/;FileEndpoint=https://{Name}.file.core.windows.net/
`
Add the "buy me a coffee button"  :)


Here the log

---
info: Host.Triggers.Warmup[0]

Initializing Warmup Extension.

[23:41:23 INF] Initializing Warmup Extension.

info: Host.Startup[503]

Initializing Host. OperationId: 'fd19d059-9afb-4740-8082-16d3608b0dc4'.

[23:41:23 INF] Initializing Host. OperationId: 'fd19d059-9afb-4740-8082-16d3608b0dc4'.

info: Host.Startup[504]

Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=fd19d059-9afb-4740-8082-16d3608b0dc4

[23:41:23 INF] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=fd19d059-9afb-4740-8082-16d3608b0dc4

info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]

ApplicationInsightsLoggerOptions

{

"SamplingSettings": {

"EvaluationInterval": "00:00:15",

"InitialSamplingPercentage": 100.0,

"MaxSamplingPercentage": 100.0,

"MaxTelemetryItemsPerSecond": 20.0,

"MinSamplingPercentage": 0.1,

"MovingAverageRatio": 0.25,

"SamplingPercentageDecreaseTimeout": "00:02:00",

"SamplingPercentageIncreaseTimeout": "00:15:00"

},

"SamplingExcludedTypes": null,

"SamplingIncludedTypes": null,

"SnapshotConfiguration": null,

"EnablePerformanceCountersCollection": true,

"HttpAutoCollectionOptions": {

"EnableHttpTriggerExtendedInfoCollection": true,

"EnableW3CDistributedTracing": true,

"EnableResponseHeaderInjection": true

},

"LiveMetricsInitializationDelay": "00:00:15",

"EnableLiveMetrics": true,

"EnableDependencyTracking": true,

"DependencyTrackingOptions": null

}

[23:41:23 INF] ApplicationInsightsLoggerOptions

{

"SamplingSettings": {

"EvaluationInterval": "00:00:15",

"InitialSamplingPercentage": 100.0,

"MaxSamplingPercentage": 100.0,

"MaxTelemetryItemsPerSecond": 20.0,

"MinSamplingPercentage": 0.1,

"MovingAverageRatio": 0.25,

"SamplingPercentageDecreaseTimeout": "00:02:00",

"SamplingPercentageIncreaseTimeout": "00:15:00"

},

"SamplingExcludedTypes": null,

"SamplingIncludedTypes": null,

"SnapshotConfiguration": null,

"EnablePerformanceCountersCollection": true,

"HttpAutoCollectionOptions": {

"EnableHttpTriggerExtendedInfoCollection": true,

"EnableW3CDistributedTracing": true,

"EnableResponseHeaderInjection": true

},

"LiveMetricsInitializationDelay": "00:00:15",

"EnableLiveMetrics": true,

"EnableDependencyTracking": true,

"DependencyTrackingOptions": null

}

info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]

LoggerFilterOptions

{

"MinLevel": "None",

"Rules": [

{

"ProviderName": null,

"CategoryName": null,

"LogLevel": null,

"Filter": "<AddFilter>b__0"

},

{

"ProviderName": "Serilog.Extensions.Logging.SerilogLoggerProvider",

"CategoryName": null,

"LogLevel": "Trace",

"Filter": null

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",

"CategoryName": null,

"LogLevel": "None",

"Filter": null

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",

"CategoryName": null,

"LogLevel": null,

"Filter": "<AddFilter>b__0"

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",

"CategoryName": null,

"LogLevel": "Trace",

"Filter": null

}



]

}

[23:41:23 INF] LoggerFilterOptions

{

"MinLevel": "None",

"Rules": [

{

"ProviderName": null,

"CategoryName": null,

"LogLevel": null,

"Filter": "<AddFilter>b__0"

},

{

"ProviderName": "Serilog.Extensions.Logging.SerilogLoggerProvider",

"CategoryName": null,

"LogLevel": "Trace",

"Filter": null

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",

"CategoryName": null,

"LogLevel": "None",

"Filter": null

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",

"CategoryName": null,

"LogLevel": null,

"Filter": "<AddFilter>b__0"

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",

"CategoryName": null,

"LogLevel": "Trace",

"Filter": null

}

]

}

info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]

LoggerFilterOptions

{

"MinLevel": "None",

"Rules": [

{

"ProviderName": null,

"CategoryName": null,

"LogLevel": null,

"Filter": "<AddFilter>b__0"

},

{

"ProviderName": "Serilog.Extensions.Logging.SerilogLoggerProvider",

"CategoryName": null,

"LogLevel": "Trace",

"Filter": null

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",

"CategoryName": null,

"LogLevel": "None",

"Filter": null

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",

"CategoryName": null,

"LogLevel": null,

"Filter": "<AddFilter>b__0"

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",

"CategoryName": null,

"LogLevel": "Trace",

"Filter": null

}



]

}

[23:41:23 INF] LoggerFilterOptions

{

"MinLevel": "None",

"Rules": [

{

"ProviderName": null,

"CategoryName": null,

"LogLevel": null,

"Filter": "<AddFilter>b__0"

},

{

"ProviderName": "Serilog.Extensions.Logging.SerilogLoggerProvider",

"CategoryName": null,

"LogLevel": "Trace",

"Filter": null

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",

"CategoryName": null,

"LogLevel": "None",

"Filter": null

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",

"CategoryName": null,

"LogLevel": null,

"Filter": "<AddFilter>b__0"

},

{

"ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",

"CategoryName": null,

"LogLevel": "Trace",

"Filter": null

}

]

}

info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]

FunctionResultAggregatorOptions

{

"BatchSize": 1000,

"FlushTimeout": "00:00:30",

"IsEnabled": true

}

[23:41:23 INF] FunctionResultAggregatorOptions

{

"BatchSize": 1000,

"FlushTimeout": "00:00:30",

"IsEnabled": true

}

info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]

SingletonOptions

{

"LockPeriod": "00:00:15",

"ListenerLockPeriod": "00:01:00",

"LockAcquisitionTimeout": "10675199.02:48:05.4775807",

"LockAcquisitionPollingInterval": "00:00:05",

"ListenerLockRecoveryPollingInterval": "00:01:00"

}

[23:41:23 INF] SingletonOptions

{

"LockPeriod": "00:00:15",

"ListenerLockPeriod": "00:01:00",

"LockAcquisitionTimeout": "10675199.02:48:05.4775807",

"LockAcquisitionPollingInterval": "00:00:05",

"ListenerLockRecoveryPollingInterval": "00:01:00"

}

info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]

QueuesOptions

{

"BatchSize": 16,

"NewBatchThreshold": 128,

"MaxPollingInterval": "00:01:00",

"MaxDequeueCount": 5,

"VisibilityTimeout": "00:00:00"

}

[23:41:23 INF] QueuesOptions

{

"BatchSize": 16,

"NewBatchThreshold": 128,

"MaxPollingInterval": "00:01:00",

"MaxDequeueCount": 5,

"VisibilityTimeout": "00:00:00"

}

info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]

BlobsOptions

{

"CentralizedPoisonQueue": false

}

[23:41:23 INF] BlobsOptions

{

"CentralizedPoisonQueue": false

}

info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]

HttpOptions

{

"DynamicThrottlesEnabled": false,

"MaxConcurrentRequests": -1,

"MaxOutstandingRequests": -1,

"RoutePrefix": "api"

}

[23:41:23 INF] HttpOptions

{

"DynamicThrottlesEnabled": false,

"MaxConcurrentRequests": -1,

"MaxOutstandingRequests": -1,

"RoutePrefix": "api"

}

info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]

EventHubOptions

{

"BatchCheckpointFrequency": 1,

"EventProcessorOptions": {

"EnableReceiverRuntimeMetric": false,

"InvokeProcessorAfterReceiveTimeout": false,

"MaxBatchSize": 10,

"PrefetchCount": 300,

"ReceiveTimeout": "00:01:00"

},

"PartitionManagerOptions": {

"LeaseDuration": "00:00:30",

"RenewInterval": "00:00:10"



}

}

[23:41:23 INF] EventHubOptions

{

"BatchCheckpointFrequency": 1,

"EventProcessorOptions": {

"EnableReceiverRuntimeMetric": false,

"InvokeProcessorAfterReceiveTimeout": false,

"MaxBatchSize": 10,

"PrefetchCount": 300,

"ReceiveTimeout": "00:01:00"

},

"PartitionManagerOptions": {

"LeaseDuration": "00:00:30",

"RenewInterval": "00:00:10"

}

}

info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]

Starting JobHost

[23:41:23 INF] Starting JobHost

info: Host.Startup[401]

Starting Host (HostId=64e02499cc94-2137340777, InstanceId=23a54e20-7735-4e1c-89c6-6aa4e073706d, Version=3.0.15149.0, ProcessId=1, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))

[23:41:23 INF] Starting Host (HostId=64e02499cc94-2137340777, InstanceId=23a54e20-7735-4e1c-89c6-6aa4e073706d, Version=3.0.15149.0, ProcessId=1, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))

info: Host.Startup[314]

Loading functions metadata

[23:41:23 INF] Loading functions metadata

info: Host.Startup[315]

5 functions loaded

[23:41:23 INF] 5 functions loaded

info: Host.Startup[0]

Generating 5 job function(s)

[23:41:23 INF] Generating 5 job function(s)

info: Host.Startup[0]

Found the following functions:

Ac.DataManager.AzureFunctions.HttpTrigger.ClickFunctions.Run

Ac.DataManager.AzureFunctions.HttpTrigger.UpdateFunctions.Run

Ac.DataManager.AzureFunctions.EventHubTrigger.ProcessaiEvents.Run

Ac.DataManager.AzureFunctions.QueueTrigger.SeedDbWithTestData.Run

Ac.DataManager.AzureFunctions.HttpTrigger.TestSetup.Run


[23:41:23 INF] Found the following functions:

Ac.DataManager.AzureFunctions.HttpTrigger.ClickFunctions.Run

Ac.DataManager.AzureFunctions.HttpTrigger.updateFunctions.Run

Ac.DataManager.AzureFunctions.EventHubTrigger.ProcessaiEvents.Run

Ac.DataManager.AzureFunctions.QueueTrigger.SeedDbWithTestData.Run

Ac.DataManager.AzureFunctions.HttpTrigger.TestSetup.Run


info: Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostHttpRoutesManager[0]

Initializing function HTTP routes

Mapped function route 'api/click/{oid}' [get,post] to 'click'

Mapped function route 'api/update/{oid}' [get,post] to 'update'

Mapped function route 'api/test-setup' [get,post] to 'test-setup'


[23:41:23 INF] Initializing function HTTP routes

Mapped function route 'api/click/{oid}' [get,post] to 'click'

Mapped function route 'api/update/{oid}' [get,post] to 'update'

Mapped function route 'api/test-setup' [get,post] to 'test-setup'


info: Host.Startup[412]

Host initialized (131ms)

[23:41:23 INF] Host initialized (131ms)

fail: Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostExceptionHandler[0]

An unhandled exception has occurred. Host is shutting down.

Microsoft.Azure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)

at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.ExecuteAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\Listeners\QueueListener.cs:line 193

at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.RunAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Timers\TaskSeriesTimer.cs:line 147

Request Information

RequestID:f83f0da4-2003-00f6-5178-cc0040000000

RequestDate:Thu, 03 Dec 2020 23:41:23 GMT

StatusMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

ErrorCode:AuthenticationFailed


[23:41:23 ERR] An unhandled exception has occurred. Host is shutting down.

Microsoft.Azure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)

at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.ExecuteAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\Listeners\QueueListener.cs:line 193

at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.RunAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Timers\TaskSeriesTimer.cs:line 147

Request Information

RequestID:f83f0da4-2003-00f6-5178-cc0040000000

RequestDate:Thu, 03 Dec 2020 23:41:23 GMT

StatusMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

ErrorCode:AuthenticationFailed

fail: Host.Startup[0]

The listener for function 'process-ai-events' was unable to start.

Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'process-ai-events' was unable to start.

---> Microsoft.Azure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)

at Microsoft.Azure.EventHubs.Processor.PartitionManager.InitializeStoresAsync()

at Microsoft.Azure.EventHubs.Processor.PartitionManager.StartAsync()

at Microsoft.Azure.EventHubs.Processor.EventProcessorHost.RegisterEventProcessorFactoryAsync(IEventProcessorFactory factory, EventProcessorOptions processorOptions)

at Microsoft.Azure.WebJobs.EventHubs.EventHubListener.StartAsync(CancellationToken cancellationToken)

at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(CancellationToken cancellationToken, Boolean allowRetry) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 69

Request Information

RequestID:d2cac3c9-c01e-00d5-0578-cc6f8b000000

RequestDate:Thu, 03 Dec 2020 23:41:23 GMT

StatusMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

ErrorCode:AuthenticationFailed


--- End of inner exception stack trace ---

[23:41:23 ERR] The listener for function 'process-ai-events' was unable to start.

Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'process-ai-events' was unable to start.

---> Microsoft.Azure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)

at Microsoft.Azure.EventHubs.Processor.PartitionManager.InitializeStoresAsync()

at Microsoft.Azure.EventHubs.Processor.PartitionManager.StartAsync()

at Microsoft.Azure.EventHubs.Processor.EventProcessorHost.RegisterEventProcessorFactoryAsync(IEventProcessorFactory factory, EventProcessorOptions processorOptions)

at Microsoft.Azure.WebJobs.EventHubs.EventHubListener.StartAsync(CancellationToken cancellationToken)

at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(CancellationToken cancellationToken, Boolean allowRetry) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 69

Request Information

RequestID:d2cac3c9-c01e-00d5-0578-cc6f8b000000

RequestDate:Thu, 03 Dec 2020 23:41:23 GMT

StatusMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

ErrorCode:AuthenticationFailed


--- End of inner exception stack trace ---

info: Host.Startup[413]

Host started (400ms)

[23:41:23 INF] Host started (400ms)

info: Host.Startup[0]

Job host started

[23:41:23 INF] Job host started

Hosting environment: Production

Content root path: /home/site/wwwroot

Now listening on: http://[::]:80

Application started. Press Ctrl+C to shut down.

info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]

Stopping JobHost

[23:41:23 INF] Stopping JobHost

info: Host.Startup[0]

Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'click'

[23:41:23 INF] Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'click'

info: Host.Startup[0]

Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'click'

[23:41:23 INF] Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'click'

info: Host.Startup[0]

Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'update'

[23:41:23 INF] Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'update'

info: Host.Startup[0]

Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'update'

[23:41:23 INF] Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'update'

info: Host.Startup[0]

Stopping the listener 'Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener' for function 'seed-db-with-test-data'

[23:41:23 INF] Stopping the listener 'Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener' for function 'seed-db-with-test-data'

info: Host.Startup[0]

Stopped the listener 'Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener' for function 'seed-db-with-test-data'

[23:41:23 INF] Stopped the listener 'Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener' for function 'seed-db-with-test-data'

info: Host.Startup[0]

Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'test-setup'

[23:41:23 INF] Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'test-setup'

info: Host.Startup[0]

Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'test-setup'

[23:41:23 INF] Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'test-setup'

info: Host.Startup[0]

Job host stopped

[23:41:23 INF] Job host stopped
---

**Comment by NTTLuke** [comment]
Hi @XiaoningLiu 
my previous post (the second one) was not related Azurite but the Azure Storage on cloud

I think It's better to open this new issue in the properly repo.
I'm going to close the issue 

thanks for your support
