### ISSUE TITLE
Internal server error when creating directory in DataLake storage

### ISSUE THREAD

**Issue by henrikhorluck** [Azure/Azurite#655]
Getting constant crashes when trying to test a service that uses DataLake storage locally, would love any help! (Btw running macOS v. 11.0.1)

### Which service(blob, file, queue, table) does this issue concern?

blob (Azure Data Lake)

### Which version of the Azurite was used?

3.9.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

npm

### What's the Node.js version?

`15.3.0`

### What problem was encountered?

500 Internal server error. See 

```
2020-12-07T21:31:42.291Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=https://127.0.0.1/devstoreaccount1/analyze-logs/Abyssal%20whip/2020/12/7/1?resource=directory RequestHeaders:{"host":"127.0.0.1:10000","x-ms-version":"2020-02-10","if-none-match":"*","x-ms-client-request-id":"1134d905-07ce-4e2a-8da1-c0dfdfccc68b","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Storage.Files.DataLake/12.5.0 (.NET 5.0.0; Darwin 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64)","x-ms-date":"Mon, 07 Dec 2020 21:31:42 GMT","authorization":"SharedKey devstoreaccount1:4wDx+RhVMUoBZjZhvDPnjAFtcpPwaYtk3gZ7rdh0ulA=","content-length":"0"} ClientIP=127.0.0.1 Protocol=https HTTPVersion=1.1
2020-12-07T21:31:42.291Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=analyze-logs Blob=Abyssal whip/2020/12/7/1
2020-12-07T21:31:42.291Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b verbose: DispatchMiddleware: Dispatching request...
2020-12-07T21:31:42.293Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b info: DispatchMiddleware: Operation=Directory_Create
2020-12-07T21:31:42.293Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2020-12-07T21:31:42.293Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b info: PublicAccessAuthenticator:validate() Start validation against public access.
2020-12-07T21:31:42.293Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b debug: PublicAccessAuthenticator:validate() Getting account properties...
2020-12-07T21:31:42.293Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: analyze-logs, blob: Abyssal whip/2020/12/7/1
2020-12-07T21:31:42.293Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container analyze-logs
2020-12-07T21:31:42.293Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2020-12-07T21:31:42.293Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n\n\n\n\n\n\n*\n\n\nx-ms-client-request-id:1134d905-07ce-4e2a-8da1-c0dfdfccc68b\nx-ms-date:Mon, 07 Dec 2020 21:31:42 GMT\nx-ms-return-client-request-id:true\nx-ms-version:2020-02-10\n/devstoreaccount1/devstoreaccount1/analyze-logs/Abyssal%20whip/2020/12/7/1\nresource:directory"
2020-12-07T21:31:42.294Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:4wDx+RhVMUoBZjZhvDPnjAFtcpPwaYtk3gZ7rdh0ulA=
2020-12-07T21:31:42.294Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2020-12-07T21:31:42.294Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b verbose: DeserializerMiddleware: Start deserializing...
2020-12-07T21:31:42.294Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b info: HandlerMiddleware: DeserializedParameters={"options":{"requestId":"1134d905-07ce-4e2a-8da1-c0dfdfccc68b","directoryHttpHeaders":{},"leaseAccessConditions":{},"modifiedAccessConditions":{"ifNoneMatch":"*"}},"resource":"directory","version":"2020-02-10"}
2020-12-07T21:31:42.295Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b error: ErrorMiddleware: Received an error, fill error information to HTTP response
2020-12-07T21:31:42.295Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b error: ErrorMiddleware: ErrorName=TypeError ErrorMessage=Cannot read property 'apply' of undefined ErrorStack="TypeError: Cannot read property 'apply' of undefined\n    at /usr/local/lib/node_modules/azurite/dist/src/blob/generated/middleware/HandlerMiddlewareFactory.js:58:18\n    at /usr/local/lib/node_modules/azurite/dist/src/blob/generated/ExpressMiddlewareFactory.js:77:63\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:317:13)\n    at /usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/local/lib/node_modules/azurite/node_modules/express/lib/router/index.js:275:10)\n    at processTicksAndRejections (node:internal/process/task_queues:93:5)"
2020-12-07T21:31:42.295Z a30ce04e-88e1-41e4-a1b0-9ec7e4ed9f3b error: ErrorMiddleware: Set HTTP code: 500
```

### Steps to reproduce the issue?

Running this code:
```cs
var fs = _client.GetFileSystemClient("analyze-logs");
var directoryClient = fs.GetDirectoryClient("Abyssal Whip/2020/12/7/1");
await fs.CreateIfNotExistsAsync();
```

### Have you found a mitigation/solution?

No :(

**Comment by blueww** [comment]
@henrikhorluck 

Thanks for raising the issue!

We still no support Datalake in Azurite.
And we already has another issue to track the feature request. https://github.com/Azure/Azurite/issues/553

**Comment by henrikhorluck** [comment]
Duplicate of #553
