### ISSUE TITLE
Cannot connect to Azurite in docker image using HTTPS

### ISSUE THREAD

**Issue by qetza** [Azure/Azurite#668]
### Which service(blob, file, queue, table) does this issue concern?
blob, queue

### Which version of the Azurite was used?
docker/latest

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What problem was encountered?
I'm trying to have a docker image of Azurite configured to use HTTPS and basic OAuth and connect to it using Azure Storage Explorer.
I've created a certificate using mkcert and started the image with the command:
```
docker run --name azurite -p 10000:10000 -p 10001:10001 -v d:\.azurite:/data mcr.microsoft.com/azure-storage/azurite azurite --cert //data/127.0.0.1.pem --key //data/127.0.0.1-key.pem --oauth basic
```

The service is running but when i try to load containers or queues using storage explorer i get the following error:
```
Unable to retrieve child resources.

Details:
{
  "name": "FetchError",
  "message": "request to https://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: Client network socket disconnected before secure TLS connection was established",
  "__zone_symbol__error": {
    "originalStack": "Error: request to https://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: Client network socket disconnected before secure TLS connection was established\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
    "zoneAwareStack": "Error: request to https://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: Client network socket disconnected before secure TLS connection was established\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)"
  },
  "stack": "FetchError: request to https://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: Client network socket disconnected before secure TLS connection was established\n    at ClientRequest.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "originalStack": "Error: request to https://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: Client network socket disconnected before secure TLS connection was established\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "zoneAwareStack": "Error: request to https://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: Client network socket disconnected before secure TLS connection was established\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "__zone_symbol__stack": "FetchError: request to https://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: Client network socket disconnected before secure TLS connection was established\n    at ClientRequest.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "__zone_symbol__name": "FetchError",
  "__zone_symbol__message": "request to https://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: Client network socket disconnected before secure TLS connection was established",
  "__zone_symbol__originalStack": "Error: request to https://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: Client network socket disconnected before secure TLS connection was established\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "__zone_symbol__zoneAwareStack": "Error: request to https://127.0.0.1:10000/devstoreaccount1/?include=metadata&comp=list failed, reason: Client network socket disconnected before secure TLS connection was established\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at Function.ExceptionSerializer.deserialize (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-exception-serializer\\dist\\ExceptionSerializer.js:49:28)\n    at NodeProcessProviderProxy._handleResponse (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:344:74)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:197:55)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)\n    at Object.__awaiter (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:111:16)\n    at NodeProcessProviderProxy._handleMessage (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:175:24)\n    at NodeProcessProviderProxy.<anonymous> (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\main\\NodeProcessProviderProxy.js:141:62)\n    at step (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:141:27)\n    at Object.next (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:122:57)\n    at C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\tslib\\tslib.js:115:75\n    at new ZoneAwarePromise (C:\\Users\\rouchon\\AppData\\Local\\Programs\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:551:29)",
  "type": "system",
  "errno": "ECONNRESET",
  "code": "ECONNRESET"
}
```

I'm working on windows 10 and using Docker Desktop with WSL2.

### Steps to reproduce the issue?
- generate certificate with mkcert: `mkcert 127.0.0.1`
- copy certificate and key to azurite data folder (will be mapped in docker image)
- run docker image: `docker run --name azurite -p 10000:10000 -p 10001:10001 -v d:\.azurite:/data mcr.microsoft.com/azure-storage/azurite azurite --cert //data/127.0.0.1.pem --key //data/127.0.0.1-key.pem --oauth basic`
- import mkcert rootca in storage explorer
- connect storage explorer to azurite
- open Blob Containers in storage explorer

### Have you found a mitigation/solution?
Running Azurite locally through npm (`azurite --oauth basic --cert 127.0.0.1.pem --key 127.0.0.1-key.pem`) works and i can connect to it using storage explorer through HTTPS.

Issue seems to be when using docker.

**Comment by henrikhorluck** [comment]
Can confirm this issue also appears with macOS 11.1, same reproduction steps

**Comment by blueww** [comment]
@qetza, @henrikhorluck 
Please change the command by adding `--blobHost 0.0.0.0 --queueHost 0.0.0.0`, and try again, like：
`docker run --name azurite -p 10000:10000 -p 10001:10001 -v d:\.azurite:/data mcr.microsoft.com/azure-storage/azurite azurite  --blobHost 0.0.0.0 --queueHost 0.0.0.0 --cert //data/127.0.0.1.pem --key //data/127.0.0.1-key.pem --oauth basic`

By default Azurite use 127.0.0.1, but on docker azurite need user 0.0.0.0.
[The default docker azurite command](https://github.com/Azure/Azurite/blob/c41329e4126809eeb64a0298c364acc0b2808adc/Dockerfile#L46) has `--blobHost 0.0.0.0 --queueHost 0.0.0.0` . But if you add any azurite parameter, will not use the default command, then need manually add the 2 parameters.

**Comment by qetza** [comment]
Thanks @blueww this worked with the addition of `-l //data` to get azurite to use the mapped `/data` folder :smile:
