### ISSUE TITLE
XmlException when uploading file

### ISSUE THREAD

**Issue by KuraiAndras** [Azure/Azurite#700]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the Azurite was used?

3.10

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub, npm

### What's the Node.js version?

15.8.0 with npm, in docker the same as in the image

### What problem was encountered?

When calling BlobContainerClient.UploadBlobAsync() the following exception is thrown:
```
System.Xml.XmlException
Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, Stream body, Int64 contentLength, String version, Nullable`1 timeout, Byte[] transactionalContentHash, String blobContentType, String blobContentEncoding, String blobContentLanguage, Byte[] blobContentHash, String blobCacheControl, IDictionary`2 metadata, String leaseId, String blobContentDisposition, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 tier, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String ifTags, String requestId, String blobTagsString, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadInternal(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, IDictionary`2 tags, BlobRequestConditions conditions, Nullable`1 accessTier, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<>c__DisplayClass54_0.<<GetPartitionedUploaderBehaviors>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Storage.PartitionedUploader`2.UploadInternal(Stream content, TServiceSpecificArgs args, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.StagedUploadInternal(Stream content, BlobUploadOptions options, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.UploadBlobAsync(String blobName, Stream content, CancellationToken cancellationToken)
   at BimVisualizer.Server.Tests.AzuriteTests.CanUploadFile() in D:\bimvisualizer\BimVisualizer.Server.Tests\AzuriteTests.cs:line 59
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
```

### Steps to reproduce the issue?

I did this while testing if I can use azurite in a unit testing environment. I tried both with setting up azurite with npm and with a [nuget](https://www.nuget.org/packages/DockerizedTesting.Azurite/) which spins up a docker container for each test case, with a custom port, then discards it. Both of them resulted in the same exception

```csharp
[Fact]
public async Task CanUploadFile()
{
    // Arrange
    // this is the default connection string
    var connectionString = Sp.GetRequiredService<IOptions<AzureStorageOptions>>().Value.ConnectionString;

    var blobServiceClient = new BlobServiceClient(connectionString);
    const string testContainerName = "TestBlob";

    var containerResponse = await blobServiceClient.CreateBlobContainerAsync(testContainerName);

    // Act
    var client = containerResponse.Value;

    var message = new MemoryStream(Encoding.Default.GetBytes("Hello"));
    // Exception is thrown here
    await client.UploadBlobAsync("HelloFile.txt", message);

    await message.DisposeAsync();

    // Assert
    await using var result = new MemoryStream();
    using var reader = new StreamReader(result);
    await client.GetBlobClient("HelloFile.txt").DownloadToAsync(result);
    (await reader.ReadToEndAsync()).Should().Be("Hello");
}
```

connection string: 
```
DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:12000/devstoreaccount1;
```

Azurite is using the correct port

### Have you found a mitigation/solution?

No

**Comment by z77ma** [comment]
Hi,
I can upvote this. The version used is 3.14.3. The Azurite is installed via npm.
@KuraiAndras, did you by chance, find a solution in the mean time?

**Comment by KuraiAndras** [comment]
Sadly, no. We ended up not using Azurite and manually testing every major functionality of our project (Luckily it was jut a server with 5-10 endpoints). We created a storage account for all of our teammates, and everyone set up their own account for running  the server locally.
Not an ideal solution for bigger projects, but in our case it was feasible.

**Comment by z77ma** [comment]
Thanks for the info. I think we also switch to usage of a storage account.

**Comment by blueww** [comment]
@KuraiAndras 
It looks I can't repro the issue with latest Azurite 3.14.3 and Azure.Storage.Blobs 12.10.0.
(I have some change to you code. Since the container name "TestBlob" is invalid, it's not allowed in Azurite any more. So I changed it to "testblob", And I use port 10000.)
If you still can repro the issue (better with latest Azurite), could you please share the Azurite debug log and the SDK version, then we can continue the investigation.

**Comment by KuraiAndras** [comment]
Well, the project that used this has been finished since, so I don't really want to fire up the old test cases. If it works now - and maybe the container name was the issue? - this issue could be closed. On the other hand @z77ma could provide some more info on their issue (maybe you also have a problem with an invalid container name?).

**Comment by blueww** [comment]
Close this issue per @KuraiAndras suggestion.
@z77ma You can still attach the debug is if it still can repro on the latest Azurite version. And we will still look at it.
