### ISSUE TITLE
"PropertiesNeedValue" error in Bad Request due to a null "RowKey" in a record in Table Storage

### ISSUE THREAD

**Issue by shoaibahmd1** [Azure/Azurite#704]
### Which service(blob, file, queue, table) does this issue concern?
This issue is seen in the Table Storage

### Which version of the Azurite was used?
I am using azurite version "3.9.0-table-alpha.1"

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
I've cloned the azurite repo (GitHub) and **running azurite in VS Code locally**

### What's the Node.js version?
I am using node version 12.18.4

### What problem was encountered?
I am trying to insert record with null "Rowkey" value in table storage (locally), but it returns Bad Request with error "PropertiesNeedValue". But on Azure Portal storage (Cloud) it allows inserting record with null "RowKey" value. Why is this behavior different? 

### Steps to reproduce the issue?
You can reproduce this issue by inserting a record in table storage with null "RowKey" value (Azurite locally).

### Have you found a mitigation/solution?
I removed a validation check for null "RowKey" value in my code and it worked.

**Comment by blueww** [comment]
I can repro similar behavior

Server allows to add an entity with RowKey as empty string:
```
POST https://[accountname].table.core.windows.net/container637499480163667407() HTTP/1.1
Accept-Charset: UTF-8
MaxDataServiceVersion: 3.0;NetFx
Accept: application/json; odata=minimalmetadata
DataServiceVersion: 3.0;
Prefer: return-no-content
x-ms-client-request-id: f9e36bb0-c937-4c82-b759-f647a3d3e704
User-Agent: Azure-Cosmos-Table/1.0.8 (.NET CLR 4.0.30319.42000; Win32NT 10.0.19042.0)
x-ms-version: 2017-07-29
x-ms-date: Fri, 26 Feb 2021 06:55:43 GMT
Authorization: SharedKey [accountname]:***
Content-Type: application/json
Host: weirp1.table.core.windows.net
Content-Length: 74

{"PartitionKey":"partitionKey3","RowKey":"","userid":1,"username":"Chris"}
HTTP/1.1 204 No Content
Cache-Control: no-cache
Content-Length: 0
ETag: W/"datetime'2021-02-26T06%3A55%3A44.064994Z'"
Location: https://weirp1.table.core.windows.net/container637499480163667407(PartitionKey='partitionKey3',RowKey='')
Server: Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: b757dc50-f002-0099-2b0c-0ca57f000000
x-ms-version: 2017-07-29
X-Content-Type-Options: nosniff
Preference-Applied: return-no-content
DataServiceId: https://weirp1.table.core.windows.net/container637499480163667407(PartitionKey='partitionKey3',RowKey='')
Date: Fri, 26 Feb 2021 06:55:44 GMT
```

But Azurite does not allow it:
```
2021-02-26T07:12:46.181Z 08ed6172-035e-4672-a245-ba2f280a1ce5 info: TableStorageContextMiddleware: RequestMethod=POST RequestURL=http://127.0.0.1/devstoreaccount1/container637499480163667407() RequestHeaders:{"accept-charset":"UTF-8","maxdataserviceversion":"3.0;NetFx","accept":"application/json; odata=minimalmetadata","dataserviceversion":"3.0;","prefer":"return-no-content","x-ms-client-request-id":"d87e0402-aa94-46df-bf39-a21d0d2179d3","user-agent":"Azure-Cosmos-Table/1.0.8 (.NET CLR 4.0.30319.42000; Win32NT 10.0.19042.0)","x-ms-version":"2017-07-29","x-ms-date":"Fri, 26 Feb 2021 07:12:46 GMT","authorization":"SharedKey devstoreaccount1:SmissGzOXk/XaT21sy+bD92qz2HEQZk9a7Oehx2L5E8=","content-type":"application/json","host":"127.0.0.1:10002","content-length":"74"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1
2021-02-26T07:12:46.181Z 08ed6172-035e-4672-a245-ba2f280a1ce5 debug: tableStorageContextMiddleware: Dispatch pattern string: /container637499480163667407()
2021-02-26T07:12:46.181Z 08ed6172-035e-4672-a245-ba2f280a1ce5 info: tableStorageContextMiddleware: Account=devstoreaccount1 tableName=container637499480163667407
2021-02-26T07:12:46.182Z 08ed6172-035e-4672-a245-ba2f280a1ce5 verbose: DispatchMiddleware: Dispatching request...
2021-02-26T07:12:46.182Z 08ed6172-035e-4672-a245-ba2f280a1ce5 info: DispatchMiddleware: Operation=Table_InsertEntity
2021-02-26T07:12:46.182Z 08ed6172-035e-4672-a245-ba2f280a1ce5 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2021-02-26T07:12:46.182Z 08ed6172-035e-4672-a245-ba2f280a1ce5 info: TableSharedKeyLiteAuthenticator:validate() Start validation against account shared key authentication.
2021-02-26T07:12:46.183Z 08ed6172-035e-4672-a245-ba2f280a1ce5 info: TableSharedKeyLiteAuthenticator:validate() Request doesn't include valid authentication header. Skip SharedKeyLite authentication.
2021-02-26T07:12:46.183Z 08ed6172-035e-4672-a245-ba2f280a1ce5 info: TableSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2021-02-26T07:12:46.183Z 08ed6172-035e-4672-a245-ba2f280a1ce5 info: TableSharedKeyAuthenticator:validate() [STRING TO SIGN]:"POST\n\napplication/json\nFri, 26 Feb 2021 07:12:46 GMT\n/devstoreaccount1/devstoreaccount1/container637499480163667407()"
2021-02-26T07:12:46.183Z 08ed6172-035e-4672-a245-ba2f280a1ce5 info: TableSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:SmissGzOXk/XaT21sy+bD92qz2HEQZk9a7Oehx2L5E8=
2021-02-26T07:12:46.184Z 08ed6172-035e-4672-a245-ba2f280a1ce5 info: TableSharedKeyAuthenticator:validate() Signature 1 matched.
2021-02-26T07:12:46.184Z 08ed6172-035e-4672-a245-ba2f280a1ce5 verbose: DeserializerMiddleware: Start deserializing...
2021-02-26T07:12:46.185Z 08ed6172-035e-4672-a245-ba2f280a1ce5 debug: deserialize(): Raw request body string is (removed all empty characters) {"PartitionKey":"partitionKey3","RowKey":"","userid":1,"username":"Chris"}
2021-02-26T07:12:46.186Z 08ed6172-035e-4672-a245-ba2f280a1ce5 info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{},"requestId":"d87e0402-aa94-46df-bf39-a21d0d2179d3","dataServiceVersion":"3.0;","responsePreference":"return-no-content","tableEntityProperties":{"PartitionKey":"partitionKey3","RowKey":"","userid":1,"username":"Chris"}},"version":"2017-07-29","body":"ReadableStream"}
2021-02-26T07:12:46.188Z 08ed6172-035e-4672-a245-ba2f280a1ce5 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-02-26T07:12:46.233Z 08ed6172-035e-4672-a245-ba2f280a1ce5 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The values are not specified for all properties in the entity.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"PropertiesNeedValue","x-ms-request-id":"08ed6172-035e-4672-a245-ba2f280a1ce5","x-ms-version":"2019-12-12"} ErrorHTTPBody="{\"odata.error\":{\"code\":\"PropertiesNeedValue\",\"message\":{\"lang\":\"en-US\",\"value\":\"The values are not specified for all properties in the entity.\\nRequestId:08ed6172-035e-4672-a245-ba2f280a1ce5\\nTime:2021-02-26T07:12:46.187Z\"}}}" ErrorStack="StorageError: The values are not specified for all properties in the entity.\n    at Function.getPropertiesNeedValue (C:\\code\\azurite\\src\\table\\errors\\StorageErrorFactory.ts:194:12)\n    at TableHandler.insertEntity (C:\\code\\azurite\\src\\table\\handlers\\TableHandler.ts:173:33)\n    at C:\\code\\azurite\\src\\table\\generated\\middleware\\HandlerMiddlewareFactory.ts:82:10\n    at C:\\code\\azurite\\src\\table\\generated\\ExpressMiddlewareFactory.ts:97:57\n    at Layer.handle [as handle_request] (C:\\code\\azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\code\\azurite\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
2021-02-26T07:12:46.233Z 08ed6172-035e-4672-a245-ba2f280a1ce5 error: ErrorMiddleware: Set HTTP code: 400
2021-02-26T07:12:46.233Z 08ed6172-035e-4672-a245-ba2f280a1ce5 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=PropertiesNeedValue
2021-02-26T07:12:46.233Z 08ed6172-035e-4672-a245-ba2f280a1ce5 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=08ed6172-035e-4672-a245-ba2f280a1ce5
2021-02-26T07:12:46.233Z 08ed6172-035e-4672-a245-ba2f280a1ce5 error: ErrorMiddleware: Set HTTP Header: x-ms-version=2019-12-12
2021-02-26T07:12:46.234Z 08ed6172-035e-4672-a245-ba2f280a1ce5 error: ErrorMiddleware: Set content type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
2021-02-26T07:12:46.234Z 08ed6172-035e-4672-a245-ba2f280a1ce5 error: ErrorMiddleware: Set HTTP body: "{\"odata.error\":{\"code\":\"PropertiesNeedValue\",\"message\":{\"lang\":\"en-US\",\"value\":\"The values are not specified for all properties in the entity.\\nRequestId:08ed6172-035e-4672-a245-ba2f280a1ce5\\nTime:2021-02-26T07:12:46.187Z\"}}}"
2021-02-26T07:12:46.234Z 08ed6172-035e-4672-a245-ba2f280a1ce5 info: EndMiddleware: End response. TotalTimeInMS=54 StatusCode=400 StatusMessage=Bad Request Headers={"server":"Azurite-Table/3.9.0-table-alpha.1","x-ms-error-code":"PropertiesNeedValue","x-ms-request-id":"08ed6172-035e-4672-a245-ba2f280a1ce5","x-ms-version":"2019-12-12","content-type":"application/json;odata=minimalmetadata;streaming=true;charset=utf-8"}
```

**Comment by blueww** [comment]
@shoaibahmd1

We will evaluate the fix.

We welcome contribution!
As you have find the way to fix it in code, it would be great if you can raise a PR to fix it!

**Comment by shoaibahmd1** [comment]
I've raised PR for fixing this issue. https://github.com/Azure/Azurite/pull/711
