### ISSUE TITLE
From spark session i can not connect to Azurite. Does it support? 

### ISSUE THREAD

**Issue by MrKedrok** [Azure/Azurite#707]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
lastest
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Docker
### What's the Node.js version?
trying use pypsark / hdoop to connect
### What problem was encountered?
Can not list access to FS
### Steps to reproduce the issue?
add to hdoop config azurite and try to connect
![image](https://user-images.githubusercontent.com/26300945/108713930-2f1d1780-7519-11eb-95d6-a8bec04e6be3.png)

### Have you found a mitigation/solution?
NO

**Comment by MrKedrok** [comment]
Hi can you  priotytize it? We woudlike to simulate SA in our project but we can not connect to that resource it will be configured or not?

**Comment by MrKedrok** [comment]
Gentle follow up with that :D

**Comment by blueww** [comment]
@MrKedrok 

Would you please share more details for the issue?
1. The command to start Azurite docker
2. for "Can not list access to FS", do you mean you would like to access Azure File service, or HDFS service? They are both not supported by Azurite now. (Azurite support Blob/Queue now.)
3. from the picture , it seems your are trying to connect hdfs, it's not supported by Azurite now.

**Comment by MrKedrok** [comment]
Yes, 
i have tried use azure file service.
Then how :
1. can I connect to blob by spark?
i have created "refined" cointainer and put there one parquet file
![image](https://user-images.githubusercontent.com/26300945/108963568-90a8c780-767a-11eb-8511-d91f6f3b46e5.png)

Next I executed that below command to create connection between my local spark session and azureite emulator blob storage.

storage_account_name = "devstoreaccount1"
storage_account_key = "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
container = "refined"
#AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;
#BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
spark.conf.set("fs.azure.account.key.{0}.blob.core.windows.net".format(storage_account_name), storage_account_key)
![image](https://user-images.githubusercontent.com/26300945/108963816-ebdaba00-767a-11eb-882d-b872b495ca9d.png)


after I tried read that data by spark
df = spark.read.parquet("wasbs://refined@devstoreaccount1.blob.core.windows.net/meta_table_1111111.parquet")

and I got error : 
2021-02-24 07:32:42,928 WARN streaming.FileStreamSink: Error while looking for metadata directory.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/spark/python/pyspark/sql/readwriter.py", line 316, in parquet
    return self._df(self._jreader.parquet(_to_seq(self._spark._sc, paths)))
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o94.parquet.
: org.apache.hadoop.fs.azure.AzureException: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
        at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.retrieveMetadata(AzureNativeFileSystemStore.java:2210)
        at org.apache.hadoop.fs.azure.NativeAzureFileSystem.getFileStatusInternal(NativeAzureFileSystem.java:2660)
        at org.apache.hadoop.fs.azure.NativeAzureFileSystem.getFileStatus(NativeAzureFileSystem.java:2605)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:557)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:545)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.immutable.List.flatMap(List.scala:355)
        at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:545)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:359)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
        at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:645)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
        at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
        at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
        at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:196)
        at com.microsoft.azure.storage.blob.CloudBlobContainer.downloadAttributes(CloudBlobContainer.java:545)
        at org.apache.hadoop.fs.azure.StorageInterfaceImpl$CloudBlobContainerWrapperImpl.downloadAttributes(StorageInterfaceImpl.java:255)
        at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.checkContainer(AzureNativeFileSystemStore.java:1337)
        at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.retrieveMetadata(AzureNativeFileSystemStore.java:2126)
        ... 26 more

That operation is support and I need add something or I can not read that data by pyspark?

**Comment by blueww** [comment]
@MrKedrok 
As this is an emulator, the blob endpoint should be "BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
The blob endpoint with "devstoreaccount1.blob.core.windows.net" should not work.

**Comment by MrKedrok** [comment]
Okey, 
so how can i connect by pyspark session to this emulator?

**Comment by blueww** [comment]
@MrKedrok 
We are not familiar with pyspark . 
You might can check with the owner for how to customize the blob endpoint.

BTW, for any Azure Storage tools which support connection string, you can use the connection string in https://github.com/Azure/Azurite#connection-strings

**Comment by MrKedrok** [comment]
ok, who is the owner for that layer? Can you provide more next steps for it?

**Comment by blueww** [comment]
@MrKedrok
I am not so familiar with pyspark. 
Which package of pypark do you use to handle storage? Could you find the package owner?

Besides that, as this is not an Azurite issue, could we close this issue?

**Comment by blueww** [comment]
Close as this is not azurite issue.
