### ISSUE TITLE
Test Failing : Azure-Storage-Node - BlobContainer - getContainerProperties - should work

### ISSUE THREAD

**Issue by edwin-huber** [Azure/Azurite#71]
Failing test case:
Under : ./externaltests/azure-storage-node/test/services/blob/blobservice-container-tests.js:**317:20**

```javascript
blobService.getContainerProperties(containerName, function (getError, container2, getResponse) {
          assert.equal(getError, null);
          assert.notEqual(container2, null);
          if (container2) {
            assert.equal('unlocked', container2.lease.status);
            assert.equal('available', container2.lease.state);
            assert.equal(null, container2.lease.duration);
            assert.notEqual(null, container2.requestId);
            assert.notEqual(container2.hasImmutabilityPolicy, null);
            assert.deepStrictEqual(typeof container2.hasImmutabilityPolicy, 'boolean');
            assert.notEqual(container2.hasLegalHold, null);
            assert.deepStrictEqual(typeof container2.hasLegalHold, 'boolean');
```

azure-storage-node tests

       BlobContainer
         getContainerProperties
           should work:
     Uncaught AssertionError [ERR_ASSERTION]: undefined != null
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\test\services\blob\blobservice-container-tests.js:317:20
      at finalCallback (E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\services\blob\blobservice.core.js:698:7)
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\filters\retrypolicyfilter.js:189:13
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\services\storageserviceclient.js:801:17
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\services\storageserviceclient.js:1014:11
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\services\storageserviceclient.js:800:15
      at processResponseCallback (E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\services\blob\blobservice.core.js:701:5)
      at Request.processResponseCallback [as _callback] (E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\services\storageserviceclient.js:329:13)
      at Request.self.callback (E:\repo\azurite\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:185:22)
      at Request.<anonymous> (E:\repo\azurite\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:1161:10)
      at IncomingMessage.<anonymous> (E:\repo\azurite\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:1083:12)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by XiaoningLiu** [comment]
Close this for legacy Azurite V2. Please use Azurite V3.
