### ISSUE TITLE
Creating a blob returns status "403 CORS not enabled or no matching rule found for this request"

### ISSUE THREAD

**Issue by delexi** [Azure/Azurite#729]
Hello,

I am trying to setup a local blob storage emulator to make development and unit testing less dependent on a working internet connection. I am running into the following problem: 

### Which service(blob, file, queue, table) does this issue concern?
blob
### Which version of the Azurite was used?
3.11.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm
### What's the Node.js version?
12.18.2
### What problem was encountered?
I run an azurite instance with the following parameters:
```azurite --oauth basic --cert 127.0.0.1.pem --key 127.0.0.1-key.pem --debug debug.log```

I used the Storage Explorer to create a container named "requestdocuments" under the storage account I added via the "Local Storage Emulator" option in Storage Explorer. The CORS settings look like this: (Sorry for the German, but I guess it is understandable anyways. If not, I can translate it.)

![grafik](https://user-images.githubusercontent.com/645625/112354054-9c64c980-8ccc-11eb-97c8-14b5ae2fbbaf.png)

I try to create a blob with the Azure Storage SDK for JS in Browsers. The SDK is v10.3.0. This is the code:
```javascript
const containerUrl = "https://127.0.0.1:10000/devstoreaccount1/requestdocuments?sv=2018-03-28&sig=uHRGqy4wa7zFoEbMcd6GIZRafcfXW4IHHGbnslnla2c%3D&spr=https&se=2021-03-25T17%3A05%3A08Z&srt=o&ss=b&sp=w";

const blobName = "testblob";

const blockBlobUrl =
  BlockBlobURL.fromBlobURL(
    BlobURL.fromContainerURL(
      new ContainerURL(
        containerUrl,
        StorageURL.newPipeline(new AnonymousCredential())
      ),
      blobName)
    );

uploadBrowserDataToBlockBlob(Aborter.none, this.file, blockBlobUrl, {
    blockSize: blockSize,
    progress: progress
})
.then(function () {
    console.log('done');
});
```

The `containerUrl` above is created on the back-end in the following manner:
```csharp
string connectionString = $"DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://127.0.0.1:10000/devstoreaccount1/";

var storageAccount = CloudStorageAccount.Parse(connectionString);

// Create a new access policy for the account.
var policy = new SharedAccessAccountPolicy()
{
    Permissions = SharedAccessAccountPermissions.Write,
    Services = SharedAccessAccountServices.Blob,
    ResourceTypes = SharedAccessAccountResourceTypes.Object,
    SharedAccessExpiryTime = DateTime.UtcNow.AddHours(24),
    Protocols = SharedAccessProtocol.HttpsOnly
};

string blobEndpoint = storageAccount.BlobEndpoint.AbsoluteUri;
string sharedAccessSignature = storageAccount.GetSharedAccessSignature(policy);

string containerUrl = $"{blobEndpoint}{containerName}{sharedAccessSignature}";
```

In the browser Dev Tools I see, that the preflight request fails with the status code: "403 CORS not enabled or no matching rule found for this request."

This is the request:
```
Request URL: https://127.0.0.1:10000/devstoreaccount1/requestdocuments/178652d5e02-4151f922-ad74594d-7dc4d079_DICOM_Ok.zip?sv=2018-03-28&sig=OUNapcaeT5j1n+nylD1QvyNtsoMlT+nlajDfvLkNha4=&spr=https&se=2021-03-25T16:58:21Z&srt=o&ss=b&sp=w
Request Method: OPTIONS
Status Code: 403 CORS not enabled or no matching rule found for this request.
Remote Address: 127.0.0.1:10000
Referrer Policy: strict-origin-when-cross-origin
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: de,en-US;q=0.9,en;q=0.8
Access-Control-Request-Headers: content-type,x-ms-blob-type,x-ms-client-request-id,x-ms-version
Access-Control-Request-Method: PUT
Connection: keep-alive
Host: 127.0.0.1:10000
Origin: http://localhost:55555
Referer: http://localhost:55555/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
```

I also see a second request which I presume the browser is not sending, because the preflight CORS request did not succeed:
```
Request URL: https://127.0.0.1:10000/devstoreaccount1/requestdocuments/178652d5e02-4151f922-ad74594d-7dc4d079_DICOM_Ok.zip?sv=2018-03-28&sig=OUNapcaeT5j1n+nylD1QvyNtsoMlT+nlajDfvLkNha4=&spr=https&se=2021-03-25T16:58:21Z&srt=o&ss=b&sp=w
Referrer Policy: strict-origin-when-cross-origin

Provisional headers are shown
content-type: application/octet-stream
Referer: http://localhost:55555/
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
x-ms-blob-type: BlockBlob
x-ms-client-request-id: 95f0537b-a964-4f23-abd3-4627a32bfd20
x-ms-version: 2018-03-28
```

This is the relevant part of the logs:
```
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 info: BlobStorageContextMiddleware: RequestMethod=OPTIONS RequestURL=https://127.0.0.1/devstoreaccount1/requestdocuments/178653f0ca0-3c30b4e7-fbe40e3f-790cbeb2_DICOM_Ok.zip?sv=2018-03-28&sig=FXNzHTtXjAw0KrVTQifAStKi5sXIiKste5YUWdAnSOQ%3D&spr=https&se=2021-03-25T17%3A18%3A47Z&srt=o&ss=b&sp=w RequestHeaders:{"host":"127.0.0.1:10000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0","accept":"*/*","accept-language":"de-DE,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate, br","access-control-request-method":"PUT","access-control-request-headers":"content-type,x-ms-blob-type,x-ms-client-request-id,x-ms-version","referer":"http://localhost:55555/ViewRequestDetails.aspx?id=26","origin":"http://localhost:55555","connection":"keep-alive","pragma":"no-cache","cache-control":"no-cache"} ClientIP=127.0.0.1 Protocol=https HTTPVersion=1.1
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=requestdocuments Blob=178653f0ca0-3c30b4e7-fbe40e3f-790cbeb2_DICOM_Ok.zip
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 verbose: DispatchMiddleware: Dispatching request...
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 info: PreflightMiddlewareFactory.createOptionsHandlerMiddleware(): OPTIONS request.
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=CORS not enabled or no matching rule found for this request.  ErrorHTTPStatusCode=403 ErrorHTTPStatusMessage=CORS not enabled or no matching rule found for this request. ErrorHTTPHeaders={"x-ms-error-code":"CorsPreflightFailure","x-ms-request-id":"be9ee3b4-4427-4dfe-b02a-cc3580e80744"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>CorsPreflightFailure</Code>\n  <Message>CORS not enabled or no matching rule found for this request.\nRequestId:be9ee3b4-4427-4dfe-b02a-cc3580e80744\nTime:2021-03-24T17:18:54.128Z</Message>\n  <MessageDetails>No CORS rules matches this request</MessageDetails>\n</Error>" ErrorStack="StorageError: CORS not enabled or no matching rule found for this request.\n    at Function.corsPreflightFailure (C:\\Users\\AlexanderBaier\\AppData\\Roaming\\nvm\\v12.18.2\\node_modules\\azurite\\dist\\src\\blob\\errors\\StorageErrorFactory.js:222:16)\n    at C:\\Users\\AlexanderBaier\\AppData\\Roaming\\nvm\\v12.18.2\\node_modules\\azurite\\dist\\src\\blob\\middlewares\\PreflightMiddlewareFactory.js:62:63\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 error: ErrorMiddleware: Set HTTP code: 403
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 error: ErrorMiddleware: Set HTTP status message: CORS not enabled or no matching rule found for this request.
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=CorsPreflightFailure
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=be9ee3b4-4427-4dfe-b02a-cc3580e80744
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 error: ErrorMiddleware: Set content type: application/xml
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>CorsPreflightFailure</Code>\n  <Message>CORS not enabled or no matching rule found for this request.\nRequestId:be9ee3b4-4427-4dfe-b02a-cc3580e80744\nTime:2021-03-24T17:18:54.128Z</Message>\n  <MessageDetails>No CORS rules matches this request</MessageDetails>\n</Error>"
2021-03-24T17:18:54.128Z be9ee3b4-4427-4dfe-b02a-cc3580e80744 info: EndMiddleware: End response. TotalTimeInMS=1 StatusCode=403 StatusMessage=CORS not enabled or no matching rule found for this request. Headers={"server":"Azurite-Blob/3.11.0","x-ms-error-code":"CorsPreflightFailure","x-ms-request-id":"be9ee3b4-4427-4dfe-b02a-cc3580e80744","content-type":"application/xml"}
2021-03-24T17:18:54.137Z 514a1eb7-4342-463b-969e-fd8992e0d85c info: BlobStorageContextMiddleware: RequestMethod=OPTIONS RequestURL=https://127.0.0.1/devstoreaccount1/requestdocuments/178653f0ca0-3c30b4e7-fbe40e3f-790cbeb2_DICOM_Ok.zip?sv=2018-03-28&sig=FXNzHTtXjAw0KrVTQifAStKi5sXIiKste5YUWdAnSOQ%3D&spr=https&se=2021-03-25T17%3A18%3A47Z&srt=o&ss=b&sp=w RequestHeaders:{"host":"127.0.0.1:10000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0","accept":"*/*","accept-language":"de-DE,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate, br","access-control-request-method":"PUT","access-control-request-headers":"content-type,x-ms-blob-type,x-ms-client-request-id,x-ms-version","referer":"http://localhost:55555/ViewRequestDetails.aspx?id=26","origin":"http://localhost:55555","connection":"keep-alive","pragma":"no-cache","cache-control":"no-cache"} ClientIP=127.0.0.1 Protocol=https HTTPVersion=1.1
2021-03-24T17:18:54.138Z 514a1eb7-4342-463b-969e-fd8992e0d85c info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=requestdocuments Blob=178653f0ca0-3c30b4e7-fbe40e3f-790cbeb2_DICOM_Ok.zip
2021-03-24T17:18:54.138Z 514a1eb7-4342-463b-969e-fd8992e0d85c verbose: DispatchMiddleware: Dispatching request...
2021-03-24T17:18:54.138Z 514a1eb7-4342-463b-969e-fd8992e0d85c error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2021-03-24T17:18:54.138Z 514a1eb7-4342-463b-969e-fd8992e0d85c info: PreflightMiddlewareFactory.createOptionsHandlerMiddleware(): OPTIONS request.
2021-03-24T17:18:54.139Z 514a1eb7-4342-463b-969e-fd8992e0d85c error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-03-24T17:18:54.139Z 514a1eb7-4342-463b-969e-fd8992e0d85c error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=CORS not enabled or no matching rule found for this request.  ErrorHTTPStatusCode=403 ErrorHTTPStatusMessage=CORS not enabled or no matching rule found for this request. ErrorHTTPHeaders={"x-ms-error-code":"CorsPreflightFailure","x-ms-request-id":"514a1eb7-4342-463b-969e-fd8992e0d85c"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>CorsPreflightFailure</Code>\n  <Message>CORS not enabled or no matching rule found for this request.\nRequestId:514a1eb7-4342-463b-969e-fd8992e0d85c\nTime:2021-03-24T17:18:54.138Z</Message>\n  <MessageDetails>No CORS rules matches this request</MessageDetails>\n</Error>" ErrorStack="StorageError: CORS not enabled or no matching rule found for this request.\n    at Function.corsPreflightFailure (C:\\Users\\AlexanderBaier\\AppData\\Roaming\\nvm\\v12.18.2\\node_modules\\azurite\\dist\\src\\blob\\errors\\StorageErrorFactory.js:222:16)\n    at C:\\Users\\AlexanderBaier\\AppData\\Roaming\\nvm\\v12.18.2\\node_modules\\azurite\\dist\\src\\blob\\middlewares\\PreflightMiddlewareFactory.js:62:63\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
2021-03-24T17:18:54.139Z 514a1eb7-4342-463b-969e-fd8992e0d85c error: ErrorMiddleware: Set HTTP code: 403
2021-03-24T17:18:54.139Z 514a1eb7-4342-463b-969e-fd8992e0d85c error: ErrorMiddleware: Set HTTP status message: CORS not enabled or no matching rule found for this request.
2021-03-24T17:18:54.139Z 514a1eb7-4342-463b-969e-fd8992e0d85c error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=CorsPreflightFailure
2021-03-24T17:18:54.139Z 514a1eb7-4342-463b-969e-fd8992e0d85c error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=514a1eb7-4342-463b-969e-fd8992e0d85c
2021-03-24T17:18:54.139Z 514a1eb7-4342-463b-969e-fd8992e0d85c error: ErrorMiddleware: Set content type: application/xml
2021-03-24T17:18:54.139Z 514a1eb7-4342-463b-969e-fd8992e0d85c error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>CorsPreflightFailure</Code>\n  <Message>CORS not enabled or no matching rule found for this request.\nRequestId:514a1eb7-4342-463b-969e-fd8992e0d85c\nTime:2021-03-24T17:18:54.138Z</Message>\n  <MessageDetails>No CORS rules matches this request</MessageDetails>\n</Error>"
2021-03-24T17:18:54.139Z 514a1eb7-4342-463b-969e-fd8992e0d85c info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=403 StatusMessage=CORS not enabled or no matching rule found for this request. Headers={"server":"Azurite-Blob/3.11.0","x-ms-error-code":"CorsPreflightFailure","x-ms-request-id":"514a1eb7-4342-463b-969e-fd8992e0d85c","content-type":"application/xml"}
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 info: BlobStorageContextMiddleware: RequestMethod=OPTIONS RequestURL=https://127.0.0.1/devstoreaccount1/requestdocuments/178653f0ca0-3c30b4e7-fbe40e3f-790cbeb2_DICOM_Ok.zip?sv=2018-03-28&sig=FXNzHTtXjAw0KrVTQifAStKi5sXIiKste5YUWdAnSOQ%3D&spr=https&se=2021-03-25T17%3A18%3A47Z&srt=o&ss=b&sp=w RequestHeaders:{"host":"127.0.0.1:10000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0","accept":"*/*","accept-language":"de-DE,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate, br","access-control-request-method":"PUT","access-control-request-headers":"content-type,x-ms-blob-type,x-ms-client-request-id,x-ms-version","referer":"http://localhost:55555/ViewRequestDetails.aspx?id=26","origin":"http://localhost:55555","connection":"keep-alive","pragma":"no-cache","cache-control":"no-cache"} ClientIP=127.0.0.1 Protocol=https HTTPVersion=1.1
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=requestdocuments Blob=178653f0ca0-3c30b4e7-fbe40e3f-790cbeb2_DICOM_Ok.zip
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 verbose: DispatchMiddleware: Dispatching request...
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 info: PreflightMiddlewareFactory.createOptionsHandlerMiddleware(): OPTIONS request.
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=CORS not enabled or no matching rule found for this request.  ErrorHTTPStatusCode=403 ErrorHTTPStatusMessage=CORS not enabled or no matching rule found for this request. ErrorHTTPHeaders={"x-ms-error-code":"CorsPreflightFailure","x-ms-request-id":"e07c92cb-3154-43b8-ad7a-1152fb2149f4"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>CorsPreflightFailure</Code>\n  <Message>CORS not enabled or no matching rule found for this request.\nRequestId:e07c92cb-3154-43b8-ad7a-1152fb2149f4\nTime:2021-03-24T17:18:58.156Z</Message>\n  <MessageDetails>No CORS rules matches this request</MessageDetails>\n</Error>" ErrorStack="StorageError: CORS not enabled or no matching rule found for this request.\n    at Function.corsPreflightFailure (C:\\Users\\AlexanderBaier\\AppData\\Roaming\\nvm\\v12.18.2\\node_modules\\azurite\\dist\\src\\blob\\errors\\StorageErrorFactory.js:222:16)\n    at C:\\Users\\AlexanderBaier\\AppData\\Roaming\\nvm\\v12.18.2\\node_modules\\azurite\\dist\\src\\blob\\middlewares\\PreflightMiddlewareFactory.js:62:63\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 error: ErrorMiddleware: Set HTTP code: 403
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 error: ErrorMiddleware: Set HTTP status message: CORS not enabled or no matching rule found for this request.
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=CorsPreflightFailure
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=e07c92cb-3154-43b8-ad7a-1152fb2149f4
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 error: ErrorMiddleware: Set content type: application/xml
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>CorsPreflightFailure</Code>\n  <Message>CORS not enabled or no matching rule found for this request.\nRequestId:e07c92cb-3154-43b8-ad7a-1152fb2149f4\nTime:2021-03-24T17:18:58.156Z</Message>\n  <MessageDetails>No CORS rules matches this request</MessageDetails>\n</Error>"
2021-03-24T17:18:58.156Z e07c92cb-3154-43b8-ad7a-1152fb2149f4 info: EndMiddleware: End response. TotalTimeInMS=0 StatusCode=403 StatusMessage=CORS not enabled or no matching rule found for this request. Headers={"server":"Azurite-Blob/3.11.0","x-ms-error-code":"CorsPreflightFailure","x-ms-request-id":"e07c92cb-3154-43b8-ad7a-1152fb2149f4","content-type":"application/xml"}
```

So this is where I am stuck. Does anyone know how to proceed from here?

### Steps to reproduce the issue?
See above.
### Have you found a mitigation/solution?
No.

**Comment by blueww** [comment]
@delexi 

For CORS rule, `allowed_methods`  should not be set as "*", would you like to set the methods you need to this properties, and try again?  (You also try to change "MaxAgeInSeconds" to a bigger value like 200) 
Please see more about cors in https://docs.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services.

If still fail, please share the debug log.

**Comment by delexi** [comment]
@blueww Thank you very much for the quick and helpful response ! :)

I changed the CORS settings according to your guidance and the blob creation went through flawlessly! These are the CORS settings for reference:
![grafik](https://user-images.githubusercontent.com/645625/112454727-4853f680-8d59-11eb-911c-ae0c6df5fba3.png)
