### ISSUE TITLE
Test Failing : Azure-Storage-Node - BlobContainer - setContainerAcl - should work with policies

### ISSUE THREAD

**Issue by edwin-huber** [Azure/Azurite#73]
Failing test case:  
Under : ./externaltests/azure-storage-node/test/services/blob/blobservice-container-tests.js:**586:01**  

Assuming that it is caused by either failing set or get container ACL code...

```javascript
blobService.setContainerAcl(containerName, signedIdentifiers, options, function (setAclError, setAclContainer1, setResponse1) {
        assert.equal(setAclError, null);
        assert.notEqual(setAclContainer1, null);
        assert.ok(setResponse1.isSuccessful);
        
        setTimeout(function () {
          blobService.getContainerAcl(containerName, function (getAclError, getAclContainer1, getResponse1) {
            assert.equal(getAclError, null);
            assert.notEqual(getAclContainer1, null);
            assert.equal(getAclContainer1.publicAccessLevel, BlobUtilities.BlobContainerPublicAccessType.BLOB);
            assert.equal(getAclContainer1.signedIdentifiers.readwrite.Expiry.getTime(), readWriteExpiryDate.getTime());
            assert.ok(getResponse1.isSuccessful);
            
            options.publicAccessLevel = BlobUtilities.BlobContainerPublicAccessType.CONTAINER;
            blobService.setContainerAcl(containerName, null, options, function (setAclError2, setAclContainer2, setResponse2) {
              assert.equal(setAclError2, null);
              assert.notEqual(setAclContainer2, null);
              assert.ok(setResponse2.isSuccessful);
```

azure-storage-node tests
base.js:266
       BlobContainer
         setContainerAcl
           should work with policies:
     Uncaught TypeError: Cannot read property 'split' of undefined
      at Object.exports.parse (E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\util\iso8061date.js:48:22)
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\models\aclresult.js:105:44
      at Array.forEach (<anonymous>)
      at Object.exports.parse (E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\models\aclresult.js:101:26)
      at processResponseCallback (E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\services\blob\blobservice.core.js:874:68)
      at Request.processResponseCallback [as _callback] (E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\services\storageserviceclient.js:329:13)
      at Request.self.callback (E:\repo\azurite\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:185:22)
      at Request.<anonymous> (E:\repo\azurite\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:1161:10)
      at IncomingMessage.<anonymous> (E:\repo\azurite\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:1083:12)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by XiaoningLiu** [comment]
Close this for legacy Azurite V2. Please use Azurite V3.
