### ISSUE TITLE
Test Failing : Azure-Storage-Node - BlobContainer - setContainerAcl - should work with signed identifiers

### ISSUE THREAD

**Issue by edwin-huber** [Azure/Azurite#74]
Failing test case:  
Under : ./externaltests/azure-storage-node/test/services/blob/blobservice-container-tests.js:**634:01**  

Assuming issue is generated here, either in how Azurite writes or return the data:

```javascript
var options = {publicAccessLevel: BlobUtilities.BlobContainerPublicAccessType.OFF};
      blobService.setContainerAcl(containerName, signedIdentifiers, options, function (setAclError, setAclContainer, setAclResponse) {
        assert.equal(setAclError, null);
        assert.notEqual(setAclContainer, null);
        assert.ok(setAclResponse.isSuccessful);
        setTimeout(function () {
          blobService.getContainerAcl(containerName, function (getAclError, containerAcl, getAclResponse) {
            assert.equal(getAclError, null);
            assert.notEqual(containerAcl, null);
            assert.notEqual(getAclResponse, null);

            if (getAclResponse) {
              assert.equal(getAclResponse.isSuccessful, true);
            }

            assert.equal(containerAcl.signedIdentifiers.id1.Start.getTime(), new Date('2009-10-10T00:00:00.123Z').getTime());
```

azure-storage-node tests
base.js:266
       BlobContainer
         setContainerAcl
           should work with signed identifiers:
     Uncaught TypeError: Cannot read property 'split' of undefined
      at Object.exports.parse (E:\repo\azurite_pdressel\Azurite\externaltests\azure-storage-node\lib\common\util\iso8061date.js:48:22)
      at E:\repo\azurite_pdressel\Azurite\externaltests\azure-storage-node\lib\common\models\aclresult.js:105:44
      at Array.forEach (<anonymous>)
      at Object.exports.parse (E:\repo\azurite_pdressel\Azurite\externaltests\azure-storage-node\lib\common\models\aclresult.js:101:26)
      at processResponseCallback (E:\repo\azurite_pdressel\Azurite\externaltests\azure-storage-node\lib\services\blob\blobservice.core.js:874:68)
      at Request.processResponseCallback [as _callback] (E:\repo\azurite_pdressel\Azurite\externaltests\azure-storage-node\lib\common\services\storageserviceclient.js:329:13)
      at Request.self.callback (E:\repo\azurite_pdressel\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:185:22)
      at Request.<anonymous> (E:\repo\azurite_pdressel\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:1161:10)
      at IncomingMessage.<anonymous> (E:\repo\azurite_pdressel\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:1083:12)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by XiaoningLiu** [comment]
Close this for legacy Azurite V2. Please use Azurite V3.
