### ISSUE TITLE
[Logic Apps] Get properties of table service is not implemented

### ISSUE THREAD

**Issue by laveeshb** [Azure/Azurite#747]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
Latest from `table` branch (948e5eb7efc8f76182d4ad6e0e248583d8a9886e)

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Local `npm` build

### What's the Node.js version?
v14.16.0

### What problem was encountered?
API to get properties of table service is not implemented

### Steps to reproduce the issue?
```
2021-04-08T00:17:05.429Z 49d3a4a5-45f6-4c1b-82a4-67b3394e2a26 info: TableStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/devstoreaccount1?sv=2018-03-28&sig=%2F%2BSzl3Nz%2BG4r2mk7rKUssoje39G3gQQoT%2FZT0ifkAWM%3D&se=2023-04-08T00%3A17%3A05Z&srt=sco&ss=bqt&sp=racupwdl&api-version=2018-03-28&comp=properties&restype=service&timeout=6 RequestHeaders:{"user-agent":"Azure-Storage/9.3.2 (.NET CLR 4.0.30319.42000; Win32NT 10.0.19042.0)","x-ms-version":"2018-03-28","x-ms-client-request-id":"8f266da2-46dc-4473-8b24-a044a8f9eb92","host":"127.0.0.1:10002","connection":"Keep-Alive"} ClientIP=127.0.0.1 Protocol=http HTTPVersion=1.1

2021-04-08T00:17:05.450Z 49d3a4a5-45f6-4c1b-82a4-67b3394e2a26 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage="Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues"  ErrorHTTPStatusCode=501 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"APINotImplemented","x-ms-request-id":"49d3a4a5-45f6-4c1b-82a4-67b3394e2a26","x-ms-version":"2019-12-12"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>APINotImplemented</Code>\n  <Message>Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues\nRequestId:49d3a4a5-45f6-4c1b-82a4-67b3394e2a26\nTime:2021-04-08T00:17:05.443Z</Message>\n</Error>" ErrorStack="\"StorageError: Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues\\n    at ServiceHandler.getProperties (C:\\\\Source\\\\Azurite\\\\dist\\\\src\\\\table\\\\handlers\\\\ServiceHandler.js:13:15)\\n    at C:\\\\Source\\\\Azurite\\\\dist\\\\src\\\\table\\\\generated\\\\middleware\\\\HandlerMiddlewareFactory.js:58:18\\n    at C:\\\\Source\\\\Azurite\\\\dist\\\\src\\\\table\\\\generated\\\\ExpressMiddlewareFactory.js:77:63\\n    at Layer.handle [as handle_request] (C:\\\\Source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at trim_prefix (C:\\\\Source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:317:13)\\n    at C:\\\\Source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:284:7\\n    at Function.process_params (C:\\\\Source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:335:12)\\n    at next (C:\\\\Source\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:275:10)\\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\""
2021-04-08T00:17:05.450Z 49d3a4a5-45f6-4c1b-82a4-67b3394e2a26 error: ErrorMiddleware: Set HTTP code: 501
2021-04-08T00:17:05.450Z 49d3a4a5-45f6-4c1b-82a4-67b3394e2a26 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=APINotImplemented
2021-04-08T00:17:05.451Z 49d3a4a5-45f6-4c1b-82a4-67b3394e2a26 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=49d3a4a5-45f6-4c1b-82a4-67b3394e2a26
2021-04-08T00:17:05.451Z 49d3a4a5-45f6-4c1b-82a4-67b3394e2a26 error: ErrorMiddleware: Set HTTP Header: x-ms-version=2019-12-12
2021-04-08T00:17:05.451Z 49d3a4a5-45f6-4c1b-82a4-67b3394e2a26 error: ErrorMiddleware: Set content type: application/xml
2021-04-08T00:17:05.451Z 49d3a4a5-45f6-4c1b-82a4-67b3394e2a26 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>APINotImplemented</Code>\n  <Message>Current API is not implemented yet. Please vote your wanted features to https://github.com/azure/azurite/issues\nRequestId:49d3a4a5-45f6-4c1b-82a4-67b3394e2a26\nTime:2021-04-08T00:17:05.443Z</Message>\n</Error>"
2021-04-08T00:17:05.453Z 49d3a4a5-45f6-4c1b-82a4-67b3394e2a26 info: EndMiddleware: End response. TotalTimeInMS=24 StatusCode=501 StatusMessage=Not Implemented Headers={"server":"Azurite-Table/3.9.0-table-alpha.1","x-ms-error-code":"APINotImplemented","x-ms-request-id":"49d3a4a5-45f6-4c1b-82a4-67b3394e2a26","x-ms-version":"2019-12-12","content-type":"application/xml"}
```

### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
As discussed in mail, this will have lower priority than other table issue, will not implement this in the recent days.
