### ISSUE TITLE
Test Failing : Azure-Storage-Node - BlobContainer - listBlobs - should work with blob with space only

### ISSUE THREAD

**Issue by edwin-huber** [Azure/Azurite#76]
Failing test case:  
Under : ./externaltests/azure-storage-node/test/services/blob/blobservice-container-tests.js:**897:20**  

```javascript
it('should work with blob with space only', function(done) {
      var blobName1 = ' ';
      var blobText1 = 'hello1';
      blobs.length = 0;

      listBlobs(null, null, null, function() {
        assert.equal(blobs.length, 0);

        blobService.createBlockBlobFromText(containerName, blobName1, blobText1, function (blobErr1) {
          assert.equal(blobErr1, null);

          // Test listing 1 blob
          listBlobs(null, null, null, function() {
            assert.equal(blobs.length, 1);
            assert.equal(blobs[0].name, blobName1);
            done();
          });
        });
      });
    });
```
azure-storage-node tests
base.js:266
       BlobContainer
         listBlobs
           should work with blob with space only:
      Uncaught AssertionError [ERR_ASSERTION]: '' == ' '
      + expected - actual
      + 
      
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\test\services\blob\blobservice-container-tests.js:897:20
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\test\services\blob\blobservice-container-tests.js:1024:7
      at finalCallback (E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\services\blob\blobservice.core.js:5824:7)
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\filters\retrypolicyfilter.js:189:13
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\services\storageserviceclient.js:801:17
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\services\storageserviceclient.js:1014:11
      at E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\services\storageserviceclient.js:800:15
      at processResponseCallback (E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\services\blob\blobservice.core.js:5827:5)
      at Request.processResponseCallback [as _callback] (E:\repo\azurite\Azurite\externaltests\azure-storage-node\lib\common\services\storageserviceclient.js:329:13)
      at Request.self.callback (E:\repo\azurite\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:185:22)
      at Request.<anonymous> (E:\repo\azurite\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:1161:10)
      at IncomingMessage.<anonymous> (E:\repo\azurite\Azurite\externaltests\azure-storage-node\node_modules\request\request.js:1083:12)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by XiaoningLiu** [comment]
Close this for legacy Azurite V2. Please use Azurite V3.
