### ISSUE TITLE
Azurite SAS blob upload does not work with Python lib.

### ISSUE THREAD

**Issue by vashu1** [Azure/Azurite#765]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the Azurite was used?

latest Docker image

$ docker run -p 10000:10000 -v files:/data mcr.microsoft.com/azure-storage/azurite -v
v12.19.0

$ docker images --digests | grep azure
mcr.microsoft.com/azure-storage/azurite     latest                                           sha256:8c9aea2abaa0f21d8b5256cb713f2319dbc3f0af38ae4d477eaf7d377eb879db   058b0a78da98

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub

### What's the Node.js version?

running docker

### What problem was encountered?

Azurite SAS blob upload does not work with Python lib.

Exception is produced: azure.core.exceptions.ServiceRequestError: Failed to parse 

Same link works with HTTP call.

### Steps to reproduce the issue?

Run
```
import uuid
from azure.storage.blob import generate_blob_sas, BlobSasPermissions
from azure.storage.blob import BlobServiceClient, upload_blob_to_url
from datetime import datetime, timedelta

host = 'http://localhost:10000'
account_key = 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=='
connect_str = f'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey={account_key};BlobEndpoint={host}/devstoreaccount1;'

blob_service_client = BlobServiceClient.from_connection_string(connect_str)
container_name = "quickstart" + str(uuid.uuid4())
container_client = blob_service_client.create_container(container_name)

PERMIT_ALL = BlobSasPermissions(read=True, add=True, create=True, write=True, delete=True, delete_previous_version=True, tag=True)

blob_client = blob_service_client.get_blob_client(container=container_name, blob='fname')
blob_sas_token = generate_blob_sas(
                blob_client.account_name,
                blob_client.container_name,
                blob_client.blob_name,
                account_key=account_key,
                permission=PERMIT_ALL,
                expiry=datetime.utcnow() + timedelta(hours=1),
            )

blob_url = f"{host}/{blob_client.account_name}/{blob_client.container_name}/" \
           f"{blob_client.blob_name}?{blob_sas_token}"

print(blob_url)
response = upload_blob_to_url(blob_url, b'content')
print(response)
```

After 90 second timeout you will get error:

```
http://localhost:10000/devstoreaccount1/quickstartda073f14-4a40-48fc-9168-639edac25860/fname?se=2021-04-28T03%3A44%3A25Z&sp=racwdxt&sv=2020-02-10&sr=b&sig=i8Id55OvUzE52QFsDVRlCgd7DtCqpBJhA%2Bdd%2BuXUKzM%3D
Traceback (most recent call last):
  File "test_upload.py", line 30, in <module>
    response = upload_blob_to_url(blob_url, b'content')
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/storage/blob/__init__.py", line 113, in upload_blob_to_url
    return client.upload_blob(data=data, blob_type=BlobType.BlockBlob, **kwargs)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/storage/blob/_blob_client.py", line 539, in upload_blob
    return upload_block_blob(**options)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/storage/blob/_upload_helpers.py", line 95, in upload_block_blob
    return client.upload(
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 217, in upload
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/_base.py", line 216, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/_base.py", line 76, in send
    response = self.next.send(request)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/_base.py", line 76, in send
    response = self.next.send(request)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/_base.py", line 76, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/_base.py", line 76, in send
    response = self.next.send(request)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/storage/blob/_shared/policies.py", line 515, in send
    raise err
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/storage/blob/_shared/policies.py", line 489, in send
    response = self.next.send(request)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/_base.py", line 76, in send
    response = self.next.send(request)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/_base.py", line 76, in send
    response = self.next.send(request)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/_base.py", line 76, in send
    response = self.next.send(request)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/storage/blob/_shared/policies.py", line 290, in send
    response = self.next.send(request)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/_base.py", line 76, in send
    response = self.next.send(request)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/_base.py", line 76, in send
    response = self.next.send(request)
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/_base.py", line 108, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/Users/vashu1/Library/Python/3.8/lib/python/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 285, in send
    raise error
azure.core.exceptions.ServiceRequestError: Failed to parse: http://localhost:10000/devstoreaccount1/quickstartda073f14-4a40-48fc-9168-639edac25860/fname?se=2021-04-28T03%3A44%3A25Z&sp=racwdxt&sv=2020-02-10&sr=b&sig=i8Id55OvUzE52QFsDVRlCgd7DtCqpBJhA%2Bdd%2BuXUKzM%3D
```

### Have you found a mitigation/solution?

Uploading file to Azurite via HTTP API

```
import requests
from datetime import datetime
import uuid

def upload_blob_to_sas(sas, data):
    x = requests.put(
        sas,
        data=data,
        headers={
            'Content-Type': 'application/octet-stream',
            'Content-Length': str(len(data)),
            'x-ms-version': '2020-02-10',
            'x-ms-blob-type': 'BlockBlob',
            'If-None-Match': '*',
            'User-Agent': 'azsdk-python-storage-blob/12.6.0 Python/3.8.9 (macOS-10.15.7-x86_64-i386-64bit)',
            'x-ms-date': datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S GMT"),
            'x-ms-client-request-id': str(uuid.uuid4()),
        }
    )
    return x
```

**Comment by blueww** [comment]
@vashu1 

As you can upload the file to Azurite in another way, it looks Azurite works.
Would you please check what's the different of the request send to Azurite in the 2 ways?
Do you use the same blob endpoint, same sas in the 2 ways?

Besides that, would you please share the Azurite debug log for this issue if any?

**Comment by blueww** [comment]
@vashu1 
I will close this issue as not hear from you from a long time.
Feel free to contact us again if you need any further assistance on Azurite.
