### ISSUE TITLE
[Table] Error while using Durable Functions with azurite

### ISSUE THREAD

**Issue by junalmeida** [Azure/Azurite#796]
### Which service(blob, file, queue, table) does this issue concern?
Table 

### Which version of the Azurite was used?
3.12.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
12.16.3

### What problem was encountered?
Couldn't extract path from URL in sub-Request

### Steps to reproduce the issue?

Log below

```
PUT http://127.0.0.1:10002/queuesdev/funcpcappdevHistory(PartitionKey='2d2c8fe4-d3a6-438f-aa83-382d93ee9569:ca',RowKey='0000000000000000') HTTP/1.1
Accept: application/json;odata=minimalmetadata
Content-Type: application/json
DataServiceVersion: 3.0;

{"EventId":-1,"IsPlayed":false,"_Timestamp":"2021-05-28T19:28:47.3971577Z","_Timestamp@odata.type":"Edm.DateTime","EventType":"OrchestratorStarted","ExecutionId":"796d2897909c4c11aec3768df50feb95"}
 ErrorStack="Error: Couldn't extract path from URL in sub-Request:\n \r\n\r\nPUT http://127.0.0.1:10002/queuesdev/funcpcappdevHistory(PartitionKey='2d2c8fe4-d3a6-438f-aa83-382d93ee9569:ca',RowKey='0000000000000000') HTTP/1.1\r\nAccept: application/json;odata=minimalmetadata\r\nContent-Type: application/json\r\nDataServiceVersion: 3.0;\r\n\r\n{\"EventId\":-1,\"IsPlayed\":false,\"_Timestamp\":\"2021-05-28T19:28:47.3971577Z\",\"_Timestamp@odata.type\":\"Edm.DateTime\",\"EventType\":\"OrchestratorStarted\",\"ExecutionId\":\"796d2897909c4c11aec3768df50feb95\"}\r\n\n    at C:\\Users\\junior\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\azurite\\dist\\src\\table\\batch\\TableBatchSerialization.js:71:23\n    at Array.map (<anonymous>)\n    at TableBatchSerialization.deserializeBatchRequest (C:\\Users\\junior\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\azurite\\dist\\src\\table\\batch\\TableBatchSerialization.js:57:45)\n    at TableBatchOrchestrator.processBatchRequestAndSerializeResponse (C:\\Users\\junior\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\azurite\\dist\\src\\table\\batch\\TableBatchOrchestrator.js:43:51)\n    at TableHandler.batch (C:\\Users\\junior\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\azurite\\dist\\src\\table\\handlers\\TableHandler.js:400:50)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
Sounds like a Batch sub operation deserialization issue, @edwin-huber able to help on this? Thanks!

**Comment by edwin-huber** [comment]
Thanks, I'll take a look...

**Comment by junalmeida** [comment]
Investigating https://github.com/Azure/Azurite/blob/51baf445d1e2532659e16a90505c4ff8a9349ea1/src/table/batch/TableBatchSerialization.ts#L88 I see the hardcoded string `devstoreaccount1`. In my use case I have multiple accounts set up to mimic my production environment, so that hardcoded string is not part of it.

**Comment by edwin-huber** [comment]
thanks, I'll update the regex
