### ISSUE TITLE
Response returned in Azurite doesn't contain copyStatus property when use synchronous copy from URL operation

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/Azurite#828]
**Error Description:**
In Azure, response of synchronous copy from URL operation contains `copyStatus`.
But response returned in Azurite doesn't contain `copyStatus` property in this case.

**To Reproduce:**
```Typescript
import { BlobServiceClient, StorageSharedKeyCredential } from "@azure/storage-blob";
import { assert } from "chai";

async function main() {
    const blobServiceClient = new BlobServiceClient("<Azurite-https-endpoint>", new StorageSharedKeyCredential("<account-name>", "<account-key>"));
    const containerClient = blobServiceClient.getContainerClient("<container-name>");
    await containerClient.create();
    const content = "Hello World";
    const blobClient = containerClient.getBlobClient("myblob");
    const blockBlobClient = blobClient.getBlockBlobClient();
    await blockBlobClient.upload(content, content.length);
    const newBlobClient = containerClient.getBlobClient("newblob");
    const copyURL = blobClient.url + "?" + "<blob-sas>";
    const result = await newBlobClient.syncCopyFromURL(copyURL);
    assert.ok(result["copyStatus"]);
}

main();
```

**Error Track:**
The process code of synchronous copy from URL operation is shown as following(synchronous copy from URL operation matches the copy from URL operation with request header `x-ms-requires-sync`):
[https://github.com/Azure/Azurite/blob/master/src/blob/handlers/BlobHandler.ts#L852](https://github.com/Azure/Azurite/blob/master/src/blob/handlers/BlobHandler.ts#L852)
![image](https://user-images.githubusercontent.com/20970631/121666278-a6cc7d80-cadb-11eb-8b39-41d2cb0f40de.png)
As the picture shown, the response of synchronous copy from URL  lacks `copyStatus` property in Azurite.

**Expected Behavior:**
Response returned in Azurite contains `copyStatus` property when use synchronous copy from URL operation.

@jongio for notification.

**Comment by blueww** [comment]
@zzhxiaofeng 

Thanks for reporting the issue!
We might can fix it by just add `copyStatus: Models.SyncCopyStatusType.Success` when set `BlobCopyFromURLResponse` as your referenced code above (not tested).

We will evaluate it.

**Comment by Socolin** [comment]
Hello,

It seems related to a bug I'm having.

After upgrading the dotnet nuget `Azure.Storage.Blobs` from `12.8.3` to `12.9.1`, I'm getting this error:

```
System.ArgumentOutOfRangeException: Unknown CopyStatus value. (Parameter 'value')
   at Azure.Storage.Blobs.Models.CopyStatusExtensions.ToCopyStatus(String value)
   at Azure.Storage.Blobs.BlobExtensions.ToBlobCopyInfo(ResponseWithHeaders`1 response)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.SyncCopyFromUriInternal(Uri source, IDictionary`2 metadata, IDictionary`2 tags, Nullable`1 accessTier, BlobRequestConditions sourceConditions, BlobRequestConditions destinationConditions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.SyncCopyFromUriAsync(Uri source, BlobCopyFromUriOptions options, CancellationToken cancellationToken)
```

`value` is null during `CopyStatusExtensions.ToCopyStatus(this string value)`

Downgrading to 12.8.3 fixed the bug, but it's not a solution.
