### ISSUE TITLE
None of the QueueClient apis seem to work at all

### ISSUE THREAD

**Issue by justinmchase** [Azure/Azurite#974]
### Which service(blob, file, queue, table) does this issue concern?
`queue`

### Which version of the Azurite was used?
`mcr.microsoft.com/azure-storage/azurite:latest`

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
`dockerhub`

### What's the Node.js version?
`14`

### What problem was encountered?
`QueueClient` all fail with 400 error

### Steps to reproduce the issue?
```ts
import { QueueServiceClient, QueueClient } from "@azure/storage-queue";
const connectionString = 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://localhost:10001/devstoreaccount1;'

const client = QueueServiceClient.fromConnectionString(connectionString)
const example = await this.client.getQueueClient('example')
await example.createIfNotExists()
```

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
/var/log # tail -f -n 100 azurite
2021-07-29T18:07:40.726Z         info: Azurite Blob service is starting on 0.0.0.0:10000
2021-07-29T18:07:40.728Z         info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-07-29T18:07:40.728Z         info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-07-29T18:07:40.759Z         info: BlobGCManager:start() Starting BlobGCManager. Set status to Initializing.
2021-07-29T18:07:40.759Z         info: BlobGCManager:start() Trigger mark and sweep loop. Set status to Running.
2021-07-29T18:07:40.759Z         info: BlobGCManager:markSweepLoop() Start next mark and sweep.
2021-07-29T18:07:40.760Z         info: BlobGCManager:markSweep() Get all extents.
2021-07-29T18:07:40.761Z         info: BlobGCManager:start() BlobGCManager successfully started.
2021-07-29T18:07:40.763Z         info: BlobGCManager:markSweep() Got 2 extents.
2021-07-29T18:07:40.763Z         info: BlobGCManager:markSweep() Get referred extents.
2021-07-29T18:07:40.765Z         info: BlobGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2021-07-29T18:07:40.765Z         info: BlobGCManager:markSweepLoop() Mark and sweep finished, taken 5ms.
2021-07-29T18:07:40.765Z         info: BlobGCManager:markSweepLoop() Sleep for 600000ms.
2021-07-29T18:07:40.767Z         info: Azurite Blob service successfully listens on http://0.0.0.0:10000
2021-07-29T18:07:40.767Z         info: Azurite Queue service is starting on 0.0.0.0:10001
2021-07-29T18:07:40.767Z         info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-07-29T18:07:40.767Z         info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-07-29T18:07:40.785Z         info: QueueGCManager:start() Starting QueueGCManager, set status to Initializing
2021-07-29T18:07:40.786Z         info: QueueGCManager:start() Trigger mark and sweep loop, set status to Running.
2021-07-29T18:07:40.786Z         info: QueueGCManager:markSweepLoop() Start new mark and sweep.
2021-07-29T18:07:40.786Z         info: QueueGCManger:markSweep() Get all extents.
2021-07-29T18:07:40.786Z         info: QueueGCManager:start() QueueGCManager successfully started.
2021-07-29T18:07:40.787Z         info: QueueGCManager:marksweep() Get 0 extents.
2021-07-29T18:07:40.787Z         info: QueueGCManager:markSweep() Get referred extents, then remove from allExtents.
2021-07-29T18:07:40.787Z         info: QueueGCManager:markSweep() Got referred extents, unreferenced extents count is 0.
2021-07-29T18:07:40.787Z         info: QueueGCManager:markSweepLoop() Mark and sweep finished, take 1ms.
2021-07-29T18:07:40.787Z         info: QueueGCManager:markSweepLoop() Sleep for 60000
2021-07-29T18:07:40.787Z         info: Azurite Queue service successfully listens on http://0.0.0.0:10001
2021-07-29T18:07:40.788Z         info: Azurite Table service is starting on 0.0.0.0:10002
2021-07-29T18:07:40.788Z         info: AccountDataStore:init() Refresh accounts from environment variable AZURITE_ACCOUNTS with value undefined
2021-07-29T18:07:40.788Z         info: AccountDataStore:init() Fallback to default emulator account devstoreaccount1.
2021-07-29T18:07:40.797Z         info: Azurite Table service successfully listens on http://0.0.0.0:10002
2021-07-29T18:08:08.835Z f3bf7b43-b255-473b-90f1-87e3f62ad294 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://azurite/devstoreaccount1/uploads?restype=container RequestHeaders:{"x-ms-version":"2020-08-04","accept":"application/xml","user-agent":"azsdk-js-storageblob/12.6.0 (NODE-VERSION v14.17.3; Linux 5.10.25-linuxkit)","x-ms-client-request-id":"e22393e9-2668-41d5-a323-28c4b98390f6","x-ms-date":"Thu, 29 Jul 2021 18:08:08 GMT","authorization":"SharedKey devstoreaccount1:4NSHrB0XkOHEGE3ZZeI9zv0nGB5FJRlCY9SLcww77jo=","cookie":"","content-length":"0","host":"azurite:10000","connection":"keep-alive"} ClientIP=10.1.19.98 Protocol=http HTTPVersion=1.1
2021-07-29T18:08:08.835Z f3bf7b43-b255-473b-90f1-87e3f62ad294 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=uploads Blob=
2021-07-29T18:08:08.836Z f3bf7b43-b255-473b-90f1-87e3f62ad294 verbose: DispatchMiddleware: Dispatching request...
2021-07-29T18:08:08.838Z f3bf7b43-b255-473b-90f1-87e3f62ad294 info: DispatchMiddleware: Operation=Container_Create
2021-07-29T18:08:08.838Z f3bf7b43-b255-473b-90f1-87e3f62ad294 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2021-07-29T18:08:08.838Z f3bf7b43-b255-473b-90f1-87e3f62ad294 info: PublicAccessAuthenticator:validate() Start validation against public access.
2021-07-29T18:08:08.838Z f3bf7b43-b255-473b-90f1-87e3f62ad294 debug: PublicAccessAuthenticator:validate() Getting account properties...
2021-07-29T18:08:08.838Z f3bf7b43-b255-473b-90f1-87e3f62ad294 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: uploads, blob: 
2021-07-29T18:08:08.840Z f3bf7b43-b255-473b-90f1-87e3f62ad294 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container uploads
2021-07-29T18:08:08.840Z f3bf7b43-b255-473b-90f1-87e3f62ad294 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2021-07-29T18:08:08.856Z f3bf7b43-b255-473b-90f1-87e3f62ad294 info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:e22393e9-2668-41d5-a323-28c4b98390f6\nx-ms-date:Thu, 29 Jul 2021 18:08:08 GMT\nx-ms-version:2020-08-04\n/devstoreaccount1/devstoreaccount1/uploads\nrestype:container"
2021-07-29T18:08:08.856Z f3bf7b43-b255-473b-90f1-87e3f62ad294 info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:4NSHrB0XkOHEGE3ZZeI9zv0nGB5FJRlCY9SLcww77jo=
2021-07-29T18:08:08.857Z f3bf7b43-b255-473b-90f1-87e3f62ad294 info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2021-07-29T18:08:08.857Z f3bf7b43-b255-473b-90f1-87e3f62ad294 verbose: DeserializerMiddleware: Start deserializing...
2021-07-29T18:08:08.859Z f3bf7b43-b255-473b-90f1-87e3f62ad294 info: HandlerMiddleware: DeserializedParameters={"options":{"metadata":{},"requestId":"e22393e9-2668-41d5-a323-28c4b98390f6"},"restype":"container","version":"2020-08-04"}
2021-07-29T18:08:08.865Z f3bf7b43-b255-473b-90f1-87e3f62ad294 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-07-29T18:08:08.866Z f3bf7b43-b255-473b-90f1-87e3f62ad294 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified container already exists.  ErrorHTTPStatusCode=409 ErrorHTTPStatusMessage=The specified container already exists. ErrorHTTPHeaders={"x-ms-error-code":"ContainerAlreadyExists","x-ms-request-id":"f3bf7b43-b255-473b-90f1-87e3f62ad294"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:f3bf7b43-b255-473b-90f1-87e3f62ad294\nTime:2021-07-29T18:08:08.860Z</Message>\n</Error>" ErrorStack="StorageError: The specified container already exists.\n    at Function.getContainerAlreadyExists (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:23:16)\n    at LokiBlobMetadataStore.createContainer (/opt/azurite/dist/src/blob/persistence/LokiBlobMetadataStore.js:292:49)\n    at ContainerHandler.create (/opt/azurite/dist/src/blob/handlers/ContainerHandler.js:35:34)\n    at /opt/azurite/dist/src/blob/generated/middleware/HandlerMiddlewareFactory.js:58:18\n    at /opt/azurite/dist/src/blob/generated/ExpressMiddlewareFactory.js:77:63\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:317:13)\n    at /opt/azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:275:10)"
2021-07-29T18:08:08.866Z f3bf7b43-b255-473b-90f1-87e3f62ad294 error: ErrorMiddleware: Set HTTP code: 409
2021-07-29T18:08:08.866Z f3bf7b43-b255-473b-90f1-87e3f62ad294 error: ErrorMiddleware: Set HTTP status message: The specified container already exists.
2021-07-29T18:08:08.866Z f3bf7b43-b255-473b-90f1-87e3f62ad294 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=ContainerAlreadyExists
2021-07-29T18:08:08.866Z f3bf7b43-b255-473b-90f1-87e3f62ad294 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=f3bf7b43-b255-473b-90f1-87e3f62ad294
2021-07-29T18:08:08.866Z f3bf7b43-b255-473b-90f1-87e3f62ad294 error: ErrorMiddleware: Set content type: application/xml
2021-07-29T18:08:08.867Z f3bf7b43-b255-473b-90f1-87e3f62ad294 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:f3bf7b43-b255-473b-90f1-87e3f62ad294\nTime:2021-07-29T18:08:08.860Z</Message>\n</Error>"
2021-07-29T18:08:08.868Z f3bf7b43-b255-473b-90f1-87e3f62ad294 info: EndMiddleware: End response. TotalTimeInMS=33 StatusCode=409 StatusMessage=The specified container already exists. Headers={"server":"Azurite-Blob/3.14.0","x-ms-error-code":"ContainerAlreadyExists","x-ms-request-id":"f3bf7b43-b255-473b-90f1-87e3f62ad294","content-type":"application/xml"}
2021-07-29T18:08:08.888Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://azurite/devstoreaccount1/artifacts?restype=container RequestHeaders:{"x-ms-version":"2020-08-04","accept":"application/xml","user-agent":"azsdk-js-storageblob/12.6.0 (NODE-VERSION v14.17.3; Linux 5.10.25-linuxkit)","x-ms-client-request-id":"dfd7f798-7735-45dc-b48a-f2dcfa4ce49f","x-ms-date":"Thu, 29 Jul 2021 18:08:08 GMT","authorization":"SharedKey devstoreaccount1:/XKHFEJiiqhTlwxBqrVqiyc9jzSe7kOY78O6qQXCJt8=","cookie":"","content-length":"0","host":"azurite:10000","connection":"keep-alive"} ClientIP=10.1.19.98 Protocol=http HTTPVersion=1.1
2021-07-29T18:08:08.889Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=artifacts Blob=
2021-07-29T18:08:08.889Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf verbose: DispatchMiddleware: Dispatching request...
2021-07-29T18:08:08.890Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf info: DispatchMiddleware: Operation=Container_Create
2021-07-29T18:08:08.890Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2021-07-29T18:08:08.890Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf info: PublicAccessAuthenticator:validate() Start validation against public access.
2021-07-29T18:08:08.890Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf debug: PublicAccessAuthenticator:validate() Getting account properties...
2021-07-29T18:08:08.890Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: artifacts, blob: 
2021-07-29T18:08:08.891Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container artifacts
2021-07-29T18:08:08.891Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2021-07-29T18:08:08.892Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf info: BlobSharedKeyAuthenticator:validate() [STRING TO SIGN]:"PUT\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:dfd7f798-7735-45dc-b48a-f2dcfa4ce49f\nx-ms-date:Thu, 29 Jul 2021 18:08:08 GMT\nx-ms-version:2020-08-04\n/devstoreaccount1/devstoreaccount1/artifacts\nrestype:container"
2021-07-29T18:08:08.892Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf info: BlobSharedKeyAuthenticator:validate() Calculated authentication header based on key1: SharedKey devstoreaccount1:/XKHFEJiiqhTlwxBqrVqiyc9jzSe7kOY78O6qQXCJt8=
2021-07-29T18:08:08.892Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf info: BlobSharedKeyAuthenticator:validate() Signature 1 matched.
2021-07-29T18:08:08.892Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf verbose: DeserializerMiddleware: Start deserializing...
2021-07-29T18:08:08.892Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf info: HandlerMiddleware: DeserializedParameters={"options":{"metadata":{},"requestId":"dfd7f798-7735-45dc-b48a-f2dcfa4ce49f"},"restype":"container","version":"2020-08-04"}
2021-07-29T18:08:08.893Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-07-29T18:08:08.894Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The specified container already exists.  ErrorHTTPStatusCode=409 ErrorHTTPStatusMessage=The specified container already exists. ErrorHTTPHeaders={"x-ms-error-code":"ContainerAlreadyExists","x-ms-request-id":"efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf\nTime:2021-07-29T18:08:08.893Z</Message>\n</Error>" ErrorStack="StorageError: The specified container already exists.\n    at Function.getContainerAlreadyExists (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:23:16)\n    at LokiBlobMetadataStore.createContainer (/opt/azurite/dist/src/blob/persistence/LokiBlobMetadataStore.js:292:49)\n    at ContainerHandler.create (/opt/azurite/dist/src/blob/handlers/ContainerHandler.js:35:34)\n    at /opt/azurite/dist/src/blob/generated/middleware/HandlerMiddlewareFactory.js:58:18\n    at /opt/azurite/dist/src/blob/generated/ExpressMiddlewareFactory.js:77:63\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:317:13)\n    at /opt/azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:275:10)"
2021-07-29T18:08:08.894Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf error: ErrorMiddleware: Set HTTP code: 409
2021-07-29T18:08:08.894Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf error: ErrorMiddleware: Set HTTP status message: The specified container already exists.
2021-07-29T18:08:08.894Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=ContainerAlreadyExists
2021-07-29T18:08:08.894Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf
2021-07-29T18:08:08.894Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf error: ErrorMiddleware: Set content type: application/xml
2021-07-29T18:08:08.894Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>ContainerAlreadyExists</Code>\n  <Message>The specified container already exists.\nRequestId:efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf\nTime:2021-07-29T18:08:08.893Z</Message>\n</Error>"
2021-07-29T18:08:08.894Z efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf info: EndMiddleware: End response. TotalTimeInMS=6 StatusCode=409 StatusMessage=The specified container already exists. Headers={"server":"Azurite-Blob/3.14.0","x-ms-error-code":"ContainerAlreadyExists","x-ms-request-id":"efa3f18b-7f5b-42f0-a9d8-d4961c85c4cf","content-type":"application/xml"}
2021-07-29T18:08:08.910Z 3de11bc4-5a6d-41fd-b468-311cade73f38 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://azurite/devstoreaccount1/commands?timeout=30 RequestHeaders:{"x-ms-version":"2020-08-04","accept":"application/xml","user-agent":"azsdk-js-storagequeue/12.5.0 (NODE-VERSION v14.17.3; Linux 5.10.25-linuxkit)","x-ms-client-request-id":"8d652efb-ae6e-4400-9d50-b9802f6b3863","x-ms-date":"Thu, 29 Jul 2021 18:08:08 GMT","authorization":"SharedKey devstoreaccount1:qFoUhub4LEdZg6e1nEaWsJDHfUuuavPKP8nboMRTFKM=","cookie":"","content-length":"0","accept-encoding":"gzip,deflate","host":"azurite:10000","connection":"keep-alive"} ClientIP=10.1.19.98 Protocol=http HTTPVersion=1.1
2021-07-29T18:08:08.910Z 3de11bc4-5a6d-41fd-b468-311cade73f38 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=commands Blob=
2021-07-29T18:08:08.910Z 3de11bc4-5a6d-41fd-b468-311cade73f38 verbose: DispatchMiddleware: Dispatching request...
2021-07-29T18:08:08.913Z 3de11bc4-5a6d-41fd-b468-311cade73f38 error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2021-07-29T18:08:08.913Z 3de11bc4-5a6d-41fd-b468-311cade73f38 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-07-29T18:08:08.913Z 3de11bc4-5a6d-41fd-b468-311cade73f38 error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at Object.dispatchMiddleware [as default] (/opt/azurite/dist/src/blob/generated/middleware/dispatch.middleware.js:41:30)\n    at /opt/azurite/dist/src/blob/generated/ExpressMiddlewareFactory.js:49:42\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:317:13)\n    at /opt/azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:275:10)\n    at blobStorageContextMiddleware (/opt/azurite/dist/src/blob/middlewares/blobStorageContext.middleware.js:72:5)\n    at /opt/azurite/dist/src/blob/middlewares/blobStorageContext.middleware.js:14:16\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)"
2021-07-29T18:08:08.913Z 3de11bc4-5a6d-41fd-b468-311cade73f38 error: ErrorMiddleware: Set HTTP code: 400
2021-07-29T18:08:08.913Z 3de11bc4-5a6d-41fd-b468-311cade73f38 error: ErrorMiddleware: Set HTTP body: undefined
2021-07-29T18:08:08.913Z 3de11bc4-5a6d-41fd-b468-311cade73f38 info: EndMiddleware: End response. TotalTimeInMS=3 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Blob/3.14.0"}
```

### Have you found a mitigation/solution?

Not yet...

**Comment by justinmchase** [comment]
It seems to get a `409` due to the container already existing, but then later reports:

> error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.

And then ends up returning a 400, which the client seems to not like at all.

**Comment by justinmchase** [comment]
Derp, nevermind. In my actual code I had a typo and was using the wrong port `10000`... that'll do it!
