### ISSUE TITLE
Azurite fails to upload a file using the official node.js SDK

### ISSUE THREAD

**Issue by dg-eparizzi** [Azure/Azurite#994]
### Which service(blob, file, queue, table) does this issue concern?
Azurite

### Which version of the Azurite was used?
`latest` at the time of writing (DockerHub)

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What's the Node.js version?
Irrelevant

### What problem was encountered?
Using the official node.js SDK,

```js
const blobName = "Battery Bank/0001/2021/08/11/11/Battery Bank-0001_2021-08-11-11-csv.gz"
const blockBlobClient = containerClient.getBlockBlobClient(blobName);
blockBlobClient.uploadData(data):
```
results in the following log
```
 "PUT /devstoreaccount1/my-container/Battery%2520Bank%2F0001%2F2021%2F08%2F11%2F11%2FBattery%2520Bank-0001_2021-08-11-11.csv.gz HTTP/1.1" 500 -
```
There seems to be an error with the URL escaping.

The exact same code works well when targeting a real Azure Blob Storage account.

**Comment by blueww** [comment]
@dg-eparizzi 
Would you please attach the debug log?
And after you upload the blob, does the blob exist with the correct name or a wrong name? (You can try to list/get the blob to check)

**Comment by dg-eparizzi** [comment]
```
2021-08-12T13:52:06.365Z 5e028b10-af3c-40f2-97e6-12dae74a8793 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://azurite/devstoreaccount1/chisholm-datalogs/Battery%20Bank%2F0003%2F2021%2F08%2F12%2FBattery%20Bank-0003_2021-08-12_12h.csv.gz RequestHeaders:{"x-ms-version":"2020-08-04","content-length":"7246","x-ms-encryption-algorithm":"AES256","content-type":"application/octet-stream","accept":"application/xml","x-ms-blob-type":"BlockBlob","user-agent":"azsdk-js-storageblob/12.7.0 (NODE-VERSION v14.17.3; Linux 5.11.0-25-generic)","x-ms-client-request-id":"ed13b616-df6a-4c21-95b5-edddce564d03","x-ms-date":"Thu, 12 Aug 2021 13:52:06 GMT","authorization":"SharedKey devstoreaccount1:mOeZBDGpYXoL+YHGTCjMxMYRyoZq6kEuH5I80xhKJfo=","cookie":"","host":"azurite:10000","connection":"keep-alive"} ClientIP=172.18.0.5 Protocol=http HTTPVersion=1.1
2021-08-12T13:52:06.365Z 5e028b10-af3c-40f2-97e6-12dae74a8793 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=chisholm-datalogs Blob=Battery Bank/0003/2021/08/12/Battery Bank-0003_2021-08-12_12h.csv.gz
2021-08-12T13:52:06.365Z 5e028b10-af3c-40f2-97e6-12dae74a8793 verbose: DispatchMiddleware: Dispatching request...
2021-08-12T13:52:06.366Z 5e028b10-af3c-40f2-97e6-12dae74a8793 info: DispatchMiddleware: Operation=BlockBlob_Upload
2021-08-12T13:52:06.366Z 5e028b10-af3c-40f2-97e6-12dae74a8793 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2021-08-12T13:52:06.366Z 5e028b10-af3c-40f2-97e6-12dae74a8793 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter "--loose" or Visual Studio Code configuration "Loose". Please vote your wanted features to https://github.com/azure/azurite/issues  ErrorHTTPStatusCode=500 ErrorHTTPStatusMessage=x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter "--loose" or Visual Studio Code configuration "Loose". Please vote your wanted features to https://github.com/azure/azurite/issues ErrorHTTPHeaders={"x-ms-error-code":"FeatureNotSupported","x-ms-request-id":"5e028b10-af3c-40f2-97e6-12dae74a8793"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>FeatureNotSupported</Code>\n  <Message>x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter \"--loose\" or Visual Studio Code configuration \"Loose\". Please vote your wanted features to https://github.com/azure/azurite/issues\nRequestId:5e028b10-af3c-40f2-97e6-12dae74a8793\nTime:2021-08-12T13:52:06.366Z</Message>\n</Error>" ErrorStack="StorageError: x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter \"--loose\" or Visual Studio Code configuration \"Loose\". Please vote your wanted features to https://github.com/azure/azurite/issues\n    at UnsupportedHeadersBlocker (/opt/azurite/dist/src/blob/middlewares/StrictModelMiddlewareFactory.js:20:19)\n    at StrictModelMiddlewareFactory.validate (/opt/azurite/dist/src/blob/middlewares/StrictModelMiddlewareFactory.js:57:19)\n    at /opt/azurite/dist/src/blob/middlewares/StrictModelMiddlewareFactory.js:49:18\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:317:13)\n    at /opt/azurite/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:275:10)\n    at Object.dispatchMiddleware [as default] (/opt/azurite/dist/src/blob/generated/middleware/dispatch.middleware.js:46:5)\n    at /opt/azurite/dist/src/blob/generated/ExpressMiddlewareFactory.js:49:42"
2021-08-12T13:52:06.366Z 5e028b10-af3c-40f2-97e6-12dae74a8793 error: ErrorMiddleware: Set HTTP code: 500
2021-08-12T13:52:06.366Z 5e028b10-af3c-40f2-97e6-12dae74a8793 error: ErrorMiddleware: Set HTTP status message: x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter "--loose" or Visual Studio Code configuration "Loose". Please vote your wanted features to https://github.com/azure/azurite/issues
2021-08-12T13:52:06.366Z 5e028b10-af3c-40f2-97e6-12dae74a8793 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=FeatureNotSupported
2021-08-12T13:52:06.366Z 5e028b10-af3c-40f2-97e6-12dae74a8793 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=5e028b10-af3c-40f2-97e6-12dae74a8793
2021-08-12T13:52:06.366Z 5e028b10-af3c-40f2-97e6-12dae74a8793 error: ErrorMiddleware: Set content type: application/xml
2021-08-12T13:52:06.366Z 5e028b10-af3c-40f2-97e6-12dae74a8793 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>FeatureNotSupported</Code>\n  <Message>x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter \"--loose\" or Visual Studio Code configuration \"Loose\". Please vote your wanted features to https://github.com/azure/azurite/issues\nRequestId:5e028b10-af3c-40f2-97e6-12dae74a8793\nTime:2021-08-12T13:52:06.366Z</Message>\n</Error>"
2021-08-12T13:52:06.366Z 5e028b10-af3c-40f2-97e6-12dae74a8793 info: EndMiddleware: End response. TotalTimeInMS=1 StatusCode=500 StatusMessage=x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter "--loose" or Visual Studio Code configuration "Loose". Please vote your wanted features to https://github.com/azure/azurite/issues Headers={"server":"Azurite-Blob/3.14.0","x-ms-error-code":"FeatureNotSupported","x-ms-request-id":"5e028b10-af3c-40f2-97e6-12dae74a8793","content-type":"application/xml"}
```

Yeah so apparently is caused by the `x-ms-encryption-algorithm` that the SDK is sending. 
Starting Azurite in Loose mode fixes the issue.
